- ISLE/isle.cpp
- ISLE/isle.h
- LEGO1/mxrect32.h
`Isle::Isle`, `Isle::~Isle`, `Isle::ReadReg`, `Isle::ReadRegBool`, `Isle::ReadRegInt`, `Isle::LoadConfig`, `Isle::SetupLegoOmni` are 100% now.
> isle: Accuracy improvements

- LEGO1/mxtimer.cpp
I'll do more, just started with noticing the call order mismatch
7:10 PM EDT: all good!
> MxTimer matching

- .github/workflows/build.yml
- tools/reccmp/reccmp.py
- tools/reccmp/requirements.txt
* Now only shows the info for a single function when a specific function is specified via -v
* Now colors the output by default
* Percentages are shown as green/yellow/red depending on the percentage completed.
* Diff +/- lines are shown as green/red.
* Includes standard --no-color argument in case we need no color for some tooling which consumes the output.
> Improve reccmp.py

- LEGO1/mxautolocker.h
I wish it always was this easy 🤓
> lego: match MxAutoLocker ctor/dtor

- LEGO1/mxbitmap.cpp
- LEGO1/mxbitmap.h
Sorry about the commit spam guys, I'll probably make a force push or stash the commits once I'm done. I'm also doing this at school (last few days, so nothing is happening), on a M1 Mac so I currently can't really build it.
A lot of what's missing is stuff relating to MxPalette, so that needs to preferably be knocked out first (at least two of the functions)
> Initial implementation of MxBitmap

- LEGO1/legonavcontroller.cpp
- LEGO1/legonavcontroller.h
- LEGO1/legoutil.h
- LEGO1/mxdsobject.cpp
One more function for `LegoNavController` and some minor style consistency fixes
> lego: Implement/match CalculateNewVel

- CMakeLists.txt
- LEGO1/act2brick.h
- LEGO1/compat.h
- LEGO1/legobackgroundcolor.h
- LEGO1/legoinputmanager.h
- LEGO1/legoomni.cpp
- LEGO1/legoomni.h
- LEGO1/legostate.cpp
- LEGO1/legostate.h
- LEGO1/mxentity.cpp
- LEGO1/mxentity.h
- LEGO1/mxmediapresenter.h
- LEGO1/mxobjectfactory.h
- LEGO1/mxomni.h
- LEGO1/mxsoundmanager.cpp
- LEGO1/mxsoundmanager.h
- LEGO1/mxstreamer.h
- LEGO1/mxstringvariable.cpp
- LEGO1/mxstringvariable.h
- LEGO1/mxtimer.h
- LEGO1/mxtransitionmanager.h
- LEGO1/mxunknown100dc6b0.cpp
- LEGO1/mxunknown100dc6b0.h
- LEGO1/mxunknown100dc6e0.cpp
- LEGO1/mxunknown100dc6e0.h
- LEGO1/mxvideoparam.cpp
- LEGO1/mxvideoparam.h
This pr provides a non-invasive alternative for https://github.com/isledecomp/isle/commit/d05393f883c4e4466f0856a8186b57d67bd56883
> Get Isle building on MinGW32

- LEGO1/legobackgroundcolor.cpp
- LEGO1/legobackgroundcolor.h
Fixed the logic of and matched `SetColorString`. Also applied some of our style rules
> lego: fix/match SetColorString

- LEGO1/mxnotificationmanager.cpp
Sitting at 90.51% on my machine, but if you look it really seems to just be the usual MSVC randomness with a bit more mov instruction reordering.
This is the last function left in `MxNotificationManager` as far as I can tell, so I'll call "Tutorial complete!"
> MxNotificationManager::FlushPending

- LEGO1/mxbackgroundaudiomanager.cpp
- LEGO1/mxbackgroundaudiomanager.h
Decompiling MxStreamer would help this
> MxBackgroundAudioManager

- LEGO1/mxdsaction.cpp
- LEGO1/mxdsaction.h
- LEGO1/mxvector.cpp
- LEGO1/mxvector.h
`MxDSAction` uses the `MxVector` classes from https://github.com/isledecomp/isle/pull/100 and it looks like we've got a perfect match in this constructor, only a minor change was needed in the `MxVector2` base class (inlined `SetData`)
> Implement/match MxDSAction constructor

- ISLE/isleapp.cpp
- LEGO1/mxdsaction.cpp
- LEGO1/mxdsaction.h
- LEGO1/mxdsobject.cpp
- LEGO1/mxdsobject.h
- LEGO1/mxvector.h
Implemented and matched most of `MxDSAction` and resolved some unknowns from `MxDSObject`. A few functions aren't quite completed/looked at yet, but I'll leave those for some other time.
There appears to be a major regression in `WndProc` on first glance but as far as I can tell "only" a lot of instructions have been reordered, so I believe it has nothing directly to do with changes in this PR.
> Implement most of MxDSAction

- LEGO1/mxdsaction.cpp
- LEGO1/mxdsaction.h
- LEGO1/mxdsfile.cpp
- LEGO1/mxtypes.h
`MxDSAction::AppendData` matches fully apart from one instruction placed differently. I've given the function and attributes preliminary "unknown" labels since I'm not aware of their purpose (yet).
> Implement MxDSAction::AppendData

- LEGO1/mxdsobject.h
- LEGO1/mxdssound.cpp
- LEGO1/mxdssound.h
> Add MxDSSound

- LEGO1/realtimeview.cpp
- LEGO1/realtimeview.h
Match RealtimeView::SetUserMaxLOD
> Match SetUserMaxLOD

- CMakeLists.txt
- LEGO1/mxdsactionlist.cpp
- LEGO1/mxdsactionlist.h
- LEGO1/mxdsmultiaction.cpp
- LEGO1/mxdsmultiaction.h
- LEGO1/mxlist.h
`MxDSMultiAction` and its descendants are the last remaining data classes to be implemented. This class basically contains a list, based on `MxList`, of other actions.
Implemented with this PR are its members (including the list class/cursor), ctor/dtor, and the first two virtual functions (all 100% matches).
> Bootstrap MxDSMultiAction

- LEGO1/mxdsaction.h
- LEGO1/mxdsmediaaction.h
- LEGO1/mxdsobject.h
- LEGO1/mxpresenter.cpp
- LEGO1/mxpresenter.h
Small function that will either: 
- pass through the source name of an MxDSAction (if present)
- return the name of the MxPresenter subclass to be used for the given action
Some interesting syntax here, but a good match.
> PresenterNameDispatch

- LEGO1/legoinputmanager.h
- LEGO1/legoomni.h
- LEGO1/legovideomanager.h
- LEGO1/mxbackgroundaudiomanager.h
- LEGO1/mxdisplaysurface.h
- LEGO1/mxomni.cpp
- LEGO1/mxomni.h
- LEGO1/mxtransitionmanager.cpp
- LEGO1/mxtransitionmanager.h
- LEGO1/mxvideomanager.h
Implements some of MxTransitionManager and the global function SetAppCursor.
SetAppCursor and MxTransitionManager::GetDDrawSurfaceFromVideoManager match 100%.
MxTransitionManager::StartTransition is very incomplete and does not match, with only 17.28%.
> implement some of MxTransitionManager

- LEGO1/legoutil.cpp
- LEGO1/legoutil.h
- LEGO1/mxomni.cpp
- LEGO1/mxomni.h
- LEGO1/mxtransitionmanager.cpp
- LEGO1/mxtransitionmanager.h
Something I missed previously, judging by its original address the function `SetAppCursor` is likely part of the "utility" function collection. This PR moves the function to that compilation unit.
> Relocate SetAppCursor to legoutil

- LEGO1/mxmusicpresenter.cpp
- LEGO1/mxmusicpresenter.h
Did this at school, so unable to test locally but this should all be correct
> MxMusicPresenter: ClassName, IsA, ctor, Init

- LEGO1/mxmidipresenter.h
noticed this when going the classname and IsA for MxMusicPresenter
> MxMIDIPresenter: ClassName, IsA

- LEGO1/mxdiskstreamprovider.cpp
- LEGO1/mxdiskstreamprovider.h
- LEGO1/mxstreamprovider.h
just something random i started doing, i guess. 63% matching
> MxDiskStreamProvider constructor

- LEGO1/legoactor.cpp
- LEGO1/legoactor.h
- LEGO1/pizza.cpp
- LEGO1/pizza.h
Incorrect type and a missing line
> Fix pizza constructor

- LEGO1/mxcontrolpresenter.cpp
- LEGO1/mxcontrolpresenter.h
> MxControlPresenter ctor/structure

- LEGO1/mxtransitionmanager.cpp
- LEGO1/mxtransitionmanager.h
- LEGO1/mxtypes.h
- LEGO1/mxvideoparamflags.h
Everything matches except for some pesky registers in StartTransition. I believe these are probably influenced by headers outside of the functions control, so I'm submitting as-is.
> Implement MxTransitionManager ctor/dtor/rest of StartTransition

- LEGO1/motorcycle.cpp
- LEGO1/motorcycle.h
Looks like I forgot this in #113 . YOLO'd this since it was small and on my Mac, this should 100% match and build based on how its similar to all the other IslePathActors.
> Motorcycle initial class structure and ctor

- LEGO1/mxdsaction.h
- LEGO1/mxpresenter.h
- LEGO1/mxtransitionmanager.cpp
- LEGO1/mxtransitionmanager.h
This PR implements and matches `MxTransitionManager::SubmitCopyRect`
I'm still working on SetupCopyRect, and that touches into various parts of the codebase, so I haven't included that here yet.
> Implement MxTransitionManager::SubmitCopyRect

- LEGO1/mxtransitionmanager.cpp
- LEGO1/mxtransitionmanager.h
Pretty straightforward. 100% match.
> MxTransitionManager Wipe transition

- CMakeLists.txt
- LEGO1/mxaudiomanager.cpp
- LEGO1/mxaudiomanager.h
- LEGO1/mxmidimanager.cpp
- LEGO1/mxmidimanager.h
implemented MxMIDIManager mostly 100% match
> implement MxMIDIManager

- LEGO1/mxloopingflcpresenter.cpp
> Unstub MxLoopingFlcPresenter destructor

- LEGO1/mxaudiopresenter.cpp
- LEGO1/mxaudiopresenter.h
I also set the type from int -> undefined4 for consistency
> MxAudioPresenter - vtable functions

- ISLE/isleapp.cpp
- LEGO1/legoomni.cpp
- LEGO1/legoomni.h
- LEGO1/mxdsobject.h
- LEGO1/mxomni.cpp
- LEGO1/mxomni.h
- LEGO1/mxstreamcontroller.cpp
- LEGO1/mxstreamcontroller.h
- LEGO1/mxstreamer.cpp
- LEGO1/mxstreamer.h
This PR implements the start function. 100% matching.
> Implement Start()

- LEGO1/legoentity.cpp
- LEGO1/mxdsaction.cpp
- LEGO1/mxvector.h
Introduces a helper function `Fill` that forwards the value to `EqualsScalar` to clean up some source code.
> Refactor vector EqualsScalar

- LEGO1/mxmusicpresenter.cpp
- LEGO1/mxmusicpresenter.h
vtable+0x34 adds the current presenter to the music manager vtable+0x38 calls destroy with the param as "FALSE"
---
I also added DECOMP_SIZE_ASSERT's, although for this class its probably unnecessary
> MxMusicPresenter vtable

- LEGO1/mxeventmanager.cpp
- LEGO1/mxeventmanager.h
- LEGO1/mxmediamanager.cpp
- LEGO1/mxmediamanager.h
- LEGO1/mxomni.cpp
All functions are 100% matching, except MxEventManager::CreateEventThread (which is almost identical to MxMusicManager::StartMIDIThread).
> Finish MxMediaManager and MxEventManager

- LEGO1/mxcompositepresenter.cpp
- LEGO1/mxcompositepresenter.h
- LEGO1/mxdiskstreamprovider.h
- LEGO1/mxunklist.h
> Start MxCompositePresenter ctor/dtor

- LEGO1/legovideomanager.cpp
- LEGO1/legovideomanager.h
- LEGO1/mxpalette.h
- LEGO1/mxvideomanager.h
MoveCursor doesn't match because the registers are swapped for some reason.
> Implement LegoVideoManager::MoveCursor and improve SetSkyColor

- LEGO1/mxdiskstreamcontroller.cpp
- LEGO1/mxdiskstreamcontroller.h
- LEGO1/mxdiskstreamprovider.cpp
- LEGO1/mxdiskstreamprovider.h
- LEGO1/mxdsfile.cpp
- LEGO1/mxdssource.cpp
- LEGO1/mxdssource.h
- LEGO1/mxnextactiondatastart.h
- LEGO1/mxramstreamprovider.cpp
- LEGO1/mxramstreamprovider.h
- LEGO1/mxstreamcontroller.cpp
- LEGO1/mxstreamcontroller.h
- LEGO1/mxstreamprovider.h
- Added MxDiskStreamController vtable
- Added MxDiskStreamProvider vtable
- Implemented MxStreamController::vtable0x20 but couldn't figure out how to get it to match
- renamed a few functions
> MxDiskStreamController vtable

- LEGO1/mxmediapresenter.h
- LEGO1/mxmusicpresenter.cpp
- LEGO1/mxmusicpresenter.h
I wasn't supposed to do the latter.
> Implement MxMusicPresenter's Destroy method and move MxMediaPresenter's Destroy method to "protected"

- CMakeLists.txt
- LEGO1/legometerpresenter.cpp
- LEGO1/legometerpresenter.h
* Add a stub class for LegoMeterPresenter.
> Add LegoMeterPresenter stub class

- LEGO1/mxtransitionmanager.cpp
Implements MxTransitionManager::Transition_Windows().
~~Currently only a 60.33% match. I've been messing around with the function for a couple of hours but I can't really seem to get anywhere in terms of improving the match. It would be great to have a second set of eyes on this.~~
Edit: 100% match now due to a couple of contributions.
> implement/match MxTransitionManager::Transition_Windows()

- LEGO1/mxregion.cpp
- LEGO1/mxregion.h
- LEGO1/mxvideomanager.cpp
100% matches, this completes the class afaik. Closing in on `MxRegion`: the list it contains looks more complex than I first assumed, it might be multidimensional.
> Implement/match MxVideoManager::InvalidateRect and UpdateRegion

- LEGO1/scorestate.cpp
- LEGO1/scorestate.h
This PR implements and completes the ScoreState vtable. Both functions are 100% matching. As far as I'm aware, this completes the class.
> implement/match ScoreState vtable

- LEGO1/mxeventpresenter.cpp
- LEGO1/mxeventpresenter.h
If I feel like it I might do the later ones but for now just this
> MxEventPresenter destructor

- LEGO1/legoomni.cpp
- LEGO1/legoomni.h
- LEGO1/mxomni.cpp
- LEGO1/mxomni.h
Minor function, 100% match. Also fixes the declaration / override.
> Implement LegoOmni::NotifyCurrentEntity

- LEGO1/mxmediapresenter.h
- LEGO1/mxsoundpresenter.cpp
- LEGO1/mxsoundpresenter.h
Destructor, destroy, function adding itself to the sound manager and vtable38.
Very small and simple.
> MxSoundPresenter

- LEGO1/legoomni.cpp
- LEGO1/legoomni.h
- LEGO1/mxbackgroundaudiomanager.cpp
- LEGO1/mxbackgroundaudiomanager.h
- LEGO1/mxomni.cpp
- LEGO1/mxomni.h
Everything matches except for MxBackgroundAudioManager::OpenMusic which has uses different registers
> implement most of MxBackgroundAudioManager

- LEGO1/jukeboxstate.cpp
- LEGO1/jukeboxstate.h
This PR implements and matches JukeBoxState. It sounds a lot more interesting than it actually is, though. The entire class is completed by this one VTable function.
> implement/match JukeBoxState

- LEGO1/legopathpresenter.cpp
- LEGO1/legopathpresenter.h
implement some LegoPathPresenter functions
> implement LegoPathPresenter

- LEGO1/act3.cpp
- LEGO1/act3.h
- LEGO1/helicopter.cpp
- LEGO1/helicopter.h
- LEGO1/islepathactor.cpp
- LEGO1/islepathactor.h
- LEGO1/legoworld.cpp
- LEGO1/legoworld.h
- LEGO1/mxentity.h
- tools/reccmp/reccmp.py
Mostly Matching, some issues with MxMatrix and/or MxVector4
> Start of helicopter Implementation

- LEGO1/helicopter.cpp
- LEGO1/helicopter.h
- LEGO1/helicopterstate.h
- LEGO1/islepathactor.cpp
- LEGO1/islepathactor.h
- LEGO1/legoactor.cpp
- LEGO1/legoactor.h
- LEGO1/legoanimationmanager.cpp
- LEGO1/legoanimationmanager.h
- LEGO1/legogamestate.h
- LEGO1/legoomni.cpp
- LEGO1/legoomni.h
- LEGO1/legopathactor.cpp
- LEGO1/legopathactor.h
- LEGO1/legoutil.cpp
- LEGO1/legoutil.h
- LEGO1/mxomni.cpp
- LEGO1/mxomni.h
- LEGO1/mxpresenter.cpp
> Implement Helicopter::VTable0xe4

- CMakeLists.txt
- LEGO1/compat.h
- LEGO1/decomp.h
- LEGO1/legogamestate.cpp
- LEGO1/legogamestate.h
- LEGO1/legoobjectfactory.cpp
- LEGO1/legoomni.cpp
- LEGO1/legoomni.h
- LEGO1/legoutil.h
- LEGO1/mxactionnotificationparam.h
- LEGO1/mxdirect3d.cpp
- LEGO1/mxdirect3d.h
- LEGO1/mxdirectdraw.cpp
- LEGO1/mxdsobject.h
- LEGO1/mxhashtable.h
- LEGO1/mxlist.h
- LEGO1/mxmusicmanager.cpp
- LEGO1/mxobjectfactory.cpp
- LEGO1/mxomni.h
- LEGO1/mxomnicreateparam.h
- LEGO1/mxpresenter.cpp
- LEGO1/mxpresenter.h
- LEGO1/mxtransitionmanager.cpp
- LEGO1/mxtypes.h
- LEGO1/pizza.h
These are build fixes to get isle building (further) with a modern mingw toolchain.
The only errors left are those due to taking the address of rvalues.
[These can be fixed easily](https://github.com/madebr/isle/commit/9dde9e7f9d3a2775b565a2fa9504e04afc78bf89), but it decreases the matching percentage.
Therefore, not part of this pr.
> MinGW build fixes

- LEGO1/mxsoundmanager.cpp
- LEGO1/mxsoundmanager.h
> Implement/match MxSoundManager::Create

- LEGO1/mxsoundmanager.cpp
- LEGO1/mxwavepresenter.cpp
- LEGO1/mxwavepresenter.h
> Implement/match remaining MxSoundManager virtual functions

- LEGO1/mxdsbuffer.cpp
- LEGO1/mxdsbuffer.h
- LEGO1/mxdssource.cpp
- LEGO1/mxramstreamcontroller.cpp
- LEGO1/mxstreamer.h
- turned mode into an enum based on MxDSBuffer::AllocateBuffer
TODO: match MxDSBuffer::AllocateBuffer
> more MxDSBuffer functions

- LEGO1/mxnextactiondatastart.h
- LEGO1/mxramstreamprovider.h
- LEGO1/mxsmkpresenter.h
- LEGO1/mxstillpresenter.h
- LEGO1/mxstreamchunk.h
- LEGO1/pizzeria.h
- LEGO1/pizzeriastate.h
- LEGO1/radio.h
- LEGO1/registrationbook.h
Exceptions: LegoAnimActor as it does something weird with a call to another private/inlined function(?) and RaceStandsEntity which seems to have two vtables
> Add missing ClassName's and IsA's

- LEGO1/legoomni.cpp
- LEGO1/legoomni.h
- LEGO1/mxbackgroundaudiomanager.cpp
- LEGO1/mxbackgroundaudiomanager.h
- LEGO1/mxcompositepresenter.cpp
- LEGO1/mxcompositepresenter.h
- LEGO1/mxcore.h
- LEGO1/mxdsaction.cpp
- LEGO1/mxdsaction.h
- LEGO1/mxdssound.h
- LEGO1/mxnotificationparam.h
- LEGO1/mxpresenter.cpp
- LEGO1/score.cpp
- Renamed MxParamType Paint to c_notificationStartAction
- implemented a few methods in MxBackgroundAudioManager
TODO:
> Finish MxBackgroundAudioManager

- LEGO1/legonavcontroller.cpp
- LEGO1/legonavcontroller.h
- LEGO1/legoobjectfactory.cpp
- LEGO1/pizza.cpp
- Marked Pizza::Tickle as a stub
- Matched LegoObjectFactory::Destroy & LegoNavController constructor and deconstructor
> Match a few methods

- tools/reccmp/reccmp.py
- tools/verexp/verexp.py
* Use `with` statement for file access
* Use f-strings instead of modulo string formatting
* Single quotes in most places
Unfortunately I am not able to test this, I don't have a copy of Lego Island and I can't get any output asm files to test with. I am also using Linux.
Is there any easy way for me to test this? I plan on improving these python tools
> Improve python tools

- LEGO1/mxaudiopresenter.cpp
- LEGO1/mxaudiopresenter.h
- LEGO1/mxbackgroundaudiomanager.cpp
- LEGO1/mxmidipresenter.cpp
- LEGO1/mxmidipresenter.h
- LEGO1/mxmusicpresenter.h
- LEGO1/mxsoundmanager.cpp
- LEGO1/mxsoundpresenter.cpp
- LEGO1/mxsoundpresenter.h
Adds the virtual table stubs for `MxMIDIPresenter` in preparation for some implementation work. Also some minor refactoring in related classes.
> Prepare MxMIDIPresenter vtable and refactoring

- tools/reccmp/reccmp.py
- tools/reccmp/requirements.txt
- tools/reccmp/template.html
- tools/reccmp/template.svg
Adds pystache as a dependency, but think it's better than manually calling `replace`
> Use templates instead of replacing

- LEGO1/mxioinfo.cpp
- LEGO1/mxioinfo.h
Better code style for `MXIOINFO::Descend` because this one was bugging me from back in #54. I thought doing this might squeeze out the final diffs, but no change.
Also: I used MxTypes where we had ints before.
> MXIOINFO code style

- LEGO1/mxdiskstreamcontroller.cpp
- LEGO1/mxdiskstreamcontroller.h
- LEGO1/mxdsaction.h
- LEGO1/mxdsobject.h
- LEGO1/mxdsstreamingaction.h
> Implement MxDiskStreamController::VTable0x20

- LEGO1/mxdsbuffer.cpp
- LEGO1/mxdsbuffer.h
- LEGO1/mxdsfile.h
- LEGO1/mxramstreamcontroller.cpp
- LEGO1/mxramstreamcontroller.h
- LEGO1/mxramstreamprovider.cpp
- LEGO1/mxstreamcontroller.h
All known functions for MxRAMStreamProvider and MxRAMStreamController are implemented and almost matching, except for ReadData (0x100d0d80).
> Finish MxRAMStreamProvider and MxRAMStreamController

- LEGO1/legogamestate.cpp
- LEGO1/legogamestate.h
- LEGO1/legoomni.cpp
- LEGO1/legoomni.h
I am 100% sure that LegoGameState::m_unk0xa6 is an array, however I don't know the size of it.
> some gamestate functions

- LEGO1/isle.cpp
- LEGO1/isle.h
- LEGO1/legogamestate.h
- LEGO1/legoutil.cpp
- LEGO1/legoutil.h
- LEGO1/legoworld.cpp
- LEGO1/legoworld.h
All implemented functions match except Isle::Create
> Additional isle functions

- LEGO1/act1state.h
- LEGO1/isle.cpp
- LEGO1/isle.h
couldn't figure out how to match it
> implement Isle::Notify

- CMakeLists.txt
- LEGO1/lego3dmanager.h
- LEGO1/lego3dview.cpp
- LEGO1/lego3dview.h
- LEGO1/legoomni.cpp
- LEGO1/legoomni.h
- LEGO1/legoworld.cpp
- LEGO1/legoworld.h
- LEGO1/mxactionnotificationparam.cpp
- LEGO1/mxactionnotificationparam.h
- LEGO1/mxbackgroundaudiomanager.cpp
- LEGO1/mxdsobject.h
- LEGO1/mxomni.cpp
- LEGO1/mxomni.h
- LEGO1/mxpresenter.h
- LEGO1/mxstreamcontroller.cpp
- LEGO1/mxstreamcontroller.h
- LEGO1/mxstreamer.cpp
- LEGO1/mxstreamer.h
- Implemented LegoOmni::PickROI (doesnt match)
- Implemented LegoOmni::Destroy (doesn't match as not all classes are implemented)
- Implmented LegoOmni::Notify (100% match)
- Implemented MxOmni::CreatePresenter (not matching due to something wrong about notification types?)
- Implemented MxStreamController::FUN_100c1e70 (100% match)
> Implement a few legoomni/mxomni functions

- LEGO1/helicopter.cpp
- LEGO1/legoomni.cpp
- LEGO1/legoomni.h
- LEGO1/legoworld.cpp
- LEGO1/legoworld.h
- LEGO1/score.cpp
- removed PlayMusic stub from legoworld (as it was already implemented in legoomni)
- moved other functions to legoomni
> fix incorrect location of functions

- LEGO1/legovideomanager.cpp
- LEGO1/legovideomanager.h
- LEGO1/mxdisplaysurface.cpp
- LEGO1/mxdisplaysurface.h
- LEGO1/mxpalette.h
Couldn't figure out how to match both functions, however the logic seems correct
> implement EnableFullScreenMovie and FUN_100ba640

- LEGO1/helicopter.cpp
- LEGO1/realtime/vector.h
This should finish the Helicopter source file. I've tried all the usual suspects and can't get the ordering correct, so no idea what's going in this function.
> Implement Helicopter subclass

- LEGO1/mxdiskstreamcontroller.cpp
- LEGO1/mxdiskstreamcontroller.h
- LEGO1/mxdiskstreamprovider.cpp
- LEGO1/mxdiskstreamprovider.h
- LEGO1/mxdsbuffer.cpp
- LEGO1/mxdsbuffer.h
- LEGO1/mxdsstreamingaction.h
- LEGO1/mxramstreamcontroller.cpp
- LEGO1/mxramstreamprovider.cpp
- LEGO1/mxramstreamprovider.h
- LEGO1/mxstreamcontroller.cpp
- LEGO1/mxstreamcontroller.h
- LEGO1/mxstreamlist.h
- LEGO1/mxstreamprovider.h
Implement a lot of MxDiskStreamController functions. Half of them match
+ MxDiskStreamController::FUN_100c7980 (0x100c7980) is 48.24% similar to the original
+  MxDiskStreamController::VTable0x28 (0x100c7ac0) is 64.81% similar to the original
+  MxDiskStreamController::VTable0x30 (0x100c7c00) is 100.00% similar to the original
+  MxDiskStreamController::FUN_100c7cb0 (0x100c7cb0) is 100.00% similar to the original
+  MxDiskStreamController::FUN_100c7ce0 (0x100c7ce0) is 100.00% similar to the original
+  MxDiskStreamController::FUN_100c7d10 (0x100c7d10) is 72.55% similar to the original
> More MxDiskStreamController functions

- LEGO1/mxdssubscriber.cpp
- LEGO1/mxdssubscriber.h
- LEGO1/mxmediapresenter.cpp
- LEGO1/mxstreamcontroller.cpp
- LEGO1/mxstreamcontroller.h
Implements the members and first few functions, all of them matching 100%.
```
+  MxDSSubscriber::MxDSSubscriber (0x100b7bb0) is 100.00% similar to the original
+  MxDSSubscriber::~MxDSSubscriber (0x100b7e00) is 100.00% similar to the original
+  MxDSSubscriber::Create (0x100b7ed0) is 100.00% similar to the original
+  MxDSSubscriber::`scalar deleting destructor' (0x100b7de0) is 100.00% similar to the original
+  MxStreamChunkList::~MxStreamChunkList (0x100b7d00) is 100.00% similar to the original
```
> Bootstrap MxDSSubscriber

- LEGO1/jukebox.cpp
- LEGO1/jukebox.h
yay jukebox constructor easy pr
> jukebox ctor

- ISLE/isleapp.cpp
- LEGO1/mxdiskstreamcontroller.h
- LEGO1/mxdsbuffer.cpp
- LEGO1/mxdsbuffer.h
With this function implemented, LegoWorldPresenter is created from isle.si
> Implement MxDSBuffer::FUN_100c67b0

- LEGO1/mxdiskstreamprovider.cpp
- LEGO1/mxdsbuffer.cpp
- LEGO1/mxdschunk.cpp
- LEGO1/mxdschunk.h
- LEGO1/mxdsstreamingaction.h
- LEGO1/mxdssubscriber.cpp
- LEGO1/mxstreamchunk.cpp
- LEGO1/mxstreamchunk.h
- LEGO1/mxstreamcontroller.cpp
- LEGO1/mxstreamcontroller.h
Implemented MxDSBuffer::ParseChunk, as well as a few more functions that it requires. This allows the game to play the nocd sound if you force it to run nocd.si
https://github.com/isledecomp/isle/assets/106913236/fb7813c8-c816-485d-9d3a-d52cabc4502a
> Implement chunk parsing

- LEGO1/define.cpp
- LEGO1/define.h
- LEGO1/legoentity.cpp
- LEGO1/legoentity.h
- LEGO1/legoentitypresenter.cpp
- LEGO1/legoentitypresenter.h
- LEGO1/mxdsaction.h
- LEGO1/mxpresenter.cpp
- LEGO1/mxpresenter.h
I couldn't figure out how to match MxPresenter::CreateEntityBackend and LegoEntityPresenter::ParseExtra, but all other functions match
> Finish LegoEntityPresenter

- LEGO1/mxdschunk.h
- LEGO1/mxstreamcontroller.cpp
> Implement/match MxStreamController::FUN_100c1f00

- LEGO1/mxdschunk.h
- LEGO1/mxstreamcontroller.cpp
- LEGO1/mxstreamlist.cpp
- LEGO1/mxstreamlist.h
> Implement/match MxStreamController::FindNextActionDataStartFromStreamingAction

- LEGO1/mxdschunk.h
- LEGO1/mxstreamcontroller.cpp
- LEGO1/mxstreamlist.cpp
- LEGO1/mxstreamlist.h
> Implement/match MxStreamController::FUN_100c20d0

- LEGO1/mxstreamer.cpp
> Implement/match MxStreamer::DeleteObject

- LEGO1/legoworldpresenter.cpp
> implement LegoWorldPresenter::StartAction

- LEGO1/legoflctexturepresenter.cpp
- LEGO1/legoflctexturepresenter.h
> LegoFlcTexturePresenter init function

- LEGO1/legotexturepresenter.cpp
- LEGO1/legotexturepresenter.h
All thats left is PutData(), along with another private function
> Bootstrap rest of LegoTexturePresenter

- LEGO1/legopalettepresenter.cpp
- LEGO1/legopalettepresenter.h
> Finish LegoPalettePresenter

- LEGO1/mxdiskstreamcontroller.cpp
- LEGO1/mxdiskstreamcontroller.h
- LEGO1/mxramstreamcontroller.cpp
- LEGO1/mxstreamcontroller.cpp
> Implement/match MxDiskStreamController destructor

- LEGO1/mxdiskstreamprovider.cpp
> Implement/match MxDiskStreamProvider destructor

- ISLE/isleapp.cpp
- LEGO1/legovideomanager.cpp
- LEGO1/mxdirect3d.cpp
- LEGO1/mxdirect3d.h
- LEGO1/mxdirectdraw.cpp
- LEGO1/mxdirectdraw.h
Match is at ~92%, only a minor part in the display mode assignment doesn't align.
> Implement/match MxDirect3D::SetDevice

- LEGO1/lego3dmanager.h
- LEGO1/mxdirect3d.cpp
- LEGO1/mxdirect3d.h
- LEGO1/mxdirectdraw.h
- LEGO1/mxvideomanager.cpp
- LEGO1/mxvideomanager.h
- LEGO1/tglsurface.h
> Implement/match MxDirect3D::D3DSetMode

- LEGO1/mxactionnotificationparam.cpp
- LEGO1/mxomni.cpp
Improved match from 60% to 80%
> Improve accuracy of MxOmni::CreatePresenter

- LEGO1/lego3dmanager.cpp
- LEGO1/lego3dmanager.h
- LEGO1/legovideomanager.cpp
- LEGO1/legovideomanager.h
- LEGO1/legoworld.h
- LEGO1/mxdirectdraw.h
- LEGO1/mxdirectx/mxstopwatch.h
- LEGO1/mxdisplaysurface.cpp
- LEGO1/mxdisplaysurface.h
- LEGO1/mxlist.h
- LEGO1/mxloopingsmkpresenter.cpp
- LEGO1/mxpresenterlist.h
- LEGO1/mxregion.cpp
- LEGO1/mxtransitionmanager.h
Match is at ~96%, rest seems to be compiler randomness. This fixes the "broken viewport" bug we've seen until now when the game launches:
https://github.com/isledecomp/isle/assets/1135351/b24e7693-4f54-4f5b-ab08-bf9b1f6fc043
> Implement/match LegoVideoManager::Tickle

- LEGO1/legoactioncontrolpresenter.cpp
> Finish LegoActionControlPresenter

- LEGO1/lego/legoomni/include/legopalettepresenter.h
- LEGO1/lego/legoomni/src/common/legoactioncontrolpresenter.cpp
- LEGO1/lego/legoomni/src/common/mxcompositemediapresenter.cpp
- LEGO1/lego/legoomni/src/video/legopalettepresenter.cpp
- LEGO1/omni/include/mxdssubscriber.h
- LEGO1/omni/include/mxmediapresenter.h
- LEGO1/omni/include/mxwavepresenter.h
- LEGO1/omni/src/audio/mxmidipresenter.cpp
- LEGO1/omni/src/audio/mxwavepresenter.cpp
- LEGO1/omni/src/common/mxmediapresenter.cpp
- LEGO1/omni/src/event/mxeventpresenter.cpp
- LEGO1/omni/src/stream/mxdssubscriber.cpp
- LEGO1/omni/src/video/mxloopingflcpresenter.cpp
- LEGO1/omni/src/video/mxloopingsmkpresenter.cpp
- LEGO1/omni/src/video/mxstillpresenter.cpp
- LEGO1/omni/src/video/mxvideopresenter.cpp
This adds/improves names of various functions/members in `MxDSSubscriber` and related `MxPresenter` classes.
> Name various functions and other members

- LEGO1/lego/sources/3dmanager/lego3dview.cpp
- LEGO1/lego/sources/3dmanager/lego3dview.h
- LEGO1/viewmanager/viewmanager.cpp
- LEGO1/viewmanager/viewmanager.h
Fixes some members of `Lego3DView` and matches the constructor and `Destroy` functions.
> Fix structure of Lego3DView

- LEGO1/lego/legoomni/include/infocenter.h
- LEGO1/lego/legoomni/include/isle.h
- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legobuildingmanager.h
- LEGO1/lego/legoomni/include/legoplantmanager.h
- LEGO1/lego/legoomni/include/legoworld.h
- LEGO1/lego/legoomni/include/score.h
- LEGO1/lego/legoomni/src/build/legobuildingmanager.cpp
- LEGO1/lego/legoomni/src/common/legoplantmanager.cpp
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/entity/legoworldpresenter.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenter.cpp
- LEGO1/lego/legoomni/src/infocenter/score.cpp
- LEGO1/lego/legoomni/src/isle/isle.cpp
- LEGO1/lego/legoomni/src/video/legoanimationmanager.cpp
100% match. Also renamed LegoWorld::Stop to LegoWorld::VTable0x50 as it is unclear what that does currently
> implement LegoWorldPresenter deconstructor

- LEGO1/omni/src/video/mxvideopresenter.cpp
from 59.32% to 68.35%. Also fixed crash
> Improve accuracy of Alphamask constructor

- LEGO1/lego/sources/3dmanager/lego3dview.cpp
- LEGO1/omni/src/video/mxbitmap.cpp
- LEGO1/viewmanager/viewmanager.cpp
- LEGO1/viewmanager/viewmanager.h
> Implement/match Lego3DView::Create

- LEGO1/lego/legoomni/include/helicopter.h
- LEGO1/lego/legoomni/include/infocenter.h
- LEGO1/lego/legoomni/include/isle.h
- LEGO1/lego/legoomni/include/islepathactor.h
- LEGO1/lego/legoomni/include/legocontrolmanager.h
- LEGO1/lego/legoomni/include/legoentity.h
- LEGO1/lego/legoomni/include/legoomni.h
- LEGO1/lego/legoomni/include/legopointofviewcontroller.h
- LEGO1/lego/legoomni/include/legorace.h
- LEGO1/lego/legoomni/include/legoworld.h
- LEGO1/lego/legoomni/include/score.h
- LEGO1/lego/legoomni/src/build/helicopter.cpp
- LEGO1/lego/legoomni/src/control/legocontrolmanager.cpp
- LEGO1/lego/legoomni/src/entity/legoentity.cpp
- LEGO1/lego/legoomni/src/entity/legopovcontroller.cpp
- LEGO1/lego/legoomni/src/entity/legorace.cpp
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenter.cpp
- LEGO1/lego/legoomni/src/infocenter/score.cpp
- LEGO1/lego/legoomni/src/isle/isle.cpp
- LEGO1/lego/legoomni/src/isle/islepathactor.cpp
- LEGO1/lego/legoomni/src/main/legoomni.cpp
- LEGO1/omni/include/mxentity.h
- implemented LegoPointOfViewController::OnViewSize, SetCurrentWorld, LegoWorld::VTable0x54, and partially implemented LegoWorld::Create
- Renamed LegoWorld::SetAsCurrentWorld to LegoWorld::Create as that method is in the vtable as the Create method
- Changed LegoEntity::Create argument to MxDSAction from MxDSObject
This PR allows the cursor to change to an arrow cursor after initialization
> Implement a few legoworld methods

- LEGO1/lego/legoomni/include/act1state.h
- LEGO1/lego/legoomni/include/isle.h
- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legoentity.h
- LEGO1/lego/legoomni/include/legogamestate.h
- LEGO1/lego/legoomni/include/legovideomanager.h
- LEGO1/lego/legoomni/src/act1/act1state.cpp
- LEGO1/lego/legoomni/src/common/legogamestate.cpp
- LEGO1/lego/legoomni/src/isle/isle.cpp
- LEGO1/lego/legoomni/src/video/legoanimationmanager.cpp
Isle::VTable0x50 doesn't match 100% because of this weird padding that I couldn't figure out in Act1State:
This PR allows the InfoCenter script to be started
> Implement Isle::VTable0x50

- CMakeLists.txt
- LEGO1/lego/legoomni/include/legoactorpresenter.h
- LEGO1/lego/legoomni/include/legoentity.h
- LEGO1/lego/legoomni/src/entity/legoactorpresenter.cpp
Implemented all vtable functions of LegoActorPresenter, ParseExtra doesn't match
> implement LegoActorPresenter

- LEGO1/lego/legoomni/include/legoworldlist.h
- LEGO1/lego/legoomni/src/main/legoomni.cpp
- LEGO1/omni/include/mxdsactionlist.h
- LEGO1/omni/include/mxentity.h
- LEGO1/omni/include/mxlist.h
- LEGO1/omni/include/mxstreamchunklist.h
- LEGO1/omni/include/mxstringlist.h
- LEGO1/omni/src/action/mxdsselectaction.cpp
couldn't figure out how to match it
> implement LegoOmni::FindByEntityIdOrAtomId

- LEGO1/lego/legoomni/include/legometerpresenter.h
- LEGO1/lego/legoomni/src/video/legometerpresenter.cpp
LegoMeterPresenter seems to just resize the bitmap based off of the extra data.
> Implement LegoMeterPresenter

- LEGO1/lego/legoomni/src/entity/legoworldpresenter.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenter.cpp
- LEGO1/omni/include/mxpresenter.h
> Implement LegoWorldPresenter::VTable0x60

- LEGO1/lego/legoomni/include/legocameracontroller.h
- LEGO1/lego/legoomni/include/legoentity.h
- LEGO1/lego/legoomni/include/legoomni.h
- LEGO1/lego/legoomni/include/legounksavedatawriter.h
- LEGO1/lego/legoomni/src/common/legofullscreenmovie.cpp
- LEGO1/lego/legoomni/src/common/legounksavedatawriter.cpp
- LEGO1/lego/legoomni/src/entity/legocameracontroller.cpp
- LEGO1/lego/legoomni/src/entity/legoentity.cpp
- LEGO1/lego/legoomni/src/main/legoomni.cpp
- LEGO1/lego/legoomni/src/video/legopalettepresenter.cpp
- LEGO1/lego/sources/roi/legoroi.h
- LEGO1/omni/include/mxmediamanager.h
- LEGO1/realtime/orientableroi.h
> Implement/match a few LegoEntity functions

- LEGO1/lego/legoomni/include/gasstation.h
- LEGO1/lego/legoomni/src/gasstation/gasstation.cpp
This PR does:
Implementing `GasStation:GasStation()` in `LEGO1/lego/legoomni/src/gasstation/gasstation.cpp`
> Implementing GasStation:GasStation() function

- LEGO1/lego/legoomni/include/beachhouseentity.h
- LEGO1/lego/legoomni/include/buildingentity.h
- LEGO1/lego/legoomni/include/elevatorbottom.h
- LEGO1/lego/legoomni/include/infocenterdoor.h
- LEGO1/lego/legoomni/include/infocenterstate.h
- LEGO1/lego/legoomni/include/legoworld.h
- LEGO1/lego/legoomni/include/registrationbook.h
- LEGO1/lego/legoomni/src/build/buildingentity.cpp
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/infocenter/elevatorbottom.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenterdoor.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenterstate.cpp
- LEGO1/lego/legoomni/src/infocenter/registrationbook.cpp
- LEGO1/lego/legoomni/src/isle/beachhouseentity.cpp
Added stubs for all classes in infocenter folder, as well as implemented some simple functions which are 100% matching. Also fixed a mistake where BeachHouseEntity::Notify should be in LegoEnity::Notify.
> Implement InfoCenter folder vtable stubs

- LEGO1/lego/legoomni/include/infocenterstate.h
- LEGO1/omni/include/mxbitmap.h
- LEGO1/omni/include/mxutil.h
- LEGO1/omni/src/common/mxutil.cpp
- LEGO1/omni/src/video/mxbitmap.cpp
- LEGO1/omni/src/video/mxdisplaysurface.cpp
Some if blocks are being reordered still.
> Finish Bitmap

- LEGO1/omni/include/mxloopingflcpresenter.h
- LEGO1/omni/src/video/mxloopingflcpresenter.cpp
> Implement/match MxLoopingFlcPresenter remaining functions

- LEGO1/omni/include/mxomni.h
- LEGO1/omni/src/main/mxomni.cpp
> Implement/match MxOmni::ActionSourceEquals

- LEGO1/lego/legoomni/include/policestate.h
- LEGO1/lego/legoomni/src/police/policestate.cpp
Very simple, but the rand() statement was, very weird, to say the least. Ghidra couldn't make much out of it. Credit goes to @tahg for figuring it out
> PoliceState constructor

- LEGO1/lego/legoomni/include/elevatorbottom.h
- LEGO1/lego/legoomni/include/infocenter.h
- LEGO1/lego/legoomni/include/infocenterdoor.h
- LEGO1/lego/legoomni/include/legocontrolmanager.h
- LEGO1/lego/legoomni/src/control/legocontrolmanager.cpp
- LEGO1/lego/legoomni/src/infocenter/elevatorbottom.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenter.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenterdoor.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenterstate.cpp
All methods match, except Infocenter::Tickle
> Implement various methods in InfoCenter folder

- LEGO1/lego/legoomni/include/policestate.h
- LEGO1/lego/legoomni/src/police/policestate.cpp
- LEGO1/lego/legoomni/src/towtrack/towtrackmissionstate.cpp
It's not matching, something weird is going on, i can't figure it out
> Implmement PoliceState::VTable0x1c

- LEGO1/lego/sources/3dmanager/lego3dview.cpp
- LEGO1/lego/sources/3dmanager/lego3dview.h
- LEGO1/viewmanager/viewmanager.cpp
- LEGO1/viewmanager/viewmanager.h
100% match. This allows for the sky to be rendered
> Implement Lego3DView::Render

- LEGO1/lego/legoomni/include/police.h
- LEGO1/lego/legoomni/src/police/police.cpp
Currently, when setting the script to show Police, nothing happens (at least for me)
> Begin work on Police class

- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/include/legolocomotionanimpresenter.h
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
- LEGO1/lego/legoomni/src/video/legolocomotionanimpresenter.cpp
100% match except LegoLocomotionAnimPresenter::Init
> begin LegoLocomotionAnimPresenter

- LEGO1/lego/legoomni/include/infocenter.h
- LEGO1/lego/legoomni/include/legoworld.h
- LEGO1/lego/legoomni/include/radio.h
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenter.cpp
- LEGO1/lego/legoomni/src/isle/radio.cpp
> Implement Infocenter::InitializeBitmaps

- LEGO1/lego/legoomni/include/isle.h
- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/include/legoomni.h
- LEGO1/lego/legoomni/include/legoworld.h
- LEGO1/lego/legoomni/src/build/helicopter.cpp
- LEGO1/lego/legoomni/src/common/legogamestate.cpp
- LEGO1/lego/legoomni/src/common/legoutil.cpp
- LEGO1/lego/legoomni/src/entity/legoentity.cpp
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/entity/legoworldpresenter.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenter.cpp
- LEGO1/lego/legoomni/src/isle/isle.cpp
- LEGO1/lego/legoomni/src/main/legoomni.cpp
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
- LEGO1/lego/legoomni/src/video/legolocomotionanimpresenter.cpp
- LEGO1/lego/sources/roi/legoroi.h
- LEGO1/omni/include/mxdsobject.h
- LEGO1/omni/include/mxomni.h
- LEGO1/omni/src/common/mxpresenter.cpp
- LEGO1/omni/src/main/mxomni.cpp
This implements the second `LegoWorld::Find`. The match is only at ~72%, mainly because one of the cursors isn't inlined just right, but functionally it should be correct.
I've also renamed various functions in the context of `LegoWorld`.
> Implement LegoWorld::Find

- LEGO1/lego/legoomni/include/legocachesoundlist.h
- LEGO1/lego/legoomni/include/legoentitylist.h
- LEGO1/lego/legoomni/include/legoworld.h
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/omni/include/mxpresenterlist.h
> Implement/match LegoWorld::Remove

- CMakeLists.txt
- LEGO1/lego/legoomni/include/legobuildingmanager.h
- LEGO1/lego/legoomni/include/legoentity.h
- LEGO1/lego/legoomni/include/legolocomotionanimpresenter.h
- LEGO1/lego/legoomni/include/legoplantmanager.h
- LEGO1/lego/legoomni/include/legosoundmanager.h
- LEGO1/lego/legoomni/include/legounknown100d6b4c.h
- LEGO1/lego/legoomni/include/legoworld.h
- LEGO1/lego/legoomni/src/audio/legounknown100d6b4c.cpp
- LEGO1/lego/legoomni/src/build/legobuildingmanager.cpp
- LEGO1/lego/legoomni/src/common/legoplantmanager.cpp
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
Match is at ~98%, just a couple instructions are ordered differently.
> Implement/match LegoWorld::Destroy (and destructor)

- LEGO1/lego/legoomni/include/legocontrolmanager.h
- LEGO1/lego/legoomni/include/legoinputmanager.h
- LEGO1/lego/legoomni/src/control/legocontrolmanager.cpp
- LEGO1/lego/legoomni/src/input/legoinputmanager.cpp
> implement LegoInputManager::Create

- LEGO1/lego/legoomni/include/legoeventnotificationparam.h
- LEGO1/lego/legoomni/src/notify/legoeventnotificationparam.cpp
> Implement/match LegoEventNotifcationParam::Clone

- LEGO1/lego/legoomni/include/mxcontrolpresenter.h
- LEGO1/lego/legoomni/src/control/mxcontrolpresenter.cpp
- LEGO1/omni/include/mxcompositepresenter.h
- LEGO1/omni/include/mxutil.h
- LEGO1/omni/include/mxvideopresenter.h
- LEGO1/omni/src/common/mxutil.cpp
Using MxBitmap::GetStart() caused an access violation in MxControlPresenter::FUN_10044270 for some reason.
> Finish MxControlPresenter

- LEGO1/lego/legoomni/src/video/mxtransitionmanager.cpp
@MishaProductions reported a crash during the pixelation transition while testing #505. There were some things obviously wrong there that are now (hopefully) fixed. Specifically:
1. For `MxTransitionManager::Dissolve`, the 16-bit mode was not doubling the `xShift` variable to account for using two bytes per pixel.
2. For `MxTransitionManager::Pixelation`, we were incorrectly multiplying `bytesPerPixel` by the entire offset into the DirectDraw surface array. We only need to do this on `xShift`. The `lPitch` value takes care of the rest because its unit is bytes-per-scanline, not pixels-per-scanline.
Also: for the Pixelation function, I was setting the row of 10 pixels in kind of a wonky way to try to imitate the original. It turns out that using a simple for-loop gets you close to how they …
> MxTransitionManager corrections

- LEGO1/lego/legoomni/include/infocenter.h
- LEGO1/lego/legoomni/include/infocenterstate.h
- LEGO1/lego/legoomni/include/legostate.h
- LEGO1/lego/legoomni/include/legovehiclebuildstate.h
- LEGO1/lego/legoomni/include/radio.h
- LEGO1/lego/legoomni/include/radiostate.h
- LEGO1/lego/legoomni/src/common/legostate.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenter.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenterstate.cpp
- LEGO1/lego/legoomni/src/isle/radiostate.cpp
The unknown struct that we've seen in various `LegoState`-based classes is a device that takes a collection of object / script IDs and has functions to pick a random out of them. I've called it `Shuffle`.
100% matches.
@disinvite The global arrays in here are examples of globals where it would be great if we can check their contents for accuracy
> Implement/match InfocenterState::InfocenterState

- LEGO1/lego/legoomni/include/infocenterstate.h
- LEGO1/lego/legoomni/include/legostate.h
- LEGO1/lego/legoomni/include/legovehiclebuildstate.h
- LEGO1/lego/legoomni/include/radiostate.h
- LEGO1/lego/legoomni/src/common/legostate.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenter.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenterstate.cpp
- LEGO1/lego/legoomni/src/isle/radiostate.cpp
Formerly called `Shuffle`, which wasn't quite accurate, since the now renamed `Playlist` has multiple modes of operation (as can be seen in the `Next` function). 100% matches.
> Implement/match LegoState::Playlist

- LEGO1/lego/legoomni/include/mxbackgroundaudiomanager.h
- LEGO1/lego/legoomni/src/audio/mxbackgroundaudiomanager.cpp
There were various bugs in `MxBackgroundAudioManager::FUN_1007ef40` - now fixed, matches 100%.
> Fix/match MxBackgroundAudioManager::FUN_1007ef40

- LEGO1/lego/legoomni/include/infocenter.h
- LEGO1/lego/legoomni/include/infocenterstate.h
- LEGO1/lego/legoomni/include/legocontrolmanager.h
- LEGO1/lego/legoomni/include/legogamestate.h
- LEGO1/lego/legoomni/include/mxcontrolpresenter.h
- LEGO1/lego/legoomni/src/common/legogamestate.cpp
- LEGO1/lego/legoomni/src/control/legocontrolmanager.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenter.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenterdoor.cpp
- LEGO1/omni/src/common/mxmediapresenter.cpp
> Implement more infocenter methods

- .github/workflows/format.yml
- CMakeLists.txt
- LEGO1/lego/legoomni/include/act1state.h
- LEGO1/lego/legoomni/include/legoutil.h
- LEGO1/lego/legoomni/src/act1/act1state.cpp
- LEGO1/lego/legoomni/src/common/legoutil.cpp
- LEGO1/lego/legoomni/src/infocenter/elevatorbottom.cpp
- LEGO1/lego/sources/misc/legostorage.h
- LEGO1/mxgeometry/mxgeometry3d.h
- util/decomp.h
Also test automatic clang-format reformatting
> Implement some Act1State functions

- LEGO1/lego/legoomni/src/audio/lego3dwavepresenter.cpp
- LEGO1/lego/legoomni/src/video/legohideanimpresenter.cpp
- LEGO1/lego/legoomni/src/video/legopartpresenter.cpp
- LEGO1/omni/include/mxwavepresenter.h
- LEGO1/omni/src/audio/mxwavepresenter.cpp
All functions are 100% matching. Also added stubs for lego3dwavepresenter
> Implement various AddToManager functions

- LEGO1/lego/legoomni/include/legoomni.h
- LEGO1/lego/legoomni/include/legopathcontroller.h
- LEGO1/lego/legoomni/include/legoworld.h
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/main/legoomni.cpp
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
Implements `LegoWorld::FUN_1001fc80` and `LegoWorld::GetCurrPathInfo` - both 100% matches.
> Implement/match remaining LegoWorld functions

- LEGO1/lego/legoomni/include/policestate.h
- LEGO1/lego/legoomni/src/police/police.cpp
When setting ISLE to run this script, it just shows a blue screen, no background or anything, and it plays the music.
Added getter/setter for the PoliceState m_unk0x0c, which is either 500 or 501. Whenever object deletion happens, its in the range of those (or 500 to 510 in one instance for some reason?)
> Implement Police::HandleKeyPress, Enable, VTable0x64

- LEGO1/lego/legoomni/include/infocenter.h
- LEGO1/lego/legoomni/include/legobuildingmanager.h
- LEGO1/lego/legoomni/include/legogamestate.h
- LEGO1/lego/legoomni/include/legoplantmanager.h
- LEGO1/lego/legoomni/include/legounksavedatawriter.h
- LEGO1/lego/legoomni/src/build/legobuildingmanager.cpp
- LEGO1/lego/legoomni/src/common/legogamestate.cpp
- LEGO1/lego/legoomni/src/common/legoplantmanager.cpp
- LEGO1/lego/legoomni/src/common/legounksavedatawriter.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenter.cpp
- LEGO1/lego/legoomni/src/main/legoomni.cpp
100% match. This is called after the game finished with a good or bad ending, and everything is reset to its original state. I've also added an enum for the selected character.
> Implement/match Infocenter::Reset

- tools/isledecomp/isledecomp/bin.py
Imported functions in the ILT might use an ordinal reference instead of a pointer to the function/symbol name. We didn't have any binaries that used this, but `CONFIG.EXE` imports ordinals from `MFC42.DLL` so we need this now. (See #533)
> reccmp: Support ordinal imports

- LEGO1/lego/legoomni/include/registrationbook.h
- LEGO1/lego/legoomni/src/infocenter/registrationbook.cpp
> implement Enable and Create in RegistrationBook

- LEGO1/lego/legoomni/include/legovideomanager.h
- LEGO1/lego/legoomni/src/infocenter/infocenter.cpp
- LEGO1/lego/legoomni/src/video/legovideomanager.cpp
> Implement/match Infocenter::StartCredits

- LEGO1/lego/legoomni/include/act3state.h
- LEGO1/lego/legoomni/include/infocenterstate.h
- LEGO1/lego/legoomni/include/legoact2state.h
- LEGO1/lego/legoomni/src/act2/legoact2state.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenter.cpp
Match is at ~84%, but all the functionality should be accurate.
> Implement Infocenter::ReadyWorld

- LEGO1/lego/legoomni/src/police/police.cpp
100% match, though it might be a switch statement, but I feel like implementing it as such might be just as ugly. I dont know.
> Implement Police::HandleEndAction

- CONFIG/MainDlg.cpp
- CONFIG/config.h
- ISLE/isleapp.cpp
- LEGO1/lego/legoomni/src/video/legovideomanager.cpp
- LEGO1/mxdirectx/mxdirect3d.cpp
- LEGO1/mxdirectx/mxdirect3d.h
- LEGO1/mxdirectx/mxdirectdraw.cpp
- LEGO1/mxdirectx/mxdirectdraw.h
Align library to the 96 source code that we have. (As much as possible given changes between that and the final release.)
> Match some names/values

- LEGO1/lego/legoomni/include/legoentity.h
- LEGO1/lego/legoomni/include/legoentitypresenter.h
- LEGO1/lego/legoomni/include/legomodelpresenter.h
- LEGO1/lego/legoomni/include/legoworld.h
- LEGO1/lego/legoomni/src/entity/legoentity.cpp
- LEGO1/lego/legoomni/src/video/legomodelpresenter.cpp
Functionality seems to be correct, but different registers are being used for some reason which results in a 57.83% match
> Implement LegoModelPresenter::ReadyTickle

- LEGO1/lego/legoomni/include/legoworld.h
- LEGO1/lego/legoomni/src/common/legogamestate.cpp
Implemented more cases to LegoGameState::SwitchArea. Currently does not match because the rest of it isn't implemented and an if statement doesn't match
> Add more cases to LegoGameState::SwitchArea

- LEGO1/lego/legoomni/include/infocenterstate.h
- LEGO1/lego/legoomni/src/infocenter/infocenter.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenterstate.cpp
- LEGO1/lego/legoomni/src/video/legomodelpresenter.cpp
This PR gives names to the dialogue playlists in `InfocenterState` and slightly changes the interface to access them.
> Name dialogue playlists

- CMakeLists.txt
- LEGO1/lego/legoomni/include/gifmanager.h
- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legobuildingmanager.h
- LEGO1/lego/legoomni/include/legoomni.h
- LEGO1/lego/legoomni/include/legoplantmanager.h
- LEGO1/lego/legoomni/include/legounksavedatawriter.h
- LEGO1/lego/legoomni/include/legovariables.h
- LEGO1/lego/legoomni/include/legoworldlist.h
- LEGO1/lego/legoomni/src/build/legobuildingmanager.cpp
- LEGO1/lego/legoomni/src/common/legoplantmanager.cpp
- LEGO1/lego/legoomni/src/common/legounksavedatawriter.cpp
- LEGO1/lego/legoomni/src/common/legovariables.cpp
- LEGO1/lego/legoomni/src/infocenter/elevatorbottom.cpp
- LEGO1/lego/legoomni/src/main/legoomni.cpp
- LEGO1/lego/legoomni/src/video/legoanimationmanager.cpp
- LEGO1/omni/include/mxvariable.h
The match is now at ~95%. The only inaccuracies left are the incorrect size of `LegoObjectFactory` (due to a few missing objects) and a discrepancy stemming from `GifManager` - probably related to the list element not being correct. There is also a function `FUN_10046c10` which looks STL generated and related to `LegoPathController`.
> Implement/match LegoOmni::Create

- LEGO1/lego/legoomni/include/infocenterstate.h
- LEGO1/lego/legoomni/src/common/legogamestate.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenter.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenterdoor.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenterstate.cpp
The "buffer elements" represent the chosen profile/player name letters. I've renamed the functions accordingly.
> Rename Infocenterstate::m_buffer to `m_letters`

- LEGO1/lego/legoomni/include/registrationbook.h
- LEGO1/lego/legoomni/src/infocenter/registrationbook.cpp
Also added the enum for this script
> implement RegistrationBook::Notify

- LEGO1/lego/legoomni/include/police.h
- LEGO1/lego/legoomni/include/policestate.h
- LEGO1/lego/legoomni/src/gasstation/gasstation.cpp
- LEGO1/lego/legoomni/src/police/police.cpp
- LEGO1/lego/legoomni/src/police/policestate.cpp
85% match for the function. Registry swaps.
> PoliceState: Create script enum + implement FUN_1005ea40

- LEGO1/lego/legoomni/include/police.h
- LEGO1/lego/legoomni/src/police/police.cpp
> Police: HandleClick

- LEGO1/lego/legoomni/include/legoomni.h
- LEGO1/lego/legoomni/src/main/legoomni.cpp
100% match. Uses a custom structure which I've called `ScriptContainer`, also 100% matches
> Implement/match LegoOmni::RegisterScripts

- LEGO1/lego/legoomni/include/animstate.h
- LEGO1/lego/legoomni/include/legoomni.h
- LEGO1/lego/legoomni/include/towtrackmissionstate.h
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenter.cpp
- LEGO1/lego/legoomni/src/infocenter/scorestate.cpp
- LEGO1/lego/legoomni/src/input/legoinputmanager.cpp
- LEGO1/lego/legoomni/src/main/legoomni.cpp
- LEGO1/lego/legoomni/src/video/legomodelpresenter.cpp
- LEGO1/lego/sources/roi/legoroi.h
- LEGO1/omni/include/mxomni.h
- LEGO1/realtime/roi.h
- LEGO1/viewmanager/viewmanager.h
> Implement/match LegoOmni::FindROI and related

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legoomni.h
- LEGO1/lego/legoomni/include/legoplantmanager.h
- LEGO1/lego/legoomni/include/legoworld.h
- LEGO1/lego/legoomni/src/common/legoplantmanager.cpp
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/entity/legoworldpresenter.cpp
- LEGO1/lego/legoomni/src/main/legoomni.cpp
- LEGO1/lego/legoomni/src/video/legoanimationmanager.cpp
> Implement/match LegoOmni::GetScriptIndex

- LEGO1/lego/legoomni/src/audio/legoloadcachesoundpresenter.cpp
- LEGO1/lego/legoomni/src/common/legoactioncontrolpresenter.cpp
- LEGO1/lego/legoomni/src/paths/legopathpresenter.cpp
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
- LEGO1/lego/legoomni/src/video/legomodelpresenter.cpp
- LEGO1/lego/legoomni/src/video/legopalettepresenter.cpp
- LEGO1/omni/include/mxdssubscriber.h
- LEGO1/omni/src/audio/mxmidipresenter.cpp
- LEGO1/omni/src/audio/mxwavepresenter.cpp
- LEGO1/omni/src/common/mxmediapresenter.cpp
- LEGO1/omni/src/event/mxeventpresenter.cpp
- LEGO1/omni/src/stream/mxdssubscriber.cpp
- LEGO1/omni/src/stream/mxstreamchunk.cpp
- LEGO1/omni/src/video/mxloopingflcpresenter.cpp
- LEGO1/omni/src/video/mxloopingsmkpresenter.cpp
- LEGO1/omni/src/video/mxstillpresenter.cpp
- LEGO1/omni/src/video/mxvideopresenter.cpp
Based on names from the 1996 source
> Rename MxDSSubscriber functions

- LEGO1/lego/legoomni/include/gasstation.h
- LEGO1/lego/legoomni/src/gasstation/gasstation.cpp
75% match, my guess is the parameters for the Handle* functions which have lots of inlining
> implement GasStation::Notify

- LEGO1/lego/legoomni/src/isle/bike.cpp
- LEGO1/lego/legoomni/src/isle/historybook.cpp
> Bike::Create, Bike::VTable0xe4

- LEGO1/lego/sources/anim/legoanim.cpp
- LEGO1/lego/sources/anim/legoanim.h
Adds the `Read` function for many classes and a few new subclasses (`LegoAnimActorEntry`, `LegoAnimScene`). 100% matches (some compiler randomness in `LegoRotationKey::Read`)
> Implement more anim.lib Read functions

- LEGO1/lego/legoomni/include/historybook.h
- LEGO1/lego/legoomni/include/legogamestate.h
- LEGO1/lego/legoomni/src/common/legogamestate.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenter.cpp
- LEGO1/lego/legoomni/src/isle/historybook.cpp
- LEGO1/omni/include/mxstillpresenter.h
- LEGO1/omni/src/video/mxstillpresenter.cpp
Not a great match yet, as most of the local variables are at the wrong offsets. I don't think it's miles away otherwise, but there are some sections that don't match well.
> Implement HistoryBook::ReadyWorld

- LEGO1/lego/sources/anim/legoanim.cpp
- LEGO1/lego/sources/anim/legoanim.h
All functions implemented here match 100%.
> Implement remaining anim.lib read functions

- LEGO1/lego/legoomni/include/legoactor.h
- LEGO1/lego/legoomni/src/entity/legoactor.cpp
> LegoActor: destructor, SetROI

- LEGO1/lego/legoomni/include/legoomni.h
- LEGO1/lego/legoomni/src/main/legoomni.cpp
- LEGO1/lego/legoomni/src/video/legomodelpresenter.cpp
- LEGO1/lego/sources/misc/legocontainer.cpp
- LEGO1/lego/sources/misc/legocontainer.h
- LEGO1/lego/sources/misc/legostorage.cpp
- LEGO1/lego/sources/misc/legostorage.h
- LEGO1/lego/sources/misc/version.h
- LEGO1/lego/sources/roi/legoroi.cpp
- LEGO1/lego/sources/roi/legoroi.h
- LEGO1/mxdirectx/mxdirect3d.h
- LEGO1/mxgeometry/mxgeometry3d.h
Another fairly large function. The match is at ~99%. This also uses `TextureContainer` map to insert an element, which further confirms the structure is correct.
> Implement/match LegoModelPresenter::CreateROI

- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/include/legoroilist.h
- LEGO1/lego/legoomni/include/legounksavedatawriter.h
- LEGO1/lego/legoomni/src/common/legounksavedatawriter.cpp
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
- LEGO1/lego/sources/anim/legoanim.cpp
- LEGO1/lego/sources/anim/legoanim.h
Match is at ~94%, a few instructions are reordered. This PR also adds a new list `LegoROIList` which will be used in several places in `LegoAnimPresenter`.
> Implement LegoAnimPresenter::FUN_100692b0

- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/include/legounksavedatawriter.h
- LEGO1/lego/legoomni/src/common/legounksavedatawriter.cpp
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
- LEGO1/library_msvc.h
> Implement/match LegoAnimPresenter::FUN_100695c0

- LEGO1/lego/legoomni/include/legoactor.h
- LEGO1/lego/legoomni/include/legoentity.h
- LEGO1/lego/legoomni/include/legogamestate.h
- LEGO1/lego/legoomni/include/legoomni.h
- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/include/legounksavedatawriter.h
- LEGO1/lego/legoomni/src/build/helicopter.cpp
- LEGO1/lego/legoomni/src/common/legogamestate.cpp
- LEGO1/lego/legoomni/src/common/legounksavedatawriter.cpp
- LEGO1/lego/legoomni/src/entity/legoactor.cpp
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenter.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenterdoor.cpp
- LEGO1/lego/legoomni/src/isle/historybook.cpp
- LEGO1/lego/legoomni/src/isle/isle.cpp
- LEGO1/lego/legoomni/src/isle/jukeboxentity.cpp
- LEGO1/lego/legoomni/src/main/legoomni.cpp
- LEGO1/lego/legoomni/src/police/policestate.cpp
- LEGO1/lego/legoomni/src/towtrack/towtrackmissionstate.cpp
- LEGO1/lego/sources/roi/legoroi.cpp
- LEGO1/lego/sources/roi/legoroi.h
Match constructor, SetVehicle.
Refactor actorId and some internal structs (based on the names players.gsi, and history.gsi)
Stopped for this PR because the refactor affected quite a few files.
> Continued work on LegoGameState

- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
> Implement/match LegoAnimPresenter::FUN_100697c0

- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/include/legoroilist.h
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
> Implement/match LegoAnimPresenter::FUN_100698b0

- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/include/legounksavedatawriter.h
- LEGO1/lego/legoomni/src/common/legounksavedatawriter.cpp
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
> Implement/match LegoAnimPresenter::FUN_10069150

- LEGO1/lego/legoomni/include/legoanimmmpresenter.h
- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/include/legohideanimpresenter.h
- LEGO1/lego/legoomni/src/video/legoanimmmpresenter.cpp
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
- LEGO1/lego/legoomni/src/video/legohideanimpresenter.cpp
- LEGO1/lego/legoomni/src/video/legolocomotionanimpresenter.cpp
- LEGO1/mxgeometry/mxgeometry3d.h
- LEGO1/omni/include/mxtimer.h
- LEGO1/realtime/vector.h
> Implement/match LegoAnimPresenter::StartingTickle

- LEGO1/lego/legoomni/include/legobackgroundcolor.h
- LEGO1/lego/legoomni/include/legobuildingmanager.h
- LEGO1/lego/legoomni/include/legogamestate.h
- LEGO1/lego/legoomni/include/legoplantmanager.h
- LEGO1/lego/legoomni/include/legounksavedatawriter.h
- LEGO1/lego/legoomni/include/legoutil.h
- LEGO1/lego/legoomni/src/build/legobuildingmanager.cpp
- LEGO1/lego/legoomni/src/common/legobackgroundcolor.cpp
- LEGO1/lego/legoomni/src/common/legogamestate.cpp
- LEGO1/lego/legoomni/src/common/legoplantmanager.cpp
- LEGO1/lego/legoomni/src/common/legounksavedatawriter.cpp
- LEGO1/lego/legoomni/src/common/legoutil.cpp
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/sources/misc/legostorage.h
- LEGO1/omni/include/mxutil.h
- LEGO1/omni/src/common/mxutil.cpp
Mostly matched. Some stack issues in Load, and weirdness with the Unwind in Save I can't figure out.
> Implement Save, Load, DeleteState

- LEGO1/lego/legoomni/include/legobuildingmanager.h
- LEGO1/lego/legoomni/include/legogamestate.h
- LEGO1/lego/legoomni/include/legoplantmanager.h
- LEGO1/lego/legoomni/include/legounksavedatawriter.h
- LEGO1/lego/legoomni/src/common/legogamestate.cpp
Username methods are kind of hacky, with being inlined or not.  Loop in AddPlayer and SwitchPlayer isn't quite right (theoretically the loop is the same in both functions.)
> LegoGameState player functions

- LEGO1/omni/src/audio/mxwavepresenter.cpp
> Match MxWavePresenter::DoneTickle

- LEGO1/lego/legoomni/include/legoworldpresenter.h
- LEGO1/lego/legoomni/src/common/legoactioncontrolpresenter.cpp
- LEGO1/lego/legoomni/src/control/mxcontrolpresenter.cpp
- LEGO1/lego/legoomni/src/entity/legoactorpresenter.cpp
- LEGO1/lego/legoomni/src/entity/legoentitypresenter.cpp
- LEGO1/lego/legoomni/src/entity/legoworldpresenter.cpp
- LEGO1/lego/legoomni/src/video/legometerpresenter.cpp
- LEGO1/lego/legoomni/src/video/legomodelpresenter.cpp
- LEGO1/omni/include/mxdsaction.h
- LEGO1/omni/src/audio/mxwavepresenter.cpp
- LEGO1/omni/src/common/mxpresenter.cpp
- LEGO1/omni/src/video/mxstillpresenter.cpp
They all match 100% now (except for a little bit of compiler randomness in some)
> Match ParseExtra functions

- LEGO1/omni/include/mxpresenter.h
- LEGO1/omni/include/mxvideopresenter.h
- LEGO1/omni/src/video/mxvideopresenter.cpp
> Improve match of MxVideoPresenter::PutFrame

- LEGO1/omni/src/video/mxdisplaysurface.cpp
> Match MxDisplaySurface::Display

- LEGO1/lego/sources/roi/legoroi.cpp
- LEGO1/lego/sources/roi/legoroi.h
- LEGO1/mxgeometry/mxgeometry3d.h
- LEGO1/mxgeometry/mxmatrix.h
- LEGO1/omni/include/mxticklemanager.h
- LEGO1/realtime/orientableroi.cpp
- LEGO1/realtime/orientableroi.h
- LEGO1/realtime/roi.h
- LEGO1/viewmanager/viewroi.cpp
- LEGO1/viewmanager/viewroi.h
> Improve matches in ROI classes

- LEGO1/omni/src/common/mxticklemanager.cpp
> Match MxTickleManager::Tickle

- LEGO1/lego/legoomni/src/common/mxcompositemediapresenter.cpp
- LEGO1/lego/legoomni/src/control/legocontrolmanager.cpp
- LEGO1/lego/legoomni/src/entity/legoworldpresenter.cpp
- LEGO1/omni/include/mxdsaction.h
- LEGO1/omni/include/mxlist.h
- LEGO1/omni/src/common/mxcompositepresenter.cpp
> Match StartAction functions, remove NextFragment

- LEGO1/lego/legoomni/include/legoomni.h
- LEGO1/realtime/lodlist.h
- LEGO1/viewmanager/viewlodlist.cpp
- LEGO1/viewmanager/viewlodlist.h
> Implement/match ViewLODListManager::Create

- LEGO1/lego/legoomni/src/video/legovideomanager.cpp
> Improve match of LegoVideoManager::Create

- LEGO1/lego/sources/3dmanager/legoview1.cpp
> Improve match/fix LegoView1::Create

- LEGO1/realtime/realtimeview.cpp
- LEGO1/realtime/realtimeview.h
- LEGO1/tgl/d3drm/impl.h
- LEGO1/viewmanager/viewmanager.cpp
- LEGO1/viewmanager/viewmanager.h
> Implement/match ViewManager ctor/dtor/structure

- LEGO1/lego/legoomni/include/legocameracontroller.h
- LEGO1/lego/legoomni/src/entity/legocameracontroller.cpp
- LEGO1/realtime/orientableroi.h
- LEGO1/viewmanager/viewmanager.cpp
- LEGO1/viewmanager/viewmanager.h
> Implement/match some ViewManager functions

- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/main/legoomni.cpp
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
- LEGO1/viewmanager/viewmanager.cpp
- LEGO1/viewmanager/viewmanager.h
- LEGO1/viewmanager/viewroi.h
> Implement/match ViewManager::RemoveAll

- LEGO1/lego/legoomni/include/beachhouseentity.h
- LEGO1/lego/legoomni/include/buildingentity.h
- LEGO1/lego/legoomni/include/gasstationentity.h
- LEGO1/lego/legoomni/include/hospitalentity.h
- LEGO1/lego/legoomni/include/infocenterentity.h
- LEGO1/lego/legoomni/include/policeentity.h
- LEGO1/lego/legoomni/include/racestandsentity.h
- LEGO1/lego/legoomni/src/build/buildingentity.cpp
> implement BuildingEntity functions

- LEGO1/modeldb/modeldb.cpp
- LEGO1/modeldb/modeldb.h
> implement ModelDbPart::Read & ModelDbModel::Read

- LEGO1/lego/legoomni/include/legomodelpresenter.h
- LEGO1/lego/legoomni/include/legoworld.h
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/video/legomodelpresenter.cpp
> Implement/match LegoModelPresenter::FUN_1007ff70

- LEGO1/lego/sources/3dmanager/lego3dview.cpp
- LEGO1/lego/sources/3dmanager/lego3dview.h
- LEGO1/realtime/orientableroi.cpp
- LEGO1/realtime/orientableroi.h
- LEGO1/viewmanager/viewmanager.cpp
- LEGO1/viewmanager/viewmanager.h
> Implement/match remaining Lego3DView functions

- LEGO1/lego/legoomni/src/video/legomodelpresenter.cpp
- LEGO1/viewmanager/viewmanager.cpp
> Implement/match ViewManager::Remove

- CMakeLists.txt
- LEGO1/lego/legoomni/src/entity/legoworldpresenter.cpp
- LEGO1/lego/sources/roi/legoroi.cpp
- LEGO1/lego/sources/roi/legoroi.h
- LEGO1/realtime/roi.h
- LEGO1/tgl/d3drm/group.cpp
- LEGO1/tgl/d3drm/impl.h
- LEGO1/tgl/tgl.h
- LEGO1/viewmanager/viewlod.cpp
- LEGO1/viewmanager/viewlod.h
- LEGO1/viewmanager/viewmanager.cpp
- LEGO1/viewmanager/viewroi.cpp
- LEGO1/viewmanager/viewroi.h
> Bootstrap LegoLOD, implement/match ViewManager::FUN_100a66a0

- CMakeLists.txt
- LEGO1/lego/legoomni/include/legogamestate.h
- LEGO1/lego/legoomni/src/common/legogamestate.cpp
- LEGO1/lego/sources/geom/legobox.cpp
- LEGO1/lego/sources/geom/legobox.h
- LEGO1/lego/sources/geom/legosphere.cpp
- LEGO1/lego/sources/geom/legosphere.h
- LEGO1/lego/sources/geom/legovertex.cpp
- LEGO1/lego/sources/geom/legovertex.h
- LEGO1/lego/sources/roi/legoroi.cpp
- LEGO1/lego/sources/roi/legoroi.h
- LEGO1/viewmanager/viewlod.h
The `geom` library matches 100%. `LegoROI::Read` is a fairly massive function, but I got the match up to 90%+ with seemingly only compiler randomness left, although there is a good chance it can be further improved by shuffling local variables around.
> Implement LegoROI::Read and geom library

- LEGO1/lego/legoomni/include/legoentity.h
- LEGO1/lego/legoomni/src/entity/legoentity.cpp
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/sources/roi/legoroi.cpp
- LEGO1/lego/sources/roi/legoroi.h
> Implement/match LegoEntity::SetROI

- LEGO1/lego/legoomni/include/legoentity.h
- LEGO1/lego/legoomni/src/build/helicopter.cpp
- LEGO1/lego/legoomni/src/entity/legoentity.cpp
- LEGO1/mxgeometry/mxgeometry3d.h
- LEGO1/omni/src/action/mxdsaction.cpp
- LEGO1/realtime/vector.h
> Implement/match LegoEntity::SetLocation

- LEGO1/lego/legoomni/include/legoentity.h
- LEGO1/lego/legoomni/include/legoobjectfactory.h
- LEGO1/lego/legoomni/src/entity/legoentity.cpp
- LEGO1/omni/include/mxobjectfactory.h
> Implement/match LegoEntity::SetWorldTransform and ResetWorldTransform

- LEGO1/lego/legoomni/include/legobuildingmanager.h
- LEGO1/lego/legoomni/include/legoentity.h
- LEGO1/lego/legoomni/include/legoplantmanager.h
- LEGO1/lego/legoomni/include/legounksavedatawriter.h
- LEGO1/lego/legoomni/src/build/legobuildingmanager.cpp
- LEGO1/lego/legoomni/src/common/legoplantmanager.cpp
- LEGO1/lego/legoomni/src/common/legounksavedatawriter.cpp
- LEGO1/lego/legoomni/src/entity/legoentity.cpp
- LEGO1/lego/legoomni/src/input/legoinputmanager.cpp
- LEGO1/lego/sources/roi/legoroi.h
> Implement/match LegoEntity::VTable0x34

- LEGO1/lego/sources/anim/legoanim.cpp
- LEGO1/lego/sources/anim/legoanim.h
- LEGO1/lego/sources/roi/legoroi.cpp
- LEGO1/lego/sources/roi/legoroi.h
> Implement various LegoROI functions

- LEGO1/lego/sources/roi/legolod.cpp
- LEGO1/lego/sources/roi/legolod.h
- LEGO1/lego/sources/roi/legoroi.cpp
> Implement/match LegoROI::FUN_100a9210

- LEGO1/lego/sources/roi/legolod.cpp
- LEGO1/lego/sources/roi/legolod.h
- LEGO1/lego/sources/roi/legoroi.cpp
- LEGO1/lego/sources/roi/legoroi.h
> Implement/match LegoROI::FUN_100a9170

- LEGO1/lego/legoomni/include/legolodlist.h
- LEGO1/lego/legoomni/include/legonamedpart.h
- LEGO1/lego/legoomni/include/legonamedpartlist.h
- LEGO1/lego/legoomni/include/legopartpresenter.h
- LEGO1/lego/legoomni/include/legoworldpresenter.h
- LEGO1/lego/legoomni/src/video/legomodelpresenter.cpp
- LEGO1/lego/legoomni/src/video/legopartpresenter.cpp
- LEGO1/lego/legoomni/src/video/legotexturepresenter.cpp
~99% match, looks like only compiler randomness left.
> Implement/match LegoPartPresenter::Read

- LEGO1/lego/legoomni/include/legolodlist.h
- LEGO1/lego/legoomni/include/legonamedpart.h
- LEGO1/lego/legoomni/include/legonamedpartlist.h
- LEGO1/lego/legoomni/include/legopartpresenter.h
- LEGO1/lego/legoomni/src/entity/legoworldpresenter.cpp
- LEGO1/lego/legoomni/src/video/legopartpresenter.cpp
> Implement/match LegoPartPresenter::Store

- LEGO1/lego/legoomni/src/video/legopartpresenter.cpp
> Implement/match LegoPartPresenter::ReadyTickle

- LEGO1/viewmanager/viewmanager.cpp
- LEGO1/viewmanager/viewmanager.h
> Implement/match ViewManager::FUN_100a6b90

- LEGO1/viewmanager/viewmanager.cpp
- LEGO1/viewmanager/viewmanager.h
> Implement/match ViewManager::Update

- LEGO1/realtime/realtimeview.h
- LEGO1/viewmanager/viewmanager.cpp
- LEGO1/viewmanager/viewmanager.h
Match is at ~60%, since it uses multiple inline functions and recursive calls to itself it's very complex to get right. The instructions all seem to match though.
> Implement ViewManager::FUN_100a66f0

- LEGO1/tgl/d3drm/group.cpp
- LEGO1/tgl/d3drm/impl.h
- LEGO1/tgl/tgl.h
- LEGO1/viewmanager/viewlod.h
- LEGO1/viewmanager/viewmanager.cpp
> Implement ViewManager::FUN_100a65b0

- LEGO1/lego/legoomni/src/entity/legocameracontroller.cpp
- LEGO1/lego/legoomni/src/entity/legoentity.cpp
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
- LEGO1/lego/legoomni/src/video/legomodelpresenter.cpp
- LEGO1/lego/legoomni/src/video/legovideomanager.cpp
- LEGO1/lego/sources/roi/legoroi.cpp
- LEGO1/realtime/orientableroi.cpp
- LEGO1/realtime/realtime.h
- LEGO1/realtime/roi.h
100% match, from the 1996 source
> Implement/match CalcWorldBoundingVolumes

- LEGO1/realtime/orientableroi.cpp
> Implement OrientableROI::GetLocalTransform

- LEGO1/lego/legoomni/src/common/mxtransitionmanager.cpp
Finally, 100% functional match (reg-swaps are present).
> match MxTransitionManager::MosaicTransition()

- LEGO1/lego/sources/anim/legoanim.cpp
- LEGO1/lego/sources/anim/legoanim.h
> Implement/match LegoAnimNodeData::FUN_100a0990

- LEGO1/lego/legoomni/include/hospital.h
- LEGO1/lego/legoomni/include/hospitalstate.h
- LEGO1/lego/legoomni/src/worlds/hospital.cpp
> implement/match Hospital::Create()

- LEGO1/lego/legoomni/include/legonavcontroller.h
- LEGO1/lego/legoomni/include/legopointofviewcontroller.h
- LEGO1/lego/legoomni/include/legosoundmanager.h
- LEGO1/lego/legoomni/src/audio/legosoundmanager.cpp
- LEGO1/lego/legoomni/src/entity/legonavcontroller.cpp
- LEGO1/lego/legoomni/src/entity/legopovcontroller.cpp
- LEGO1/lego/sources/roi/legoroi.cpp
- LEGO1/lego/sources/roi/legoroi.h
> Implement/match LegoPointOfViewController::Tickle

- LEGO1/lego/legoomni/src/worlds/hospital.cpp
> implement/match Hospital::~Hospital()

- LEGO1/lego/legoomni/include/hospital.h
- LEGO1/lego/legoomni/src/worlds/hospital.cpp
Enable() and VTable0x64() are 100% matching. Notify() should be functionally equivalent, think it doesn't match due to its jump table
> implement Hospital::Notify(), Enable(), VTable0x64()

- LEGO1/lego/legoomni/include/legoentity.h
- LEGO1/lego/legoomni/src/entity/legoentity.cpp
- LEGO1/lego/legoomni/src/entity/legopovcontroller.cpp
> Implement/match LegoEntity::GetWorldPosition/Direction/Up

- LEGO1/lego/legoomni/include/hospital.h
- LEGO1/lego/legoomni/src/worlds/hospital.cpp
> implement/match Hospital::Tickle()

- LEGO1/lego/legoomni/include/legobuildingmanager.h
- LEGO1/lego/legoomni/include/legocharactermanager.h
- LEGO1/lego/legoomni/include/legoplantmanager.h
- LEGO1/lego/legoomni/src/build/legobuildingmanager.cpp
- LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
- LEGO1/lego/legoomni/src/common/legoplantmanager.cpp
- LEGO1/lego/legoomni/src/entity/legoentity.cpp
> Implement/match LegoEntity::VTable0x3c

- LEGO1/lego/legoomni/include/act1state.h
- LEGO1/lego/legoomni/include/ambulance.h
- LEGO1/lego/legoomni/include/isle.h
- LEGO1/lego/legoomni/include/islepathactor.h
- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legogamestate.h
- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/include/legoutils.h
- LEGO1/lego/legoomni/include/legovideomanager.h
- LEGO1/lego/legoomni/include/legoworld.h
- LEGO1/lego/legoomni/include/racestate.h
- LEGO1/lego/legoomni/include/towtrack.h
- LEGO1/lego/legoomni/src/act1/act1state.cpp
- LEGO1/lego/legoomni/src/actors/ambulance.cpp
- LEGO1/lego/legoomni/src/actors/helicopter.cpp
- LEGO1/lego/legoomni/src/actors/jukeboxentity.cpp
- LEGO1/lego/legoomni/src/actors/towtrack.cpp
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/common/legoutils.cpp
- LEGO1/lego/legoomni/src/entity/legocameracontroller.cpp
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/video/legovideomanager.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
- LEGO1/mxgeometry/mxgeometry3d.h
Match is at ~94%, with most of the diff due to the jump tables.
> Implement/match Isle::Enable

- LEGO1/lego/legoomni/include/act1state.h
- LEGO1/lego/legoomni/src/act1/act1state.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
- LEGO1/omni/include/mxcore.h
Match at ~90%, with remaining diff looking like compiler randomness.
> Implement/match Isle::FUN_10032d30

- LEGO1/lego/legoomni/include/registrationbook.h
- LEGO1/lego/legoomni/src/worlds/registrationbook.cpp
> implement RegistrationBook::HandleClick

- LEGO1/lego/legoomni/include/isle.h
- LEGO1/lego/legoomni/include/islepathactor.h
- LEGO1/lego/legoomni/include/legogamestate.h
- LEGO1/lego/legoomni/src/actors/helicopter.cpp
- LEGO1/lego/legoomni/src/actors/islepathactor.cpp
- LEGO1/lego/legoomni/src/worlds/hospital.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
- LEGO1/lego/legoomni/src/worlds/registrationbook.cpp
- LEGO1/mxgeometry/mxmatrix.h
Match at ~79%, the remaining diff is jump table and what seems like a little bit of compiler randomness
> Implement/match Isle::FUN_10032620

- LEGO1/lego/legoomni/src/worlds/hospital.cpp
> implement/match Hospital::HandleKeyPress()

- LEGO1/lego/legoomni/include/act1state.h
- LEGO1/lego/legoomni/include/isle.h
- LEGO1/lego/legoomni/include/legobackgroundcolor.h
- LEGO1/lego/legoomni/include/legogamestate.h
- LEGO1/lego/legoomni/include/legoutils.h
- LEGO1/lego/legoomni/src/act1/act1state.cpp
- LEGO1/lego/legoomni/src/common/legobackgroundcolor.cpp
- LEGO1/lego/legoomni/src/common/legoutils.cpp
- LEGO1/lego/legoomni/src/worlds/elevatorbottom.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
~84% match, the rest is jump table
> Implement/match Isle::HandleClick

- LEGO1/lego/legoomni/src/common/legobackgroundcolor.cpp
100% matches. You can change the sky color and brightness now:
> Implement a few LegoBackgroundColor functions

- LEGO1/lego/legoomni/src/audio/legoloadcachesoundpresenter.cpp
- LEGO1/lego/legoomni/src/video/legopartpresenter.cpp
- LEGO1/lego/legoomni/src/video/legotexturepresenter.cpp
> implement misc presenter functions

- LEGO1/lego/legoomni/include/legoanimactor.h
- LEGO1/lego/legoomni/include/legocharactermanager.h
- LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
- LEGO1/lego/legoomni/src/common/legogamestate.cpp
- LEGO1/lego/legoomni/src/paths/legoanimactor.cpp
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
- LEGO1/lego/legoomni/src/video/legomodelpresenter.cpp
The match is at ~80%, most of the diff is due to the `LegoAnimActor` class structure being incorrect. Since it's a non-trivial structure including virtual inheritance it cannot be implemented easily in this PR.
> Implement LegoCharacterManager::GetROI

- LEGO1/lego/legoomni/include/legoutils.h
- LEGO1/lego/legoomni/src/actors/bike.cpp
- LEGO1/lego/legoomni/src/actors/helicopter.cpp
- LEGO1/lego/legoomni/src/common/legoutils.cpp
> implement RemoveFromCurrentWorld

- LEGO1/lego/legoomni/include/registrationbook.h
- LEGO1/lego/legoomni/src/worlds/registrationbook.cpp
- LEGO1/omni/include/mxcompositepresenter.h
- LEGO1/omni/src/common/mxutilities.cpp
RegistrationBook::CreateSurface and RegistrationBook::HandleKeyPress don't match, but functionality seems to be correct
> Implement a few registrationbook methods

- LEGO1/omni/include/mxdisplaysurface.h
- LEGO1/omni/src/video/mxdisplaysurface.cpp
This allows elevator buttons to light up, as well as other UI elements change bitmaps when clicked:
74.09% match
> Implement MxDisplaySurface::VTable0x30

- LEGO1/lego/legoomni/src/worlds/hospital.cpp
97.22% match due to ordering, should be functionally accurate.
> implement Hospital::HandleClick()

- LEGO1/lego/legoomni/src/worlds/hospital.cpp
Matching except for jump table.
> implement/match Hospital::HandleButtonDown()

- CMakeLists.txt
- LEGO1/lego/legoomni/include/act3.h
- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legocharactermanager.h
- LEGO1/lego/legoomni/include/legoentity.h
- LEGO1/lego/legoomni/include/legoomni.h
- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/include/legopathcontroller.h
- LEGO1/lego/legoomni/include/misc.h
- LEGO1/lego/legoomni/src/actors/helicopter.cpp
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
- LEGO1/lego/legoomni/src/common/misc.cpp
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/main/legoomni.cpp
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
- LEGO1/lego/legoomni/src/worlds/act3.cpp
Implement/match StartEntityAction
> Animmanager

- LEGO1/lego/legoomni/include/legocameracontroller.h
- LEGO1/lego/legoomni/src/entity/legocameracontroller.cpp
Match is at ~78%, but the rest is compiler randomness / instruction reordering. That is very common with the large matrix operations from `vec.h`.
> Implement/match LegoCameraController::FUN_100123e0

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legonavcontroller.h
- LEGO1/lego/legoomni/include/legoomni.h
- LEGO1/lego/legoomni/include/legovideomanager.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/common/legogamestate.cpp
- LEGO1/lego/legoomni/src/entity/legonavcontroller.cpp
- LEGO1/lego/legoomni/src/video/legovideomanager.cpp
Begin implementation of LegoNavController::Notify. I also implemented LegoVideoManager::ToggleFPS & LegoNavController::SetLocation which match.
> Begin LegoNavController::Notify

- LEGO1/lego/legoomni/include/policeentity.h
- LEGO1/lego/legoomni/src/police/policeentity.cpp
I thought that keeping it in the header was weird, so I moved it to the cpp file
> PoliceEntity::VTable0x50

- LEGO1/lego/legoomni/include/ambulance.h
- LEGO1/lego/legoomni/include/ambulancemissionstate.h
- LEGO1/lego/legoomni/include/legogamestate.h
- LEGO1/lego/legoomni/include/legovariables.h
- LEGO1/lego/legoomni/src/actors/ambulance.cpp
- LEGO1/lego/legoomni/src/common/legovariables.cpp
The destructor doesn't match for some reason. LegoGameState::RegisterState I also made public, because unless there is some inline function to access that, it needs to be called
> Ambulance::Create, dtor

- LEGO1/lego/legoomni/include/legopathcontroller.h
- LEGO1/lego/legoomni/include/legopathpresenter.h
- LEGO1/lego/legoomni/include/legoworld.h
- LEGO1/lego/legoomni/src/entity/legonavcontroller.cpp
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
- LEGO1/lego/legoomni/src/paths/legopathpresenter.cpp
Also changed g_debugPassword to char array. 100% matches
> Finish LegoPathPresenter

- LEGO1/lego/legoomni/src/entity/legonavcontroller.cpp
Matched LegoNavController::CalculateNewPosDir & LegoNavController::CalculateNewTargetVel
> Match 2 legonavcontroller functions

- LEGO1/lego/legoomni/src/actors/islepathactor.cpp
Matches, though I think reccmp doesn't know where the function ends
> IslePathActor: implement notify, remove usage of this keyword

- LEGO1/lego/legoomni/src/entity/legopovcontroller.cpp
> Match LegoPointOfViewController::Tickle

- LEGO1/lego/legoomni/src/common/legogamestate.cpp
Slight tweak to LegoGameState::RegisterState() that matches it to 100%.
> match LegoGameState::RegisterState()

- LEGO1/lego/legoomni/include/legoanimactor.h
- LEGO1/lego/legoomni/include/legocarraceactor.h
- LEGO1/lego/legoomni/include/legoextraactor.h
- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/include/legoraceactor.h
- LEGO1/lego/legoomni/src/entity/legocarraceactor.cpp
- LEGO1/lego/legoomni/src/paths/legoextraactor.cpp
- LEGO1/lego/legoomni/src/paths/legopathactor.cpp
- LEGO1/lego/legoomni/src/race/legoraceactor.cpp
> Implement ExtraActor vftable and passthrough methods

- LEGO1/lego/legoomni/include/hospitalentity.h
- LEGO1/lego/legoomni/src/hospital/hospitalentity.cpp
> implement/match HospitalEntity::VTable0x50()

- LEGO1/lego/legoomni/src/common/legoutils.cpp
> implement/match FUN_1003ef60()

- tools/isledecomp/isledecomp/bin.py
- tools/isledecomp/isledecomp/compare/core.py
- tools/isledecomp/isledecomp/compare/db.py
Debug builds typically use the linker option [`/incremental:yes`](https://learn.microsoft.com/en-us/cpp/build/reference/incremental-link-incrementally?view=msvc-170), and ours is no different. The effect is that most function calls are thunked: the `call` instruction takes you to the address of a `jmp` instruction that points to the actual code.
This can make things difficult to annotate and debug. While it's easy to find the location of the actual function, you won't see this in the asm diff output because of the indirection.
This change adds the ability to detect these thunks and add a stub annotation. We can tell whether the binary file is from a debug build based on the [data directory section of the PE header](https://learn.microsoft.com/en-us/cpp/build/reference/incremental-link-incr …
> Identify thunks in debug builds

- LEGO1/lego/legoomni/include/legoextraactor.h
- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/src/paths/legoextraactor.cpp
- LEGO1/lego/legoomni/src/paths/legopathactor.cpp
- LEGO1/realtime/matrix.h
- LEGO1/realtime/vector.h
100% match on a4.  Can't tell if FUN_1002aae0 is all compiler randomness or not, but I think there might be something with the `right` variable.  (I think I've named the components of the matrix correctly, but not entirely sure.)
Beta function at 0x10080f35, but it's clearly not exactly the same as release.
> Implement LegoExtraActor:: VTable0xa4 & FUN_1002aae0

- LEGO1/lego/legoomni/src/common/legoutils.cpp
> implement/match ReadNamedTexture()

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
> implement/match LegoAnimationManager::FindVehicle()

- tools/isledecomp/isledecomp/compare/asm/parse.py
- tools/isledecomp/tests/test_sanitize.py
In #748, we found a situation where incorrect code could appear to match due to incorrectly replacing address values with placeholders. The function in question is short, so I will place it here:
```cpp
// FUNCTION: LEGO1 0x10060140
MxBool LegoAnimationManager::FindVehicle(const char* p_name, MxU32& p_index)
{
for (MxS32 i = 0; i < _countof(g_vehicles); i++) {
if (!strcmpi(p_name, g_vehicles[i].m_name)) {
p_index = i;
return TRUE;
}
}
return FALSE;
}
```
This is the correct code, but we do not consider it matching 100% due to missing annotations. If the upper bound of the loop was `sizeof(g_vehicles)` instead, the function was scored at 100%.
The problem is subtle and has to do with an MSVC optimization. The assembly uses `EDI` for the value of the `i` variable, but also maintains `EBX` …
> reccmp: Don't use placeholder for address comparison

- LEGO1/lego/legoomni/include/legocharactermanager.h
- LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
> Implement/match LegoCharacterManager::GetRefCount

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
100% functional match. Open to naming suggestions if anyone can think of something more appropriate.
> implement/match LegoAnimationManager::DeleteAnimations()

- LEGO1/lego/legoomni/include/act3.h
- LEGO1/lego/legoomni/include/infocenterentity.h
- LEGO1/lego/legoomni/include/isle.h
- LEGO1/lego/legoomni/include/legoact2.h
- LEGO1/lego/legoomni/include/legoact2state.h
- LEGO1/lego/legoomni/include/policeentity.h
- LEGO1/lego/legoomni/src/actors/helicopter.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenterentity.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
not there yet, still some weird things to root out.
Giving InfoCenterEntity the same treatment as PoliceEntity in #720 . Similar, but a bit more complicated. Maybe this has to do with what makes the information center act differently (the red background) during different acts
----
Now 83% match, a few weird register shifts
> InfoCenterEntity::VTable0x50 implementation

- LEGO1/lego/legoomni/include/legocharactermanager.h
- LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
100% matches (except for the offset in `GetData` which we can't match yet)
> Implement/match LegoCharacterData::GetData and FUN_10085140

- LEGO1/lego/legoomni/include/legobackgroundcolor.h
- LEGO1/lego/legoomni/src/common/legobackgroundcolor.cpp
- LEGO1/lego/legoomni/src/common/legogamestate.cpp
- LEGO1/lego/legoomni/src/common/legoutils.cpp
- LEGO1/lego/sources/3dmanager/legoview1.cpp
- LEGO1/lego/sources/3dmanager/legoview1.h
> Implement/match LegoBackgroundColor::SetLightColor and related

- LEGO1/lego/legoomni/include/legocharactermanager.h
- LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
> Implement/match LegoCharacterManager::FUN_10085210

- LEGO1/lego/legoomni/include/legocharactermanager.h
- LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
100% match.
Also improved match of `CreateROI` from ~80% to ~95%
> Implement/match LegoCharacterManager::FUN_10084ec0

- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/src/paths/legopathactor.cpp
Technically, the dtor is implemented as well, but the type is unknown and so it's a poor match.  I left it at STUB because of this. Member 0x134 doesn't seem to actually be initialized anywhere, and about the only references I could find to it anywhere were to delete it.
> Implement/Match LegoPathActor ctor

- LEGO1/lego/legoomni/include/legocharactermanager.h
- LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
> Implement/match LegoCharacterManager::FUN_10084cf0

- LEGO1/lego/legoomni/include/legocharactermanager.h
- LEGO1/lego/legoomni/include/legoentity.h
- LEGO1/lego/legoomni/include/legounknown100d5778.h
- LEGO1/lego/legoomni/src/audio/legounknown100d5778.cpp
- LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
~98% match, rest is compiler randomness.
> Implement/match LegoCharacterManager::FUN_10083f10

- LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
~80% match, but rest looks very much like usual compiler randomness.
> Implement LegoCharacterManager::FUN_10083db0

- LEGO1/viewmanager/viewmanager.cpp
> Implement/match ViewManager::Pick

- LEGO1/lego/legoomni/include/gasstation.h
- LEGO1/lego/legoomni/include/gasstationstate.h
- LEGO1/lego/legoomni/src/gasstation/gasstationstate.cpp
- LEGO1/lego/legoomni/src/worlds/gasstation.cpp
These are just annoying. Still nothing happening in the world yet. Just crashes.
> More gasstation functions

- LEGO1/lego/legoomni/include/legobuildingmanager.h
- LEGO1/lego/legoomni/include/legoentity.h
- LEGO1/lego/legoomni/include/legoeventnotificationparam.h
- LEGO1/lego/legoomni/include/legoplantmanager.h
- LEGO1/lego/legoomni/src/build/legobuildingmanager.cpp
- LEGO1/lego/legoomni/src/common/legoplantmanager.cpp
- LEGO1/lego/legoomni/src/entity/legoentity.cpp
> Implement/match LegoEntity::Notify

- LEGO1/lego/legoomni/include/legoinputmanager.h
- LEGO1/lego/legoomni/src/input/legoinputmanager.cpp
~97% match, rest most likely compiler randomness.
You can now enter some buildings from the isle:
https://github.com/isledecomp/isle/assets/1135351/b8fd59be-f2ef-47d3-b418-619761d58399
> Implement/match LegoInputManager::FUN_1005cdf0

- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/src/paths/legopathactor.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
- LEGO1/mxgeometry/mxgeometry3d.h
- LEGO1/mxgeometry/mxmatrix.h
- LEGO1/realtime/matrix.h
- LEGO1/realtime/vector.h
- LEGO1/viewmanager/viewmanager.cpp
This should've been a relatively straightforward function, except it's inlining basically all of the operator = calls, and I can't figure out how to prevent it from doing so.
> Implement PathActor VTable0x80 and PathActorStruct FUN_1009a140

- CMakeLists.txt
- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/sources/geom/legoedge.cpp
- LEGO1/lego/sources/geom/legoedge.h
- LEGO1/lego/sources/geom/legoweedge.cpp
- LEGO1/lego/sources/geom/legoweedge.h
100% match.  This is presumably a struct, not a class. Members are accessed directly in beta code, aside from these 4 helper functions.  Tested by temporarily adding dummy calls.
> Refactor/Implement/Match LegoEdge

- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/include/legocharactermanager.h
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
- LEGO1/lego/sources/anim/legoanim.h
~100% match, also added some missing annotations
> Implement/match LegoAnimPresenter::FUN_1006a4f0

- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/src/paths/legopathactor.cpp
Still some issues. There's the vector initialization, and then there's a stubborn if/else block at the end. I tried the condition/if/else both ways and it didn't make a difference. I'm not sure what I'm missing.
> Implement LegoPathActor::Vtable0x84

- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
~94% match, rest looks like compiler randomness
> Implement/match LegoAnimPresenter::FUN_10069b10

- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/include/legoroilist.h
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
> Implement/match LegoAnimPresenter::FUN_100699e0

- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/include/legoentity.h
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
> Implement/match LegoAnimPresenter::FUN_1006c8a0

- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
> Implement/match LegoAnimPresenter::FUN_1006abb0

- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
- LEGO1/realtime/vector.h
Match is ~90%, rest looks like compiler randomness
> Implement/match LegoAnimPresenter::PutFrame

- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
- LEGO1/lego/sources/anim/legoanim.cpp
- LEGO1/lego/sources/anim/legoanim.h
> Implement/match LegoAnimPresenter::FUN_1006b9a0

- LEGO1/lego/legoomni/include/legoworld.h
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
100% match. Also added a few things to LegoAnimPresenter::EndAction to prevent crash
> implement LegoAnimPresenter::VTable0x8c

- LEGO1/lego/legoomni/include/legoutils.h
- LEGO1/lego/legoomni/src/common/legoutils.cpp
- LEGO1/lego/sources/anim/legoanim.h
This function is responsible for setting the camera position according to animation data. Something is wrong with it as the camera position is set in the middle of nowhere. Not sure what is wrong with it. Other functions match
> implement FUN_1003e050

- LEGO1/lego/sources/roi/legoroi.cpp
- LEGO1/lego/sources/roi/legoroi.h
> Implement/match LegoROI::FUN_100a8e80

- LEGO1/lego/sources/anim/legoanim.cpp
- LEGO1/lego/sources/anim/legoanim.h
Animations now work!
https://github.com/isledecomp/isle/assets/106913236/3656f0f8-2a48-4d91-ac1f-0dc48ff5bbb8
> implement LegoAnimNodeData::FindKeys

- LEGO1/lego/legoomni/src/video/legovideomanager.cpp
You can now access the credits:
> Implement LegoVideoManager::FUN_1007c520

- LEGO1/lego/legoomni/src/paths/legopathactor.cpp
Also fixed a logical error in 8c, and matched it better. Still not 100%, but might be as close as we can get, rest seems to be randomness.
> Implement/Match LegoPathActor::VTable0x74

- LEGO1/realtime/matrix.h
Match at ~90%, fixes the animations:
https://github.com/isledecomp/isle/assets/1135351/4dd47dd2-4173-4d06-bdaf-fe62d76b9915
> Implement Matrix4::FromQuaternion

- LEGO1/lego/legoomni/src/common/legotextureinfo.cpp
100% match. Phonemes are now working:
https://github.com/isledecomp/isle/assets/1135351/2970e7f9-70de-4c8e-91f4-25773a935ec9
> Implement/match LegoTextureInfo::FUN_10066010

- LEGO1/lego/legoomni/include/legocharactermanager.h
- LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
- LEGO1/lego/legoomni/src/video/legophonemepresenter.cpp
- LEGO1/lego/sources/misc/legocontainer.cpp
- LEGO1/lego/sources/misc/legocontainer.h
100% match. Also renamed the "texture list" to cached texture list.
> Implement/match LegoPhonemePresenter::EndAction

- LEGO1/omni/include/mxomnicreateflags.h
- LEGO1/omni/include/mxomnicreateparam.h
- LEGO1/omni/src/main/mxomnicreateflags.cpp
- LEGO1/omni/src/main/mxomnicreateparam.cpp
The beta shows that this class uses the bitmask struct `FlagBitfield` from MxTypes.h. Similar to other flag-type classes.
I removed the extra setters because they don't appear to be used.
> Beta matching MxOmniCreateFlags

- LEGO1/define.cpp
- LEGO1/define.h
- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legoomni.h
- LEGO1/lego/legoomni/include/legotraninfo.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/entity/legoentity.cpp
- LEGO1/lego/legoomni/src/main/legoomni.cpp
- LEGO1/omni/include/mxdsaction.h
- LEGO1/omni/src/action/mxdsaction.cpp
Match is at ~84% due to `StartActionIfUnknown0x13c` not inlining correctly. Implements the `LegoTranInfo` structure.
> Implement LegoAnimationManager::FUN_100609f0 / LegoTranInfo

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legoanimmmpresenter.h
- LEGO1/lego/legoomni/include/legotraninfo.h
- LEGO1/lego/legoomni/include/legotraninfolist.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/common/legoanimmmpresenter.cpp
> Imlpement/match LegoAnimMMPresenter::ParseExtra and related

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legoanimmmpresenter.h
- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/include/legotraninfo.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/common/legoanimmmpresenter.cpp
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
> Implement/match LegoAnimMMPresenter::ReadyTickle

- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/include/legotraninfo.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/common/legoanimmmpresenter.cpp
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
> Implement/match LegoAnimMMPresenter::StartingTickle

- LEGO1/lego/legoomni/include/legoanimmmpresenter.h
- LEGO1/lego/legoomni/src/common/legoanimmmpresenter.cpp
> Implement/match LegoAnimMMPresenter Streaming/RepeatingTickle and Notify

- LEGO1/lego/legoomni/src/common/legoanimmmpresenter.cpp
- LEGO1/omni/include/mxtype18notificationparam.h
> Implement/match LegoAnimMMPresenter::EndAction

- LEGO1/lego/legoomni/include/legoanimmmpresenter.h
- LEGO1/lego/legoomni/src/common/legoanimmmpresenter.cpp
- LEGO1/lego/legoomni/src/common/mxcompositemediapresenter.cpp
- LEGO1/omni/include/mxpresenter.h
- LEGO1/omni/include/mxvideopresenter.h
- LEGO1/omni/src/common/mxmediapresenter.cpp
- LEGO1/omni/src/common/mxpresenter.cpp
- LEGO1/omni/src/video/mxloopingflcpresenter.cpp
- LEGO1/omni/src/video/mxloopingsmkpresenter.cpp
- LEGO1/omni/src/video/mxstillpresenter.cpp
- LEGO1/omni/src/video/mxvideopresenter.cpp
> Implement/match LegoAnimMMPresenter::FUN_1004b450

- LEGO1/lego/legoomni/include/legoanimmmpresenter.h
- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/src/common/legoanimmmpresenter.cpp
- LEGO1/lego/legoomni/src/paths/legoextraactor.cpp
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
- LEGO1/lego/legoomni/src/video/legolocomotionanimpresenter.cpp
> Implement/match LegoAnimMMPresenter::FUN_1004b530

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legoanimmmpresenter.h
- LEGO1/lego/legoomni/include/legotraninfo.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/common/legoanimmmpresenter.cpp
> Implement/match LegoAnimMMPresenter::FUN_1004b580

- LEGO1/lego/legoomni/include/legoanimmmpresenter.h
- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/src/common/legoanimmmpresenter.cpp
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
> Implement/match LegoAnimMMPresenter::FUN_1004b5b0

- LEGO1/lego/legoomni/src/common/legoanimmmpresenter.cpp
> Implement/match LegoAnimMMPresenter::FUN_1004b610 and FUN_1004b6b0

- LEGO1/lego/legoomni/include/legoworld.h
- LEGO1/lego/legoomni/src/common/legoanimmmpresenter.cpp
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
100% match. Paper planes work now:
https://github.com/isledecomp/isle/assets/1135351/ef7bd51c-1b09-41bd-9c18-c7d08ee1b70a
> Implement/match LegoAnimMMPresenter::FUN_1004b6d0

- LEGO1/lego/legoomni/include/legoanimmmpresenter.h
- LEGO1/lego/legoomni/src/common/legoanimmmpresenter.cpp
> Implement/match LegoAnimMMPresenter::~LegoAnimMMPresenter

- LEGO1/lego/legoomni/include/legocharactermanager.h
- LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
- LEGO1/lego/legoomni/src/entity/legoentity.cpp
https://github.com/isledecomp/isle/assets/1135351/f4903b2c-07f4-47cf-9df2-98b3bfb84292
> Fix SwitchHat

- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
> Implement/match LegoAnimPresenter::EndAction

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
> Implement/match LegoAnimPresenter::FUN_1006ab70

- LEGO1/lego/legoomni/include/legopathcontroller.h
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
> Implement/match LegoWorld::FUN_1001fda0

- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
- LEGO1/mxgeometry/mxmatrix.h
> Implement/match LegoAnimPresenter::FUN_1006afc0

- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
- LEGO1/lego/sources/roi/legoroi.cpp
- LEGO1/lego/sources/roi/legoroi.h
> Implement/match LegoAnimPresenter::FUN_1006b900

- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
> Implement/match LegoAnimPresenter::SubstituteVariables

- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
> Implement/match LegoAnimPresenter::FUN_1006aa60

- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
~94% match, rest looks like entropy
> Implement/match LegoAnimPresenter::VTable0x94

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
100% matches (some entropy in dtor)
> Implement/match LegoAnimationManager ctor/dtor

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
> Implement/match LegoAnimationManager::Init

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
> Implement/match LegoAnimationManager::FUN_10063780 and FUN_10063aa0

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
> Implement/match LegoAnimationManager::FUN_10062770

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
> Implement/match LegoAnimationManager::GetCharacterIndex

- LEGO1/lego/legoomni/include/pizzeria.h
- LEGO1/lego/legoomni/src/actors/isleactor.cpp
- LEGO1/lego/legoomni/src/actors/pizzeria.cpp
100% match. Pizzeria is now rendered:
> Implement/match Pizzeria::Create

- LEGO1/lego/legoomni/include/legocontrolmanager.h
- LEGO1/lego/legoomni/include/pizza.h
- LEGO1/lego/legoomni/include/skateboard.h
- LEGO1/lego/legoomni/src/actors/pizza.cpp
- LEGO1/lego/legoomni/src/actors/skateboard.cpp
Hello everyone,
this project sparked my curiosity, so I started working getting into it a bit. I implemented some of the methods on the `SkateBoard` class. Those that I covered got a 100 % match. I am still rather new to decompilation, so feedback and changes are very much welcome.
The type of the result of `CurrentWorld()->Find()` is an educated guess, since the function bodys `FUN_100381b0()` and `FUN_100382b()` that are called on the result are located in the middle of `Pizza` implementations.
If these commits look fine to you, I will try to finish this class soon.
> Progress towards implementing SkateBoard

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/common/legogamestate.cpp
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
> Implement/match LegoAnimationManager::Resume

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
> Implement/match LegoAnimationManager::Suspend

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
> Implement/match LegoAnimationManager::FUN_1005f6d0 and FUN_1005f700

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legotraninfo.h
- LEGO1/lego/legoomni/include/legovideomanager.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
> Implement/match LegoAnimationManager::Tickle

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
> Implement/match LegoAnimationManager::FUN_10060570

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legoanimmmpresenter.h
- LEGO1/lego/legoomni/src/actors/islepathactor.cpp
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/common/legoanimmmpresenter.cpp
- LEGO1/lego/legoomni/src/entity/legonavcontroller.cpp
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/gasstation/gasstationentity.cpp
- LEGO1/lego/legoomni/src/hospital/hospitalentity.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenterentity.cpp
- LEGO1/lego/legoomni/src/isle/beachhouseentity.cpp
- LEGO1/lego/legoomni/src/police/policeentity.cpp
- LEGO1/lego/legoomni/src/race/racestandsentity.cpp
Unfortunately a fairly poor match at ~48%. There's some sort of construct probably related to the flags that I can't make sense of for now. The beta version of that function doesn't have all that extra logic so it's of little help.
> Implement LegoAnimationManager::FUN_10061010

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
> Implement/match LegoAnimationManager::FUN_10061530

- LEGO1/lego/legoomni/include/legobuildingmanager.h
- LEGO1/lego/legoomni/include/legocachsound.h
- LEGO1/lego/legoomni/include/legopathcontroller.h
- LEGO1/lego/legoomni/include/legounknown100d5778.h
- LEGO1/lego/legoomni/include/legoworld.h
- LEGO1/lego/legoomni/src/audio/legocachsound.cpp
- LEGO1/lego/legoomni/src/audio/legounknown100d5778.cpp
- LEGO1/lego/legoomni/src/build/legobuildingmanager.cpp
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
- LEGO1/lego/sources/geom/legowegedge.h
- LEGO1/realtime/matrix.h
* 100% match most of the remaining methods, only Tickle and FUN_10030630 remain.
* The interesting finding is that the curious members of the LegoBuildingManager form a short embedded fixed-length array used to store info about current animation of buildings.
* I saw that you removed the SetY which I had added to MxMatrix. Agree that this method doesn't make sense on MxMatrix, however I've added it back to Matrix4. I see the pattern of setting / getting the Y component used in enough places that I doubt they were just hoping they remembered the subscript correctly every time. Let me know if you agree or still don't think it makes sense to include.
> LegoBuildingManager Round 2

- LEGO1/lego/legoomni/include/animstate.h
- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legoworld.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
> Implement/match LegoAnimationManager::FUN_100623a0

- LEGO1/lego/legoomni/include/animstate.h
- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
> Implement/match LegoAnimationManager::ModelExists

- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
> Implement/match LegoAnimationManager::FUN_10062580

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/realtime/vector.h
> Implement/match LegoAnimationManager::FUN_10062650

- LEGO1/lego/legoomni/include/legogamestate.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
> Implement/match LegoAnimationManager::FUN_10062710

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
> Implement/match LegoAnimationManager::FUN_100627d0

- LEGO1/lego/legoomni/include/legocharactermanager.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
> Implement/match LegoCharacterManager::FUN_10083b20 and FUN_10085180

- LEGO1/lego/legoomni/include/islepathactor.h
- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/include/legopathcontroller.h
- LEGO1/lego/legoomni/src/actors/islepathactor.cpp
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/paths/legopathactor.cpp
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
- LEGO1/lego/sources/geom/legounkown100db7f4.h
- LEGO1/lego/sources/geom/legoweedge.h
> Implement/match LegoPathController::FUN_10045c20 and LegoPathController ctor

- CMakeLists.txt
- LEGO1/lego/legoomni/include/legopathboundary.h
- LEGO1/lego/legoomni/include/legopathcontroller.h
- LEGO1/lego/legoomni/include/legopathstruct.h
- LEGO1/lego/legoomni/src/paths/legopathboundary.cpp
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
- LEGO1/lego/legoomni/src/paths/legopathpresenter.cpp
- LEGO1/lego/legoomni/src/paths/legopathstruct.cpp
- LEGO1/lego/sources/geom/legounkown100db7f4.cpp
- LEGO1/lego/sources/geom/legounkown100db7f4.h
- LEGO1/library_msvc.h
> Implement/match LegoPathController::Read

- LEGO1/lego/sources/3dmanager/legoview1.cpp
- LEGO1/lego/sources/3dmanager/legoview1.h
- LEGO1/lego/sources/3dmanager/tglsurface.cpp
- LEGO1/lego/sources/3dmanager/tglsurface.h
- LEGO1/mxdirectx/mxstopwatch.h
A few minor changes, no new diffs on the build. Just tying this off before I start looking at the other tgl stuff that _is_ different.
> Beta addrs for TglSurface and related

- LEGO1/lego/legoomni/include/legopathstruct.h
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
> Implement/match LegoPathController::FUN_10047b30

- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/include/legopathcontroller.h
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
- LEGO1/lego/sources/geom/legounkown100db7f4.cpp
- LEGO1/lego/sources/geom/legounkown100db7f4.h
> Implement/match LegoPathController::ReadEdge

- LEGO1/lego/legoomni/include/legopathcontroller.h
- LEGO1/lego/legoomni/include/legopathstruct.h
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
- LEGO1/lego/sources/geom/legoweedge.h
- LEGO1/lego/sources/geom/legowegedge.cpp
- LEGO1/lego/sources/geom/legowegedge.h
- LEGO1/mxgeometry/mxgeometry3d.h
100% match. Spawn locations work now:
https://github.com/isledecomp/isle/assets/1135351/d3b5f41d-f7ca-47dc-bf9c-8a8bcce98a77
> Implement/match LegoPathController::ReadBoundaries

- LEGO1/lego/legoomni/include/legopathcontroller.h
- LEGO1/lego/legoomni/include/legopathstruct.h
- LEGO1/lego/legoomni/src/main/legomain.cpp
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
- LEGO1/realtime/vector.h
> Implement/match LegoPathController::Create and Init

- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
> Implement/match LegoPathController::Destroy

- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/include/legopathcontroller.h
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
> Implement/match LegoPathController::Tickle

- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/include/legopathboundary.h
- LEGO1/lego/legoomni/include/legopathcontroller.h
- LEGO1/lego/legoomni/include/legopathstruct.h
- LEGO1/lego/legoomni/include/legoworld.h
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/paths/legopathboundary.cpp
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
- LEGO1/lego/sources/geom/legowegedge.cpp
- LEGO1/lego/sources/geom/legowegedge.h
100% matches (some with entropy)
> Implement various small LegoPathController functions

- LEGO1/lego/legoomni/include/legopathboundary.h
- LEGO1/lego/legoomni/include/legopathcontroller.h
- LEGO1/lego/legoomni/include/legoworld.h
- LEGO1/lego/legoomni/src/actors/helicopter.cpp
- LEGO1/lego/legoomni/src/actors/islepathactor.cpp
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/common/legoanimmmpresenter.cpp
- LEGO1/lego/legoomni/src/common/legogamestate.cpp
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/paths/legoextraactor.cpp
- LEGO1/lego/legoomni/src/paths/legopathactor.cpp
- LEGO1/lego/legoomni/src/paths/legopathboundary.cpp
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
> Implement/match LegoPathController::AddActor and RemoveActor

- LEGO1/lego/legoomni/include/legopathboundary.h
- LEGO1/lego/legoomni/include/legopathcontroller.h
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
- LEGO1/lego/sources/geom/legounkown100db7f4.h
- LEGO1/mxgeometry/mxgeometry3d.h
~95% match, minor inaccuracies
> Implement/match LegoPathController::FUN_10046050

- LEGO1/lego/legoomni/include/legovideomanager.h
- LEGO1/lego/legoomni/src/video/legovideomanager.cpp
> Match LegoVideoManager::Destroy

- LEGO1/lego/legoomni/include/legopathboundary.h
- LEGO1/lego/legoomni/src/paths/legopathboundary.cpp
> Implement/match LegoPathBoundary ctor/dtor

- LEGO1/lego/legoomni/include/legohideanimpresenter.h
- LEGO1/lego/legoomni/src/video/legohideanimpresenter.cpp
> Implement/match some LegoHideAnimPresenter functions

- LEGO1/lego/legoomni/include/infocenterstate.h
- LEGO1/lego/legoomni/src/act1/act1state.cpp
- LEGO1/lego/legoomni/src/build/legobuildingmanager.cpp
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
- LEGO1/lego/legoomni/src/common/legogamestate.cpp
- LEGO1/lego/legoomni/src/common/legotextureinfo.cpp
- LEGO1/lego/legoomni/src/entity/legoactor.cpp
- LEGO1/lego/legoomni/src/entity/legonavcontroller.cpp
- LEGO1/lego/legoomni/src/infocenter/infocenterstate.cpp
- LEGO1/lego/legoomni/src/input/legoinputmanager.cpp
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
- LEGO1/lego/legoomni/src/video/legolocomotionanimpresenter.cpp
- LEGO1/lego/legoomni/src/worlds/historybook.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
- LEGO1/lego/sources/misc/legounknown.cpp
- LEGO1/lego/sources/roi/legolod.cpp
- LEGO1/lego/sources/roi/legoroi.cpp
- LEGO1/mxdirectx/mxdirectdraw.cpp
- util/decomp.h
A beta assert at `100c2d9a` reveals that they used a macro that presumably worked just like our `_countof`, so I've renamed it to their version.
> Rename _countof to sizeOfArray

- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/include/legohideanimpresenter.h
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
- LEGO1/lego/legoomni/src/video/legohideanimpresenter.cpp
- LEGO1/lego/sources/anim/legoanim.h
- LEGO1/lego/sources/geom/legowegedge.h
Most functions are matching, `FUN_1006db60` has an issue with the setting of the flag that worsens the match.
> Implement/match remaining LegoHideAnimPresenter functions

- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/src/paths/legopathpresenter.cpp
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
- LEGO1/lego/legoomni/src/video/legoloopinganimpresenter.cpp
- LEGO1/omni/include/mxdschunk.h
- LEGO1/omni/src/audio/mxwavepresenter.cpp
- LEGO1/omni/src/common/mxmediapresenter.cpp
- LEGO1/omni/src/stream/mxdsbuffer.cpp
- LEGO1/omni/src/stream/mxdschunk.cpp
- LEGO1/omni/src/stream/mxdssubscriber.cpp
- LEGO1/omni/src/stream/mxramstreamprovider.cpp
- LEGO1/omni/src/stream/mxstreamchunk.cpp
- LEGO1/omni/src/stream/mxstreamcontroller.cpp
- LEGO1/omni/src/video/mxloopingflcpresenter.cpp
- LEGO1/omni/src/video/mxloopingsmkpresenter.cpp
- LEGO1/omni/src/video/mxvideopresenter.cpp
It just has two functions - 100% matches (with entropy)
Also renamed the chunk flags based on a Beta assert
https://github.com/isledecomp/isle/assets/1135351/5fcc2459-1105-44ea-acf0-5c804d9c955d
> Implement/match LegoLoopingAnimPresenter

- LEGO1/lego/legoomni/include/legolocomotionanimpresenter.h
- LEGO1/lego/legoomni/include/legoroimaplist.h
- LEGO1/lego/legoomni/src/video/legolocomotionanimpresenter.cpp
> Implement/match LegoLocomotionAnimPresenter

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legotraninfo.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/mxgeometry/mxgeometry3d.h
- LEGO1/mxgeometry/mxmatrix.h
> Implement/match LegoAnimationManager::FUN_10064b50

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legoextraactor.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/paths/legoextraactor.cpp
~84% match, bust rest looks like entropy
> Implement/match LegoAnimationManager::FUN_10064380

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
100% matches
https://github.com/isledecomp/isle/assets/1135351/1c801f18-777c-49a9-bb4b-2837bb39eba5
> Implement/match LegoAnimationManager::FUN_10064740 and FUN_10064670

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legoutils.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/common/legoutils.cpp
> Implement/match FUN_1003ef00 and related

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/sources/geom/legounkown100db7f4.h
- LEGO1/lego/sources/geom/legowegedge.h
> Implement/match LegoAnimationManager::FUN_10064120

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
~75% match - known issue with inlining of vector assignment/construction
> Implement LegoAnimationManager::FUN_10064010

- LEGO1/viewmanager/viewmanager.cpp
- LEGO1/viewmanager/viewmanager.h
> Implement/match ViewManager::FUN_100a6150

- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
> Implement/match LegoAnimationManager::FUN_10063fb0

- LEGO1/lego/legoomni/src/paths/legopathactor.cpp
- LEGO1/lego/legoomni/src/paths/legopathboundary.cpp
- LEGO1/lego/sources/geom/legounkown100db7f4.cpp
- LEGO1/lego/sources/geom/legounkown100db7f4.h
- LEGO1/lego/sources/geom/legowegedge.h
~97% match, rest looks like entropy
> Implement/match LegoPathBoundary::Intersect

- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/src/paths/legopathactor.cpp
Match only at ~60%. Unfortunately this function isn't present in that way in the BETA. It uses an inline function with recursion. The stack allocation isn't quite right at the moment, but it should be functionally accurate.
> Implement LegoPathActor::VTable0x68

- LEGO1/lego/sources/misc/legounknown.cpp
- LEGO1/lego/sources/misc/legounknown.h
- LEGO1/realtime/vector.h
~72% match. Should be accurate functionally but bad stack allocation
> Implement LegoUnknown::FUN_1009a1e0

- LEGO1/lego/legoomni/include/act2actor.h
- LEGO1/lego/legoomni/include/legocarraceactor.h
- LEGO1/lego/legoomni/include/legoextraactor.h
- LEGO1/lego/legoomni/include/legojetski.h
- LEGO1/lego/legoomni/include/legojetskiraceactor.h
- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/include/legopathboundary.h
- LEGO1/lego/legoomni/include/legopathcontroller.h
- LEGO1/lego/legoomni/include/legopathedgecontainer.h
- LEGO1/lego/legoomni/include/legoracecar.h
- LEGO1/lego/legoomni/src/actors/act2actor.cpp
- LEGO1/lego/legoomni/src/entity/legocarraceactor.cpp
- LEGO1/lego/legoomni/src/entity/legojetski.cpp
- LEGO1/lego/legoomni/src/entity/legojetskiraceactor.cpp
- LEGO1/lego/legoomni/src/paths/legoextraactor.cpp
- LEGO1/lego/legoomni/src/paths/legopathactor.cpp
- LEGO1/lego/legoomni/src/paths/legopathboundary.cpp
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
- LEGO1/lego/legoomni/src/race/legoracecar.cpp
> Implement/match LegoPathController::FUN_1004a240

- LEGO1/lego/legoomni/include/legocarraceactor.h
- LEGO1/lego/legoomni/include/legojetski.h
- LEGO1/lego/legoomni/include/legojetskiraceactor.h
- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/include/legopathcontroller.h
- LEGO1/lego/legoomni/include/legopathedgecontainer.h
- LEGO1/lego/legoomni/include/legoracecar.h
- LEGO1/lego/legoomni/src/entity/legocarraceactor.cpp
- LEGO1/lego/legoomni/src/entity/legojetski.cpp
- LEGO1/lego/legoomni/src/entity/legojetskiraceactor.cpp
- LEGO1/lego/legoomni/src/paths/legoextraactor.cpp
- LEGO1/lego/legoomni/src/paths/legopathactor.cpp
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
- LEGO1/lego/legoomni/src/race/legoracecar.cpp
Match is relatively poor at ~30%. A large amount of inline functions makes matching it difficult, and the BETA version of the function is of limited use. Functionally should be correct.
> Implement LegoPathActor::VTable0x9c

- LEGO1/lego/legoomni/include/legocarraceactor.h
- LEGO1/lego/legoomni/include/legoextraactor.h
- LEGO1/lego/legoomni/include/legojetski.h
- LEGO1/lego/legoomni/include/legojetskiraceactor.h
- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/include/legopathboundary.h
- LEGO1/lego/legoomni/include/legoracecar.h
- LEGO1/lego/legoomni/src/entity/legocarraceactor.cpp
- LEGO1/lego/legoomni/src/entity/legojetski.cpp
- LEGO1/lego/legoomni/src/entity/legojetskiraceactor.cpp
- LEGO1/lego/legoomni/src/paths/legoextraactor.cpp
- LEGO1/lego/legoomni/src/paths/legopathactor.cpp
- LEGO1/lego/legoomni/src/paths/legopathboundary.cpp
- LEGO1/lego/legoomni/src/race/legoracecar.cpp
- LEGO1/lego/sources/geom/legounkown100db7f4.h
100% match. Paths work now:
https://github.com/isledecomp/isle/assets/1135351/67dc614b-7266-43c4-b149-1ede43007510
> Implement/match LegoPathActor::SwitchBoundary

- LEGO1/lego/legoomni/include/isle.h
- LEGO1/lego/legoomni/include/jukeboxstate.h
- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legohideanimpresenter.h
- LEGO1/lego/legoomni/include/legopathcontroller.h
- LEGO1/lego/legoomni/include/legopathstruct.h
- LEGO1/lego/legoomni/include/legoutils.h
- LEGO1/lego/legoomni/include/legoworld.h
- LEGO1/lego/legoomni/src/actors/islepathactor.cpp
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/common/legoutils.cpp
- LEGO1/lego/legoomni/src/paths/legopathboundary.cpp
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
- LEGO1/lego/legoomni/src/paths/legopathstruct.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
- LEGO1/lego/sources/geom/legowegedge.cpp
- LEGO1/lego/sources/geom/legowegedge.h
- tools/ncc/ncc.style
`LegoPathStruct` handles "triggers" that, while moving across the island, cause the music to change, actors to spawn, animations to play etc. - 100% matches except on the main function with ~85% (partially off stack allocation).
https://github.com/isledecomp/isle/assets/1135351/3759113f-1070-48ed-b480-7895c65db27b
> Implement/match LegoPathStruct

- LEGO1/lego/legoomni/include/isle.h
- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/paths/legopathactor.cpp
- LEGO1/lego/legoomni/src/paths/legopathboundary.cpp
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
- LEGO1/lego/legoomni/src/paths/legopathstruct.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
- LEGO1/lego/sources/geom/legowegedge.cpp
- LEGO1/lego/sources/geom/legowegedge.h
100% matches. Also improved some naming
> Implement/match LegoPathActor::VTable0xa4 and VTable0xa8

- LEGO1/lego/legoomni/src/worlds/isle.cpp
> Implement/match Isle::FUN_10033350

- LEGO1/lego/legoomni/include/isle.h
- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
- LEGO1/omni/include/mxtype19notificationparam.h
> Implement/match Isle::HandleType19Notification

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legocharactermanager.h
- LEGO1/lego/legoomni/include/legocharacters.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
> Implement/match LegoAnimationManager::FUN_10063b90

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/src/actors/helicopter.cpp
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/sources/anim/legoanim.cpp
- LEGO1/mxgeometry/mxgeometry3d.h
> Implement/match LegoAnimationManager::FUN_100648f0

- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
- LEGO1/lego/sources/roi/legoroi.cpp
- LEGO1/lego/sources/roi/legoroi.h
Poor match at ~30% - very large amount of inline functions involved, stack allocation incorrect
> Implement LegoROI::FUN_100a9410

- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/src/paths/legoextraactor.cpp
- LEGO1/lego/legoomni/src/paths/legopathactor.cpp
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
~84% match, `find` isn't inlined correctly
> Implement/match LegoExtraActor::VTable0x6c

- LEGO1/lego/legoomni/src/actors/islepathactor.cpp
> Implement/match IslePathActor::FUN_1001b660

- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/include/legopathboundary.h
- LEGO1/lego/legoomni/src/paths/legopathboundary.cpp
- LEGO1/lego/sources/geom/legowegedge.h
Matches except for some entropy and (likely) a type mismatch with the STL set, see the comments
> Implement/match LegoPathBoundary::FUN_100586e0 and FUN_10057fe0

- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
- LEGO1/realtime/matrix.h
Match at ~80%, mainly stack allocation shifted
> Implement/match LegoAnimPresenter::FUN_1006b140

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
> Implement/match LegoAnimationManager::FUN_10063270

- LEGO1/lego/legoomni/include/legoanimpresenter.h
- LEGO1/lego/legoomni/src/common/legoanimmmpresenter.cpp
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
> Implement/match LegoAnimMMPresenter::FUN_1004b840

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legopathcontroller.h
- LEGO1/lego/legoomni/include/legoworld.h
- LEGO1/lego/legoomni/src/actors/helicopter.cpp
- LEGO1/lego/legoomni/src/actors/islepathactor.cpp
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/common/legoanimmmpresenter.cpp
- LEGO1/lego/legoomni/src/common/legogamestate.cpp
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
~86% match, but rest looks like entropy. Completes the last missing animation phase:
https://github.com/isledecomp/isle/assets/1135351/f55f1b5c-7e98-4292-b8aa-fe4ffdaf3e84
> Implement/match LegoAnimationManager::FUN_10062e20

- LEGO1/lego/legoomni/include/legocontrolmanager.h
- LEGO1/lego/legoomni/include/mxcontrolpresenter.h
- LEGO1/lego/legoomni/src/common/mxcontrolpresenter.cpp
- LEGO1/lego/legoomni/src/control/legocontrolmanager.cpp
- LEGO1/lego/legoomni/src/worlds/infocenter.cpp
- LEGO1/omni/include/mxdsobject.h
> Implement/match LegoControlManager::FUN_100293c0

- CMakeLists.txt
- LEGO1/lego/legoomni/include/lego3dsound.h
- LEGO1/lego/legoomni/include/lego3dwavepresenter.h
- LEGO1/lego/legoomni/include/legocachsound.h
- LEGO1/lego/legoomni/src/audio/lego3dsound.cpp
- LEGO1/lego/legoomni/src/audio/lego3dwavepresenter.cpp
- LEGO1/omni/include/mxaudiopresenter.h
> Implement/match Lego3DWavePresenter::StartingTickle

- LEGO1/lego/legoomni/include/lego3dsound.h
- LEGO1/lego/legoomni/include/legoactor.h
- LEGO1/lego/legoomni/src/audio/lego3dsound.cpp
- LEGO1/lego/legoomni/src/entity/legoactor.cpp
- LEGO1/lego/legoomni/src/entity/legocarraceactor.cpp
> Implement/match Lego3DSound::Create

- LEGO1/lego/legoomni/include/lego3dsound.h
- LEGO1/lego/legoomni/src/audio/lego3dsound.cpp
- LEGO1/lego/legoomni/src/audio/lego3dwavepresenter.cpp
- LEGO1/lego/legoomni/src/audio/legocachsound.cpp
> Implement/match Lego3DSound::UpdatePosition

- LEGO1/lego/legoomni/include/legosoundmanager.h
- LEGO1/lego/legoomni/src/audio/lego3dsound.cpp
- LEGO1/lego/legoomni/src/audio/legocachsound.cpp
- LEGO1/lego/legoomni/src/audio/legosoundmanager.cpp
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/common/legoutils.cpp
- LEGO1/lego/legoomni/src/entity/legocameracontroller.cpp
- LEGO1/lego/legoomni/src/entity/legonavcontroller.cpp
- LEGO1/lego/legoomni/src/entity/legopovcontroller.cpp
100% match (with entropy). 3D sound works now
> Implement/match LegoSoundManager::UpdateListener

- LEGO1/lego/legoomni/include/legocachesoundmanager.h
- LEGO1/lego/legoomni/include/legocachsound.h
- LEGO1/lego/legoomni/include/legoloadcachesoundpresenter.h
- LEGO1/lego/legoomni/src/audio/legocachesoundmanager.cpp
- LEGO1/lego/legoomni/src/audio/legocachsound.cpp
- LEGO1/lego/legoomni/src/audio/legoloadcachesoundpresenter.cpp
- LEGO1/omni/include/mxdsmediaaction.h
- LEGO1/omni/include/mxdssound.h
- LEGO1/omni/src/audio/mxwavepresenter.cpp
> Implement/match LegoCacheSound::Create and LegoLoadCacheSoundPresenter::StreamingTickle

- LEGO1/lego/legoomni/include/lego3dsound.h
- LEGO1/lego/legoomni/include/legocachesoundmanager.h
- LEGO1/lego/legoomni/include/legocachsound.h
- LEGO1/lego/legoomni/src/audio/lego3dsound.cpp
- LEGO1/lego/legoomni/src/audio/legocachesoundmanager.cpp
- LEGO1/lego/legoomni/src/audio/legocachsound.cpp
- LEGO1/lego/legoomni/src/entity/legoactor.cpp
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/paths/legoextraactor.cpp
- LEGO1/lego/legoomni/src/paths/legopathactor.cpp
100% matches. Cached sounds like the crash sound when running into Lego actors now work.
> Implement/match LegoCacheSound::Play and Lego3DSound::FUN_10011a60

- LEGO1/lego/legoomni/src/audio/legocachesoundmanager.cpp
~94% match, rest seems to be entropy
> Match LegoCacheSoundManager::FindSoundByKey

- LEGO1/lego/legoomni/include/legobuildingmanager.h
- LEGO1/lego/legoomni/include/legocharactermanager.h
- LEGO1/lego/legoomni/include/legoentity.h
- LEGO1/lego/legoomni/include/legomain.h
- LEGO1/lego/legoomni/include/legoplantmanager.h
- LEGO1/lego/legoomni/src/build/legobuildingmanager.cpp
- LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
- LEGO1/lego/legoomni/src/common/legoplantmanager.cpp
- LEGO1/lego/legoomni/src/common/misc.cpp
- LEGO1/lego/legoomni/src/entity/legoentity.cpp
> Implement/match LegoEntity::ClickAnimation

- LEGO1/lego/legoomni/include/legoactors.h
- LEGO1/lego/legoomni/include/legobuildingmanager.h
- LEGO1/lego/legoomni/include/legocharactermanager.h
- LEGO1/lego/legoomni/include/legoentity.h
- LEGO1/lego/legoomni/include/legoplantmanager.h
- LEGO1/lego/legoomni/src/build/legobuildingmanager.cpp
- LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
- LEGO1/lego/legoomni/src/common/legoplantmanager.cpp
- LEGO1/lego/legoomni/src/entity/legoentity.cpp
> Implement/match LegoEntity::SwitchSound / SwitchMove / SwitchColor / SwitchMood

- LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
> Implement/match LegoCharacterManager::SwitchColor

- LEGO1/lego/legoomni/include/ambulance.h
- LEGO1/lego/legoomni/include/bike.h
- LEGO1/lego/legoomni/include/dunebuggy.h
- LEGO1/lego/legoomni/include/helicopter.h
- LEGO1/lego/legoomni/include/islepathactor.h
- LEGO1/lego/legoomni/include/jetski.h
- LEGO1/lego/legoomni/include/motocycle.h
- LEGO1/lego/legoomni/include/racecar.h
- LEGO1/lego/legoomni/include/skateboard.h
- LEGO1/lego/legoomni/include/towtrack.h
- LEGO1/lego/legoomni/src/actors/ambulance.cpp
- LEGO1/lego/legoomni/src/actors/bike.cpp
- LEGO1/lego/legoomni/src/actors/dunebuggy.cpp
- LEGO1/lego/legoomni/src/actors/helicopter.cpp
- LEGO1/lego/legoomni/src/actors/islepathactor.cpp
- LEGO1/lego/legoomni/src/actors/jetski.cpp
- LEGO1/lego/legoomni/src/actors/motorcycle.cpp
- LEGO1/lego/legoomni/src/actors/racecar.cpp
- LEGO1/lego/legoomni/src/actors/skateboard.cpp
- LEGO1/lego/legoomni/src/actors/towtrack.cpp
> Implement/match Ambulance::Notify

- LEGO1/omni/include/mxaudiomanager.h
- LEGO1/omni/include/mxmediamanager.h
- LEGO1/omni/src/audio/mxaudiomanager.cpp
- LEGO1/omni/src/audio/mxmusicmanager.cpp
- LEGO1/omni/src/audio/mxsoundmanager.cpp
- LEGO1/omni/src/audio/mxsoundpresenter.cpp
- LEGO1/omni/src/common/mxmediamanager.cpp
- LEGO1/omni/src/event/mxeventmanager.cpp
- LEGO1/omni/src/video/mxvideomanager.cpp
> Rename InitPresenters to Create, remove this keyword

- LEGO1/lego/legoomni/src/entity/act2policestation.cpp
Closest I've gottne to was 88.37%.
> Act2PoliceStation::Notify

- tools/isledecomp/isledecomp/compare/asm/instgen.py
When comparing functions, we look at the size of the function in recomp and read that many bytes from the original. It is likely that we will read too many or too few bytes. Even for an effective match, using different registers or a different stack order can use more or less bytes for those instructions.
So there is a need to get the exact size of functions in the original file. In our specific situation with MSVC, we can exploit the fact that (non-debug builds) start each[^1] function aligned to the 16-byte boundary. The remainder is padded with `0xcc` bytes, or the `int3` instruction. These are there so that we break into the debugger if (because of a bug) the instruction pointer strays outside of a function.
If our disassembler reads an `int3`, we know we are done with that function. …
> Stop disassembling if we hit int3

- ISLE/isleapp.cpp
- LEGO1/lego/legoomni/include/legomain.h
- LEGO1/lego/legoomni/src/entity/legonavcontroller.cpp
- LEGO1/lego/legoomni/src/input/legoinputmanager.cpp
- LEGO1/lego/legoomni/src/main/legomain.cpp
- LEGO1/omni/include/mxomni.h
- LEGO1/omni/src/main/mxomni.cpp
The naming didn't really communicate the purpose of those functions
> Rename Start/StopTimer to Pause/Resume

- LEGO1/lego/legoomni/include/carrace.h
- LEGO1/lego/legoomni/include/jetskirace.h
- LEGO1/lego/legoomni/include/legorace.h
- LEGO1/lego/legoomni/include/legoworld.h
- LEGO1/lego/legoomni/src/common/legogamestate.cpp
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/race/carrace.cpp
- LEGO1/lego/legoomni/src/race/jetskirace.cpp
- LEGO1/lego/legoomni/src/race/legorace.cpp
Implemented most of LegoRace subclass. Also renamed a few virtual methods according to LegoRace::Notify.
> Begin LegoRace class

- LEGO1/lego/legoomni/include/ambulance.h
- LEGO1/lego/legoomni/include/islepathactor.h
- LEGO1/lego/legoomni/src/actors/ambulance.cpp
- LEGO1/lego/legoomni/src/actors/islepathactor.cpp
> Implement/match Ambulance::HandleEndAction

- LEGO1/lego/legoomni/include/ambulance.h
- LEGO1/lego/legoomni/src/actors/ambulance.cpp
> Implement/match Ambulance::HandleClick

- LEGO1/lego/legoomni/include/ambulance.h
- LEGO1/lego/legoomni/src/actors/ambulance.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
> Implement/match Ambulance::ActivateSceneActions

- LEGO1/lego/legoomni/include/legoutils.h
- LEGO1/lego/legoomni/src/actors/buildings.cpp
> Implement/match JailEntity::HandleClick and CaveEntity::HandleClick

- LEGO1/lego/legoomni/include/ambulance.h
- LEGO1/lego/legoomni/include/legovariables.h
- LEGO1/lego/legoomni/src/actors/ambulance.cpp
- LEGO1/lego/legoomni/src/common/legovariables.cpp
> Implement/match Ambulance::VTable0x70

- LEGO1/lego/legoomni/include/legoutils.h
- LEGO1/lego/legoomni/src/actors/ambulance.cpp
- LEGO1/lego/legoomni/src/common/legoutils.cpp
> Implement/match Ambulance::HandleButtonDown

- LEGO1/lego/legoomni/include/ambulance.h
- LEGO1/lego/legoomni/include/legostate.h
- LEGO1/lego/legoomni/src/actors/ambulance.cpp
> Implement/match remaining Ambulance functions

- LEGO1/lego/sources/anim/legoanim.cpp
- LEGO1/lego/sources/anim/legoanim.h
> Implement LegoAnimScene::FUN_1009f490

- LEGO1/lego/legoomni/include/ambulance.h
- LEGO1/lego/legoomni/include/gasstation.h
- LEGO1/lego/legoomni/include/hospital.h
- LEGO1/lego/legoomni/include/isle.h
- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legocarbuild.h
- LEGO1/lego/legoomni/include/legorace.h
- LEGO1/lego/legoomni/include/legostate.h
- LEGO1/lego/legoomni/include/pizza.h
- LEGO1/lego/legoomni/include/pizzeria.h
- LEGO1/lego/legoomni/include/police.h
- LEGO1/lego/legoomni/include/towtrack.h
- LEGO1/lego/legoomni/src/actors/ambulance.cpp
- LEGO1/lego/legoomni/src/actors/pizza.cpp
- LEGO1/lego/legoomni/src/actors/pizzeria.cpp
- LEGO1/lego/legoomni/src/actors/towtrack.cpp
- LEGO1/lego/legoomni/src/build/legocarbuild.cpp
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/race/legorace.cpp
- LEGO1/lego/legoomni/src/worlds/gasstation.cpp
- LEGO1/lego/legoomni/src/worlds/hospital.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
- LEGO1/lego/legoomni/src/worlds/police.cpp
- LEGO1/lego/sources/misc/legostorage.h
A bunch of new `::Serialize` functions are implemented. I got most of them to 100 %, except for `PizzeriaState::Serialize` which has one minor difference. The usual compiler entropy has increased and decreased the matches for a bunch of other functions.
> feat: Implement several ::Serialize functions

- tools/ghidra_scripts/import_functions_and_types_from_pdb.py
- tools/ghidra_scripts/lego_util/function_importer.py
- tools/ghidra_scripts/lego_util/pdb_extraction.py
> Support stubs in function import

- LEGO1/lego/legoomni/include/bike.h
- LEGO1/lego/legoomni/src/actors/bike.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
> Implement/match Bike

- LEGO1/lego/legoomni/include/legobuildingmanager.h
- LEGO1/lego/legoomni/include/legoplantmanager.h
- LEGO1/lego/legoomni/src/common/legobuildingmanager.cpp
- LEGO1/lego/legoomni/src/common/legoplantmanager.cpp
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
100% matches (some with entropy)
> Implement/match more LegoPlantManager functions

- LEGO1/lego/legoomni/include/legobuildingmanager.h
- LEGO1/lego/legoomni/include/legocharactermanager.h
- LEGO1/lego/legoomni/include/legoplantmanager.h
- LEGO1/lego/legoomni/src/common/legobuildingmanager.cpp
- LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
- LEGO1/lego/legoomni/src/common/legoplantmanager.cpp
- LEGO1/lego/legoomni/src/entity/legoentity.cpp
> Implement/match LegoPlantManager interaction functions

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legonavcontroller.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/entity/legonavcontroller.cpp
All the new functions match to 100 %.
I'd appreciate some feedback on the naming:
* `AnimState::m_unk0x10` clearly stores a dynamically sized array, and the values have the same semantics as `AnimInfo::m_unk0x22`. Would it make sense to rename this array, and what would a good name be?
* `AnimState::m_unk0x0c` clearly stores the length of `AnimState::m_unk0x10`.
* `AnimInfo::m_locationsFlags` is subject to the same issue - the array structure is clear, but the semantics of the stored data are not. I added a name here which should be changed in the future.
* If you have better name suggestions for `AnimState::InitFromAnims` and `AnimState::CopyToAnims`, I'd appreciate to hear them.
> Implement AnimState

- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
Backport of https://github.com/isledecomp/isle-portable/pull/29
> m_extraCharacterId is an integer, not a pointer

- LEGO1/lego/legoomni/src/common/legoplantmanager.cpp
> Implement/match LegoPlantManager::FUN_10027120

- LEGO1/define.cpp
- LEGO1/define.h
- LEGO1/lego/legoomni/include/legorace.h
- LEGO1/lego/legoomni/include/legoraceactor.h
- LEGO1/lego/legoomni/include/legoracecar.h
- LEGO1/lego/legoomni/src/race/legoracecar.cpp
The implementation here is quite the struggle due to the virtual inheritance used.
I get an address mismatch at `0x10012fb1`. This is because the compiler replaces the loop over `i` by a loop over the pointer into the static array, and checks whether we have reached the array's end. Of course, the static array has a different address in the recompile, so the mismatch is expected. Do we have some kind of marker / comment for this situation that `reccmp` would understand?
Furthermore, I am not entirely sure that I have annotated the strings correctly. A double check would be appreciated.
> Start implementing `LegoRaceCar`

- LEGO1/lego/legoomni/include/legobuildingmanager.h
- LEGO1/lego/legoomni/include/legoplantmanager.h
- LEGO1/lego/legoomni/src/common/legobuildingmanager.cpp
- LEGO1/lego/legoomni/src/common/legoplantmanager.cpp
> Implement/match LegoPlantManager::ScheduleAnimation

- LEGO1/lego/legoomni/include/gasstation.h
- LEGO1/lego/legoomni/src/worlds/gasstation.cpp
> Implement/match GasStation::HandleButtonDown

- LEGO1/lego/legoomni/src/worlds/gasstation.cpp
- LEGO1/omni/include/mxactionnotificationparam.h
~72% match but rest could be randomness
> Implement GasStation::HandleEndAction

- LEGO1/lego/legoomni/include/dunebuggy.h
- LEGO1/lego/legoomni/include/legovariables.h
- LEGO1/lego/legoomni/src/actors/dunebuggy.cpp
- LEGO1/lego/legoomni/src/actors/pizza.cpp
- LEGO1/lego/legoomni/src/common/legovariables.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
> Implement/match DuneBuggy class

- LEGO1/modeldb/modeldb.cpp
- LEGO1/modeldb/modeldb.h
> Implement/match FreeModelDbWorlds

- LEGO1/lego/legoomni/include/bumpbouy.h
- LEGO1/lego/legoomni/include/legovideomanager.h
- LEGO1/lego/legoomni/src/actors/bike.cpp
- LEGO1/lego/legoomni/src/actors/bumpbouy.cpp
- LEGO1/lego/legoomni/src/actors/dunebuggy.cpp
- LEGO1/lego/legoomni/src/actors/motorcycle.cpp
- LEGO1/lego/legoomni/src/actors/skateboard.cpp
- LEGO1/lego/legoomni/src/worlds/historybook.cpp
> Implement/match BumpBouy class

- LEGO1/lego/legoomni/include/dunebuggy.h
- LEGO1/lego/legoomni/include/jetski.h
- LEGO1/lego/legoomni/include/legovariables.h
- LEGO1/lego/legoomni/src/actors/dunebuggy.cpp
- LEGO1/lego/legoomni/src/actors/jetski.cpp
- LEGO1/lego/legoomni/src/common/legovariables.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
100% matches (except a minor part in `HandleClick`)
> Implement/match Jetski class

- LEGO1/lego/legoomni/include/legovariables.h
- LEGO1/lego/legoomni/include/towtrack.h
- LEGO1/lego/legoomni/src/actors/towtrack.cpp
- LEGO1/lego/legoomni/src/common/legovariables.cpp
> Implement/match TowTrack::VTable0x70

- LEGO1/lego/legoomni/include/carrace.h
- LEGO1/lego/legoomni/include/legoracers.h
- LEGO1/lego/legoomni/include/raceskel.h
- LEGO1/lego/legoomni/src/race/legoracers.cpp
- LEGO1/lego/legoomni/src/race/raceskel.cpp
- LEGO1/lego/sources/geom/legowegedge.h
- tools/isledecomp/isledecomp/compare/core.py
- tools/isledecomp/isledecomp/cvdump/analysis.py
Looking forward to your feedback as always!
> Implement `LegoRaceCar::HandleSkeletonKicks` and dependents

- LEGO1/lego/legoomni/include/legoactor.h
- LEGO1/lego/legoomni/include/legocarraceactor.h
- LEGO1/lego/legoomni/src/common/misc.cpp
- LEGO1/lego/legoomni/src/entity/legocarraceactor.cpp
- LEGO1/lego/legoomni/src/race/raceskel.cpp
- LEGO1/lego/sources/geom/legounkown100db7f4.h
- LEGO1/lego/sources/geom/legoweedge.h
- LEGO1/realtime/orientableroi.h
The big new function only has one mismatching line that does not influence the semantics. The rest are refactors and quick wins.
I also found an assertion casting doubt on the signature of `LegoWEEdge::IsEqual` - I'd be curious to learn if anyone knows more about this.
> Implement/match `LegoCarRaceActor::FUN_10080590`

- LEGO1/define.cpp
- LEGO1/define.h
- LEGO1/lego/legoomni/include/legoraceactor.h
- LEGO1/lego/legoomni/src/race/legoraceactor.cpp
- LEGO1/lego/legoomni/src/race/legoracers.cpp
- LEGO1/realtime/matrix.h
- LEGO1/realtime/vector.h
These functions match up to compiler entropy / minor non-functional diffs.
Note that there are some striking similarities between several functions. I am not exactly sure what is going on here - BETA10 does not suggest that these are inlined versions of the same function (although you can never be sure). Furthermore, we can never be sure what degree of code duplication the original code had. I'm curious to hear if you have more insight.
> Implement/match `LegoRaceActor`

- LEGO1/lego/legoomni/include/towtrack.h
- LEGO1/lego/legoomni/src/actors/towtrack.cpp
> Implement/match TowTrack::HandleClick

- LEGO1/lego/legoomni/include/towtrack.h
- LEGO1/lego/legoomni/src/actors/towtrack.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
> Implement/match TowTrack::Leave and related

- LEGO1/lego/legoomni/include/towtrack.h
- LEGO1/lego/legoomni/src/actors/towtrack.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
> Implement/match TowTrack::ActivateSceneActions

- LEGO1/lego/legoomni/src/actors/towtrack.cpp
> Implement/match TowTrack::FUN_1004dbe0

- LEGO1/lego/legoomni/include/ambulance.h
- LEGO1/lego/legoomni/include/towtrack.h
- LEGO1/lego/legoomni/src/actors/ambulance.cpp
- LEGO1/lego/legoomni/src/actors/towtrack.cpp
Match in this PR is just at ~70%, but rest is mostly compiler randomness (confirmed)
> Implement TowTrack::HandlePathStruct

- LEGO1/lego/legoomni/include/towtrack.h
- LEGO1/lego/legoomni/src/actors/towtrack.cpp
> Implement/match TowTrack::HandleEndAction

- LEGO1/lego/legoomni/include/legocarbuild.h
- LEGO1/lego/legoomni/include/legojetski.h
- LEGO1/lego/legoomni/include/legojetskiraceactor.h
- LEGO1/lego/legoomni/include/legorace.h
- LEGO1/lego/legoomni/include/legoracers.h
- LEGO1/lego/legoomni/include/legoracespecial.h
- LEGO1/lego/legoomni/src/build/legocarbuild.cpp
- LEGO1/lego/legoomni/src/entity/legojetski.cpp
- LEGO1/lego/legoomni/src/race/legorace.cpp
I looked for various constructors not matching perfectly and found a couple of issues I fixed here.
I will probably continue to work on `LegoCarBuild`, where I have some progress that is not yet ready to be merged.
> Various fixes in constructors

- LEGO1/lego/legoomni/include/carrace.h
- LEGO1/lego/legoomni/include/legoanimactor.h
- LEGO1/lego/legoomni/include/legoextraactor.h
- LEGO1/lego/legoomni/include/legoobjectfactory.h
- LEGO1/lego/legoomni/include/raceskel.h
- LEGO1/lego/legoomni/src/common/legoobjectfactory.cpp
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/paths/legoanimactor.cpp
- LEGO1/lego/legoomni/src/race/carrace.cpp
- LEGO1/lego/legoomni/src/race/legoracers.cpp
- LEGO1/lego/legoomni/src/race/raceskel.cpp
- LEGO1/lego/sources/roi/legoroi.h
- LEGO1/mxgeometry/mxgeometry3d.h
- LEGO1/omni/include/mxobjectfactory.h
- LEGO1/omni/src/common/mxobjectfactory.cpp
Finding the correct vtables for `RaceSkel` revealed two missing virtual functions, which I also added. All the new functions (including synthetic ones) match to 100 %.
I also added a bunch of BETA10 annotations that I found along the way. Note that I only search for assertions and other discrepancies for some, but not all of the functions I annotated.
Looking forward to your review!
> Implement `RaceSkel`, add BETA10 annotations

- LEGO1/library_msvc.h
It's not _all_ the symbols from the PDB, but I think this is everything reachable via other annotations.
> Add more MSVC annotations for LEGO1

- LEGO1/omni/include/mxtimer.h
- LEGO1/omni/src/common/mxtimer.cpp
Beta addrs, setter function for the static `g_lastTimeCalculated` variable, and removing `this->`.
> MxTimer touch-up

- LEGO1/omni/include/mxdsfile.h
- LEGO1/omni/src/stream/mxdsfile.cpp
I plugged in `MxResult` in each place where it fits and we had used another dword type. The `Open()` function is the only one with a value other than 0 or -1, so I went with `-FAILURE` and marked it.
> Beta match MxDSFile

- .github/workflows/format.yml
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/viewmanager/viewmanager.cpp
- LEGO1/viewmanager/viewmanager.h
haven't ran any formatting so that'll probably fail, if this is merged i'd appreciate if you could format it @foxtacles
> some educated guesses for unknown view manager names

- LEGO1/lego/legoomni/include/pizza.h
- LEGO1/lego/legoomni/src/actors/pizza.cpp
> Implement/match Pizza::FUN_10038220

- LEGO1/lego/legoomni/include/legocarbuildpresenter.h
- LEGO1/lego/legoomni/include/legoutils.h
- LEGO1/lego/legoomni/include/legovideomanager.h
- LEGO1/lego/legoomni/src/build/legocarbuildpresenter.cpp
- LEGO1/lego/legoomni/src/common/legoutils.cpp
- LEGO1/lego/legoomni/src/entity/legoentity.cpp
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/sources/3dmanager/lego3dmanager.cpp
- LEGO1/lego/sources/3dmanager/lego3dview.cpp
- LEGO1/lego/sources/anim/legoanim.h
- LEGO1/lego/sources/misc/legotree.h
- LEGO1/lego/sources/roi/legoroi.cpp
- LEGO1/lego/sources/roi/legoroi.h
- LEGO1/library_msvc.h
- LEGO1/mxgeometry/mxgeometry3d.h
- LEGO1/omni/include/mxdsobject.h
- LEGO1/realtime/matrix.h
- LEGO1/realtime/orientableroi.h
- LEGO1/realtime/realtime.cpp
- LEGO1/realtime/vector.h
`LegoCarBuildAnimPresenter::StreamingTickle()` matches up to the stack layout, which I couldn't get quite right.
I also added a number of `BETA10` annotations and found a bunch of stubs.
> Implement `LegoCarBuildAnimPresenter::StreamingTickle()`

- LEGO1/lego/legoomni/include/legocarbuild.h
- LEGO1/lego/legoomni/include/legocarbuildpresenter.h
- LEGO1/lego/legoomni/src/build/legocarbuild.cpp
- LEGO1/lego/legoomni/src/build/legocarbuildpresenter.cpp
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
- LEGO1/lego/sources/anim/legoanim.cpp
- LEGO1/lego/sources/anim/legoanim.h
- LEGO1/lego/sources/misc/legotree.cpp
- LEGO1/lego/sources/misc/legotree.h
- LEGO1/library_msvc.h
- LEGO1/omni/src/common/mxpresenter.cpp
`FUN_10079160()` matches up to stack order, the rest matches up to entropy or to 100 %.
I have worked a bit on automatic stack comparison in order to simplify debugging stack mismatches (or at least in order to tell whether the code is correct). I'll open a PR when it's somewhat usable.
> Implement `LegoCarBuildAnimPresenter::FUN_10079160()` and others

- LEGO1/lego/legoomni/include/legocarbuildpresenter.h
- LEGO1/lego/legoomni/include/legoextraactor.h
- LEGO1/lego/legoomni/include/legoraceactor.h
- LEGO1/lego/legoomni/src/build/legocarbuild.cpp
- LEGO1/lego/legoomni/src/build/legocarbuildpresenter.cpp
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
- LEGO1/lego/sources/anim/legoanim.cpp
- LEGO1/lego/sources/anim/legoanim.h
- LEGO1/lego/sources/misc/legotree.cpp
- LEGO1/lego/sources/misc/legotree.h
- LEGO1/omni/include/mxpresenter.h
- LEGO1/omni/include/mxstreamchunk.h
- LEGO1/omni/include/mxvideopresenter.h
- LEGO1/omni/src/common/mxmediapresenter.cpp
- LEGO1/omni/src/common/mxpresenter.cpp
- LEGO1/omni/src/video/mxvideopresenter.cpp
- LEGO1/realtime/roi.h
also contains some drive-by fixes for BETA10 annotations
> Complete `LegoCarBuildAnimPresenter`

- LEGO1/lego/legoomni/include/legocarbuild.h
- LEGO1/lego/legoomni/include/legocarbuildpresenter.h
- LEGO1/lego/legoomni/include/legomain.h
- LEGO1/lego/legoomni/include/mxbackgroundaudiomanager.h
- LEGO1/lego/legoomni/src/actors/islepathactor.cpp
- LEGO1/lego/legoomni/src/actors/jukeboxentity.cpp
- LEGO1/lego/legoomni/src/actors/radio.cpp
- LEGO1/lego/legoomni/src/audio/mxbackgroundaudiomanager.cpp
- LEGO1/lego/legoomni/src/build/legocarbuild.cpp
- LEGO1/lego/legoomni/src/build/legocarbuildpresenter.cpp
- LEGO1/lego/legoomni/src/common/misc.cpp
- LEGO1/lego/legoomni/src/main/legomain.cpp
- LEGO1/lego/legoomni/src/main/scripts.cpp
- LEGO1/lego/legoomni/src/paths/legopathstruct.cpp
- LEGO1/omni/include/mxdssound.h
- LEGO1/omni/include/mxnotificationparam.h
- LEGO1/omni/include/mxsoundmanager.h
* Implement LegoCarBuild::FUN_10024c20 and dependents
* Implement LegoCarBuild::FUN_100250e0 and dependents
* Type refactor in `MxBackgroundAudioManager`: `int` to existing `enum`
> Implement LegoCarBuild functions, refactor BackgroundAudioManager

- LEGO1/lego/legoomni/include/pizza.h
- LEGO1/lego/legoomni/include/skateboard.h
- LEGO1/lego/legoomni/src/actors/pizza.cpp
- LEGO1/lego/legoomni/src/actors/skateboard.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
100% match on `Pizza::FUN_100382b0`, `Pizza::StopActions` has some randomness. Variable names adapted from BETA10
> Implement/match Pizza::FUN_100382b0 and Pizza::StopActions

- LEGO1/lego/legoomni/include/pizza.h
- LEGO1/lego/legoomni/include/pizzeria.h
- LEGO1/lego/legoomni/src/actors/pizza.cpp
- LEGO1/lego/legoomni/src/actors/pizzeria.cpp
> Implement/match Pizza::HandleClick

- LEGO1/lego/legoomni/include/pizza.h
- LEGO1/lego/legoomni/src/actors/pizza.cpp
> Implement/match PizzaMissionState::PizzaMissionState

- LEGO1/lego/legoomni/include/pizza.h
- LEGO1/lego/legoomni/src/actors/pizza.cpp
> Implement/match Pizza::HandlePathStruct

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/pizza.h
- LEGO1/lego/legoomni/src/actors/pizza.cpp
- LEGO1/lego/legoomni/src/actors/pizzeria.cpp
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
> Implement/match Pizza::PlayAction

- LEGO1/lego/legoomni/include/legostate.h
- LEGO1/lego/legoomni/include/pizzeria.h
- LEGO1/lego/legoomni/src/actors/pizzeria.cpp
- LEGO1/lego/legoomni/src/actors/radio.cpp
- LEGO1/lego/legoomni/src/worlds/infocenter.cpp
100% match (with some randomness)
> Implement/match PizzeriaState::PizzeriaState

- LEGO1/lego/legoomni/include/pizza.h
- LEGO1/lego/legoomni/include/pizzeria.h
- LEGO1/lego/legoomni/src/actors/pizza.cpp
- LEGO1/lego/legoomni/src/actors/pizzeria.cpp
> Implement/match PizzeriaState::NextAction

- LEGO1/lego/legoomni/include/isle.h
- LEGO1/lego/legoomni/include/pizza.h
- LEGO1/lego/legoomni/src/actors/pizza.cpp
100% match. Pizza missions work now:
> Implement/match Pizza::HandleEndAction

- LEGO1/lego/legoomni/include/isle.h
- LEGO1/lego/legoomni/include/legostate.h
- LEGO1/lego/legoomni/src/worlds/isle.cpp
> Implement/match Act1State::Act1State

- LEGO1/lego/legoomni/include/isle.h
- LEGO1/lego/legoomni/src/worlds/isle.cpp
> Implement/match Act1State::PlayCptClickDialogue

- LEGO1/lego/legoomni/include/helicopter.h
- LEGO1/lego/legoomni/include/isle.h
- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legonamedplane.h
- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/include/legostate.h
- LEGO1/lego/legoomni/include/score.h
- LEGO1/lego/legoomni/src/actors/bumpbouy.cpp
- LEGO1/lego/legoomni/src/actors/jukeboxentity.cpp
- LEGO1/lego/legoomni/src/build/legocarbuild.cpp
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/common/legogamestate.cpp
- LEGO1/lego/legoomni/src/common/legoutils.cpp
- LEGO1/lego/legoomni/src/paths/legopathactor.cpp
- LEGO1/lego/legoomni/src/worlds/infocenter.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
100% match. Also refactored/improved some naming.
> Implement/match Act1State::RemoveActors

- LEGO1/lego/legoomni/include/legonamedplane.h
- LEGO1/lego/legoomni/src/paths/legopathactor.cpp
- LEGO1/lego/sources/geom/legowegedge.h
> Implement/match LegoPathActor::UpdatePlane

- LEGO1/lego/legoomni/include/doors.h
- LEGO1/lego/legoomni/src/actors/doors.cpp
- LEGO1/lego/sources/geom/legowegedge.h
100% match on `Doors::ParseAction`, `Doors::VTable0x70` has a very minor aspect that doesn't match (annotated)
> Implement/match Doors::VTable0x70 and Doors::ParseAction

- LEGO1/lego/legoomni/include/act2genactor.h
- LEGO1/lego/legoomni/src/actors/act2genactor.cpp
> Implement/match Act2GenActor::VTable0x94

- LEGO1/lego/legoomni/include/legogamestate.h
- LEGO1/lego/legoomni/src/worlds/historybook.cpp
> Implement/match HistoryBook::~HistoryBook

- LEGO1/lego/legoomni/src/worlds/registrationbook.cpp
> Implement/match RegistrationBook::FUN_100778c0

- LEGO1/lego/sources/roi/legolod.cpp
- LEGO1/lego/sources/roi/legolod.h
- LEGO1/lego/sources/roi/legoroi.cpp
- LEGO1/lego/sources/roi/legoroi.h
> Implement/match LegoROI::FUN_100a9dd0

- LEGO1/lego/legoomni/include/isle.h
- LEGO1/lego/legoomni/include/islepathactor.h
- LEGO1/lego/legoomni/include/legonamedplane.h
- LEGO1/lego/legoomni/include/legonamedtexture.h
- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/include/legoutils.h
- LEGO1/lego/legoomni/src/common/legoutils.cpp
- LEGO1/lego/legoomni/src/paths/legopathactor.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
~92% match on `Act1State::PlaceActors` (incorrect STL inlining), 100% on all others
> Implement/match Act1State::PlaceActors and related

- LEGO1/lego/legoomni/src/build/legocarbuild.cpp
> Match LegoCarBuild::Tickle

- LEGO1/lego/legoomni/include/legoact2.h
- LEGO1/lego/legoomni/src/worlds/legoact2.cpp
> Implement/match LegoAct2::Create

- LEGO1/lego/legoomni/src/worlds/legoact2.cpp
> Implement/match LegoAct2::Escape

- LEGO1/lego/legoomni/include/act2actor.h
- LEGO1/lego/legoomni/src/actors/act2actor.cpp
> Implement/match some Act2Actor functions

- LEGO1/lego/legoomni/src/actors/racecar.cpp
> Implement/match RaceCar

- LEGO1/lego/legoomni/include/legoutils.h
- LEGO1/lego/legoomni/src/build/legocarbuild.cpp
- LEGO1/lego/legoomni/src/common/legoutils.cpp
> Implement/match RotateY

- LEGO1/lego/legoomni/include/legoutils.h
- LEGO1/lego/legoomni/src/actors/ambulance.cpp
- LEGO1/lego/legoomni/src/common/legoutils.cpp
> Implement/match PickEntity

- LEGO1/lego/legoomni/src/build/legocarbuildpresenter.cpp
- LEGO1/lego/sources/anim/legoanim.cpp
- LEGO1/lego/sources/anim/legoanim.h
> Implement/match LegoAnimNodeData::SetName

- LEGO1/lego/legoomni/src/common/legobuildingmanager.cpp
> Implement/match LegoBuildingManager::FUN_10030030

- LEGO1/lego/legoomni/include/legocachesoundmanager.h
- LEGO1/lego/legoomni/include/legoracers.h
- LEGO1/lego/legoomni/src/common/legobuildingmanager.cpp
- LEGO1/lego/legoomni/src/race/legoracers.cpp
- LEGO1/tgl/d3drm/renderer.cpp
> Implement/match LegoBuildingManager::Tickle

- LEGO1/lego/legoomni/src/common/legoplantmanager.cpp
> Implement/match LegoPlantManager::Tickle

- LEGO1/lego/legoomni/include/legojetskiraceactor.h
- LEGO1/lego/legoomni/include/legoracespecial.h
- LEGO1/lego/legoomni/src/entity/legojetskiraceactor.cpp
- LEGO1/lego/legoomni/src/race/jetskirace.cpp
The new functions match to 100 % and also match BETA10 structurally (when available).
> Implement parts of LegoJetskiRaceActor

- LEGO1/lego/legoomni/include/carrace.h
- LEGO1/lego/legoomni/include/doors.h
- LEGO1/lego/legoomni/include/jetskirace.h
- LEGO1/lego/legoomni/include/legoentity.h
- LEGO1/lego/legoomni/include/legoinputmanager.h
- LEGO1/lego/legoomni/include/legonavcontroller.h
- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/include/legoracers.h
- LEGO1/lego/legoomni/src/actors/doors.cpp
- LEGO1/lego/legoomni/src/build/legocarbuild.cpp
- LEGO1/lego/legoomni/src/common/misc.cpp
- LEGO1/lego/legoomni/src/entity/legoactor.cpp
- LEGO1/lego/legoomni/src/entity/legoentity.cpp
- LEGO1/lego/legoomni/src/main/scripts.cpp
- LEGO1/lego/legoomni/src/race/carrace.cpp
- LEGO1/lego/legoomni/src/race/jetskirace.cpp
- LEGO1/lego/legoomni/src/race/legoracers.cpp
- LEGO1/lego/legoomni/src/race/legoracespecial.cpp
- LEGO1/library_msvc.h
- LEGO1/omni/include/mxactionnotificationparam.h
- LEGO1/omni/include/mxentity.h
- reccmp-project.yml
Most of the new functions match to 100 %, there are small deviations for `CarRace::Create()` and `CarRace::HandlePathStruct()` - input is appreciated. I also added a number of BETA10 annotations and improved `JetskiRace::HandlePathStruct()`.
The car race can now be started, but it isn't really playable because the doors cannot be opened yet.
> Implement `CarRace`

- LEGO1/lego/legoomni/include/act2actor.h
- LEGO1/lego/legoomni/include/legoact2.h
- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/src/actors/act2actor.cpp
- LEGO1/lego/legoomni/src/actors/helicopter.cpp
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/common/misc.cpp
- LEGO1/lego/legoomni/src/main/legomain.cpp
- LEGO1/lego/legoomni/src/paths/legoextraactor.cpp
- LEGO1/lego/legoomni/src/paths/legopathactor.cpp
- LEGO1/lego/legoomni/src/worlds/legoact2.cpp
- LEGO1/lego/sources/roi/legoroi.h
- reccmp-project.yml
The new functions match to 100 % effectively. I also refactored the `GetState()` / `SetState()` function calls a bit.
> Implement `LegoAct2::Tickle()` and others

- LEGO1/lego/legoomni/src/entity/legojetskiraceactor.cpp
- LEGO1/lego/legoomni/src/race/carrace.cpp
- LEGO1/lego/legoomni/src/worlds/legoact2.cpp
Also fixed some content of a global
> Remove static storage specifier so vars can be found through datacmp

- LEGO1/lego/legoomni/include/legoact2.h
- LEGO1/lego/legoomni/src/main/legomain.cpp
- LEGO1/lego/legoomni/src/worlds/legoact2.cpp
- LEGO1/omni/include/mxdsaction.h
There is only one slight mismatch which I couldn't work out, the rest matches exactly.
> Implement/match `LegoAct2::FUN_10052560()`

- LEGO1/lego/legoomni/include/legoact2.h
- LEGO1/lego/legoomni/src/race/carrace.cpp
- LEGO1/lego/legoomni/src/race/jetskirace.cpp
- LEGO1/lego/legoomni/src/worlds/legoact2.cpp
- LEGO1/mxgeometry/mxmatrix.h
Match is at ~87%, but the remaining diff seems to be an issue with the stack layout only.
@jonschz Am I using `stackcmp` correctly? I can't seem to get it to work:
```
PS C:\Users\Christian\Downloads\isle> reccmp-stackcmp --target LEGO1 0x10050380
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "c:\users\christian\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\scripts\reccmp-stackcmp.exe\__main__.py", line 7, in <module>
File "C:\Users\Christian\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\reccmp\tools\stackcmp.py", line 322, in main
origfile, recompfile, …
```
> Implement/match `LegoAct2::Notify`

- LEGO1/lego/legoomni/include/legoact2.h
- LEGO1/lego/legoomni/src/actors/buildings.cpp
- LEGO1/lego/legoomni/src/worlds/legoact2.cpp
> Implement/match `LegoAct2::HandleTransitionEnd`

- LEGO1/lego/legoomni/include/act3actors.h
- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/src/actors/act3actors.cpp
Code is very similar to LegoRaceActor, so I had to modify it a little bit for it to match. Act3Actor::VTable0x90 does not match 100% due to something being weird with the ```+ 2000.0f``` addition
> Implement functions in Act3Actor

- LEGO1/lego/legoomni/include/act2actor.h
- LEGO1/lego/legoomni/include/legoanimactor.h
- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/src/actors/act2actor.cpp
- LEGO1/lego/legoomni/src/paths/legoanimactor.cpp
- LEGO1/lego/legoomni/src/paths/legopathactor.cpp
The static array and its data structure will be refined once we know more about it.
> Implement `Act2Actor::Act2Actor()`, add BETA10 references

- LEGO1/lego/legoomni/include/legoact2.h
- LEGO1/lego/legoomni/src/common/legogamestate.cpp
- LEGO1/lego/legoomni/src/worlds/legoact2.cpp
100% match. Act 2 does now launch:
> Implement/match `LegoAct2::ReadyWorld`

- LEGO1/lego/legoomni/include/act2actor.h
- LEGO1/lego/legoomni/include/act2brick.h
- LEGO1/lego/legoomni/include/legoact2.h
- LEGO1/lego/legoomni/src/actors/act2actor.cpp
- LEGO1/lego/legoomni/src/entity/act2brick.cpp
- LEGO1/lego/legoomni/src/worlds/legoact2.cpp
Match is at ~92%, but rest is most likely entropy
> Implement/match `LegoAct2::HandlePathStruct`

- LEGO1/lego/legoomni/include/legoact2.h
- LEGO1/lego/legoomni/src/worlds/legoact2.cpp
Match is ~92%, rest looks like entropy
> Implement/match `LegoAct2::SpawnBricks`

- LEGO1/lego/legoomni/include/legopathcontroller.h
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
- LEGO1/lego/sources/geom/legounkown100db7f4.h
> Implement/match LegoPathCtrlEdge::FUN_10048c40

- CMakeLists.txt
- LEGO1/lego/legoomni/include/act3.h
- LEGO1/lego/legoomni/include/act3ammo.h
- LEGO1/lego/legoomni/include/legonavcontroller.h
- LEGO1/lego/legoomni/src/actors/act3ammo.cpp
- LEGO1/lego/legoomni/src/actors/helicopter.cpp
- LEGO1/lego/legoomni/src/worlds/act3.cpp
> Add `Act3Ammo`, match `Act3::Act3`

- LEGO1/lego/legoomni/include/act3.h
- LEGO1/lego/legoomni/include/act3actors.h
- LEGO1/lego/legoomni/include/act3ammo.h
- LEGO1/lego/legoomni/include/act3brickster.h
- LEGO1/lego/legoomni/include/act3cop.h
- LEGO1/lego/legoomni/include/act3shark.h
- LEGO1/lego/legoomni/include/helicopter.h
- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/src/actors/act3ammo.cpp
- LEGO1/lego/legoomni/src/worlds/act3.cpp
Match is at ~92%, rest looks like entropy
> Implement/match `Act3::Enable`

- LEGO1/lego/legoomni/include/act3.h
- LEGO1/lego/legoomni/include/act3brickster.h
- LEGO1/lego/legoomni/include/helicopter.h
- LEGO1/lego/legoomni/src/actors/act3brickster.cpp
- LEGO1/lego/legoomni/src/worlds/act3.cpp
> Implement/match `Act3::Notify`

- LEGO1/lego/legoomni/include/legoanimactor.h
- LEGO1/lego/legoomni/include/legocharactermanager.h
- LEGO1/lego/legoomni/include/legoextraactor.h
- LEGO1/lego/legoomni/include/legopathboundary.h
- LEGO1/lego/legoomni/include/legopathcontroller.h
- LEGO1/lego/legoomni/include/legoworld.h
- LEGO1/mxgeometry/mxgeometry3d.h
I fixed the new name ambiguities now that https://github.com/isledecomp/reccmp/pull/29 is merged. This also comes with a slight increase in match percentage, both on LEGO1 and BETA10.
> Fix name ambiguities

- LEGO1/lego/legoomni/include/act2actor.h
- LEGO1/lego/legoomni/include/legoact2.h
- LEGO1/lego/legoomni/src/actors/act2actor.cpp
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/main/legomain.cpp
- LEGO1/lego/legoomni/src/paths/legoanimactor.cpp
- LEGO1/lego/legoomni/src/paths/legopathactor.cpp
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
- LEGO1/lego/legoomni/src/worlds/legoact2.cpp
- LEGO1/lego/sources/3dmanager/lego3dview.h
- LEGO1/mxgeometry/mxmatrix.h
- LEGO1/viewmanager/viewmanager.h
I didn't quite get this one perfect, unfortunately. Both LEGO1 and BETA10 are matched structurally, but the stack is not correct on LEGO1 and other small mistakes might hide somewhere. BETA10 is quite different - we can remove the `#ifdef NDEBUG` when the match on LEGO1 is good enough.
> Implement `Act2Actor::VTable0x70`

- .github/workflows/build.yml
- LEGO1/lego/legoomni/include/act3.h
- LEGO1/lego/legoomni/include/act3ammo.h
- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/include/legopathcontroller.h
- LEGO1/lego/legoomni/src/actors/act2actor.cpp
- LEGO1/lego/legoomni/src/actors/act3ammo.cpp
- LEGO1/lego/legoomni/src/actors/helicopter.cpp
- LEGO1/lego/legoomni/src/paths/legopathactor.cpp
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
- LEGO1/lego/legoomni/src/worlds/act3.cpp
100% matches (with entropy; confirmed by adding dummy class)
I've also added an implementation for `Act3List::FUN_100720d0`, but it doesn't match very well. Not sure if the STL operations are correct. @disinvite maybe you could take a look? I remember you've worked a lot with lists like these before.
Also matched `Helicopter::HandleControl` close to 100%
Raised the total function count by 30 to account for new STUBs
> Implement/match `Act3::ShootPizza` and `Act3::ShootDonut`

- LEGO1/lego/legoomni/src/actors/act2actor.cpp
- LEGO1/lego/legoomni/src/worlds/legoact2.cpp
100% matches. Act 2 is playable through to the end now:
> Implement/match `LegoAct2::FUN_100516b0` and `LegoAct2::FUN_100517b0`

- LEGO1/lego/legoomni/include/act3ammo.h
- LEGO1/lego/legoomni/src/actors/act3ammo.cpp
- LEGO1/lego/legoomni/src/worlds/act3.cpp
> Implement/match `Act3Ammo::Create`, `Act3Ammo::FUN_10053cb0`, `Act3Ammo::FUN_10053d30`

- LEGO1/lego/legoomni/include/act3.h
- LEGO1/lego/legoomni/src/worlds/act3.cpp
Both 100%. Second arg to `Insert` is probably an enum of some kind.
> Act3List Insert() and Clear()

- LEGO1/lego/legoomni/include/act3ammo.h
- LEGO1/lego/legoomni/src/actors/act3ammo.cpp
> Implement/match `Act3Ammo::FUN_10053b40`

- LEGO1/lego/legoomni/include/act3.h
- LEGO1/lego/legoomni/include/act3ammo.h
- LEGO1/lego/legoomni/include/act3shark.h
- LEGO1/lego/legoomni/src/actors/act3shark.cpp
> Implement/match `Act3Shark` functions

- LEGO1/lego/legoomni/include/act3.h
- LEGO1/lego/legoomni/include/act3actors.h
- LEGO1/lego/legoomni/src/actors/act3actors.cpp
- LEGO1/lego/legoomni/src/worlds/act3.cpp
100% match (with entropy, confirmed)
> Implement/match `Act3Brickster::ParseAction`

- LEGO1/lego/legoomni/include/act2actor.h
- LEGO1/lego/legoomni/include/act2brick.h
- LEGO1/lego/legoomni/include/act2genactor.h
- LEGO1/lego/legoomni/include/act3.h
- LEGO1/lego/legoomni/include/act3actors.h
- LEGO1/lego/legoomni/include/act3ammo.h
- LEGO1/lego/legoomni/include/doors.h
- LEGO1/lego/legoomni/include/legoextraactor.h
- LEGO1/lego/legoomni/include/legojetski.h
- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/include/legoraceactor.h
- LEGO1/lego/legoomni/include/legoracers.h
- LEGO1/lego/legoomni/src/actors/act2actor.cpp
- LEGO1/lego/legoomni/src/actors/act2genactor.cpp
- LEGO1/lego/legoomni/src/actors/act3actors.cpp
- LEGO1/lego/legoomni/src/actors/doors.cpp
- LEGO1/lego/legoomni/src/entity/act2brick.cpp
- LEGO1/lego/legoomni/src/entity/legojetski.cpp
- LEGO1/lego/legoomni/src/entity/legojetskiraceactor.cpp
- LEGO1/lego/legoomni/src/paths/legoextraactor.cpp
- LEGO1/lego/legoomni/src/paths/legopathactor.cpp
- LEGO1/lego/legoomni/src/race/legoraceactor.cpp
- LEGO1/lego/legoomni/src/race/legoracers.cpp
- LEGO1/lego/legoomni/src/race/legoracespecial.cpp
- LEGO1/lego/legoomni/src/worlds/act3.cpp
100% match. This function was formerly called `VTable0x94`, but its purpose is obvious at this point - it is called when two actors "hit" each other. The term "hitactor" is also used in various places.
> Implement/match `Act3Brickster::HitActor`

- LEGO1/lego/legoomni/include/legoutils.h
- LEGO1/lego/legoomni/src/common/legoutils.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
- LEGO1/lego/sources/misc/legoimage.h
Match is at ~85%, rest looks like compiler randomness.
The save files of the decomp version should now be fully compatible with the retail version. I've done a few tests and everything seems to work as expected.
> Implement/match `WriteDefaultTexture`

- LEGO1/lego/legoomni/include/act2actor.h
- LEGO1/lego/legoomni/include/legoact2.h
- LEGO1/lego/legoomni/include/legoanimactor.h
- LEGO1/lego/legoomni/include/legomain.h
- LEGO1/lego/legoomni/include/legosoundmanager.h
- LEGO1/lego/legoomni/src/actors/act2actor.cpp
- LEGO1/lego/legoomni/src/common/legobuildingmanager.cpp
- LEGO1/lego/legoomni/src/common/misc.cpp
- LEGO1/lego/legoomni/src/worlds/legoact2.cpp
- LEGO1/lego/sources/roi/legoroi.cpp
- reccmp-project.yml
Matches to 74 % formally, but the diff only shows one minor stack difference I couldn't figure out.
> Implement `Act2Actor::FUN_10019700`

- LEGO1/lego/legoomni/include/act3.h
- LEGO1/lego/legoomni/include/helicopter.h
- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/src/actors/act3actors.cpp
- LEGO1/lego/legoomni/src/actors/helicopter.cpp
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/entity/act2brick.cpp
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
- LEGO1/lego/legoomni/src/worlds/act3.cpp
- LEGO1/lego/legoomni/src/worlds/legoact2.cpp
- LEGO1/mxgeometry/mxgeometry3d.h
> Implement/match `Act3::GoodEnding`

- .github/workflows/build.yml
- LEGO1/lego/legoomni/include/act3.h
- LEGO1/lego/legoomni/include/act3actors.h
- LEGO1/lego/legoomni/include/act3ammo.h
- LEGO1/lego/legoomni/src/actors/act3actors.cpp
- LEGO1/lego/legoomni/src/actors/act3ammo.cpp
- LEGO1/lego/legoomni/src/worlds/act3.cpp
- LEGO1/realtime/matrix.h
Match is at ~95%, rest looks like entropy
> Implement/match `Act3Ammo::Animate`

- LEGO1/lego/legoomni/include/legoplantmanager.h
- LEGO1/lego/legoomni/src/actors/act2actor.cpp
- LEGO1/lego/legoomni/src/common/legobuildingmanager.cpp
- LEGO1/lego/legoomni/src/common/legoplantmanager.cpp
Matches LEGO1 and BETA10 structurally. LEGO1 percentage is at 73 %, but it seems to be entirely due to entropy (wrong registers).
> Implement/match `Act2Actor::FUN_10019b90`

- LEGO1/lego/legoomni/src/race/legoracers.cpp
This function appears to be correct overall. Some parts close to the return statements don't match fully, might be entropy. `LegoRaceCar::HitActor` has the same issue.
> Implement/match `LegoJetski::HitActor`

- LEGO1/lego/legoomni/include/act2actor.h
- LEGO1/lego/legoomni/include/legopathcontroller.h
- LEGO1/lego/legoomni/src/actors/act2actor.cpp
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
> Implement/match `LegoPathController::FUN_1004a380`

- LEGO1/lego/legoomni/src/actors/act3ammo.cpp
~97% match, rest is incorrect vector inlining (we've seen that before)
> Implement/match `Act3Ammo::FUN_10053db0`

- LEGO1/lego/legoomni/include/act3.h
- LEGO1/lego/legoomni/src/worlds/act3.cpp
~This adds an imlpementation for `Act3::FUN_10072ad0`. It's a pretty straightforward function, however I can't get it to match beyond 55%. I've tried all sorts of variants that I can think of - I might be missing something obvious here.~
~I'll leave the PR open for a few days in case someone wants to give it a shot.~
Figured it out, it's just highly susceptible to entropy:
> Implement/match `Act3::FUN_10072ad0`

- LEGO1/lego/legoomni/include/act3.h
- LEGO1/lego/legoomni/include/act3actors.h
- LEGO1/lego/legoomni/src/actors/act3actors.cpp
- LEGO1/lego/legoomni/src/common/legoobjectfactory.cpp
- LEGO1/lego/legoomni/src/worlds/act3.cpp
Getting this ready to merge early in order to unblock `Act3Cop::FUN_10040360`.
> Add `g_copDest`

- .github/workflows/build.yml
- LEGO1/lego/legoomni/include/act3actors.h
- LEGO1/lego/legoomni/src/actors/act3actors.cpp
- LEGO1/lego/legoomni/src/common/legotextureinfo.cpp
> Implement/match `Act3Shark::Animate`

- LEGO1/lego/legoomni/include/act3actors.h
- LEGO1/lego/legoomni/include/legoanimactor.h
- LEGO1/lego/legoomni/src/actors/act3actors.cpp
Down to entropy on LEGO1 and BETA10. The assertions are quite helpful here.
> Implement/match `Act3Cop::ParseAction`

- .github/workflows/build.yml
- LEGO1/lego/sources/anim/legoanim.cpp
- LEGO1/lego/sources/anim/legoanim.h
100% matches. The functions are unused.
> Implement/match `Write` functions in `LegoAnim` class

- LEGO1/lego/legoomni/src/worlds/legoact2.cpp
Fixes the missing final animation of `LegoAct2` (the Infomaniac popping up to tell you about building the helicopter again)
> Fix `LegoAct2::Notify`

- LEGO1/lego/legoomni/src/actors/act3actors.cpp
> Implement/match `Act3Cop::Animate`

- LEGO1/lego/legoomni/include/act3.h
- LEGO1/lego/legoomni/include/act3actors.h
- LEGO1/lego/legoomni/src/actors/act3actors.cpp
- LEGO1/lego/legoomni/src/worlds/act3.cpp
Match is at ~95% - rest seems to be entropy
> Implement/match `Act3Brickster::Animate`

- LEGO1/lego/legoomni/src/common/legogamestate.cpp
> Match `LegoGameState::Load`

- LEGO1/lego/legoomni/include/act3.h
- LEGO1/lego/legoomni/include/act3actors.h
- LEGO1/lego/legoomni/include/act3ammo.h
- LEGO1/lego/legoomni/include/helicopter.h
- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/src/actors/act3actors.cpp
- LEGO1/lego/legoomni/src/actors/act3ammo.cpp
- LEGO1/lego/legoomni/src/actors/helicopter.cpp
- LEGO1/lego/legoomni/src/worlds/act3.cpp
Match at ~95%, rest looks like entropy. Act 3 mostly works now (the cops aren't eating the donuts yet)
> Implement/match `Act3Brickster::FUN_100417c0`

- LEGO1/lego/legoomni/src/video/legovideomanager.cpp
- LEGO1/omni/include/mxdisplaysurface.h
- LEGO1/omni/src/video/mxdisplaysurface.cpp
LegoVideoManager::DrawFPS: 83.95%
MxDisplaySurface::FUN_100bc8b0: 85.51%
I'm a bit stuck, so I'm posting it here for review.
> Implement LegoVideoManager::DrawFPS

- LEGO1/tgl/d3drm/device.cpp
- LEGO1/tgl/d3drm/group.cpp
- LEGO1/tgl/d3drm/impl.h
- LEGO1/tgl/tgl.h
- `GroupImpl::Bounds`: 71.63%
- `DeviceImpl::HandleActivate`: 100%
- `DeviceImpl::HandlePaint`: 100%
> Implement GroupImpl::Bounds

- LEGO1/lego/legoomni/src/actors/act3actors.cpp
Match at ~94%, rest coud be entropy. Act 3 works now - the entire game should be playable now:
Play tests are appreciated to find any potential bugs (that aren't present in retail). Thanks everyone!
> Implement/match `Act3Cop::FUN_10040360`

- LEGO1/lego/legoomni/src/actors/helicopter.cpp
- LEGO1/mxgeometry/mxgeometry3d.h
- LEGO1/realtime/vector.h
This improves the match and appears to be more correct to me, though I didn't get it above 73 %. The zoom on the brickster is still wrong (I didn't test it before so I don't know if the behaviour has changed).
> Improve `Helicopter::Animate()`

- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legomain.h
- LEGO1/lego/legoomni/include/legoplantmanager.h
- LEGO1/lego/legoomni/include/legoworld.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/common/legoplantmanager.cpp
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/entity/legoworldpresenter.cpp
- LEGO1/lego/legoomni/src/main/legomain.cpp
- LEGO1/lego/legoomni/src/worlds/legoact2.cpp
This adds an enum for the world IDs and uses this type consistently throughout the code base.
> Add `LegoOmni::World` enum

- .github/workflows/build.yml
- CMakeLists.txt
- LEGO1/lego/legoomni/include/legoanimationmanager.h
- LEGO1/lego/legoomni/include/legocharactermanager.h
- LEGO1/lego/legoomni/include/legoplantmanager.h
- LEGO1/lego/legoomni/src/actors/ambulance.cpp
- LEGO1/lego/legoomni/src/actors/bike.cpp
- LEGO1/lego/legoomni/src/actors/dunebuggy.cpp
- LEGO1/lego/legoomni/src/actors/islepathactor.cpp
- LEGO1/lego/legoomni/src/actors/jetski.cpp
- LEGO1/lego/legoomni/src/actors/motorcycle.cpp
- LEGO1/lego/legoomni/src/actors/pizza.cpp
- LEGO1/lego/legoomni/src/actors/skateboard.cpp
- LEGO1/lego/legoomni/src/actors/towtrack.cpp
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
- LEGO1/lego/legoomni/src/common/legoplantmanager.cpp
- LEGO1/lego/legoomni/src/entity/legonavcontroller.cpp
- LEGO1/lego/legoomni/src/race/carrace.cpp
- LEGO1/lego/legoomni/src/worlds/act3.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
- LEGO1/lego/legoomni/src/worlds/legoact2.cpp
Match at ~92%. The debug functionality is all present now.
Also, since all functions are now referenced within the module, I've enabled `OPT:REF` (same as for `ISLE.EXE`) to get rid of unused library functions
> Implement/match `LegoNavController::Notify`

- README.md
This PR brings the project's README more in line with the current status.
The changes I've made are mostly in regard to the reality that we unfortunately cannot guarantee byte-for-byte matching binaries at this point in time. These parts of the README were written very early on in the project, when we didn't fully understand the concept of compiler entropy and were still under the assumption that having complete `LEGO1` headers would guarantee identical binary output. Because of the uncertainness and complexity of the situation with the compiler, I have put a bigger focus on functional accuracy instead.
I have also made changes to the `LEGO1.DLL` status description now that the game is fully playable when built from our source code. As far as we know, there should be no more inaccuracies …
> readme refresh 2

- .github/workflows/build.yml
- LEGO1/lego/legoomni/src/paths/legopathboundary.cpp
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
- LEGO1/lego/sources/geom/legoedge.h
- LEGO1/lego/sources/geom/legounkown100db7f4.h
- LEGO1/lego/sources/geom/legoweedge.cpp
- LEGO1/lego/sources/geom/legoweedge.h
- LEGO1/lego/sources/geom/legowegedge.cpp
- LEGO1/lego/sources/geom/legowegedge.h
`LegoWEGEdge::VTable0x04`: ~95% match (at least before entropy)
`LegoWEGEdge::FUN_1009aea0`: ~82% match
> Implement/match `LegoWEGEdge` functions

- LEGO1/lego/legoomni/include/helicopter.h
- LEGO1/lego/legoomni/include/legoworld.h
- LEGO1/lego/legoomni/src/actors/helicopter.cpp
- LEGO1/lego/legoomni/src/common/legoutils.cpp
- LEGO1/lego/legoomni/src/entity/legoentity.cpp
- LEGO1/lego/legoomni/src/entity/legonavcontroller.cpp
- LEGO1/lego/legoomni/src/paths/legopathactor.cpp
- LEGO1/lego/legoomni/src/race/legoracers.cpp
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
- LEGO1/lego/legoomni/src/video/legoloopinganimpresenter.cpp
> Match `Helicopter::HandleEndAnim`

- CMakeLists.txt
- LEGO1/omni/include/mxbitmap.h
- LEGO1/omni/include/mxsmk.h
- LEGO1/omni/include/mxsmkpresenter.h
- LEGO1/omni/src/video/mxloopingsmkpresenter.cpp
- LEGO1/omni/src/video/mxsmk.cpp
- LEGO1/omni/src/video/mxsmkpresenter.cpp
Name confirmed via original NMAKE File in the 1996 source code.
> rename MxSmack to MxSmk

- LEGO1/lego/legoomni/include/legotextureinfo.h
- LEGO1/lego/legoomni/src/common/legobackgroundcolor.cpp
- LEGO1/lego/legoomni/src/common/legotextureinfo.cpp
- LEGO1/lego/legoomni/src/common/legoutils.cpp
- LEGO1/lego/sources/anim/legoanim.cpp
- LEGO1/omni/src/video/mxdisplaysurface.cpp
- LEGO1/tgl/d3drm/texture.cpp
I could no longer live with these warnings ;)
> Fix warnings triggered by isle-portable

- LEGO1/realtime/matrix.h
- LEGO1/realtime/vector.h
- LEGO1/realtime/vector4d.inl.h
> Use `COMPAT_MODE` to fix inline function not defined warnings on modern compilers

- .github/workflows/build.yml
Part 2 of #1351
Leaving this as a draft until the pipeline has run successfully
Edit: Looks good: https://github.com/isledecomp/isle/actions/runs/12855083539/job/35840232678?pr=1352
>  Refactor diffs in the pipeline, part 2

- LEGO1/lego/legoomni/src/worlds/registrationbook.cpp
> Match `RegistrationBook::ReadyWorld`

- LEGO1/lego/legoomni/src/entity/act2brick.cpp
- LEGO1/lego/sources/roi/legoroi.h
> Match `Act2Brick::Create`

- LEGO1/lego/legoomni/include/infocenter.h
- LEGO1/lego/legoomni/include/legocontrolmanager.h
- LEGO1/lego/legoomni/include/legogamestate.h
- LEGO1/lego/legoomni/src/actors/ambulance.cpp
- LEGO1/lego/legoomni/src/actors/bike.cpp
- LEGO1/lego/legoomni/src/actors/dunebuggy.cpp
- LEGO1/lego/legoomni/src/actors/jetski.cpp
- LEGO1/lego/legoomni/src/actors/motorcycle.cpp
- LEGO1/lego/legoomni/src/actors/radio.cpp
- LEGO1/lego/legoomni/src/actors/skateboard.cpp
- LEGO1/lego/legoomni/src/actors/towtrack.cpp
- LEGO1/lego/legoomni/src/audio/mxbackgroundaudiomanager.cpp
- LEGO1/lego/legoomni/src/control/legocontrolmanager.cpp
- LEGO1/lego/legoomni/src/entity/legoworld.cpp
- LEGO1/lego/legoomni/src/main/scripts.cpp
- LEGO1/lego/legoomni/src/race/legoracemap.cpp
- LEGO1/lego/legoomni/src/worlds/elevatorbottom.cpp
- LEGO1/lego/legoomni/src/worlds/gasstation.cpp
- LEGO1/lego/legoomni/src/worlds/hospital.cpp
- LEGO1/lego/legoomni/src/worlds/infocenter.cpp
- LEGO1/lego/legoomni/src/worlds/infocenterdoor.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
- LEGO1/lego/legoomni/src/worlds/police.cpp
- LEGO1/lego/legoomni/src/worlds/registrationbook.cpp
- LEGO1/lego/legoomni/src/worlds/score.cpp
- LEGO1/omni/include/mxpresenter.h
- LEGO1/omni/src/video/mxvideomanager.cpp
Closes #1359. I also removed some incorrect getters and setters, which did improve the match in some cases.
> Match `Infocenter::HandleControl`

- LEGO1/lego/legoomni/include/infocenter.h
- LEGO1/lego/legoomni/src/common/legostate.cpp
- LEGO1/lego/legoomni/src/worlds/infocenter.cpp
Why does the "Enter" button on a fresh PR submit immediately?
Up to 96 %, the rest might be entropy, but I couldn't trigger it intentionally.
Closes #1358
> Match `Infocenter::ReadyWorld`

- LEGO1/lego/legoomni/src/actors/ambulance.cpp
> Fix enum in `Ambulance::HandlePathStruct`

- LEGO1/mxdirectx/mxdirect3d.cpp
Another one targeted by the entropy build. (Max accuracy 94.94%)
The beta shows where they call `memcpy` and where they just copy structs directly via assignment. Variable name `d` for the `MxAssignedDevice` confirmed by the assert.
The only diff I still see with the beta is in how the `d->m_flags` value gets set. It isn't done in place with the `or` instruction as we have it. I left it alone for now because it doesn't affect retail.
The drop on `MxDirect3D::D3DSetMode` is more entropy.
> `MxDirect3D::SetDevice` to 100%

- LEGO1/lego/legoomni/include/legoanimactor.h
- LEGO1/lego/legoomni/include/legosoundmanager.h
- LEGO1/lego/legoomni/src/actors/act2actor.cpp
- LEGO1/lego/legoomni/src/audio/lego3dsound.cpp
- LEGO1/lego/legoomni/src/audio/legocachesoundmanager.cpp
- LEGO1/lego/legoomni/src/audio/legosoundmanager.cpp
- LEGO1/library_msvc.h
- LEGO1/omni/include/mxsoundmanager.h
- LEGO1/omni/include/mxticklemanager.h
- LEGO1/omni/src/audio/mxsoundmanager.cpp
- LEGO1/omni/src/common/mxticklemanager.cpp
- reccmp-project.yml
A collection of BETA10 addresses that I collected while working on various things (that mostly didn't get anywhere).
> Add various BETA10 references and fixes

- LEGO1/lego/legoomni/src/video/legohideanimpresenter.cpp
- LEGO1/lego/sources/anim/legoanim.h
- LEGO1/lego/sources/geom/legowegedge.h
> Match `LegoHideAnimPresenter::FUN_1006db60`

- LEGO1/omni/src/video/mxvideopresenter.cpp
Using `MxBitmap::GetStart` just like #1425.
Doesn't match beta exactly. Maybe some code was shuffled around after adding the alpha mask.
> `MxVideoPresenter::IsHit` to 100%

- LEGO1/omni/src/video/mxdisplaysurface.cpp
> Match `MxDisplaySurface::SetPalette`

- LEGO1/mxdirectx/legodxinfo.cpp
> Match `LegoDeviceEnumerate::SupportsMMX`

- README.md
> README: update playlist link

- CONFIG/ConfigCommandLineInfo.cpp
- CONFIG/MainDlg.cpp
- CONFIG/config.cpp
- CONFIG/detectdx5.cpp
- ISLE/isleapp.cpp
- LEGO1/lego/legoomni/include/legomain.h
- LEGO1/lego/legoomni/src/common/legoutils.cpp
- LEGO1/lego/legoomni/src/video/legovideomanager.cpp
- LEGO1/omni/src/audio/mxmusicmanager.cpp
- LEGO1/omni/src/stream/mxdsfile.cpp
- LEGO1/omni/src/system/mxcriticalsection.cpp
- LEGO1/omni/src/system/mxsemaphore.cpp
- LEGO1/omni/src/video/mxbitmap.cpp
> make all calls to winapi format-agnostic

- LEGO1/omni/src/video/mxbitmap.cpp
As seen in this video: https://github.com/isledecomp/isle-portable/pull/76
CC @AJenbo
> Fix wrong use of `delete` vs `delete[]`

- LEGO1/tgl/d3drm/view.cpp
This assert is obviously wrong, it would be checking uninitiated data which isn't meaningful, but inside the clause above it makes perfect sens.
> Correct assert in view.cpp

- LEGO1/omni/src/video/mxstillpresenter.cpp
Without this the game doesn't  run on Linux :)
@foxtacles can you please make a github suggestion for the cast you want me to apply here? Then if I understand it I'll at the 3 others that I found since.
> Fix delete[] in mxstillpresenter.cpp

- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/common/legobuildingmanager.cpp
- LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
- LEGO1/lego/legoomni/src/common/legogamestate.cpp
- LEGO1/lego/legoomni/src/common/legoplantmanager.cpp
- LEGO1/lego/legoomni/src/entity/legoworldpresenter.cpp
- LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
- LEGO1/lego/legoomni/src/video/legomodelpresenter.cpp
- LEGO1/lego/legoomni/src/video/legopalettepresenter.cpp
- LEGO1/lego/legoomni/src/video/legopartpresenter.cpp
- LEGO1/lego/legoomni/src/video/legotexturepresenter.cpp
- LEGO1/lego/sources/anim/legoanim.cpp
- LEGO1/lego/sources/misc/legoimage.cpp
- LEGO1/lego/sources/misc/legostorage.h
- LEGO1/lego/sources/misc/legotree.cpp
- LEGO1/lego/sources/roi/legolod.cpp
- LEGO1/lego/sources/roi/legoroi.cpp
- LEGO1/lego/sources/shape/legocolor.cpp
- LEGO1/lego/sources/shape/legomesh.cpp
- LEGO1/lego/sources/shape/legosphere.cpp
- LEGO1/lego/sources/shape/legovertex.cpp
- LEGO1/modeldb/modeldb.cpp
- LEGO1/omni/src/action/mxdsaction.cpp
- LEGO1/omni/src/action/mxdsmediaaction.cpp
- LEGO1/omni/src/stream/mxstreamchunk.cpp
- LEGO1/omni/src/video/mxbitmap.cpp
Ideally, this should cause no accuracy regression.
> Use sizeof(type) instead of sizeof(variableName) when (de)serializing data

- ISLE/isleapp.cpp
- ISLE/isleapp.h
- LEGO1/lego/legoomni/src/video/legovideomanager.cpp
- LEGO1/viewmanager/viewroi.cpp
- LEGO1/viewmanager/viewroi.h
Commit https://github.com/isledecomp/isle/commit/fce97ea06f5c8a852f63971e55a810c9e7351ac9 changed the name of `MxVideoParamFlags::SetF2bit0` and `MxVideoParamFlags::GetF2bit0` to `MxVideoParamFlags::SetLacksLightSupport` and `MxVideoParamFlags::GetLacksLightSupport`.
This propagates those naming changes to Stuff using those two functions.
> propagate name changes from commit fce97ea

- LEGO1/tgl/d3drm/device.cpp
- LEGO1/tgl/d3drm/impl.h
- LEGO1/tgl/tgl.h
Not much of a diff on this one. I changed the param on `HandlePaint` to support the variable cast to `HDC`.
> `TglImpl::DeviceImpl` functions

- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
As pointed out by @madebr here https://github.com/isledecomp/isle-portable/issues/192
> Apply RAND_MAX to legoanimationmanager.cpp

- LEGO1/viewmanager/viewmanager.cpp
- LEGO1/viewmanager/viewmanager.h
> BETA matches in `ViewManager`

- LEGO1/lego/sources/anim/legoanim.cpp
- LEGO1/lego/sources/roi/legoroi.cpp
- LEGO1/lego/sources/roi/legoroi.h
- LEGO1/realtime/orientableroi.cpp
- LEGO1/realtime/orientableroi.h
- LEGO1/realtime/roi.h
- LEGO1/viewmanager/viewroi.cpp
- LEGO1/viewmanager/viewroi.h
Inspired by #1565 (I'd wait for that one to be merged first and then rebase).
~~There's one part that confused me. If we can't figure it out, I'll remove it from this PR.~~ Will open another PR, see below.
Tasks:
> Add BETA10 addresses for `LegoROI`

- LEGO1/lego/legoomni/include/legogamestate.h
- LEGO1/lego/legoomni/src/common/legogamestate.cpp
- LEGO1/lego/legoomni/src/worlds/act3.cpp
- LEGO1/lego/legoomni/src/worlds/infocenter.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
- LEGO1/lego/legoomni/src/worlds/legoact2.cpp
Leaving as a draft until the CI has run. Might consider an entropy build as well before merging.
Some of those getters/setters are proven not to exist in BETA10. However, some of the fields don't even exist in BETA10, so nothing can be concluded with certainty.
> Remove getters/setters that (likely) don't exist

- LEGO1/lego/legoomni/include/legopathactor.h
- LEGO1/lego/legoomni/include/legoracers.h
- LEGO1/lego/legoomni/include/legoracespecial.h
- LEGO1/lego/legoomni/src/paths/legopathactor.cpp
- LEGO1/lego/legoomni/src/race/carrace.cpp
- LEGO1/lego/legoomni/src/race/jetskirace.cpp
- LEGO1/lego/legoomni/src/race/legoraceactor.cpp
- LEGO1/lego/legoomni/src/race/legoracers.cpp
- LEGO1/lego/legoomni/src/race/legoracespecial.cpp
Hello, decided to take a look at a small piece of the code to see if I could name any of the variables or functions. I managed to get a few down, but not that much. (hopefully enough to grant a pull request)
> Names for race related or adjacent functions and variables

- LEGO1/lego/legoomni/src/common/legoutils.cpp
Fixing https://github.com/isledecomp/isle-portable/issues/483
> Fix writing default texture

- LEGO1/lego/legoomni/src/common/legoanimmmpresenter.cpp
- LEGO1/lego/legoomni/src/common/mxcompositemediapresenter.cpp
- LEGO1/lego/legoomni/src/common/mxcontrolpresenter.cpp
- LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
- LEGO1/omni/include/mxdsaction.h
- LEGO1/omni/include/mxdsmultiaction.h
- LEGO1/omni/src/action/mxdsaction.cpp
- LEGO1/omni/src/action/mxdsmultiaction.cpp
- LEGO1/omni/src/common/mxmediapresenter.cpp
- LEGO1/omni/src/stream/mxdsbuffer.cpp
- LEGO1/omni/src/stream/mxstreamcontroller.cpp
This should not be confused with `GetStartTime()`, as that represents the time offset from the SI file.
> Clear time started unknown in `MxDSAction`

- CMakeLists.txt
> `CONFIG`: use `new` and `delete` from `MFC42.dll`

- LEGO1/lego/legoomni/include/act3.h
- LEGO1/lego/legoomni/include/legoinputmanager.h
- LEGO1/lego/legoomni/include/legovideomanager.h
- LEGO1/lego/legoomni/src/main/legomain.cpp
- LEGO1/lego/legoomni/src/worlds/act3.cpp
- LEGO1/omni/include/mxvideomanager.h
- LEGO1/omni/src/video/mxdisplaysurface.cpp
Originally I wanted to match `Act3List::FUN_100720d0`, but I didn't get a decent match on that one yet. Here's the rest of my changes to simplify the review (and I don't know if/when I'll find the time to match the function).
Still running an entropy build before this goes out for review.
> Interpret `Act3List` properties, minor fixes

- LEGO1/lego/legoomni/include/act3.h
- LEGO1/lego/legoomni/src/worlds/act3.cpp
Got this up to 100 % effective.
This was a nasty one, mostly because some of the code makes little sense. I left some comments.
Closes #1360.
> Match `Act3List::FUN_100720d0`

- LEGO1/lego/legoomni/include/legocontrolmanager.h
- LEGO1/lego/legoomni/src/actors/ambulance.cpp
- LEGO1/lego/legoomni/src/actors/bike.cpp
- LEGO1/lego/legoomni/src/actors/dunebuggy.cpp
- LEGO1/lego/legoomni/src/actors/helicopter.cpp
- LEGO1/lego/legoomni/src/actors/jetski.cpp
- LEGO1/lego/legoomni/src/actors/motorcycle.cpp
- LEGO1/lego/legoomni/src/actors/skateboard.cpp
- LEGO1/lego/legoomni/src/actors/towtrack.cpp
- LEGO1/lego/legoomni/src/build/legocarbuild.cpp
- LEGO1/lego/legoomni/src/common/mxcontrolpresenter.cpp
- LEGO1/lego/legoomni/src/race/carrace.cpp
- LEGO1/lego/legoomni/src/race/jetskirace.cpp
- LEGO1/lego/legoomni/src/race/legoracemap.cpp
- LEGO1/lego/legoomni/src/worlds/elevatorbottom.cpp
- LEGO1/lego/legoomni/src/worlds/gasstation.cpp
- LEGO1/lego/legoomni/src/worlds/hospital.cpp
- LEGO1/lego/legoomni/src/worlds/infocenter.cpp
- LEGO1/lego/legoomni/src/worlds/infocenterdoor.cpp
- LEGO1/lego/legoomni/src/worlds/isle.cpp
- LEGO1/lego/legoomni/src/worlds/jukebox.cpp
- LEGO1/lego/legoomni/src/worlds/police.cpp
- LEGO1/lego/legoomni/src/worlds/registrationbook.cpp
- LEGO1/lego/legoomni/src/worlds/score.cpp
The name is maybe a bit weird, but based on the name from `MxControlPresenter`.
> Clear unknown in `LegoControlManagerNotificationParam`

- LEGO1/lego/legoomni/src/build/legocarbuild.cpp
Looks like a minor oversight during a _clear unknowns_ PR and the lack of CI for BETA10. Maybe we should address the latter at some point.
> Fix regression: BETA10 does not compile

- .github/workflows/build.yml
Fixes #1637. Might want to double check the CMake options I used.
> Build `BETA10` in CI

- LEGO1/lego/legoomni/include/legocharactermanager.h
- LEGO1/lego/legoomni/include/legogamestate.h
- LEGO1/lego/legoomni/include/legovariables.h
- LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
- LEGO1/lego/legoomni/src/common/legogamestate.cpp
- LEGO1/lego/legoomni/src/common/legovariables.cpp
- LEGO1/omni/include/mxvariable.h
Not much matching required here. I added a new constructor for `LegoFullScreenMovie` and the `DebugVariable` class.
> Beta functions for `MxVariable`

- LEGO1/lego/legoomni/include/legopathboundary.h
- LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
- LEGO1/lego/legoomni/src/video/legomodelpresenter.cpp
- LEGO1/lego/legoomni/src/worlds/act3.cpp
- LEGO1/lego/sources/geom/legoweedge.cpp
- LEGO1/lego/sources/geom/legoweedge.h
- LEGO1/lego/sources/geom/legowegedge.cpp
- LEGO1/lego/sources/geom/legowegedge.h
- LEGO1/lego/sources/roi/legoroi.cpp
- LEGO1/library_msvc.h
A bunch of matches I found while working on other parts that didn't (yet) go anywhere.
> Add BETA10 matches for `LegoWEGEdge` and others

- LEGO1/lego/legoomni/include/infocenter.h
- LEGO1/lego/legoomni/src/worlds/infocenter.cpp
Removes enums that were better defined elsewhere already (Intro actions and Lego actors)
> Remove obsolete enums in Infocenter
