isledecomp/isle

ISLE/isle.cpp

Replaced some hardcoded values with the Windows-defined macro constants as per documentation:
https://learn.microsoft.com/en-us/windows/win32/menurc/wm-syscommand

Use Windows-defined type constants in WM_SYSCOMMAND

---

ISLE/define.cpp
ISLE/define.h
ISLE/isle.cpp
ISLE/main.cpp

Matched Fully: `startDirectSound`, `WNDCLASS_NAME`, `readReg`
Partially Matched: `setupVideoFlags`
Changes:
In `startDirectSound` `lpDS` is now initialized to zero.
`WNDCLASS_NAME` is now a macro definition.
`WINDOW_TITLE` has been left untouched. However, in 1.0 it is also a macro, and it has a value of "Lego Island". The decomp already matches to 1.1, but I thought it would be good to mention that.
In `readReg` now creating and assigning an out and size variable.
In `setupVideoFlags` calling `EnableUnknown2` after `EnableWideViewAngle`.
All changes have been checked against 1.0 and 1.1 and other than `WINDOW_TITLE` they match both.
There is another difference in `setupVideoFlags` that I was unable to fix. The first line of the decompiled original binary looks like this
```
bVar2 = …
```

Match some functions and values to the original binary

---

ISLE/main.cpp

Noticed a couple other potential Unicode issues and thought I'd clean those up rq
In doing this I specifically excluded the `.vscode` directory that also enforces Windows-1252 encoding in the editor, let me know if that'd be a worthwhile PR on its own.

isle: replace other instances of ®️ with \xAE

---

LEGO1/mxomnicreateparam.cpp
LEGO1/mxomnicreateparam.h

Minor bug introduced in https://github.com/isledecomp/isle/pull/15 which lead to `ISLE.EXE` not working anymore (in conjunction with the original `LEGO1.DLL`) since a signature was changed in an incompatible way.

Fix broken MxOmniCreateParam ctor interface

---

LEGO1/mxvideoparamflags.h

This commit broke `ISLE.EXE`: https://github.com/isledecomp/isle/commit/f8263a3ef86cfd3623bd933807915e00ebe46687
`MxBool` is a 1-byte char, the Windows-defined `BOOL` is a 4-byte int. Easy to mix up for sure.

lego1/isle: Fix wrong video param flag interfaces

---

LEGO1/mxstring.cpp
LEGO1/mxstring.h

Added some missing functions to MxString. The function at 0x100ae580 looks like a constructor for something else, so this may be all of it.
Everything matches except the swapped regs for `cmp eax, esi` in the MxString to char* comparator. What's odd is that other functions in the class can influence this order. For example, if I comment out one of the newly added ToUpperCase or ToLowerCase functions.

lego1: MxString matching

---

ISLE/isle.cpp

Making a separate PR for this one since the accuracy checker has a problem with detecting a 100% match with this function. Maybe because of the jump table? Not sure. As far as I can tell it does match the original assembly completely.
I don't mind that the check isn't perfect in all cases, just wanting to give you the opportunity to further improve it using this example @itsmattkc

isle: Match Isle::SetupCursor

---

ISLE/define.h
ISLE/isle.h
ISLE/main.cpp

This PR: https://github.com/isledecomp/isle/pull/32 accidentally broke `ISLE.EXE` - not so much because of the code changes, but because of a `Windows.h` include that sneaked `GetClassName` in and lead to immediate crashes.
I removed all remaining instances of `windows.h` includes and replaced them with `legoinc.h`

Hotfix: messed up structure due to windows.h

---

ISLE/isle.cpp
ISLE/isle.h
LEGO1/mxvideoparamflags.cpp
LEGO1/mxvideoparamflags.h

Using a bitfield for MxVideoParamFlags results in the same xor/and logic that was partially inlined in the header file. This approach is a lot cleaner and there's a good chance this is what the devs would have landed on.
The code generation is really finicky -- other inlines in the header influence the code just by being there -- so I decided to stub out all of them. This got the match to 100%.
While I was in isle.cpp::SetupVideoFlags, I changed the signature so that the `m_using16bit` parameter is just `using16bit`. Two of the parameters from SetupVideoFlags are negated when we set the flags, which seems odd. Maybe a name change is in order on backBuffers?

Use bitfield for MxVideoParamFlags

---

LEGO1/legoomni.cpp
LEGO1/legoomni.h
LEGO1/mxcore.cpp
LEGO1/mxcore.h

A minor PR matching the currently implemented `GetClassName` / `IsClass` functions. They generally need to be declared inline. This pattern is probably used in all other classes as well.

lego: match GetClassName/IsClass

---

LEGO1/mxstring.cpp
LEGO1/mxstring.h

Followed the hint from @madebr in #31 that the next function in MxString was operator+. The one after that is operator+= and both are at 100%.
~~I thought maybe these new changes would magically fix the swapped regs in the `cmp` instruction from operator= at `0x100ae510`, but no luck.~~
Replaced malloc/free with new/delete, which had the side effect of fixing the swapped regs in operator=

lego1: Two more operators for MxString

---

LEGO1/legoomni.cpp
LEGO1/legoomni.h
LEGO1/mxomni.cpp
LEGO1/mxomni.h

- The m_unka0 field in LegoOmni is an MxDsAction, which allows the deconstructor to match
- Implemented LegoOmni::GetInstance and Destroy instance
- moves a few functions to their correct places

lego1: match LegoOmni::GetInstance and deconstructor and add a few methods

---

LEGO1/mxbitmap.cpp
LEGO1/mxbitmap.h

Matched and cleaned up `MxBitmap::Read` (and implemented `MxBitmap::vtable28`), also added the stubs for the other functions. Their signatures aren't necessarily 100% correct yet, just based on a cursory glance.

lego1: match MxBitmap::Read and vtable

---

tools/reccmp/reccmp.py

I noticed all paths in the output of `cvdump.exe` started with `.\`.
This pr proposes to do a naive string append + replace instead of executing winepath each time.
For my machine, this reduces the time of `reccmp.py` from ~80s to ~2s.
While looking for this bug, I added logging support which might be useful in the future.
Last, I sneaked in a little fix for those people developing on big-endian machines.

Faster reccmp.py on linux

---

LEGO1/mxdsfile.cpp

Not entirely sure _why_ this works, but it works.

LEGO1: MxDSFile::Open is now matching 100%

---

LEGO1/legoutil.cpp

`reccmp.py` currently gets confused by jump tables and only reports a ~90% match, but the actual code is matching now.

LEGO1: ConvertHSVToRGB is now effectively 100% matched

---

LEGO1/mxatomid.h
LEGO1/mxdsaction.cpp
LEGO1/mxdsanim.cpp
LEGO1/mxdsevent.cpp
LEGO1/mxdsmediaaction.cpp
LEGO1/mxdsmultiaction.cpp
LEGO1/mxdsobject.cpp
LEGO1/mxdsobject.h
LEGO1/mxdsobjectaction.cpp
LEGO1/mxdsparallelaction.cpp
LEGO1/mxdsselectaction.cpp
LEGO1/mxdsserialaction.cpp
LEGO1/mxdssound.cpp
LEGO1/mxdsstill.cpp
LEGO1/mxdstypes.h

`m_unk0c` is a type ID in `MxDSObject`, and it's set in every `MxDS*` ctor that belongs to the `MxDSObject` family. It was renamed to `m_type`. In some classes, this is all the ctor does so they match completely now.
The regressions in some of the ctors are meaningless since the bulk of the code in them is still missing. Setting the type like this is correct though. 
The regressions (operand swaps) in two `MxDSObject` functions appeared after adding `DECOMP_SIZE_ASSERT`, so they should be disregarded.
I've marked the dtors as `STUB`'s that were completely empty (but shouldn't be) so they don't appear in the report anymore. The dtors that indeed don't "do" anything (other than the implicit stuff) had their `// TODO` and `STUB` removed if it was present and match 100% now.
Also refactored …

lego: add MxDSType enum, add it to all ctors, refactor `MxDSObject`

---

CMakeLists.txt
LEGO1/mxdiskstreamprovider.cpp
LEGO1/mxdiskstreamprovider.h
LEGO1/mxsemaphore.cpp
LEGO1/mxsemaphore.h
LEGO1/mxstreamprovider.h
LEGO1/mxthread.cpp
LEGO1/mxthread.h
LEGO1/mxtimer.h

* Add MxSemphore + MxThread and the two implementations I could find of MxThread (consumers extend it and override the Run method).
* Implement a function in MxDiskStreamProvider which uses thread and semaphore to confirm correct layout / size of those classes.
* All 100% match except two functions with a pair of registers swapped.
* Fix a bug in MxTimer which went unnoticed because both globals are just `<OFFSET>` in the diff tool.

MxSemphore + MxThread + MxThread implementions 100% Match

---

tools/reccmp/reccmp.py
tools/reccmp/template.html

* Rather than using \<OFFSET\> as a replacement for all offsets in a function, label the unique offsets as \<OFFSET1\>, \<OFFSET2\>, etc. Doing this will avoid false-positive 100% matches resulting from the same function being called two times where a different on should have been called or vice versa. And the same for globals. I already encountered one case of this in the wild.
* When a 100% match initially fails, try to make the functions match by swapping register allocations. This makes it possible to get a 100% match where the generated machine code differs only in register allocation.
* Only apply the above when it is possible to reach a 100% match in that way. Otherwise show the developer the unadulterated diff to avoid causing problems. (This register swapping approach is only …

reccmp.py Disambiguate <OFFSET> + Better 100% match mechanics

---

LEGO1/mxdisplaysurface.h
LEGO1/mxunknown100dc768.h
LEGO1/mxvideomanager.cpp
LEGO1/mxvideomanager.h

Completes/matches the implementation of `MxVideoManager::RealizePalette` and adds the `MxDisplaySurface` class and its virtual functions to do so.

lego1: match MxVideoManager::RealizePalette

---

CMakeLists.txt
LEGO1/mxdisplaysurface.cpp
LEGO1/mxdisplaysurface.h

Some initial implementation work on `MxDisplaySurface`. If I read the Ghidra commit history correctly most of this information has been contributed by @itsmattkc already, so I mainly just verified it and put it into (clean) code.

lego1: Add MxDisplaySurface class members and some functions

---

CMakeLists.txt
ISLE/isleapp.cpp
LEGO1/mxnotificationmanager.cpp
LEGO1/mxticklemanager.cpp
LEGO1/mxticklemanager.h
LEGO1/mxtypes.h

A 100% match of everything in MxTickleManager except the actual Tickle method. SetClientTickleInterval is at a pitiful 24.14% but if you look at 85f4a5521978180c54b46c2b682a857a77ffaa7c you'll see the exact same code at 100%, it just gets obliterated by register allocation (the part that checks the flag). The Tickle method also feels really close to me, but it has issues with register allocation too (the part that checks the flag, and what seems to be unnecessary shuffling of a few vars between the stack and registers). So it's only at 52.17%, but it seems unproductive to keep working on it right now as it may just sort itself out.

MxTickleManager mostly done

---

CMakeLists.txt
LEGO1/mxmatrix.cpp
LEGO1/mxmatrix.h
LEGO1/mxvector.cpp
LEGO1/mxvector.h
tools/reccmp/reccmp.py

* All of the MxVectors share an inheritance chain. MxVector4 inherits from MxVector3 which inherits from MxVector2.
* They all operate on a shared `float*` data member which points to the underlying storage.
* There are also MxVector3/4Data classes, which inherit from Vector3/4, but add concrete storage for the Vector data rather than just an abstract data pointer, and point the data member at that storage.
* The same is true for MxMatrix, with there being an abstract and a concrete variant of it.
* Also improve reccmp.py register matching algorithm. It previously could not recognize an effective match when a swap had to take place between two registers used on the same line. It turns out this happens a lot in floating point math code so I adjusted the implementation to break the …

Implement MxVector2/3/4 and MxMatrix

---

LEGO1/mxdsaction.cpp
LEGO1/mxvector.h

Matches `CopyFrom` in `MxDSAction`. I've added an alternative accessor to the concrete storage of the vector since in this case the elements aren't addressed individually.

Match MxDSAction::CopyFrom

---

LEGO1/mxdsaction.h
LEGO1/mxdsmediaaction.cpp
LEGO1/mxdsmediaaction.h

Everything matches, except:
`Deserialize`: a case of different register allocations / instruction swaps
`CopyFrom`: different instructions for assigning values, probably has to do with the data types of `unk_9c` and `unk_a0` being wrong for now

Implement MxDSMediaAction

---

.github/workflows/build.yml

This is a minor thing, but builds on the master branch fail for all the forks. The reason is that only the main repo has the creds required to upload the progress report to legoisland.org. There's no reason to even attempt this for a fork, so just skip this step if we are on master branch but not isledecomp/isle.

[workflow] Skip upload step for forks

---

CMakeLists.txt
LEGO1/compat.h
LEGO1/mxatomid.cpp
LEGO1/mxatomid.h
LEGO1/mxatomidcounter.cpp
LEGO1/mxatomidcounter.h
LEGO1/mxomni.cpp
LEGO1/mxomni.h

Rewrite of #99. Implement all of MxAtomId. This class interfaces with a reference counter data structure created in MxOmni. I had this partly reversed in the previous PR. Hat tip to @BranDougherty for identifying the red-black tree as a use of the STL.
I used a `<set>` for holding the reference counters. This seems odd because a `<map>` should be the best option: we have MxString as the key and MxU16 as the value. And yet if you try with a map, when we alloc the structure in `MxOmni::Create`, the leaf (or _Nil) node size is much larger than it should be. Also: the Inc/Dec functions at 0x100ad7f0/0x100ad800 refer to offset +0x10, so there's obviously more there than just the MxU16. That offset includes the preceding MxString for a total of 20 bytes on the combined key/value type (rounded …

Implement MxAtomId and reference counter (stl set)

---

CMakeLists.txt
LEGO1/mxdsaction.h
LEGO1/mxdsstreamingaction.cpp
LEGO1/mxdsstreamingaction.h

Everything matches except for the destructor (which requires implementation of `MxDSBuffer`)

Implement MxDSStreamingAction

---

LEGO1/mxdsanim.cpp
LEGO1/mxdsanim.h
LEGO1/mxdsevent.cpp
LEGO1/mxdsevent.h
LEGO1/mxdsobjectaction.cpp
LEGO1/mxdsobjectaction.h
LEGO1/mxdsstill.cpp
LEGO1/mxdsstill.h

100% matches. They are all essentially identical, except for `MxDSObjectAction` which has a virtual `CopyFrom`

Add MxDSAnim, MxDSEvent, MxDSObjectAction, MxDSStill

---

LEGO1/mxdisplaysurface.cpp
LEGO1/mxdisplaysurface.h
LEGO1/mxomni.h
LEGO1/mxrect32.h
LEGO1/mxvideoparam.h

It is a 100% match apart from a few register/instruction swaps we've seen before.
Note: the usage of the `goto` pattern is intentional. I don't believe there is any other way to implement the same branching assembly without using `goto`. Looking at the 1996 source, it appears to be commonly used in functions such as these, so I'm assuming this is correct.

Implement/match MxDisplaySurface::Create

---

LEGO1/mxdsaction.cpp
LEGO1/mxdsaction.h
LEGO1/mxpresenter.cpp
LEGO1/mxpresenter.h

`MxPresenter::Tickle` is a 100% match (ignoring the jump table issue with reccmp). I'm not quite sure what the 5th state is for yet so I've labelled it `unk5`.
I've also implemented/matched two minor functions `SetEnabled` and `IsEnabled`.

Add tickle states and implement/match MxPresenter::Tickle

---

LEGO1/legoomni.cpp
LEGO1/legoomni.h
LEGO1/mxdsaction.cpp
LEGO1/mxdsaction.h
LEGO1/mxomni.cpp
LEGO1/mxomni.h
LEGO1/mxpresenter.cpp
LEGO1/mxpresenter.h

Refactor of #117.
MxPresenter::ParseExtra almost matches, except for the length variable getting optimized away into a register. I'm also not sure why the length is clamped to 0xFFFF before the memcpy but this happens in a few other places, too.
I didn't have a name for "KeyValueStringParse" in the previous PR. It is a sort of general purpose function, but one of these purposes is to get values out of strings from MxOb chunks.
Added stubs for the other MxOmni vtable functions to get a better match on ParseExtra. The names (where there are names) came from the ghidra server.
The 0x3c member of MxPresenter seems to point at another MxPresenter (based on the vtable pointers you get in the debugger) so I set its type.

MxPresenter::ParseExtra

---

CMakeLists.txt
LEGO1/mxlist.h
LEGO1/mxmediamanager.cpp
LEGO1/mxmediamanager.h
LEGO1/mxpresenterlist.cpp
LEGO1/mxpresenterlist.h

The pattern used for `MxList` (and subsequently `MxPresenterList`) is fairly similar to the one used for `MxHashTable`/`MxVariableTable` so I could re-use a fair amount of @disinvite 's code. `MxList` isn't complete yet, it looks like it will also have a `MxListCursor` similarly to `MxHashTableCursor`.
`MxMediaManager` contains the `MxPresenterList` and a function to initialize it, both are implemented and matching.

Add MxList, MxPresenterList, add to MxMediaManager

---

LEGO1/mxlist.h
LEGO1/mxmediamanager.cpp

`MxMediaManager::Tickle` iterates over all its internally held presenters, "tickles" them and eventually calls `VTable0x4c` on all of them.

Implement/match MxMediaManager::Tickle

---

LEGO1/mxdsaction.h
LEGO1/mxpoint32.h
LEGO1/mxpresenter.cpp
LEGO1/mxpresenter.h

There is a very minor diff, which might be related to how the location floats are accessed, but otherwise the function matches. The remaining unknown members of `MxPresenter` were coordinates (consisting of `MxPoint32`, introduced with this PR; and a single `Mx32`)
`MxPresenter::Init` also matches now.

Implement/match MxPresenter::StartAction

---

LEGO1/legoomni.cpp
LEGO1/mxdsfile.cpp
LEGO1/mxdsfile.h
LEGO1/mxdsmultiaction.cpp
LEGO1/mxdsmultiaction.h
LEGO1/mxdsobject.cpp
LEGO1/mxdsobject.h
LEGO1/mxdsparallelaction.cpp
LEGO1/mxdsselectaction.cpp
LEGO1/mxdsselectaction.h
LEGO1/mxdsserialaction.cpp
LEGO1/mxdsserialaction.h
LEGO1/mxdssource.cpp
LEGO1/mxdssource.h

- 100% match on LegoOmni::CreateStreamObject. 
- Near match on MxDSObject::DeserializeDSObjectDispatch. Instruction order and the jump table are throwing this one off.
- Aesthetic change to MxDSFile::Read to improve clarity. Changed the params to match our style guide.
- Removed some unneeded casts to (char*) when calling MXIOINFO::Read
- Added size asserts and dummy members to children of MxDSAction. This was needed for DeserializeDSObjectDispatch.
- Added MxDSSource::GetBuffer. The buffer type is currently (void*), so there's a slightly ugly cast when it gets called in CreateStreamObject.

LegoOmni::CreateStreamObject and related

---

LEGO1/mxmatrix.cpp

Quick one in MxMatrix. The for loop variables need to be optimized away for this to match. To do that, I used a pointer to update m_data and then just incremented it directly rather than relying on the `row * 4 + col` calculation each time.
It seems to work, except for the usual business of the wrong registers getting used. Also, I'm not sure why the compiler thinks that the the first param is `esp + 0x18` instead of `+ 0x10`. You can see how this gets called in the neighbor function EqualsMxProduct, and there are only two dword-sized params.

Improve match for MxMatrix::EqualsDataProduct

---

LEGO1/mxdsaction.h
LEGO1/mxdsmultiaction.cpp
LEGO1/mxdsmultiaction.h
LEGO1/mxlist.h

Implements all the remaining functions of `MxDSMultiAction`. They are all 100% matches.
Note: currently the match for `Deserialize` is only about ~74%, however this is entirely due to compiler randomness. To prove this, I've moved the location of the implementation *before* `GetSizeOnDisk` and that will then yield a 100% match:
However, I will leave the location as-is to preserve the order as observed in the original.

Implement/match remaining MxDSMultiAction functions

---

ISLE/isleapp.cpp
LEGO1/legoomni.cpp
LEGO1/legoomni.h
LEGO1/mxbackgroundaudiomanager.cpp
LEGO1/mxdsaction.cpp
LEGO1/mxdsaction.h
LEGO1/mxomni.cpp
LEGO1/mxomni.h

LegoOmni and MxOmni share some vtable functions, but some changes in MxOmni caused shifts in LegoOmni's table.
We should probably have a script that ensures correct vtables and their addresses. I'm not sure how to pull that info from the PDB yet but it's got to be in there.

Fix LegoOmni vtable

---

CMakeLists.txt
LEGO1/define.cpp
LEGO1/define.h
LEGO1/extra.h
LEGO1/legoentity.cpp
LEGO1/legoentity.h
LEGO1/legoomni.cpp
LEGO1/legoomni.h
LEGO1/legoutil.cpp
LEGO1/legoutil.h
LEGO1/mxentity.cpp
LEGO1/mxentity.h
LEGO1/mxpresenter.cpp
LEGO1/mxpresenter.h

Two new functions and a few changes all related to parsing the Extra string from an MxOb chunk. Specifically: parsing the "Action" section. For example:
```"Action:openram;\lego\scripts\Race\CarRaceR;0"``` (from CARRACE.SI)
Action is the key we are interested in; the rest is the value, with ';' as the delimiter. The first section is the action type, and a new function MatchActionString converts this to an int (enum) that I put in the new file extra.h.
There's no obvious name for the second and third tokens and they don't appear (or are ignored) for some action types. I named these m_actionArgString and m_actionArgNumber for now. The new function LegoEntity::ParseAction sets these variables.
I commented out the size assert on MxEntity (or we could just remove it). It felt more correct to …

LegoEntity parsing extra Action strings

---

LEGO1/legoentity.cpp
LEGO1/legoentity.h
LEGO1/mxentity.cpp
LEGO1/mxentity.h

Added a Reset method to LegoEntity. It zeroes out member values or restores to defaults.
In each place this is called, we are inside of a LegoEntity method or have just created an object where the LegoEntity vtable is set. In #141, we debated how many of the members in the 0x68 sized LegoEntity footprint belong to superclass MxEntity. With this Reset method setting members from 0x10 and up, I feel pretty confident that MxEntity owns just the two members referenced in SetEntityId(). I moved everything over to LegoEntity and updated the size asserts.
The Destroy() method has a parameter (probably a bool based on the callers) but Ghidra (and I) can't see where it's used. Adding this brings the destructor to 100%.
The debugger shows m_unk54 set to an object with vtable 0x100dbe38. The shared …

LegoEntity::Reset

---

LEGO1/mxdisplaysurface.h
LEGO1/mxtransitionmanager.cpp
LEGO1/mxtransitionmanager.h

Dissolve transition, as selected by the Tickle() method. The code comments give my reasoning for naming the two array members from the class. I tried to figure out `FUN_1004c4d0` and `FUN_1004c580` (called by each of the transition functions) to at least give a name, but they both depend on pieces we don't have yet. `FUN_1004c4d0` is doing a memcpy on something. Maybe part of page flipping?
The pixel plot for the "two bytes per pixel" case doesn't match exactly. There is either some subtlety in the casting that I'm missing, or it's our old pal compiler weirdness.
Do we have a preference for using the `ddraw.h` macros for calling virtual methods? e.g. `IDirectDrawSurface_BltFast` versus `surf->BltFast()`.

MxTransitionManager::Dissolve

---

LEGO1/legoomni.cpp
LEGO1/legoomni.h
LEGO1/mxtransitionmanager.cpp
LEGO1/mxtransitionmanager.h

EndTransition is *almost* 100%. It's off by a single instruction (`mov dword ptr [ebp - 4] , esi`), which alters some surrounding jmps:
If anyone has any suggestions to improve this, I'd be happy to hear them, though it could also be random compiler entropy and is arguably close enough to be merged at this state (the missing instruction is literally pointless since it immediately gets replaced in the next instruction anyway)

Implement MxTransitionManager::EndTransition and GetCurrentWorld

---

LEGO1/mxmediamanager.h
LEGO1/mxsoundmanager.cpp
LEGO1/mxsoundmanager.h
LEGO1/mxthread.h

Also make MxThread's destructor public.
ckdev also found the type of m_unk34, which is very helpful. I placed the import for DirectSound at the header of mxmediamanager so the other classes have it

MxSoundManager: dtor, destroy, update types

---

LEGO1/mxdisplaysurface.cpp
LEGO1/mxdisplaysurface.h
LEGO1/mxdsaction.h
LEGO1/mxmediapresenter.cpp
LEGO1/mxmediapresenter.h
LEGO1/mxpresenter.h
LEGO1/mxtransitionmanager.cpp
LEGO1/mxtransitionmanager.h
LEGO1/mxvideopresenter.cpp
LEGO1/mxvideopresenter.h

This PR implements and matches `MxTransition::SetWaitIndicator`
This PR implements `MxTransition::SetupCopyRect`
`SetupCopyRect` does not currently match.
This PR touches into various other classes out of necessity.

Implement MxTransitionManager SetWaitIndicator and SetupCopyRect

---

LEGO1/mxdisplaysurface.cpp
LEGO1/mxdisplaysurface.h
LEGO1/mxtransitionmanager.cpp
LEGO1/mxtransitionmanager.h

Implements MxTransitionManager::Tickle() and MxTransitionManager::FUN_1004bcf0().
FUN_1004bcf0 is 100% matching. Tickle() was matching before merge.
This PR also additionally stubs all of the unimplemented transition methods.

MxTransitionManager::Tickle() & FUN_1004bcf0

---

tools/reccmp/reccmp.py

There is a typo in the reccmp.py script, preventing the program to run on my system. This should solve the issue.

Corrected typo in reccmp.py

---

LEGO1/mxbitmap.h
LEGO1/mxdisplaysurface.cpp
LEGO1/mxdisplaysurface.h
LEGO1/mxpresenter.h
LEGO1/mxsmkpresenter.cpp
LEGO1/mxsmkpresenter.h
LEGO1/mxtransitionmanager.cpp
LEGO1/mxtransitionmanager.h
LEGO1/mxvideopresenter.cpp
LEGO1/mxvideopresenter.h

I was looking at SetupCopyRect() in MxTransitionManager (#165) to see if I could improve the match percentage. No such luck but I have some minor improvements to offer for the related code.
GetWidth() and GetHeight() from MxVideoPresenter point at a reference to MxBitmap. Confirmed with debugger. The 0x60 vtable method from subclass MxSmkPresenter sets this up, so I implemented that to give an example. The 0x60 method from MxVideoPresenter is a no-op. The width and height methods should be correct, but the compiler keeps picking the wrong order for the if/else. I went with the most concise syntax in hope that it will resolve itself later.
The one direct improvement to SetupCopyRect has to do with the m_location member of m_waitIndicator. Grabbing both the x and y coordinates of the …

Supporting items for SetupCopyRect()

---

LEGO1/compat.h

I've found a rather obscure workaround that eliminates all of the `C4786` warning spam. The fact that the `#pragma` doesn't work has been a bug that survived all the way into VC6:
https://web.archive.org/web/20140128153313/http://support.microsoft.com/kb/167355
The workaround has been figured out by someone about 20 years ago, credit is in the comments.

Silence all C4786 warnings

---

ISLE/isleapp.cpp

WinMain stays at 99.52% but this is much more likely to be how the code was actually written.

Remove goto from isleapp.cpp

---

CMakeLists.txt
ISLE/isleapp.cpp
LEGO1/mxramstreamcontroller.cpp
LEGO1/mxramstreamcontroller.h
LEGO1/mxramstreamprovider.cpp
LEGO1/mxramstreamprovider.h
LEGO1/mxstreamcontroller.cpp
LEGO1/mxstreamcontroller.h
LEGO1/mxstreamer.cpp
LEGO1/mxstreamprovider.cpp
LEGO1/mxstreamprovider.h

Everything matches except MxRAMStreamProvider::MxRAMStreamProvider because the vtable gets written after `m_bufferSize = 0;` for some reason.

MxStream provider and controller vtables

---

LEGO1/mxbitmap.cpp
LEGO1/mxbitmap.h
LEGO1/mxsmkpresenter.cpp

Some minor touch-ups to MxBitmap. Should be no change to match percentage.
- The BMP header magic string "BM" was backwards. It is `42 4d` in the file, but is compared as a little-endian unsigned short, so the value in C should be `0x4d42`.
- We discussed this on the Matrix chat a while back, but after some more thought, I think the correct thing is for the m_bitDepth member (renamed here to m_isHighColor) to just be an `MxBool`. It's strange that they use a switch statement to check the values, but not invalid. We know the devs used enums in other places; if this was intended to have more values, it would have been an enum and would be 4 bytes wide. What other values could there be? Grayscale mode?
- Added a helper function to replace the `(value + 3) & -4` expressions. This is a nice …

MxBitmap code clarity

---

LEGO1/mxdsmultiaction.h
LEGO1/mxdsselectaction.cpp
LEGO1/mxdsselectaction.h

Matches:
* `GetSizeOnDisk`: 100%
* `Deserialize`: ~97% (remaining % is compiler randomness)
`Deserialize` is a fairly involved function, but gives a hint on what the "select" part of the class name is referring to - it only picks out a single action from the data stream based on an identifier and adds it to the list.
I believe this marks the completion in terms of both functional implementation and accuracy of all the subclasses of `MxDSObject` (unless I missed something), except for this one `TODO`: https://github.com/isledecomp/isle/blob/master/LEGO1/mxdsaction.cpp#L165

Implement remaining MxDSSelectAction functions

---

LEGO1/mxdsmediaaction.cpp
LEGO1/mxdsmediaaction.h

This completes the remaining, open inaccuracies in the class. Two members are part of a structure (which remains unknown for now; could be `MxPoint32` or similar).

Fix MxDSMediaAction structure/matches

---

LEGO1/mxvector.cpp
LEGO1/mxvector.h

Implemented SetMatrixProductWrapper with 100% match. Notably this function is a wrapper for SetMatrixProduct with different parameters. The name is not the same with the function overloading paradigm since it makes the function no longer have 100% binary match.

Implemented  MxVector4::SetMatrixProductWrapper

---

LEGO1/mxdsaction.cpp

Completes the last remaining accuracy `TODO` in `MxDSAction` (and fixes a bug), so `MxDSObject` and all of its subclasses should be 100% implemented and fully matching now (disregarding compiler randomness).
Also replaced a magic number with the proper flag enum value.

MxDSAction::MergeFrom: match to 100%

---

LEGO1/infocenterstate.h
LEGO1/legogamestate.cpp
LEGO1/legogamestate.h
LEGO1/mxdsaction.cpp
LEGO1/mxdsaction.h
LEGO1/mxdschunk.cpp
LEGO1/mxdschunk.h
LEGO1/mxdsmultiaction.cpp
LEGO1/mxdsmultiaction.h
LEGO1/mxdssource.cpp
LEGO1/mxdssource.h
LEGO1/mxmatrix.cpp
LEGO1/mxmatrix.h

This PR renames all uncertain member/variable/method names to `unk` equivalents. The reason for this is that labeling something that is unknown does not change the fact that, ultimately, it is still unknown and just serves to further complicate the code style of the project. These names still end up providing little useful information to the developer. This naming style also creates further issues as the existence of these labels in the code makes it impossible to get an accurate number of unlabeled members/variables/methods if we were to, for instance, `grep` or otherwise search for all instances of `unk` or `unknown` in the repository.

rename all uncertain labels to unk

---

LEGO1/legoobjectfactory.cpp
LEGO1/legoobjectfactory.h
LEGO1/mxobjectfactory.cpp
LEGO1/mxobjectfactory.h

* Add `MxObjectFactory::Delete` implementation
* Update `MxObjectFactory::Create` to be more similar to original binary.
---
`master`:
```
MxObjectFactory::Create (0x100b12c0) is 27.18% similar to the original
```
This branch:
```
MxObjectFactory::Create (0x100b12c0) is 99.23% similar to the original
MxObjectFactory::Destroy (0x100b1a30) is 100.00% similar to the original
```

Refine MxObjectFactory

---

LEGO1/mxvideomanager.cpp
LEGO1/mxvideomanager.h
LEGO1/mxvideoparam.cpp

Implements `MxVideoManager::Destroy` and related functions (destructor, virtual `Destroy`). 100% matches.
Also replaced some `malloc/free` with `new/delete[]` in `MxVideoParam`

Implement MxVideoManager::Destroy / destructor

---

LEGO1/mxtransitionmanager.cpp

Some work towards the pixelation transition function. aka: the default transition in the game if you don't change it with Rebuilder.
The main thing that keeps this from matching is the pixel plot section that begins at `0x1004c07f`. If we are using 8-bit color, we need to replace 10 bytes with the pixelated color, and 20 bytes for 16-bit. The problem is the way that the color value `DWORD` is prepared before we set it in the `lpSurface` pointer. The code (for 8-bit color) looks like this:
```assembly
; DL has the color value we want to set
MOV     AL,DL
MOV     AH,AL       ; AX = DL:DL
MOV     AL,DL       ; unnecessary
MOV     EBX,EAX
SHL     EBX,0x10    ; EBX = DLDL:0
MOV     BX,AX       ; EBX = DLDL:DLDL
; [...]
; EAX is the offset in lpSurface
MOV     dword ptr [EAX],EBX
MOV     dword …
```

MxTransitionManager Pixelation transition

---

CMakeLists.txt
LEGO1/mxmusicmanager.cpp
LEGO1/mxmusicmanager.h
LEGO1/mxomni.cpp
LEGO1/mxregion.cpp
LEGO1/mxregion.h
LEGO1/mxvideomanager.cpp
LEGO1/mxvideomanager.h
LEGO1/mxvideoparam.cpp

Depends on https://github.com/isledecomp/isle/pull/207
Implements `MxVideoManager::vtable0x28` and `0x2c`, 100% matches.
They are both very similar. `0x28` uses `MxDisplaySurface::Init` and `0x2c` uses `MxDisplaySurface::Create` instead. `m_unk60` indicates which one of the methods has been used to initialize the class. I can't really think of good names right now so I'll leave them as-is. 
Note: the usage of the `goto` pattern is intentional, just like in `MxDisplaySurface`. I've also added this pattern to `MxMusicManager::StartMIDIThread` in order to achieve a 100% match. There's no other way to get the 100% match I believe (also the usage of this pattern is confirmed by the 1996 source).

Implement MxVideoManager::vtable0x28 and Create

---

LEGO1/mxtransitionmanager.cpp

This PR implements MxTransitionManager::Transition_Broken().
This function is 100% matching as of time of writing.

implement/match MxTransitionManager::Transition_Broken()

---

LEGO1/mxeventmanager.cpp
LEGO1/mxeventmanager.h
LEGO1/mxmusicmanager.cpp
LEGO1/mxmusicmanager.h
LEGO1/mxnotificationmanager.cpp
LEGO1/mxnotificationmanager.h
LEGO1/mxomni.cpp
LEGO1/mxomnicreateparam.h
LEGO1/mxsoundmanager.cpp
LEGO1/mxsoundmanager.h
LEGO1/mxstreamer.cpp
LEGO1/mxstreamer.h
LEGO1/mxstring.cpp
LEGO1/mxstring.h
LEGO1/mxticklemanager.h

Mostly refactoring (renaming the "create" functions to `Create` with proper argument names) and several fixes, getting the match of `MxOmni::Create` to 100%.

MxOmni::Create 100% match, make Create calls consistent

---

CMakeLists.txt
LEGO1/legovehiclebuildstate.cpp
LEGO1/legovehiclebuildstate.h

This is a bit of an odd class which reflects it's class name through a member field set on construction (rather then through proper inheritance). I've named this class `LegoVehicleBuildState` as it doesn't have a single static string associated with it in the binary. Instead it's created for all of the following "class" strings in the `LegoObjectFactory::Create` method:
* `LegoRaceCarBuildState`
* `LegoCopterBuildState`
* `LegoDuneCarBuildState`
* `LegoJetskiBuildState`
New functions/method match rates:
```
LegoVehicleBuildState::LegoVehicleBuildState (0x10025f30) is 100.00% similar to the original
LegoVehicleBuildState::UnkStruct::UnkStruct (0x10017c00) is 100.00% similar to the original
LegoVehicleBuildState::ClassName (0x10025ff0) is 100.00% similar to the original …
```

Add LegoVehicleBuildState

---

LEGO1/gasstationstate.cpp
LEGO1/gasstationstate.h
LEGO1/legostate.cpp
LEGO1/legostate.h

Implements GasStationState::GasStationState(). This is not matching due to register swapping, and I wasn't able to remedy it successfully.
This PR also adds a size assert for LegoState as we were able to confirm it is a small class at only `0x08`. All classes that derive from it are expected to create their own members.

implement GasStationState::GasStationState()

---

LEGO1/legostate.cpp
LEGO1/legostate.h
LEGO1/legostream.cpp
LEGO1/legostream.h

This PR corrects LegoState::VTable0x1C to take a `LegoFileStream *` parameter instead of the initially assumed `LegoState *` parameter that happened to coincidentally work out while still retaining its' match. I've confirmed this is the correct class through dynamic analysis. It also implements LegoFileStream::FUN_10006030 (moved from `LegoState`) which is currently a 75% match. This function is tricky and I wasn't able to improve it further from around an hour's worth of testing.

fix LegoState::VTable0x1C fake-match & implement LegoFileStream::FUN_10006030

---

LEGO1/legoinputmanager.h
LEGO1/legoomni.cpp
LEGO1/legoomni.h

This PR implements the missing global function at `0x10015750`, which returns the main LegoControlManager instance from the main LegoInputManager instance. This function is 100% matching.

implement/match global ControlManager() function

---

LEGO1/scorestate.cpp
LEGO1/scorestate.h

This PR gives the name `SetScoreCubeTutorialFlag` to `VTable0x18` in ScoreState and labels its associated member. This bool `m_playCubeTutorial` is responsible for determining whether or not the explanation audio for the first time a player visits the Score Cube room plays.

label ScoreState::VTable0x18 and associated member

---

LEGO1/legostate.cpp
LEGO1/legostate.h
LEGO1/scorestate.cpp
LEGO1/scorestate.h

Noticed after meging that the override isn't working. I've given the function a more generic name since it's based in `LegoState`. Maybe its purpose is something like "Activate", but we'd have to figure that out first.

Rename virtual function to fix override

---

LEGO1/mxnotificationmanager.h
LEGO1/mxomni.cpp
LEGO1/mxomni.h
LEGO1/mxstreamer.cpp
LEGO1/mxstreamer.h

Implements `MxOmni::DoesEntityExist` and `MxStreamer::FUN_100b9b30`, 100% matches.

Implement MxOmni::DoesEntityExist and related

---

LEGO1/mxbitmap.cpp
LEGO1/mxbitmap.h
LEGO1/mxvideopresenter.cpp
LEGO1/mxvideopresenter.h

Implementing the constructor (and destructor) for what I am calling the `AlphaMask` struct inside of `MxVideoPresenter`. My reasoning is: we are walking the bitmap rows in order (regardless of top-down or bottom-up orientation) and setting a bit in the allocated array if the given pixel has a non-zero value. I'm not sure yet how this gets used, but that's outside the scope of this PR.
There is a similar constructor in the `MxVideoPresenter` subclass `MxStillPresenter`. It's a lot shorter, but still should be a separate PR.
The `BITMAPINFOHEADER` struct has a field `biCompression` that can have a few different values. A value of zero corresponds to `BI_RGB`, which means uncompressed. By default, the rows of the bitmap are ordered bottom-up (that is, the lowest row of pixels on the screen …

MxVideoPresenter AlphaMask (formerly UnkStruct)

---

LEGO1/mxvideopresenter.cpp
LEGO1/mxvideopresenter.h

Turns out that what I thought was the `MxStillPresenter` version of the `AlphaMask` (#226) constructor is actually the copy constructor that belongs in `MxVideoPresenter`.
100% match. I also made both constructors have a `const` parameter because why not.
This gets called for `MxStillPresenter` at `0x100ba49f` so I had it in my head that it belonged to that class.
Whoops! ~You forgot to put the CD in your computer.~

Copy constructor for MxVideoPresenter::AlphaMask

---

LEGO1/mxdsbuffer.cpp
LEGO1/mxdsbuffer.h
LEGO1/mxdssource.cpp
LEGO1/mxdssource.h

- Implemented MxDSBuffer constructor
- It appears that MxDSSource::FUN_100bffd0 (now renamed to ReadToBuffer) writes to an MxDSBuffer, which makes it match

Implement MxDSBuffer constructor, match MxDSSource::FUN_100bffd0

---

LEGO1/define.cpp
LEGO1/define.h
LEGO1/mxstillpresenter.cpp
LEGO1/mxstillpresenter.h

Not an exact match, but wrong for all the usual reasons.
This function does an odd thing with the "extra" string length that also happens in the main `MxPresenter::ParseExtra`. The variable is word-sized, but then we mask out the more significant other bits with an `AND EAX, 0xffff`. I doubt my literal interpretation of that matches the original, but it at least gets the instruction in there.
Is this extra length + char* another structure? Why `memcpy` the data versus the more logical `strcpy`?

MxStillPresenter::ParseExtra

---

3rdparty/smk/smk.h
LEGO1/mxsmkpresenter.cpp
LEGO1/mxsmkpresenter.h

I couldn't figure out how to fully match MxSmkPresenter::VTable0x88 (or what it even does)

MxSmkPresenter vtables

---

LEGO1/mxnextactiondatastart.h
LEGO1/mxstreamcontroller.cpp
LEGO1/mxstreamcontroller.h

MxStreamController::vtable0x2c matches, but when including MxNextActionDataStart.h it no longer matches.

Implement MxStreamController::vtable0x2c

---

tools/reccmp/reccmp.py

The `cvdump` tool reads our recompiled PDB and lists each source file and function, with pairs of source line numbers and offsets into the binary where the instructions for that compiled line begin. You can reasonably assume (and we do) that the first line number given is the start of the function, regardless of formatting in the source file.
The main loop of `reccmp` scans each file for the `// OFFSET` marker, then finds the line number of the next opening curly brace, which is the start of code for that function.
These two pieces of information come together in `get_recompiled_address` where we look for a match to begin comparing the assembly. However, as the code comment points out, we are not guaranteed an absolute path in the PDB, so we have to use the `os.path.samefile` function to …

Improved source file path comparison in reccmp

---

LEGO1/mxdsselectaction.cpp
LEGO1/mxlist.h
LEGO1/mxregion.cpp
LEGO1/mxstringlist.h

The recent leak of the alpha version and its `LEGO1D.DLL` file help a fair bit with resolving the inlining patterns the developers have used (even though a lot of the code is outdated), especially in classes like `MxList`. The reason is that in the debug version, no functions are inlined at all as far as I can tell.
Using this information I was able to match `MxRegionTopBottom::FUN_100c5280` and probably a few more in the future. The key insight is that the members of the `MxListEntry` class are accessed through getters/setters and not directly.
~The regressions are due to compiler randomness (can be shown by relocating them elsewhere in the compilation units), but I'm still investigating to see if it's fixable, thus draft/WIP.~
Figured out that `Append` and `OtherAppend` are actually the …

Match MxRegionTopBottom::FUN_100c5280

---

ISLE/isleapp.cpp
LEGO1/legoeventnotificationparam.cpp
LEGO1/legoeventnotificationparam.h
LEGO1/legoinputmanager.cpp
LEGO1/legoinputmanager.h
LEGO1/mxactionnotificationparam.h
LEGO1/mxlist.h
LEGO1/mxnotificationparam.h
LEGO1/mxqueue.h
LEGO1/mxstreamer.h

Implements the `MxQueue` datatype that we need for `LegoInputManager`. It is a subclass of `MxList`, adding only the Enqueue and Dequeue methods. I had to open up the scope from private to protected in `MxList` to make this work. Only Dequeue is implemented right now because I don't think Enqueue is ever called. If you go off the 96 source (and I did) then it seems the `QUEUE_EVENTS` macro is not defined, and so Enqueue is not called in `QueueEvent()`.
Sidebar while on the topic of these complex datatypes: we have a few now, and all seem to require superclasses like `MxHashTableParent` that don't make much sense. I think what's happening here is that all collection datatypes have a common ancestor, say: `MxCollection`. With that, you get an `m_count` variable and a `m_customDestructor` …

MxQueue and parts of LegoInputManager

---

.clang-format
LEGO1/mxomnicreateflags.h

This adds the `QualifierOrder` check to `clang-format` to enforce the style we have been using until now. Except for one file we have applied it consistently so far.

(clang-format) Add QualifierOrder

---

CMakeLists.txt
LEGO1/mxdsactionlist.cpp
LEGO1/mxdschunk.h
LEGO1/mxdssubscriber.cpp
LEGO1/mxdssubscriber.h
LEGO1/mxmediapresenter.cpp
LEGO1/mxmediapresenter.h
LEGO1/mxpresenter.cpp
LEGO1/mxpresenter.h
LEGO1/mxpresenterlist.cpp
LEGO1/mxstreamchunklist.cpp
LEGO1/mxstreamchunklist.h

* Adds the members to `MxMediaPresenter`. What we have here is a list of stream chunks, a current chunk, and a cursor into the stream chunk list, as well as an instance of `MxDSSubscriber`.
* Implements `Destroy` and `StartAction` and the list w/ annotations, 100% matches
For the list, I've re-used the same implementation pattern as before. @disinvite - the refactoring of the list stuff you mentioned in https://github.com/isledecomp/isle/pull/268 would be great indeed going forward since it feels like more boilerplate than it should be.

Bootstrap MxMediaPresenter

---

LEGO1/mxcollection.h
LEGO1/mxhashtable.h
LEGO1/mxstring.h
LEGO1/mxvariabletable.cpp
LEGO1/mxvariabletable.h

Part 1 of the promised refactor surrounding collection classes. This introduces `MxCollection` as the superclass for `MxHashTable`.
The goal is to have `MxList` extend this class as well, but I ended up refactoring a lot of `MxHashTable` and `MxVariableTable` (both added by me in #87) to fix problems and bring the code style in line with with @foxtacles did with `MxList`. So this PR will just focus on `MxHashTable` and I will do the rest in a follow-up PR.
Summary:
- `MxHashTable` does not use pure virtual calls, so these are removed.
- Using `T` instead of `T*` for `MxHashTable`. There may not be another hash table in `LEGO1`, but if there is, it will be better to have a more generic generic.
- Adding a lot of `TEMPLATE` markers for reccmp.
- Using more Mx types.
- …

Refactor MxHashTable/MxVariableTable

---

CMakeLists.txt
LEGO1/legoinputmanager.cpp
LEGO1/legoinputmanager.h
LEGO1/legopathcontrollerlist.cpp
LEGO1/legopathcontrollerlist.h
LEGO1/legoworld.h
LEGO1/mxcollection.h
LEGO1/mxdsactionlist.cpp
LEGO1/mxdsactionlist.h
LEGO1/mxhashtable.h
LEGO1/mxlist.h
LEGO1/mxpresenterlist.cpp
LEGO1/mxpresenterlist.h
LEGO1/mxregion.h
LEGO1/mxregionlist.cpp
LEGO1/mxregionlist.h
LEGO1/mxstreamchunklist.cpp
LEGO1/mxstreamchunklist.h
LEGO1/mxstringlist.cpp
LEGO1/mxstringlist.h
LEGO1/mxvariabletable.h

Continued from #283. `MxList` template classes now extend from `MxCollection`. We also have `MxPtrList`, which is the same as `MxList` but you can omit the `*` when declaring the template. It is not used consistently as you'll see from the code changed here, but it does conveniently explain the missing link between `MxList` and the most-derived class in a few places.
I left the cursor classes alone for now. Converting the list classes is probably enough for a single PR review.
- Restored the `this` reference in places where I had mistakenly removed it in #283. This was added in #245 to support two-phase compilation. (See also: https://stackoverflow.com/questions/4643074/why-do-i-have-to-access-template-base-class-members-through-the-this-pointer/4643295#4643295)
- We did get a slight …

MxList refactor

---

LEGO1/mxeventpresenter.cpp
LEGO1/mxeventpresenter.h

* Implements `CopyData`, `ReadyTickle`, `StartingTickle` and `PutData`
* `m_data` is obviously some sort of structure but I don't have enough information yet on what it is. It can most likely be extracted from `libweaver`
* All 100% except `PutData`, which does something odd with an extra `strlen` that I can't get to match.

Implement/match MxEventPresenter

---

LEGO1/mxsoundmanager.h
LEGO1/mxsoundpresenter.h
LEGO1/mxwavepresenter.cpp
LEGO1/mxwavepresenter.h

* Uncovers some of the members of `MxWavePresenter`
* Assumes the [`WAVFmt` type from `libweaver`](https://github.com/itsmattkc/SIEdit/blob/master/lib/othertypes.h#L8) (the extra two members beyond the `WAVEFORMATEX` struct are not used yet)
* Implements the following functions:
```
MxWavePresenter::~MxWavePresenter (0x1000d640 / 0x1002b000) is 100.00% similar to the original
MxWavePresenter::Destroy (0x1000d6a0 / 0x1002b060) is 100.00% similar to the original
MxWavePresenter::VTable0x6c (0x1000d6b0 / 0x1002b070) is 100.00% similar to the original
MxWavePresenter::Init (0x100b1ad0 / 0x1002b080) is 100.00% similar to the original
MxWavePresenter::AddToManager (0x100b1af0 / 0x1002b0a0) is 100.00% similar to the original
MxWavePresenter::Destroy (0x100b1b10 / 0x1002b0c0) is 100.00% similar …
```

Bootstrap MxWavePresenter, implement/match some functions

---

tools/reccmp/reccmp.py
tools/reccmp/template.html

Template functions look like this using angle brackets: `MxList<MxPresenter *>::~MxList<MxPresenter *>`
In the HTML output of reccmp, we escape the angle bracket characters by converting to `&lt;` and `&gt;`. These are displayed correctly on the page because we create the display elements using the `innerHTML` property, so they become un-escaped. The side effect of this is that the literal data contains the escaped characters, so you can't search for templates unless you escape the text yourself in the search box.
This changes the reccmp output so that we escape for JSON instead, as we are ultimately building up a javascript array and inserting it into template.html using pystache (#292). We can have the browser escape the text automatically by using the `innerText` property instead of …

Fix reccmp html output for template functions

---

LEGO1/legorace.cpp
LEGO1/legorace.h

The base class for other race classes. There are these vtable entries that are just empty, but the outcome of the asm doesnt include the `ret 0x4`, just `ret`, which is weird.
And the vtable0x18 override, I need help, adding it in causes the linker to complain

LegoRace initial layout

---

LEGO1/define.cpp
LEGO1/define.h
LEGO1/mxaudiopresenter.cpp
LEGO1/mxaudiopresenter.h
LEGO1/mxdschunk.h
LEGO1/mxomni.cpp
LEGO1/mxsoundmanager.cpp
LEGO1/mxsoundmanager.h
LEGO1/mxwavepresenter.cpp
LEGO1/mxwavepresenter.h

Implements the remaining functions in `MxWavePresenter`.
```
+  MxWavePresenter::WriteToSoundBuffer (0x100b1bd0) is 100.00% similar to the original
+  MxWavePresenter::StreamingTickle (0x100b1ea0) is 100.00% similar to the original
+  MxWavePresenter::DoneTickle (0x100b20c0) is 82.35% similar to the original
+  MxWavePresenter::AppendChunk (0x100b2130) is 100.00% similar to the original
+  MxWavePresenter::PutData (0x100b2160) is 100.00% similar to the original
+  MxWavePresenter::EndAction (0x100b2280) is 100.00% similar to the original
+  MxWavePresenter::SetVolume (0x100b2300) is 100.00% similar to the original
+  MxWavePresenter::Enable (0x100b2360) is 100.00% similar to the original
+  MxWavePresenter::ParseExtra (0x100b23a0) is 86.32% similar to the original
+ …
```

Implement/match remaining MxWavePresenter functions

---

.clang-format
LEGO1/legoobjectfactory.h
LEGO1/legopalettepresenter.h
LEGO1/mxobjectfactory.h

This rule ensures that there is an empty line before each access modifier (except at the beginning of the struct/class). We have already been writing code using this rule so this just formalizes it (and fixes a few instances).

(clang-format) Add EmptyLineBeforeAccessModifier

---

LEGO1/mxloopingmidipresenter.cpp
LEGO1/mxloopingmidipresenter.h
LEGO1/mxmidipresenter.h
LEGO1/mxmusicmanager.cpp
LEGO1/mxmusicmanager.h

This appears to be the complete class, relatively small. All 100% matches:
```
MxLoopingMIDIPresenter::ClassName (0x100b1830 / 0x100207b0) is 100.00% similar to the original
MxLoopingMIDIPresenter::IsA (0x100b1840 / 0x100207c0) is 100.00% similar to the original
MxLoopingMIDIPresenter::`scalar deleting destructor' (0x100b19c0 / 0x10020ad0) is 100.00% similar to the original
MxLoopingMIDIPresenter::StreamingTickle (0x100c2a80 / 0x1001c7d0) is 100.00% similar to the original
MxLoopingMIDIPresenter::DoneTickle (0x100c2ae0 / 0x1001c830) is 100.00% similar to the original
MxLoopingMIDIPresenter::PutData (0x100c2b00 / 0x1001c850) is 100.00% similar to the original
```

Implement/match MxLoopingMIDIPresenter

---

LEGO1/mxsmkpresenter.cpp
LEGO1/mxsmkpresenter.h
LEGO1/mxstillpresenter.cpp
LEGO1/mxstillpresenter.h
LEGO1/mxtransitionmanager.cpp
LEGO1/mxvideopresenter.cpp
LEGO1/mxvideopresenter.h

Adds `MxStillPresenter`'s virtual table and implements a few functions:
```
MxStillPresenter::Destroy (0x100435b0 / 0x10026270) is 100.00% similar to the original
MxStillPresenter::ClassName (0x100435c0 / 0x10020850) is 100.00% similar to the original
MxStillPresenter::IsA (0x100435d0 / 0x10020860) is 100.00% similar to the original
MxStillPresenter::`scalar deleting destructor' (0x100436e0 / 0x10020970) is 100.00% similar to the original
MxStillPresenter::Destroy (0x100b9c70 / 0x10026280) is 100.00% similar to the original
MxStillPresenter::LoadHeader (0x100b9cc0 / 0x100262d0) is 87.72% similar to the original
MxStillPresenter::CreateBitmap (0x100b9d10 / 0x10026320) is 100.00% similar to the original
MxStillPresenter::NextFrame (0x100b9db0 / 0x100263c0) is 100.00% similar to the original …
```

Bootstrap MxStillPresenter

---

CMakeLists.txt
LEGO1/mxcriticalsection.cpp
LEGO1/mxcriticalsection.h
LEGO1/mxdiskstreamcontroller.cpp
LEGO1/mxdiskstreamcontroller.h
LEGO1/mxdiskstreamprovider.h
LEGO1/mxdssubscriber.h
LEGO1/mxnextactiondatastart.h
LEGO1/mxstreamcontroller.cpp
LEGO1/mxstreamcontroller.h
LEGO1/mxstreamlist.cpp
LEGO1/mxstreamlist.h

I've been hacking away at `MxStreamController` and related classes, but I thought I would tie off some stuff related to the class members as it probably warrants its own review.
`MxStreamController`, `MxDiskStreamController` and `MxDiskStreamProvider` all use STL lists to hold data. Much like the `MxList` hierarchy, there are four classes in total: two from the STL layer, a wrapper class, and then a final most-derived class. For example:
- `list<MxDSAction *,allocator<MxDSAction *> >::~list<MxDSAction *,allocator<MxDSAction *> >`
- `List<MxDSAction *>::~List<MxDSAction *>`
- `MxStreamList<MxDSAction *>::~MxStreamList<MxDSAction *>`
- `MxStreamListMxDSAction::~MxStreamListMxDSAction`
There are no vtables here, so it (probably) doesn't matter whether the wrapper class (`MxStreamList`) is …

STL lists for stream classes

---

3rdparty/flic/flic.h
CMakeLists.txt
LEGO1/mxflcpresenter.cpp
LEGO1/mxflcpresenter.h
LEGO1/mxloopingflcpresenter.cpp
LEGO1/mxloopingflcpresenter.h

vtable70 is basically creating a bitmap; doing this needs m_unk64, which is the main point of interest.
It *appears* that just like MxSmkPresenter, there is a general structure of a "FLIC", at least what appears to be a FLIC header. All that matters currently with m_unk64 is that +0x8 is the width and +0xa is the height.
This PR is just a test for now, we'll have to see whether this is what m_unk64 is or isn't.

MxFlcPresenter vtable70, m_unk64

---

LEGO1/mxdisplaysurface.cpp
LEGO1/mxdisplaysurface.h
LEGO1/mxstillpresenter.cpp
LEGO1/mxvideomanager.h

Match is at ~97%, there's a few instructions that are moved around a little bit, similar to other places where we initialize `MxRect32`.

Implement/match MxStillPresenter::LoadFrame

---

CMakeLists.txt
LEGO1/legoomni.cpp
LEGO1/legoomni.h
LEGO1/legoworld.cpp
LEGO1/legoworldlist.cpp
LEGO1/legoworldlist.h
LEGO1/mxdsactionlist.h
LEGO1/mxdsmultiaction.cpp
LEGO1/mxdsselectaction.cpp
LEGO1/mxlist.h
LEGO1/mxmediapresenter.cpp
LEGO1/mxpresenterlist.h
LEGO1/mxregion.cpp
LEGO1/mxregionlist.h
LEGO1/mxstreamchunklist.h
LEGO1/mxstreamcontroller.cpp
LEGO1/mxstringlist.h

Third and final `MxCollection` refactoring, following #290 and #283. I also added a new `MxList` of `LegoWorld` pointers to `LegoOmni`. Template type confirmed by debugger.
For cursors of a specific list type, we had been using a typedef on `MxListChild` or `MxListChildChild` for the specific situation. This PR replaces those with a dedicated class for the `MxList` derivative being used. `MxListChildChild` was used in conjunction with an `MxPtrList` so I replaced those with `MxPtrListCursor` and it lines up to the same number of vtables.
There is a slight added code overhead. Each cursor now needs its own initializer list to pacify the compiler. For example:
```cpp
// VTABLE: LEGO1 0x100d7e50
class MxDSActionListCursor : public MxListCursor<MxDSAction*> {
public: …
```

Refactor MxList cursors

---

.editorconfig
.github/workflows/build.yml
.pylintrc
CMakeLists.txt
LEGO1/compat.h
compile.cmd
tools/patch_c2.py
tools/reccmp/reccmp.py
tools/verexp/verexp.py

Unfortunately, the workaround we use to get rid of the warning (by declaring a static class) leads to a junk artifact being inserted into the binaries (probably in several places, but I haven't checked). I've noticed that today when strangely, the recompiled offsets of the functions in `ISLE.EXE` were all wrong:
```
IsleApp::IsleApp (0x401000 / 0x401020) is 100.00% similar to the original
IsleApp::~IsleApp (0x4011a0 / 0x4011c0) is 100.00% similar to the original
IsleApp::Close (0x401260 / 0x401280) is 100.00% similar to the original
...
```
(notice how the recompiled `IsleApp::IsleApp` starts at `0x401020` - this is because of that class)
For the sake of accuracy, I'm proposing to substitute the workaround with a solution in the build system. ~~I've created a basic script that wraps the …

(Proposal) Use alternative C4786 warning suppression

---

ISLE/isleapp.cpp

`WndProc` has been the only function we have never seen a 100% match on, which led me to believe there must still be an inaccuracy left to be fixed (unrelated to compiler randomness).
Turned out that was correct, and with the changes in this PR and certain constellations (compiler randomness), `WndProc` is now able to match to 100%:

Increased `ISLE` accuracy

---

LEGO1/mxramstreamcontroller.cpp
LEGO1/mxramstreamcontroller.h
LEGO1/mxstreamcontroller.cpp
LEGO1/mxstreamcontroller.h

```
MxRAMStreamController::vtable0x24 (0x100c6320) is 100.00% similar to the original
MxStreamController::vtable0x24 (0x100c1740) is 100.00% similar to the original
MxStreamController::vtable0x30 (0x100c1ce0) is 100.00% similar to the original
```

implement a few mxstreamercontroller vtables

---

LEGO1/mxbackgroundaudiomanager.cpp
LEGO1/mxcompositepresenter.cpp
LEGO1/mxcompositepresenter.h
LEGO1/mxdsaction.cpp
LEGO1/mxdsaction.h
LEGO1/mxdsmultiaction.h
LEGO1/mxdsobject.h
LEGO1/mxlist.h
LEGO1/mxmediapresenter.cpp
LEGO1/mxpresenter.cpp
LEGO1/mxpresenter.h

This adds 3 more functions:
```
+  MxCompositePresenter::StartAction (0x100b6410) is 100.00% similar to the original
+  MxCompositePresenter::EndAction (0x100b65e0) is 100.00% similar to the original
+  MxCompositePresenter::Notify (0x100b6760) is 100.00% similar to the original
```
`m_unk8c` in `MxDSAction` has been named `m_origin`, since it is always set to the class instance that created the action in the first place.

Implement/match more of MxCompositePresenter

---

LEGO1/mxdirectdraw.cpp
tools/isledecomp/isledecomp/bin.py
tools/reccmp/reccmp.py

Extends the `Bin` component of the `isledecomp` library to read in the relocation table from the binary. This gives us the list of every virtual address that would be relocated upon loading the module. That is, broadly speaking, the location of every item of interest in the `.text`, `.rdata`, and `.data` sections.
This needs some filtering to become really useful. The list includes all of the `funcinfo` sections, along with the addresses in each for all the Unwind functions used in C++ exception handling. (More info here: http://www.openrce.org/articles/full_view/21) So there's some noise in the results for `.text` if you're just looking for the start of functions. `funcinfo` sections are easy to identify by the magic number `0x19930520` and I wonder whether a tool to examine those would …

Use relocation table with reccmp

---

LEGO1/mxcompositemediapresenter.cpp
LEGO1/mxcompositemediapresenter.h
LEGO1/mxcompositepresenter.h

The code basically matches, except for the weirdness with the `cursor.Next` loop (similar to the parent classes' `StartAction`). Left a comment in the code again to elaborate on the oddity.

Implement/match MxCompositeMediaPresenter::StartAction

---

LEGO1/mxcompositemediapresenter.cpp
LEGO1/mxcompositemediapresenter.h
LEGO1/mxcompositepresenter.h
LEGO1/mxdsaction.h
LEGO1/mxmediapresenter.h
LEGO1/mxtransitionmanager.cpp
LEGO1/mxvideopresenter.cpp

Implements the remaining functions:
```
MxCompositeMediaPresenter::StartingTickle (0x100742e0 / 0x10012700) is 96.90% similar to the original
MxCompositeMediaPresenter::Tickle (0x10074470 / 0x10012890) is 74.29% similar to the original
MxCompositeMediaPresenter::PutData (0x10074540 / 0x10012960) is 100.00% similar to the original
```
`StartingTickle` has a little bit of compiler randomness. `Tickle` would match 100% but `reccmp` runs into the known issue with jump tables.

Implement/match rest of MxCompositeMediaPresenter

---

LEGO1/isle.cpp
LEGO1/legogamestate.cpp
LEGO1/legoomni.cpp
LEGO1/legoworld.cpp
LEGO1/motorcycle.h
LEGO1/mxdsbuffer.h
LEGO1/mxdsselectaction.h
LEGO1/mxramstreamcontroller.h
LEGO1/score.h
tools/isledecomp/isledecomp/parser/linter.py
tools/isledecomp/tests/test_linter.py

The `decomplinter` tool will now alert to offsets being reused in a module when scanning the code base. You can call the `reset()` method with argument `True` to "fully" reset the linter's state.
I fixed the handful of files that had this new problem. Most were `// GLOBAL` markers pointing at the wrong string.

Decomp linter warning for offset reuse

---

LEGO1/mxbitmap.h
LEGO1/mxpoint32.h
LEGO1/mxpresenter.h
LEGO1/mxrect32.h
LEGO1/mxrectlist.h
LEGO1/mxregion.cpp
LEGO1/mxsize32.h
LEGO1/mxsmack.cpp
LEGO1/mxsmack.h
LEGO1/mxsmkpresenter.cpp
LEGO1/mxstillpresenter.cpp
LEGO1/mxtransitionmanager.cpp
LEGO1/mxvideomanager.cpp
LEGO1/mxvideopresenter.cpp

This PR implements `MxSmkPresenter::LoadFrame`, which requires a new list containing `MxRect32`. This is the first function I ran into that creates a `MxList`-based list on the stack; it took quite a while to get everything matching since there are a lot of inline functions again. It's at 100% now.
`LoadFrame` was the last function of that class without implementation. The heavy lifting of the Smack frame decoding happens in `MxSmack::FUN_100c5db0` though, which still needs some work.
I've also managed to match `MxRegion::VTable0x18` to almost 100% (some compiler randomness left). The key here was a missing copy constructor and assignment function in `MxRect32`.

Implement/match rest of MxSmkPresenter

---

LEGO1/mxsmack.cpp
LEGO1/mxsmack.h
LEGO1/mxsmkpresenter.cpp

`MxSmack::LoadFrame` loads a frame. If there is a palette chunk - which means the palette has changed - it will be processed before the actual frame will be decoded by the Smacker SDK using the function `SmackDoFrameToBuffer`. Match is at 100%.
What remains unclear is the offset of the palette, which seems to be off by 4 byte for us. Maybe the version of the Smacker SDK we have is the problem here and the structure (past the header) has been different at the time; that would probably be the most likely scenario.

Implement/match MxSmack::LoadFrame

---

LEGO1/mxsmack.cpp
LEGO1/mxsmack.h

The last missing function in the `MxSmack` class was `GetRect`, which uses `SmackGetRect` under the hood. Match is at ~98%, remaining percent appears to be compiler randomness.

Finish implementation of MxSmack

---

LEGO1/mxdsmediaaction.h
LEGO1/mxlist.h
LEGO1/mxloopingsmkpresenter.cpp
LEGO1/mxloopingsmkpresenter.h
LEGO1/mxsmkpresenter.cpp
LEGO1/mxsmkpresenter.h

Implements the entire class, 100% matches.
```
MxLoopingSmkPresenter::MxLoopingSmkPresenter (0x100b48b0 / 0x1001f660) is 100.00% similar to the original
MxLoopingSmkPresenter::~MxLoopingSmkPresenter (0x100b4950 / 0x1001f810) is 100.00% similar to the original
MxLoopingSmkPresenter::Init (0x100b49b0 / 0x1001f870) is 100.00% similar to the original
MxLoopingSmkPresenter::Destroy (0x100b49d0 / 0x1001f890) is 100.00% similar to the original
MxLoopingSmkPresenter::VTable0x88 (0x100b4a00 / 0x1001f8c0) is 100.00% similar to the original
MxLoopingSmkPresenter::NextFrame (0x100b4a30 / 0x1001f8f0) is 100.00%* similar to the original
MxLoopingSmkPresenter::VTable0x8c (0x100b4a90 / 0x1001f950) is 100.00% similar to the original
MxLoopingSmkPresenter::RepeatingTickle (0x100b4b00 / 0x1001f9c0) is …
```

Implement/match MxLoopingSmkPresenter

---

.github/workflows/unittest.yml
tools/isledecomp/isledecomp/dir.py
tools/isledecomp/isledecomp/syminfo.py
tools/isledecomp/tests/test_parser_statechange.py
tools/isledecomp/tests/test_path_resolver_nt.py
tools/isledecomp/tests/test_path_resolver_posix.py
tools/reccmp/reccmp.py

The `WinePathConverter` class was used as:
1. a wrapper around calls to `winepath`, for converting to and from Wine paths
2. for converting Windows-like paths in the `cvdump` output to match Unix paths returned by `os.walk`
This refactor to `PathResolver` doesn't add much in the way of features, but I think the added separation of concerns and documentation is useful. I'm working on adding more checks and comparisons to our palette with `cvdump` and the `SymInfo` module that drives it, and the fact that there was not a unified API across platforms for this path conversion was a sticking point.
If we are not on Windows, the goal in this and the previous module is actually to _avoid_ calling `winepath` whenever possible. This call is expensive, although this is mitigated a lot by having the …

Refactor WinePathConverter into PathResolver

---

LEGO1/mxcore.h
LEGO1/mxdssubscriber.cpp
LEGO1/mxdssubscriber.h
LEGO1/mxlist.h
LEGO1/mxramstreamcontroller.cpp

Implements the remaining functions of `MxDSSubscriber`, all 100% matches.
```
+  MxDSSubscriber::DeleteChunks (0x100b8030) is 100.00%* similar to the original
+  MxDSSubscriber::AddChunk (0x100b8150) is 100.00% similar to the original
+  MxDSSubscriber::FUN_100b8250 (0x100b8250) is 100.00%* similar to the original
+  MxDSSubscriber::FUN_100b8360 (0x100b8360) is 100.00% similar to the original
+  MxDSSubscriber::FUN_100b8390 (0x100b8390) is 100.00%* similar to the original
```

Implement/match rest of MxDSSubscriber

---

LEGO1/mxdiskstreamprovider.cpp
LEGO1/mxdiskstreamprovider.h
LEGO1/mxstreamcontroller.cpp
LEGO1/mxstreamcontroller.h
LEGO1/mxstreamlist.h
LEGO1/mxstreamprovider.cpp
LEGO1/mxstreamprovider.h

Adds the destructor of `MxStreamController`, which mainly clears the lists and destroys its elements. Unfortunately the match isn't great (currently at ~60%), which seems to be mainly due to the inlining not coming out as desired. I've tried various things but this is the best I could come up with. Functionally it should be correct.

Implement MxStreamController::~MxStreamController

---

LEGO1/lego3dview.h
LEGO1/legovideomanager.cpp
LEGO1/legovideomanager.h
LEGO1/mxdisplaysurface.cpp
LEGO1/mxdisplaysurface.h

All functions match except for MxDisplaySurface::Display due to the rectange stuff. Sadly this doesn't make the nocd animation work as many other functions such as LegoVideoManager::Tickle aren't implemented. Also improved the match of a few functions.

Implement a few LegoVideoManager/MxDisplaySurface functions

---

CMakeLists.txt
LEGO1/library_msvc.h
tools/isledecomp/isledecomp/bin.py
tools/isledecomp/isledecomp/cvdump/__init__.py
tools/isledecomp/isledecomp/cvdump/parser.py
tools/isledecomp/isledecomp/cvdump/runner.py
tools/isledecomp/isledecomp/syminfo.py

This adds a more structured framework for parsing the output from `cvdump` when analyzing our recomp PDB files.
To use it, you can import `Cvdump` from `isledecomp.cvdump` and use the fluent interface to set which options you want. e.g.
```python
cv = (
Cvdump(pdb)
.lines()
.symbols()
.publics()
.section_contributions()
.run()
)
```
The final call to `run()` will return the parser object with the parsed results already loaded.
You can omit the component calls to subsections like `.lines()` and it will run `cvdump` with all options enabled. This is the same thing the command line `cvdump` does if you don't specify any flags.
As a proof of concept, we are now comparing against a select group of library functions found under `PUBLICS`, and annotated in `library_msvc.h`. After comparing a few …

Cvdump parser and comparing library functions

---

LEGO1/library_msvc.h
tools/isledecomp/isledecomp/syminfo.py

Quick addendum to #383 to get our match percentage back where it should be.
In the new `library_msvc.h` file where we can annotate functions from the standard library, I had `_malloc` and `_free` pointing at what should be the `operator new` and `operator delete` functions.
We are referencing those by the "decorated" ([as Microsoft calls them](https://learn.microsoft.com/en-us/cpp/build/reference/decorated-names)) or "mangled" symbol names `??2@YAPAXI@Z` and `??3@YAXPAX@Z`.

Fix new/delete symbol references

---

CMakeLists.txt
LEGO1/mxlist.h
LEGO1/mxrect32.h
LEGO1/mxregion.cpp
LEGO1/mxregion.h
LEGO1/mxregioncursor.cpp
LEGO1/mxregioncursor.h
LEGO1/mxregionlist.h
LEGO1/mxvideopresenter.cpp
LEGO1/mxvideopresenter.h

`MxRegionCursor` is a special kind of cursor, not based on the usual `MxListCursor`, but a custom implementation that operates specifically on the lists inside `MxRegion`. This class is required for `MxVideoPresenter::PutFrame`.
Matches are all at ~100%, 2-3 functions have a bit of compiler randomness / comparison swaps.
```
+  MxRegionCursor::MxRegionCursor (0x100c3f70) is 100.00% similar to the original
+  MxRegionCursor::~MxRegionCursor (0x100c40b0) is 100.00% similar to the original
+  MxRegionCursor::VTable0x18 (0x100c4140) is 100.00% similar to the original
+  MxRegionCursor::VTable0x20 (0x100c41d0) is 100.00% similar to the original
+  MxRegionCursor::VTable0x28 (0x100c4260) is 100.00% similar to the original
+  MxRegionCursor::VTable0x30 (0x100c4360) is 100.00% similar to the …
```

Implement/match MxRegionCursor class

---

tools/isledecomp/isledecomp/cvdump/runner.py

Noticed a bug introduced by #383 on platforms that use Wine. The command line parameters for `cvdump` were set in the wrong order.

Wine cvdump bugfix

---

LEGO1/mxdisplaysurface.cpp
LEGO1/mxdisplaysurface.h
LEGO1/mxrect32.h
LEGO1/mxsize32.h
LEGO1/mxstillpresenter.cpp
LEGO1/mxvideomanager.h
LEGO1/mxvideopresenter.cpp
LEGO1/mxvideopresenter.h

This adds the implementation of `MxVideoPresenter::PutFrame`. Functionally it should be accurate, however the match is only at ~37% due to a large number of moving pieces, some of which aren't quite right yet (most notably, the initialization of the rectangles). The challenge lies in discovering the "correct" application of inline functions, similarly to other large function bodies in the code base.

Implement MxVideoPresenter::PutFrame

---

LEGO1/legoomni.cpp
LEGO1/legoomni.h
LEGO1/mxpoint32.h
LEGO1/mxrect32.h
LEGO1/mxsize32.h
LEGO1/mxstillpresenter.cpp
LEGO1/mxvideopresenter.cpp

This implements `FUN_100b6e10`, a function that is being used by various methods in `MxDisplaySurface`. This function consists basically of a large sequence of inlined calls, which aren't quite right yet - which is the reason why the match seems currently very poor at ~4%. However, functionally it is equivalent.
What causes the poor match is the fact that only one rectangle initialization is not being inlined (the first one), even though it should be both which would cause both rects to be on the stack and prevent the optimization the compiler currently applies to the following inlined functions.
I've also made several adjustments to `MxRect32` and related classes.

Implement `FUN_100b6e10` and MxRect32 adjustments

---

LEGO1/legovideomanager.cpp
LEGO1/mxbitmap.h
LEGO1/mxdisplaysurface.cpp
LEGO1/mxdisplaysurface.h

This adds the implementation for `VTable0x28`, which was the last piece necessary to render something from the initial Smacker video in `nocd.si`.
The match isn't great at ~30% and it will probably take a lot of further experimentation to get it right, since it's a very large function again and minor differences in variable placement/usage, inline functions etc. are highly important. Functionally I believe it should be accurate, although it's easy to miss something with a function of this size, so I'm inviting everyone to check it out and look for any issues. The 16-bit branches are the one currently most relevant.
Many variable names are also still placeholders or should be improved - suggestions welcome.
https://github.com/isledecomp/isle/assets/1135351/160b91bb-d31c-4aa9-87ab-1fbb29bdd4 …

Implement MxDisplaySurface::VTable0x28

---

LEGO1/mxdirect3d.cpp
LEGO1/mxdirect3d.h

This PR implements `MxDeviceEnumerate::EnumDirectDrawCallback` and associated data structures. There are additional enumerations with their own data structures that have been stubbed out for now.
Match is at 95%, I believe the rest is compiler randomness.

Implement/match MxDeviceEnumerate::EnumDirectDrawCallback

---

LEGO1/mxdirect3d.cpp
LEGO1/mxdirect3d.h
util/compat.h

`ParseDeviceName` matches 100%.
`ProcessDeviceBytes` is at 75%, however the code is pretty much equivalent except for a minor difference in stack allocation and the inner loop layout.
I've added a macro for C++11 `static_assert` since it comes in useful in cases such as seen in `ProcessDeviceBytes`.

Implement/match MxDeviceEnumerate::ParseDeviceName and ProcessDeviceBytes

---

LEGO1/legovideomanager.cpp
LEGO1/mxdirect3d.cpp
LEGO1/mxdirect3d.h

This implements most functions that are necessary to complete the sequence of routines that are required in `LegoVideoManager::Create`. Most of them match 100%, although a few of them have discrepancies with regards to how the loops are laid out, which I can't seem to get right - but functionally should be accurate.

Implement/match most remaining MxDirect3D device enumeration functions

---

LEGO1/mxdirect3d.cpp
LEGO1/mxdirect3d.h

doesn't fully match due to some issue with the _D3DDeviceDesc / MxAssignedDevice structure. Based off of the leaked source code

implement MxDirect3D::GetZBufferDepth

---

LEGO1/lego3dview.cpp
LEGO1/viewmanager/viewlodlist.cpp
LEGO1/viewmanager/viewlodlist.h

This PR is just to allow the game to launch again after the implementation of `LegoVideoManager::Create`.
`ViewLODListManager::Create` has been copied verbatim from the 1996 code and does not match, however it's "good enough" for the startup routine to finish. Obviously there are still a lot of stubs in between and there is no new functionality, however the game launches again with the Smacker video (if `NOCD.SI` is loaded)

Let game launch again

---

LEGO1/lego3dmanager.cpp
LEGO1/lego3dmanager.h
LEGO1/lego3dview.cpp
LEGO1/lego3dview.h
LEGO1/legovideomanager.cpp
LEGO1/legovideomanager.h
LEGO1/mxdirect3d.h
LEGO1/tgl/d3drm/impl.h
LEGO1/tgl/d3drm/renderer.cpp
LEGO1/tgl/d3drm/view.cpp
LEGO1/tgl/tgl.h
LEGO1/tglsurface.h

100% match. Note that this function unconventionally reaches into the implementation and uses the D3DRM interface directly, instead of using the TGL layer.
I've added the `Tgl::Device` creation in `Lego3DView` so that the game continues to start. It also became apparent that they are using the `Direct3DRM2` interface instead of `Direct3DRM` so I changed some of the TGL implementation accordingly.

Implement/match LegoVideoManager::ConfigureD3DRM

---

.github/workflows/format.yml
CMakeLists.txt
ISLE/isleapp.cpp
LEGO1/legovideomanager.h
LEGO1/mxdirectx/mxdirect3d.cpp
LEGO1/mxdirectx/mxdirect3d.h
LEGO1/mxdirectx/mxdirectdraw.cpp
LEGO1/mxdirectx/mxdirectdraw.h

This PR relocates the two classes `MxDirectDraw` and `MxDirect3D` to the `mxdirectx` submodule, as seen in the original sources. Those classes do not make use of Omni types, so I've changed them back to the intrinsic ones.

Move MxDirectDraw and MxDirect3D to mxdirectx

---

CMakeLists.txt

- Fix building isle with ninja without having to pass `-j1` to disable parallelism.
This pr adds isle and lego1 to 2 separate job pools with 1 job available, effectively disabling parallelism per-target.
- ~add `compare-isle` and `compare-lego1` cmake targets, which run `reccmp.py` and open the report in the browser.
For this to work, you need to configure cmake with:~
```sh
cmake -S . -B build_ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -GNinja -DORIGINAL_ISLE="Z:/home/maarten/projects/isle/original/ISLE.EXE" -DORIGINAL_LEGO1="Z:/home/maarten/projects/isle/original/LEGO1.DLL"
```
- add `clang-format` target that runs clang-format on all sources in the `ISLE` and `LEGO1` directories.

cmake: fix default ninja + add clang-format target

---

.github/workflows/analyze.yml
.github/workflows/build.yml
CMakeLists.txt
LEGO1/lego/legoomni/include/legocameracontroller.h
LEGO1/lego/legoomni/include/legoentity.h
LEGO1/lego/legoomni/include/legopointofviewcontroller.h
LEGO1/lego/legoomni/src/common/legoactioncontrolpresenter.cpp
LEGO1/lego/legoomni/src/entity/legocameracontroller.cpp
LEGO1/lego/legoomni/src/entity/legoentity.cpp
LEGO1/lego/legoomni/src/entity/legopovcontroller.cpp
LEGO1/lego/legoomni/src/video/legovideomanager.cpp
LEGO1/lego/sources/3dmanager/lego3dmanager.h
LEGO1/lego/sources/3dmanager/lego3dview.h
LEGO1/lego/sources/3dmanager/legoview1.h
LEGO1/lego/sources/3dmanager/tglsurface.cpp
LEGO1/lego/sources/3dmanager/tglsurface.h
LEGO1/omni/include/mxutil.h
LEGO1/res/resource.h
LEGO1/viewmanager/viewlodlist.h
util/compat.h
util/decomp.h

- Enable decomilation assertions when Visual C++ version <= 5.0
Visual C++ 4.2.0 == cl version 10.20 ([wikipedia](https://en.wikipedia.org/w/index.php?title=Microsoft_Visual_C%2B%2B&section=4#Internal_version_numbering))
- Disable assertions for modern C++ + mingw: the size assertions did not fail in minw@Linux, but failed when building with Visual Studio 2019 or msys2 mingw.
- Pass `-Zc:__cplusplus` to make the `__cplusplus` macro contain the actual `__cplusplus` version (needed for `static_assert`)
- `LegoCameraController` overrides methods that are not declared/implemented in its parents
- Don't forward declare namespaced classes as `class Tgl::Device` but as `namespace Tgl { class Device; }`.
msys2 mingw complained with the following warning: `declaration 'class Tgl::Device' does not …

Support building isle with modern MSVC + msys2

---

LEGO1/lego/legoomni/include/legoentitylist.h
LEGO1/lego/legoomni/include/legoworld.h
LEGO1/lego/legoomni/include/legoworldlist.h
LEGO1/lego/legoomni/src/entity/legoworld.cpp
LEGO1/omni/include/mxcorelist.h

100% match for `LegoWorld::Create` which instantiates both lists. They are fairly standard and based on `MxPtrList`. I've added the cursors as well, though they aren't used anywhere yet but should be correct as well.

Implement lists used in LegoWorld

---

ISLE/library_msvc.h
ISLE/library_smartheap.h
LEGO1/define.cpp
LEGO1/lego/legoomni/src/common/legobackgroundcolor.cpp
LEGO1/lego/legoomni/src/common/legofullscreenmovie.cpp
LEGO1/lego/legoomni/src/common/legogamestate.cpp
LEGO1/lego/legoomni/src/common/legostream.cpp
LEGO1/lego/legoomni/src/main/legoomni.cpp
LEGO1/lego/legoomni/src/video/legometerpresenter.cpp
LEGO1/library_msvc.h
LEGO1/omni/src/common/mxvariabletable.cpp
LEGO1/omni/src/video/mxstillpresenter.cpp
tools/isledecomp/isledecomp/compare/core.py
tools/isledecomp/isledecomp/compare/db.py
tools/isledecomp/isledecomp/cvdump/analysis.py
tools/isledecomp/isledecomp/cvdump/demangler.py
tools/isledecomp/isledecomp/parser/codebase.py
tools/isledecomp/isledecomp/parser/error.py
tools/isledecomp/isledecomp/parser/linter.py
tools/isledecomp/isledecomp/parser/marker.py
tools/isledecomp/isledecomp/parser/node.py
tools/isledecomp/isledecomp/parser/parser.py
tools/isledecomp/isledecomp/parser/util.py
tools/isledecomp/tests/test_demangler.py
tools/isledecomp/tests/test_linter.py
tools/isledecomp/tests/test_parser.py
tools/isledecomp/tests/test_parser_statechange.py
tools/isledecomp/tests/test_parser_util.py

The `// GLOBAL` annotation marks where we have a variable with global scope that is declared on the next line of code. This PR adds the option to identify these variables indirectly, either because they are in generated code or library code. The syntax is the same as other annotations that allow you to pinpoint something by name reference:
```cpp
// GLOBAL: ISLE 0x4108e8
// __osver
```
Variables identified this way do not require the `g_` prefix that we use for variables in our code, for obvious reasons.
String literals are annotated with `// STRING`. It is possible to track these down without an annotation, which is what we have been doing, but it is nice to have the documentation right in the code. These are now enabled for use by `reccmp` comparison. We will still search the original …

Decomp parser: indirect globals and string markers

---

LEGO1/lego/legoomni/include/infocenter.h
LEGO1/lego/legoomni/src/infocenter/infocenter.cpp

This PR names nearly every single action in INFOMAIN.SI in the associated enum. I organized and named them the best way I saw fit.
Actions intended to point the player in the right direction are labeled as "Guidance". I was initially using the name "Pointer" for these, but I didn't want there to be any confusion between these and actual C++ pointers. Any actions that are completely unused in normal gameplay are labeled as "Unused".
Additionally, I've made some small tweaks to the naming of already documented actions. I've appended "Dialogue" to all of the actions names that represent dialogue. Laura Brick was erroneously named "lora", and Nick Brick was named "officier"; both of which I've corrected here.

name nearly every infomain action

---

LEGO1/lego/legoomni/src/common/legogamestate.cpp

Noticed some of these LegoGameState members were missing and not being initialized in the constructor like the original function. Adding these fixes the recompiled LEGO1.DLL instantly crashing in Wine (before, it was trying to access m_savePath before its initialization; no idea why this behavior is acceptable in Windows).

initialize more members in LegoGameState

---

LEGO1/lego/legoomni/include/infocenter.h
LEGO1/lego/legoomni/src/infocenter/infocenter.cpp

Tiny PR that renames the Infocenter methods `PlayDialogue()` and `StopCurrentDialogue()` to `PlayAction()` and `StopCurrentAction()` respectively. I feel like generalizing these names makes more sense because an action doesn't necessarily imply the presence of dialogue, and the ones that do are already marked as such by the INFOMAIN script enum.

rename dialogue to action in infocenter methods

---

LEGO1/lego/legoomni/include/infocenterstate.h
LEGO1/lego/legoomni/src/common/legogamestate.cpp
LEGO1/lego/legoomni/src/infocenter/infocenter.cpp

This PR implements InfoCenter's destructor. This function is 100% matching.
It remains to be seen what the true purpose of `m_buffer` is, but I confirmed through dynamic analysis that this loop in the destructor was resolving to `MxStillPresenter::Enable()` through it; I've made this member an array of MxStillPresenters to accommodate.

implement/match InfoCenter::~InfoCenter()

---

LEGO1/lego/legoomni/include/gifmanager.h
LEGO1/lego/legoomni/src/common/gifmanager.cpp
LEGO1/lego/legoomni/src/infocenter/score.cpp
tools/isledecomp/isledecomp/compare/db.py

`GifManager` and its superclass `GifManagerBase` are using the STL types `<map>` and `<list>`. I've added those in and removed cases where we re-implemented the STL functions.
We aren't generating the `_Insert` method yet, but that should be a match based on other similar STL types. We probably won't see it until we build out `LegoTexturePresenter`.
`LegoOmni::Destroy` calls something to walk the `<map>` tree and delete nodes. This feels like an inline function that should be called, but I'm not sure which one.
Also: I modified the compare database to truncate at 255 characters when matching symbol names. This is all that gets generated in the PDB, per our favorite compiler warning C4786. This will allow us to use the unadulterated versions of the names in the decomp markers.

GifManager: use STL members

---

LEGO1/lego/legoomni/include/jukebox.h
LEGO1/lego/legoomni/src/build/helicopter.cpp
LEGO1/lego/legoomni/src/infocenter/elevatorbottom.cpp
LEGO1/lego/legoomni/src/infocenter/infocenter.cpp
LEGO1/lego/legoomni/src/infocenter/infocenterdoor.cpp
LEGO1/lego/legoomni/src/infocenter/score.cpp

This PR adds an enum representing all JUKEBOX.SI actions/songs into jukebox.h. I've structured them as follows:
* L.E.G.O. Radio exclusive sounds are prefixed with legoRadio (including duplicates of already existing tracks in the index meant to be played on the radio; probably duplicated to avoid seeking backwards in JUKEBOX.SI during radio playback)
* Songs played from the Jukebox are prefixed with jukeBox.
Additionally, I've updated all calls to PlayMusic to make use of this enum.

add jukeboxscript enum

---

LEGO1/omni/include/mxdisplaysurface.h
LEGO1/omni/src/video/mxdisplaysurface.cpp

Currently it matches at 53.74%. With this function implemented (and if you remove Enable(FALSE) in MxStillPresenter::ParseExtra), the infocenter background gets drawn:

Implement MxDisplaySurface::VTable0x44

---

CMakeLists.txt

This reduces the `ISLE.EXE` size closer to the original, by removing unused parts of linked libraries. It was discovered in the Matrix chat by @disinvite and @tahg that `/OPT:REF` needs to be explicitly turned back on when creating a build with debug symbols / PDB.

Remove unused functions from ISLE.EXE

---

LEGO1/lego/legoomni/include/legomodelpresenter.h
LEGO1/lego/legoomni/include/legopathcontrollerlist.h
LEGO1/lego/legoomni/include/legounksavedatawriter.h
LEGO1/lego/legoomni/include/legoworld.h
LEGO1/lego/legoomni/src/common/legounksavedatawriter.cpp
LEGO1/lego/legoomni/src/entity/legoworld.cpp
LEGO1/lego/sources/roi/legoroi.h
LEGO1/mxgeometry/mxgeometry3d.h
LEGO1/omni/include/mxpresenterlist.h

`LegoWorld::LegoWorld` is now at 100% match with the addition of 3 STL members and filling in some annotations.
The two `<set>` members appear to contain pointers to `MxPresenter`. The key comparison is just looking at the pointer values, but I suppose if the goal is to have a unique list of presenters then that's valid.
The `<list>` at +0xe0 contains pointers to `AutoROI`, confirmed via the debugger. The only vtable I saw for the list elements matched what we have for `AutoROI`. It could be a generic `ViewROI*` list, too. I didn't want to insert the dependency in between `LegoROI` and `ViewROI` right now so it's just mocked up.
The `AutoROI` object comes from `LegoModelPresenter`. The function at `0x1007ff70` adds to the `+0xe0` list near the instruction `0x10080031`, where we take the …

LegoWorld STL members

---

.github/workflows/format.yml
LEGO1/lego/legoomni/include/legoentitylist.h
LEGO1/lego/legoomni/include/legoworld.h
LEGO1/lego/legoomni/src/entity/legoworld.cpp
LEGO1/lego/legoomni/src/infocenter/infocenter.cpp

100% match.
The `m_set0xa8` container currently has `MxPresenter*` as its element type, which seems odd because this function has an explicit test if an element of it is a `MxPresenter`, which wouldn't be necessary if this container really had this type in it, so I'm assuming that it probably contains `MxCore*` since that's the only parent class left. We can leave it as-is for now though until we learn what its actual purpose is.

Implement/match LegoWorld::FUN_10021790

---

tools/isledecomp/isledecomp/cvdump/demangler.py
tools/isledecomp/isledecomp/parser/parser.py
tools/isledecomp/isledecomp/parser/util.py
tools/isledecomp/tests/test_curly.py
tools/isledecomp/tests/test_demangler.py
tools/isledecomp/tests/test_parser.py

This enhances our parser to identify a namespace. This can come from the actual keyword `namespace` or from a class or struct. This directly affects our parsing in two ways:
1. If an actual `namespace` is used, any global variables or any class vtables should include it. In the current code base, we have the `Tgl` namespace.
2. A static variable under a class takes on the class name as its namespace. For example, `MxOmni::g_instance`.
For those static variables, we can place the `// GLOBAL` marker inside the class above the declaration and this will work. In all cases where this would be useful, we already have the annotation above the fully qualified variable reference where its value is assigned. We had a bug with reading the full names, but this is now fixed. Match percentage should …

parser: Identify namespaces

---

LEGO1/lego/legoomni/src/video/legometerpresenter.cpp
LEGO1/omni/include/mxdisplaysurface.h
LEGO1/omni/include/mxstillpresenter.h
LEGO1/omni/include/mxvideopresenter.h
LEGO1/omni/src/video/mxdisplaysurface.cpp
LEGO1/omni/src/video/mxflcpresenter.cpp
LEGO1/omni/src/video/mxloopingflcpresenter.cpp
LEGO1/omni/src/video/mxloopingsmkpresenter.cpp
LEGO1/omni/src/video/mxsmkpresenter.cpp
LEGO1/omni/src/video/mxstillpresenter.cpp
LEGO1/omni/src/video/mxvideopresenter.cpp

Match is at ~91%, the rest is compiler randomness/register swaps. The flags in `MxVideoPresenter` are of the `FlagBitfield` kind, similar to `MxVideoParamFlags`, so I've changed the rest of the code base to use it.

Implement/match MxStillPresenter::Clone

---

tools/roadmap/roadmap.py

This adds a new command line option `--order` to the `roadmap` tool that will suggest the order of modules (i.e. translation units). This is broken out by build target, so for `LEGO1` each library will show its own list of modules.
By default, we are looking for functions from each module and where they first appear in the binary. We also show the average displacement for each function from that module (i.e. how far off it is in the recomp from where it should be.) `Score::Score` is the first function from `LEGO1` so naturally the `score.cpp` module appears first in the list. You can provide an argument to `--order` to pick which symbol type you want to look at. For example: `--order vtable` will look at only vtables.
*Caution:* This will _only_ show modules that are currently used in the …

roadmap: Suggest order of modules

---

CMakeLists.txt
LEGO1/omni/include/mxdsfile.h
LEGO1/omni/include/mxioinfo.h
LEGO1/omni/src/stream/mxdsfile.cpp

The destructor of `MxDSFile` is actually inlined everywhere, but it needs to be exported. The workaround is to use `dllexport` directly on the destructor, but only when we compile the DLL. This is necessary to match the scalar ddtor. Also added annotations.

Match MxDSFile scalar ddtor, add annotations

---

LEGO1/lego/legoomni/include/police.h
LEGO1/lego/legoomni/src/police/police.cpp

75% match. I think implementing those handler functions will maybe fix it? `HandleKeyPress` looking at Ghidra may actually just take the whole LegoEventNotificationParam itself.
Also renamed m_unk0x10c to m_transitionDestination

Implement Police::Notify

---

.github/workflows/build.yml
.github/workflows/unittest.yml
tools/isledecomp/isledecomp/bin.py
tools/isledecomp/isledecomp/compare/asm/parse.py
tools/isledecomp/isledecomp/compare/db.py
tools/isledecomp/isledecomp/compare/lines.py
tools/isledecomp/tests/conftest.py
tools/isledecomp/tests/test_islebin.py
tools/roadmap/roadmap.py

Been going down the performance rabbit hole for our python tooling. Here are a few quick things that should help a lot. No change to match percentage or `reccmp` output.
* In `isledecomp.bin`, read the entire binary file at once and use python `memoryview` instead of buffer file I/O. Changed some of the API methods to allow access to the individual sections if any scripts want them.
* Minor change to `roadmap` script now that we are decoding the ASCII version of the section name instead of providing the raw 8 bytes from the PE header.
* Added unit test for `isledecomp.bin`. This pulls down the original `LEGO1.DLL` so we can test the output from that module. I added this to the github CI.
* Memoize expensive `pathlib` calls in `isledecomp.compare.lines`. This is the module that relates the …

parser: Performance enhancements

---

CMakeLists.txt
ISLE/define.cpp
ISLE/define.h
ISLE/isleapp.cpp
tools/isledecomp/isledecomp/compare/core.py
tools/isledecomp/isledecomp/compare/db.py
tools/isledecomp/isledecomp/parser/error.py
tools/isledecomp/isledecomp/parser/node.py
tools/isledecomp/isledecomp/parser/parser.py
tools/isledecomp/tests/test_parser.py

After some analysis with the `roadmap` tool on `ISLE`, I came to the conclusion that two global variables `g_lastFrameTime` and `g_startupDelay` used only in the `IsleApp::Tick` function are actually static variables _from_ that function.
Before:
```
0003:0000005c          0  dat  4       g_targetHeight
0003:00000060          0  dat  4       g_targetDepth
0003:00000064          0  dat  4       g_reqEnableRMDevice
// omitted
0003:0000011c          8  str  19      'LEGO® Island Error'
0003:00000130          8  str  120     '"LEGO® Island" is not detecting...
0003:000001a8          8  str  18      'Lego Island Error'
0003:000001bc       -340  dat  4       g_startupDelay
0003:000001c0       -340  dat  4       g_lastFrameTime
0003:000001c4          0  str  24      'Lego Island MainNoM App'
``` …

Match static function variables

---

LEGO1/lego/legoomni/src/act2/legoact2.cpp
LEGO1/lego/legoomni/src/act3/act3.cpp
LEGO1/lego/legoomni/src/build/legocarbuild.cpp
LEGO1/lego/legoomni/src/gasstation/gasstation.cpp
LEGO1/lego/legoomni/src/hospital/hospital.cpp
LEGO1/lego/legoomni/src/isle/jukebox.cpp

I noticed that it wasn't just Police, a lot of other classes seem to just have this. I think the purpose of `VTable0x5C` is just a function for in a few use cases the devs to ask 'is this a child of the LegoWorld' class without needing to go through IsA, which would probably save runtime. I didn't rename VTable0x5C, I just matched the functions. A match is a match.
I really do think the purpose of these functions are for the LegoWorldPresenter destructor to know not to destroy the entire world but [just the entities,](https://github.com/isledecomp/isle/blob/917485247ba6dcd1db8ba77b4b81ee9ab5a25fe8/LEGO1/lego/legoomni/src/entity/legoworldpresenter.cpp#L44) but I dont know.

Children classes of LegoWorld's VTable0x5c function

---

LEGO1/lego/legoomni/src/infocenter/infocenter.cpp

This finished the last `TODO` in the main Infocenter script, which is the functionality of the "i"-button (which teleports you back and forth between the Infocenter and the previous area). The match of the entire function isn't great at ~65%, but given its massive size it will probably require a lot more work to improve this.

Implement `c_bigInfoCtl` of Infocenter::HandleClick

---

LEGO1/lego/legoomni/include/legogamestate.h
LEGO1/lego/legoomni/src/build/helicopter.cpp
LEGO1/lego/legoomni/src/common/legogamestate.cpp
LEGO1/lego/legoomni/src/infocenter/infocenter.cpp
LEGO1/lego/legoomni/src/isle/isle.cpp
LEGO1/lego/legoomni/src/main/legoomni.cpp
LEGO1/lego/legoomni/src/video/legomodelpresenter.cpp

This adds an enum for the 3 acts, replacing some magic values across the code base.
Note that I've also renamed the previous `GetCurrentAct` to `GetLoadedAct`, and `GetUnknown10` to `GetCurrentAct`. The `GetLoadedAct` function is to determine which of the act scripts/world is currently loaded, not the one that is meant to be active/current.

Introduce and use enum for acts

---

LEGO1/lego/legoomni/include/elevatorbottom.h
LEGO1/lego/legoomni/include/infocenter.h
LEGO1/lego/legoomni/include/infocenterdoor.h
LEGO1/lego/legoomni/include/legogamestate.h
LEGO1/lego/legoomni/include/police.h
LEGO1/lego/legoomni/include/score.h
LEGO1/lego/legoomni/src/build/helicopter.cpp
LEGO1/lego/legoomni/src/common/legogamestate.cpp
LEGO1/lego/legoomni/src/infocenter/elevatorbottom.cpp
LEGO1/lego/legoomni/src/infocenter/infocenter.cpp
LEGO1/lego/legoomni/src/infocenter/infocenterdoor.cpp
LEGO1/lego/legoomni/src/infocenter/registrationbook.cpp
LEGO1/lego/legoomni/src/infocenter/score.cpp
LEGO1/lego/legoomni/src/isle/isle.cpp
LEGO1/lego/legoomni/src/police/police.cpp

This adds an enum containing values for all the areas. The goal here is to replace the large number of magic values in the code base.

Add LegoGameState::Area enum

---

.github/workflows/build.yml
.github/workflows/legobin.yml
.github/workflows/unittest.yml

Adds a reusable workflow that will download and cache `CONFIG.EXE`, `ISLE.EXE`, and `LEGO1.DLL`.
The "Build" and "Test" actions depend on these files. If the "Test" action ran first (and it usually does) then we were not pulling in `CONFIG.EXE` so the "Build" action would fail.
I went with ubuntu-latest to download the files because this seems to start faster than the Windows runner.

CI: Reusable workflow for downloading original binaries

---

CMakeLists.txt
LEGO1/lego/legoomni/include/lego3dwavepresenter.h
LEGO1/lego/legoomni/include/legocachesound.h
LEGO1/lego/legoomni/include/legounknown100d5778.h
LEGO1/lego/legoomni/include/legounknown100d6b4c.h
LEGO1/lego/legoomni/include/legounksavedatawriter.h
LEGO1/lego/legoomni/src/audio/lego3dwavepresenter.cpp
LEGO1/lego/legoomni/src/audio/legocachesound.cpp
LEGO1/lego/legoomni/src/audio/legounknown100d5778.cpp
LEGO1/lego/legoomni/src/audio/legounknown100d6b4c.cpp
LEGO1/lego/legoomni/src/common/legounksavedatawriter.cpp
LEGO1/omni/include/mxstring.h
LEGO1/omni/src/common/mxatomid.cpp
tools/reccmp/template.html

This started as an exploration into the STL members of `LegoUnknown100d6b4c`, and then expanded out into `LegoCacheSound` and a new related class `LegoUnknown100d5778`.
My goal in pulling in those other classes was to try to understand how `LegoUnknown100d6b4c` works. I don't have the _why_ but I'm more confident about the members being a set and list. It didn't really come together until I reversed the function at `0x1003d290`. The list and set are both using the same "value type" for the nodes, and you can tell that because they both use the same destructor at `0x1003d030`. The unwind section shows this object being instantiated as the arg for the STL functions. (In typical MSVC fashion, I had this function at 100% but it stopped matching when I used getter methods instead of direct …

LegoCacheSound and related STL

---

LEGO1/lego/legoomni/include/gasstation.h
LEGO1/lego/legoomni/include/gasstationstate.h
LEGO1/lego/legoomni/src/gasstation/gasstation.cpp

I'm still a little confused with some things. There is some global variable, and to be honest I'm new to dealing with globals and statics in decompilation in general, but I'm off a little bit with that global data. The destructor doesn't match because of this.
In the Create function, there is some check about the GasStationState's m_unk0x14 that I just cannot seem to get it match. Ghidra says it sets the value to 4, and then checks if the previous value is not 4, but I already tried doing that and it wasn't matching. Something weird is happening there.

GasStation destructor, enable, create

---

LEGO1/lego/legoomni/include/legoworld.h
tools/isledecomp/isledecomp/compare/core.py
tools/isledecomp/isledecomp/compare/db.py
tools/isledecomp/isledecomp/utils.py
tools/isledecomp/tests/test_compare_db.py
tools/isledecomp/tests/test_demangler.py
tools/reccmp/reccmp.py
tools/reccmp/template.html

The new feature from this PR is that stub functions are now reported in both the text and HTML outputs from `reccmp`. (attn: @tahg)
I added a `--silent` option to reccmp that omits the text output. This is more for my benefit when doing performance testing with the profiler so that there's less stuff printed to the terminal.
The behind-the-scenes work has to do with address uniqueness. Addrs from the original should be unique in our database because they only ever point at one thing. The decomp linter will detect if the address is reused, so we have protection on pull requests. Addrs from the recomp should be unique too, but there are situations where one would be duplicated in the data read from the PDB. For example: the `strlwr` function gets two symbols: `_strlwr` and `__strlwr`. …

reccmp: Unique addresses and stub reporting

---

tools/isledecomp/isledecomp/utils.py
tools/reccmp/reccmp.py

This adds a new feature to reccmp where you can save the current summary to a JSON format file. After you've made some changes, you can refer back to this saved report to see how your new code affects the match percentage.
One of our github CI actions diffs the text output from reccmp against a saved copy from the previous run on the master branch on the main repo. (i.e. LEGOPROGRESS.TXT) This works well but it's not always easy to read. Also: there isn't a way to run this check on your local dev environment unless you write your own script.
To create the file, add the `--json <file>` argument to reccmp.
To run the diff, use the `--diff <file>` argument, pointing at the previously generated file.
The output looks like this, dividing the altered functions into five categories:
```
New (2): …
```

reccmp: New diff option

---

LEGO1/lego/sources/3dmanager/tglsurface.cpp
LEGO1/tgl/d3drm/impl.h
LEGO1/tgl/d3drm/view.cpp
LEGO1/tgl/tgl.h

This fixes/implements and matches the implementation of `Tgl::View::Render` to 100%.
The choice of not following the template pattern of TGL as seen in the 1996 wasn't a good one. It turns out, unsurprisingly, that the inlining patterns actually matter quite a lot to get matching code, as evidenced by this function. We will most likely have to reverse course on the current TGL implementation and re-use what we find in 1996, even if we don't particularly like it from an engineering standpoint.

Implement/match Tgl::View::Render

---

LEGO1/lego/legoomni/include/legomodelpresenter.h
LEGO1/lego/legoomni/include/legoobjectfactory.h
LEGO1/lego/legoomni/include/legopartpresenter.h
LEGO1/lego/legoomni/include/racestate.h
LEGO1/lego/legoomni/src/video/legopartpresenter.cpp
LEGO1/omni/include/mxthread.h
LEGO1/tgl/tgl.h

A few minor changes to match various `scalar deleting destructor` functions.
The ones from the `Tgl` namespace just needed annotations for the regular (synthetic) destructors.
In other cases, a destructor needed to be added or removed from the header. The deciding factor is whether the scalar dtor sets the class vtable during the destruction.
Of the remaining destructors that are close to matching: I left LegoPathController alone because it is missing two STL members. They both look like a `<set>` with different value types at +0x20 and +0x30. LegoROI calls ~ViewROI, but this function is non-trivial. ViewROI has a destructor defined as inline, but it is not this one.

Match more scalar deleting destructors

---

LEGO1/lego/legoomni/include/legoomni.h
LEGO1/lego/legoomni/src/main/legoomni.cpp

This is another function called in `LegoOmni::Create` that registers what appears to be path data, which can also be found in the "extra" data of some actors in the `.si` files:
```
Act3Brickster,
Speed:0.0,
Path:edg02_67;2;0.5;0;0.5,
COLLIDE_BOX,
Animation:Brickstr_Shoot;-1.0;Brickstr_Walk;1.0
```
There appears to be no overlap between the data found in the `.si` files and the data registered in this function.
100% match

Implement/match RegisterExtraPaths

---

CMakeLists.txt
LEGO1/lego/legoomni/include/legomodelpresenter.h
LEGO1/lego/legoomni/include/legounksavedatawriter.h
LEGO1/lego/legoomni/include/legoworld.h
LEGO1/lego/legoomni/src/common/legounksavedatawriter.cpp
LEGO1/lego/legoomni/src/entity/legoworld.cpp
LEGO1/lego/legoomni/src/video/legomodelpresenter.cpp
LEGO1/lego/legoomni/src/video/legovideomanager.cpp
LEGO1/lego/sources/roi/legoroi.cpp
LEGO1/lego/sources/roi/legoroi.h
LEGO1/realtime/orientableroi.cpp
LEGO1/realtime/roi.h
LEGO1/viewmanager/viewmanager.h
LEGO1/viewmanager/viewroi.h

This PR fixes the `*ROI` class hierarchy. Turns out what I assumed is a distinct class `AutoROI` is actually `LegoROI` - plus a thin class on top of it which I've called `TimeROI`, which is only used in `LegoVideoManager::Create`.
Constructors/destructors of `LegoROI` and `ViewROI` and related functions generally match now.

Fix LegoROI / add TimeROI

---

CMakeLists.txt
LEGO1/lego/legoomni/include/legoanimpresenter.h
LEGO1/lego/legoomni/src/entity/legoworld.cpp
LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
LEGO1/lego/sources/anim/legoanim.cpp
LEGO1/lego/sources/anim/legoanim.h
LEGO1/lego/sources/misc/legotree.h
LEGO1/lego/sources/roi/legoroi.h

This PR adds a partial implementation of `anim.lib`, with `LegoAnim` being its main/root class (formerly called `LegoAnimClass` in our sources). The structure of the animation classes has changed quite a bit since the 1996 source, although a few things stayed the same.
All the functions implemented so far are 100% matching. I'll be adding more over the coming days.

Bootstrap anim.lib

---

tools/isledecomp/isledecomp/parser/error.py
tools/isledecomp/isledecomp/parser/parser.py
tools/isledecomp/tests/test_parser.py

For "lineref" function annotations, we are trying to find the line with the opening curly brace `{` because this is where the PDB says the function starts.
We can do this even if the function is only on one line. e.g.
```// FUNCTION: TEST 0x1234
virtual void Destroy() { something_here(); }
```
If that line has no curly brace, we assume it is a regular function. We will try to find the curly brace on the following lines and can get stuck in this state until the end of the file. This can happen if the annotation is above a function declaration, forward reference, or worse, a function call. e.g.
```
// FUNCTION: TEXT 0x555
void SomeFunction();
```
In cases like this, we now throw a `NO_IMPLEMENTATION` error. The annotation should go wherever the actual code goes.

parser: Detect function declaration

---

tools/isledecomp/isledecomp/compare/asm/parse.py
tools/isledecomp/isledecomp/compare/core.py
tools/isledecomp/isledecomp/compare/diff.py
tools/isledecomp/isledecomp/utils.py
tools/reccmp/reccmp.js
tools/reccmp/reccmp.py
tools/reccmp/template.html
tools/vtable/vtable.py

Our diff output uses `unified_diff` from the Python `difflib` library to produce text like this:
```diff
---
+++
@@ -1,6 +1,6 @@
mov eax, dword ptr [esp + 4]
test eax, eax
je 0x6
push eax
-call <OFFSET1>
+call _MemFreePtr@4 (FUNCTION)
ret
```
To help with the display, we can add some color to lines that begin with `-` or `+`. Markdown  just did the same above.
Many functions are long and the parts that differ are small, so we show up to 10 lines of "context" before and after each diff rather than the entire thing. The `@@ -1,6 +1,6 @@` blurb at the top tells where we are in the textual output. This means we are looking at lines 1 through 6 of both the original and recomp assembly output.
Question: how can we show the virtual addresses instead?
We can't put the addresses in the actual text …

reccmp: HTML refactor and diff address display

---

tools/isledecomp/isledecomp/compare/diff.py
tools/isledecomp/isledecomp/utils.py
tools/reccmp/reccmp.js

A few small fixes for the "diff-with-addresses" feature (#581).
- `reccmp` verbose mode could sometimes crash if the function being displayed had no original addresses for whatever reason, usually if the function is a stub.
- Another one from verbose mode: recomp addresses would sometimes appear even if `--print-rec-addr` was not enabled.
- According to our friends at [wikipedia](https://en.wikipedia.org/wiki/Diff#Unified_format), the `@@` thing in the unified diff is the "range information". In regular diff it should specify the starting line and the number of lines for this diff hunk. My version of this had the start and end virtual address, so this is not totally faithful. We can't get the number of bytes occupied by each hunk, but we can show the starting address and number of lines …

reccmp: diff bugfixes

---

LEGO1/lego/legoomni/include/legobuildingmanager.h
LEGO1/lego/legoomni/include/legoplantmanager.h
LEGO1/lego/legoomni/include/legounksavedatawriter.h
LEGO1/lego/legoomni/include/legovariables.h
LEGO1/lego/legoomni/src/build/legobuildingmanager.cpp
LEGO1/lego/legoomni/src/common/legoplantmanager.cpp
LEGO1/lego/legoomni/src/common/legounksavedatawriter.cpp
LEGO1/lego/legoomni/src/common/legovariables.cpp
LEGO1/lego/legoomni/src/video/legomodelpresenter.cpp

Another child of `MxVariable`, with the key string "CUSTOMIZE_ANIM_FILE". The value is sent to static functions from `LegoUnkSaveDataWriter`, `LegoPlantManager` and `LegoBuildingManager`. They all have the same code to set a static member for the respective class.
The constructor for `LegoUnkSaveDataWriter` should inline almost all of the constructor for the new variable, but it's not happening. If not for that then it should match. The function at `0x10085aa0` is a wrapper for the `MxVariable` constructor except that it sets a second vtable.
The STL map from `LegoUnkSaveDataWriter` is also referenced in the constructor so I looked into that too. I feel pretty confident about the value type being the pair of  `LegoROI*` and `MxU32/MxS32`; I left it as its own struct for the moment. …

CustomizeAnimFile MxVariable

---

tools/reccmp/reccmp.js
tools/reccmp/template.html

The new design for the reccmp HTML view (#581) used classes that extend built-in HTML elements such as HTMLTableRowElement (`<tr>`). The problem is that [this is not supported by Safari](https://caniuse.com/mdn-api_document_createelement_options_parameter).
The answer is to use components that extend HTMLElement directly. With some tricky CSS we can emulate a regular HTML table but with custom elements instead. The display should be equivalent to the previous version. Tested on Safari for Mac and iPhone and it seems to work fine on both.

reccmp: Fix for HTML view on Safari

---

CMakeLists.txt
LEGO1/lego/legoomni/src/common/legotextureinfo.cpp
LEGO1/lego/sources/misc/legocontainer.cpp
LEGO1/lego/sources/misc/legocontainer.h

This PR implements `LegoTextureContainer::Insert` and fixes the element type of `LegoTextureList`. 
The match isn't great at ~55% due to a different stack allocation; functionally it should be correct. Since it's a very large function it's difficult to find the correct setup of variables, as usual.

Implement LegoTextureContainer::Insert

---

LEGO1/lego/legoomni/include/legoanimpresenter.h
LEGO1/lego/legoomni/include/legocachesoundlist.h
LEGO1/lego/legoomni/include/legoentitylist.h
LEGO1/lego/legoomni/include/legolocomotionanimpresenter.h
LEGO1/lego/legoomni/include/legopathcontrollerlist.h
LEGO1/lego/legoomni/include/legoworldlist.h
LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
LEGO1/lego/legoomni/src/video/legolocomotionanimpresenter.cpp
LEGO1/lego/legoomni/src/video/legomodelpresenter.cpp
LEGO1/lego/sources/misc/legocontainer.h
LEGO1/lego/sources/misc/legostorage.h
LEGO1/omni/include/mxcollection.h
LEGO1/omni/include/mxdsactionlist.h
LEGO1/omni/include/mxlist.h
LEGO1/omni/include/mxpresenterlist.h
LEGO1/omni/include/mxrectlist.h
LEGO1/omni/include/mxregionlist.h
LEGO1/omni/include/mxstreamchunklist.h
LEGO1/omni/include/mxstringlist.h
LEGO1/omni/include/mxvideopresenter.h

Fixes a few minor style/naming issues, among other things an issue with clang-format's `RemoveSemicolon` (which happened to be fixed recently though, so we can upgrade to a newer version at some point: https://github.com/llvm/llvm-project/pull/82278)

Minor style/naming fixes

---

CMakeLists.txt
LEGO1/lego/legoomni/include/legopartpresenter.h
LEGO1/lego/legoomni/include/legotexturepresenter.h
LEGO1/lego/legoomni/include/legoworldpresenter.h
LEGO1/lego/legoomni/src/entity/legoworldpresenter.cpp
LEGO1/lego/legoomni/src/video/legopartpresenter.cpp
LEGO1/lego/legoomni/src/video/legotexturepresenter.cpp
LEGO1/library_msvc.h
LEGO1/modeldb/modeldb.cpp
LEGO1/modeldb/modeldb.h

This bootstraps `modeldb`, which has methods that parse a `.wdb` file.
For now, two functions are implemented and matching 100%:
`LegoWorldPresenter::LoadWorld`
`ReadModelDbWorlds`

Implement ModelDb (WDB reader/parser)

---

LEGO1/omni/include/mxpresenter.h
LEGO1/omni/src/common/mxpresenter.cpp

The game crashed as MxPresenter::CreateEntity returned null, and LegoWorldPresenter expects it not to be null. Fixed an issue where the default name would be overwritten with the extra data size. After this fix, the game now crashes in LegoModelPresenter as the names of LegoROI aren't being read yet.

fix bug in MxPresenter::CreateEntity

---

CMakeLists.txt
LEGO1/lego/sources/geom/legomesh.cpp
LEGO1/lego/sources/geom/legomesh.h
LEGO1/lego/sources/misc/legocolor.cpp
LEGO1/lego/sources/misc/legocolor.h
LEGO1/lego/sources/roi/legolod.cpp
LEGO1/lego/sources/roi/legolod.h
LEGO1/lego/sources/roi/legoroi.cpp
LEGO1/lego/sources/roi/legoroi.h
LEGO1/tgl/d3drm/group.cpp
LEGO1/tgl/d3drm/impl.h
LEGO1/tgl/d3drm/unk.cpp
LEGO1/tgl/tgl.h
LEGO1/viewmanager/viewlod.cpp
LEGO1/viewmanager/viewlod.h
LEGO1/viewmanager/viewmanager.cpp

This adds the implementation for `LegoLOD::Read`, which should be accurate but due to the very large number of locals the stack allocation is not accurate right now. The match is at ~60%.
`LegoColor` and `LegoMesh` match 100%.

Implement LegoLOD::Read and related

---

CMakeLists.txt
LEGO1/lego/sources/roi/legolod.cpp
LEGO1/tgl/d3drm/group.cpp
LEGO1/tgl/d3drm/impl.h
LEGO1/tgl/d3drm/mesh.cpp
LEGO1/tgl/d3drm/meshbuilder.cpp
LEGO1/tgl/d3drm/renderer.cpp
LEGO1/tgl/d3drm/unk.cpp
LEGO1/tgl/tgl.h
LEGO1/viewmanager/viewlod.cpp
LEGO1/viewmanager/viewlod.h
LEGO1/viewmanager/viewmanager.cpp

Match is at ~65%, with afaik only the stack allocation being an issue.
I've renamed the `Tgl::Unk` class to `Tgl::MeshBuilder`, since it's clearly responsible for producing instances of `Tgl::Mesh`. Note that the entirety of `tgl` is kind of a mess right now and probably needs to be redone, because the original template patterns have not been re-used. These however are required to have a chance of getting matching code.

Implement TglImpl::MeshBuilder::CreateMesh

---

LEGO1/lego/legoomni/include/act1state.h
LEGO1/lego/legoomni/include/legonamedtexture.h
LEGO1/lego/legoomni/include/legonamedtexturelist.h
LEGO1/lego/legoomni/include/legotextureinfo.h
LEGO1/lego/legoomni/include/legotexturepresenter.h
LEGO1/lego/legoomni/include/legoutil.h
LEGO1/lego/legoomni/src/act1/act1state.cpp
LEGO1/lego/legoomni/src/common/legotextureinfo.cpp
LEGO1/lego/legoomni/src/common/legoutil.cpp
LEGO1/lego/legoomni/src/entity/legoworldpresenter.cpp
LEGO1/lego/legoomni/src/video/legotexturepresenter.cpp
LEGO1/lego/sources/misc/legocontainer.h
LEGO1/lego/sources/roi/legolod.cpp
LEGO1/lego/sources/roi/legolod.h
LEGO1/lego/sources/roi/legoroi.h
LEGO1/omni/include/mxmediapresenter.h

`LegoTexturePresenter::Read` has matched ~96% before, but compiler randomness brings it down sometimes. `Store` is at 100%. Renamed `NamedTexture` to `LegoNamedTexture`.

Implement LegoTexturePresenter::Read and Store

---

tools/isledecomp/isledecomp/compare/asm/const.py
tools/isledecomp/isledecomp/compare/asm/parse.py
tools/isledecomp/isledecomp/compare/core.py
tools/isledecomp/isledecomp/cvdump/analysis.py
tools/isledecomp/isledecomp/cvdump/parser.py
tools/isledecomp/isledecomp/cvdump/runner.py
tools/isledecomp/isledecomp/cvdump/types.py

The sanitize function prepares each assembly instruction line for the text diff. On latest, we call it about 275,000 times in both original and recomp version of `LEGO1.DLL`. Of those calls, only about 62,000 result in any change to the operands.
The biggest optimization by far is to just not call the sanitize function if the string "0x" doesn't appear in `inst.op_str`. If there's no hex value to sanitize, skip the function altogether. I first approached this problem by isolating the mnemonics we would consider replacing and checking `inst.op_str` against the list of registers, but this way (elegant or not) seems to be the best.
Another thing we can check is whether the instruction is "big enough" to have a pointer or immediate value that is an address. If the instruction is not a jump …

reccmp: Sanitize performance (and more)

---

LEGO1/lego/legoomni/include/mxtransitionmanager.h
LEGO1/lego/legoomni/src/actors/helicopter.cpp
LEGO1/lego/legoomni/src/actors/jukeboxentity.cpp
LEGO1/lego/legoomni/src/common/mxtransitionmanager.cpp
LEGO1/lego/legoomni/src/worlds/elevatorbottom.cpp
LEGO1/lego/legoomni/src/worlds/historybook.cpp
LEGO1/lego/legoomni/src/worlds/infocenter.cpp
LEGO1/lego/legoomni/src/worlds/infocenterdoor.cpp
LEGO1/lego/legoomni/src/worlds/jukebox.cpp
LEGO1/lego/legoomni/src/worlds/police.cpp
LEGO1/lego/legoomni/src/worlds/score.cpp

This PR renames the MxTransitionManager transitions. Some assertions in Beta 1.0's debug build reveal their actual names:
To my surprise, I was fairly spot on with the name guesses I made a couple years back. Wipe is actually called WipeDown, and Pixelation is actually called Mosaic. There are no assertions for the Windows transition or the completely broken one. 
These assertions also reveal that "Transition" comes at the end in their function names, rather than being prepended like we had before. Aside from this, we were actually extremely close to the original function names.
I've also renamed the relevant MxTransitionManager enum labels to reflect the changes.

rename MxTransitionManager transitions

---

LEGO1/lego/sources/anim/legoanim.cpp
LEGO1/lego/sources/anim/legoanim.h
LEGO1/lego/sources/roi/legoroi.cpp
LEGO1/realtime/matrix.h

This implements various functions in `LegoAnim`:
`CreateLocalTransform` is the main function that uses various inline functions. Since one of them isn't implemented, it doesn't fully match yet.
`GetTranslation` matches 100%.
`GetScale` probably matches 100%, but since it's inlined in `CreateLocalTransform` there is no sure way to tell (yet).
`GetRotation` is not implemented yet since it requires at least one further subclass and various methods, which I will work on in a separate PR.

Implement LegoAnim::CreateLocalTransform

---

LEGO1/lego/legoomni/include/mxtransitionmanager.h
LEGO1/lego/legoomni/src/common/mxtransitionmanager.cpp

Small styling difference inferred from the naming style of these Transition functions revealed in the Beta 1.0 debug build that escaped #655.

MxTransitionManager::TransitionNone() -> NoTransition()

---

LEGO1/omni/src/common/mxutilities.cpp

Changed some code in the public KeyValueStringParse function from `MxUtilities` to more closely match Beta 1.0. Two parameter names and a variable name were revealed in the asserts and I changed `p_output` to be shorter to match.
No effect on match percentage for the release `LEGO1` except marginal compiler entropy in three places.
My main goal with this is to get some discussion going about what things from the beta we should add to our codebase.
- Do we want the asserts even though they are no-ops in non-debug builds? (Maybe that _is_ the reason to add them)
- Any consideration for line numbers of the asserts? I commented the line numbers for the three here, but ours will probably never match exactly with the addition of the decomp assertions and ifdefs for building on newer compilers. …

KeyValueStringParse closer to beta version

---

LEGO1/lego/legoomni/include/elevatorbottom.h
LEGO1/lego/legoomni/include/gasstation.h
LEGO1/lego/legoomni/include/historybook.h
LEGO1/lego/legoomni/include/hospital.h
LEGO1/lego/legoomni/include/infocenter.h
LEGO1/lego/legoomni/include/infocenterdoor.h
LEGO1/lego/legoomni/include/jukebox.h
LEGO1/lego/legoomni/include/legogamestate.h
LEGO1/lego/legoomni/include/police.h
LEGO1/lego/legoomni/include/score.h
LEGO1/lego/legoomni/src/common/legogamestate.cpp
LEGO1/lego/legoomni/src/worlds/elevatorbottom.cpp
LEGO1/lego/legoomni/src/worlds/gasstation.cpp
LEGO1/lego/legoomni/src/worlds/historybook.cpp
LEGO1/lego/legoomni/src/worlds/hospital.cpp
LEGO1/lego/legoomni/src/worlds/infocenter.cpp
LEGO1/lego/legoomni/src/worlds/infocenterdoor.cpp
LEGO1/lego/legoomni/src/worlds/isle.cpp
LEGO1/lego/legoomni/src/worlds/jukebox.cpp
LEGO1/lego/legoomni/src/worlds/police.cpp
LEGO1/lego/legoomni/src/worlds/score.cpp

An assert in the Beta 1.0 debug build reveals the real name of the `e_noArea` enum value, and the `LegoWorld` derived class members that use this enum to track their destination location:
I've renamed all instances of `m_transitionDestination` here to reflect the real member name. Some of these members were still labeled as `unk`, and so I've corrected all of them to use `m_destLocation`.

slight style tweaks to LegoGameState and related members

---

LEGO1/omni/include/mxbitset.h
LEGO1/omni/include/mxdsbuffer.h
LEGO1/omni/include/mxmemorypool.h
LEGO1/omni/include/mxstreamer.h
LEGO1/omni/src/stream/mxdsbuffer.cpp
LEGO1/omni/src/stream/mxstreamer.cpp

Another insight from the beta. The MxStreamer class has two nearly identical members with a constructor that does some odd things:
```cpp
inline MxStreamerSubClass1(undefined4 p_size)
{
m_buffer = NULL;
m_size = p_size;
undefined4* ptr = &m_unk0x08;
for (int i = 0; i >= 0; i--) {
ptr[i] = 0;
}
}
```
They are referenced in MxDSBuffer where there is equally strange bit twiddling in AllocateBuffer and the destructor.
The beta showed that the two members of MxStreamer are MxMemoryPool objects, wrappers around an MxBitset datatype. STL `bitset` provides a convenient way to access and flip individual bits while using a minimal memory footprint. MxBitset is just a reimplementation of that, and I copied most of the structure from the STL file, as I assume Mindscape did. This is almost entirely …

Implement MxMemoryPool

---

tools/isledecomp/isledecomp/bin.py
tools/isledecomp/isledecomp/compare/core.py
tools/isledecomp/isledecomp/compare/db.py
tools/isledecomp/tests/test_islebin.py

Some small changes to make it easier to run `reccmp` against any of the beta builds. Should not affect our work with the retail files.
First: When `reccmp` scans the decomp markers/annotations in the code files, we focus only on the ones that match our "module name". e.g. `LEGO1` vs `ISLE`. We currently decide the module name for this session by looking at the base file name of the PDB that you provided.
This change reverts back to using the base file name of the original binary. This is how `reccmp` worked in the original script; I changed it to use the PDB filename at some point and I don't remember why. In practice, when comparing the retail files, this doesn't matter. The name will always be one of `("CONFIG", "ISLE", "LEGO1")` but this gets tricky as we introduce new files.
We …

Make reccmp more compatible with debug builds

---

LEGO1/omni/src/action/mxdsaction.cpp

Uses `GetExtra` in the same way as the `ParseExtra` functions

Improve code of MxDSAction::MergeFrom

---

LEGO1/lego/legoomni/include/actions/isle_actions.h

This PR refactors the action headers by regenerating them with the latest actionheadergen, which includes several changes. There is only one actual diff due to the manual refactoring done in #683, but I'll give context to what changed regardless:
* Duplicates are now properly removed by not assuming they were always in pairs.
* Enums now split into two at 2000 entries (not action IDs, these can sometimes be mutually exclusive). This prevents compiler errors from the parsing of giant enums.
* Conditional compilation was added so these enums can be forward declared.

refactor action headers

---

LEGO1/lego/legoomni/include/act1state.h
LEGO1/lego/legoomni/include/isle.h
LEGO1/lego/legoomni/include/jukeboxentity.h
LEGO1/lego/legoomni/include/legogamestate.h
LEGO1/lego/legoomni/src/act1/act1state.cpp
LEGO1/lego/legoomni/src/actors/jukeboxentity.cpp
LEGO1/lego/legoomni/src/audio/mxbackgroundaudiomanager.cpp
LEGO1/lego/legoomni/src/common/legogamestate.cpp
LEGO1/lego/legoomni/src/worlds/isle.cpp
LEGO1/omni/include/mxomni.h
LEGO1/omni/src/main/mxomni.cpp

`Isle::HandleEndAction` - match at ~88%, can't fix the signage of the object ID comparison without breaking the match right now.
`Isle::HandleElevatorEndAction` - 100% match.
The elevator navigation now works and floor 2 plays the sea animation:
https://github.com/isledecomp/isle/assets/1135351/501d1d02-1480-4e4d-b1ef-34bc0a94dee3
Observation deck:

Implement/match Isle::HandleEndAction and Isle::HandleElevatorEndAction

---

tools/reccmp/reccmp.js
tools/reccmp/template.html

I've been working on adding more stuff to the `reccmp` HTML display.
- The first and most fundamental change is pagination. We had been showing the many thousands of records for `LEGO1` on a single page, but the browser really starts chugging when you need to sort these rows or redraw the full list after clearing your search filter. I set the page size to 200 and this seems to perform well on my ~potato~ computer. To mitigate the loss of how convenient it is to have everything on the page at once, the page select dropdown acts as a kind of index for the full dataset based on the sorting column.
- We now have the option to display the recomp address alongside the original. (attn @tahg)
- The `onclick` handlers for each function row work a bit differently now. I've found myself wanting to …

More features for reccmp HTML UI

---

tools/requirements.txt

The [`capstone`](https://github.com/capstone-engine/capstone/) library that we use for bytes-to-assembly conversion has a compatibility problem with Python 3.12. Python has [deprecated and removed the `distutils` package](https://docs.python.org/3.10/whatsnew/3.10.html#distutils-deprecated) in that version, and `capstone` depends on it.
The people working on `capstone` are aware of this: https://github.com/capstone-engine/capstone/issues/2223
In the meantime, to keep our tools working, we will add `setuptools` as a dependency if Python is 3.12 or newer.

Keep capstone working on Python 3.12

---

tools/isledecomp/isledecomp/compare/db.py
tools/isledecomp/isledecomp/cvdump/analysis.py

Bugfix for the virtual inheritance feature in #717, identified by @tahg.
Broadly, there are three kinds of vftable symbols we have to contend with:
1. ``LegoAnimActor::`vftable'``, the "bare" vftable
2. ``LegoAnimActor::`vftable'{for `LegoPathActor'}``, for methods overriden from a virtual superclass
3. ``LegoAnimActor::`vftable'{for `LegoAnimActor'}``, for methods introduced by this class that is itself virtually extended
I changed some code at the last minute to prevent type 2 vftables from matching against type 1, but this broke matching on type 3.
This is now fixed. I assume that the use of a type 3 means that the type 1 symbol could not be there. If we find that this is wrong, we can fix it but we will lose some slight flexibility in the `// VTABLE` annotations. You would have to be …

Bugfix for virtual inheritance comparing

---

LEGO1/lego/legoomni/include/hospital.h
LEGO1/lego/legoomni/src/worlds/hospital.cpp

This PR labels some members of Hospital. Two of the three globals are booleans that track the state of the visibility of the two flashing LED bitmaps, and they flip themselves on their own respective timers that is compared to the universal timer member. 
I also renamed `m_unk0x10c` to `m_currentAction`. I noticed this *always* gets set right after `PlayAction()` gets called, so I tried including it directly in the inline function just out of curiosity; however, it unfortunately breaks the match.

label some hospital members

---

tools/isledecomp/isledecomp/compare/core.py
tools/isledecomp/isledecomp/parser/codebase.py

The `isledecomp.bin` module is our way of emulating a virtual address lookup. If you try to reference a virtual address outside the bounds of the file image, this will throw the `InvalidVirtualAddressError` exception. The common reason for this is that your decomp annotation is missing one of the digits, and so it is under the defined imagebase value (`0x10000000` for LEGO1) and there is no data at that location.
We don't catch this exception in `reccmp`, and this leads to a pretty rude looking error stack for a simple typo:
```
Traceback (most recent call last):
File "X:\isle\tools\reccmp\reccmp.py", line 341, in <module>
raise SystemExit(main())
^^^^^^
File "X:\isle\tools\reccmp\reccmp.py", line 242, in main
isle_compare = IsleCompare(origfile, recompfile, args.pdb, args.decomp_dir) …
```

Ignore annotations that would cause an exception

---

LEGO1/lego/legoomni/src/hospital/hospitalstate.cpp

Matches except for CxxFrameHandler jmp position. Function is noticeably sensitive to entropy.

implement HospitalState::VTable0x1c()

---

tools/isledecomp/isledecomp/compare/core.py
tools/isledecomp/isledecomp/compare/db.py

We base our function comparison on the known size of the recomp function via the PDB. We use that size to read the same number of bytes for the original function. If we read so many bytes that we stray into the function that follows, our comparison will get worse as the function size increases.
If we have the second function also marked, we can detect that this has occurred and shrink the original function footprint. This gives a marginal increase in match percentage, but these functions are still wrong because they are longer (in recomp) than they should be.
Two adjuster thunk functions went down in accuracy, but the real reason is that the annotations point to the wrong place.

reccmp: Detect when we exceed original function size

---

LEGO1/lego/legoomni/include/legocarraceactor.h
LEGO1/lego/legoomni/include/legoextraactor.h
LEGO1/lego/legoomni/include/legopathactor.h
LEGO1/lego/legoomni/include/legoraceactor.h
LEGO1/lego/legoomni/src/entity/legocarraceactor.cpp
LEGO1/lego/legoomni/src/paths/legoanimactor.cpp
LEGO1/lego/legoomni/src/paths/legoextraactor.cpp
LEGO1/lego/legoomni/src/race/legoraceactor.cpp
LEGO1/realtime/matrix.h

Implemented but not matched. Despite reccmp's really low rating of 45% it's not that bad. Some sort of unused stack variable that is in the original but not present in my version is throwing off offsets. Afaict it should exist between the two vectors. Unless it's a PACK issue that requires Vector3 to be on an 8 byte boundary?  There's some issues with inlining of vector functions too which is causing a few additional differences. The inlined matrix code seems to match exactly, barring the shifted stack pointer.

Implement LegoExtraActor::VTable0x90

---

LEGO1/lego/legoomni/include/legoutils.h
LEGO1/lego/legoomni/src/common/legoutils.cpp
LEGO1/lego/legoomni/src/worlds/isle.cpp

100% match. This function handles updating the world's light position relatively using the globe controls on the Observation Deck.

implement/match UpdateLightPosition()

---

.github/workflows/build.yml
ISLE/library_smartheap.h
tools/datacmp.py
tools/isledecomp/isledecomp/cvdump/types.py
tools/isledecomp/tests/test_cvdump_types.py

Expanding the `datacmp` tool from #618 and adding it to our CI actions. If you're unfamiliar, this takes the same argument list as `reccmp` but compares variables only. For any struct or array datatype, the tool will compare each index or member.
By default, `datacmp` shows a brief summary and any diffs it found. If you want to see all the variables, add the `--all` or `-a` parameter. If a diff is found, you will see the members that didn't match. If you want to see everything in that variable, add the `--verbose` or `-v` flag. You can combine `-a` and `-v` to see all details of every variable.
There was a design flaw that I have now fixed: the tool did not consider data that fell outside of the defined members in a struct (i.e. padding). We are now comparing everything in the footprint …

Add variable comparison to CI

---

LEGO1/lego/legoomni/include/legocharactermanager.h
LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp

`Exists` has compiler randomness and the offset can't match (yet), therefore only ~70%.
`GetActor` is 100%.
Renamed `Find` to `GetData` to be consistent.
Also fixed some of the other functions that had loops that were detected as 100% matching, but were actually incorrect. These functions now dematch to <100%, but are correct now. Refactored `LegoChar*` usage to `char*` to be consistent.

Implement/match LegoCharacterManager GetActor/Exists, fix loops

---

tools/reccmp/reccmp.py

Noticed this while working on #753.

fix typo in reccmp effective match string

---

LEGO1/lego/sources/roi/legoroi.cpp

Fix for the loop in `LegoROI::ColorAliasLookup`. The loop on the `g_roiColorAliases` array checks against the end address of the variable. When I started this function back in #259, I did not use the `_countof` macro that we now know is the way these loops work.
We don't need the `g_normalizeByteToFloat` constant as its own variable. We can just use a float constant inline and it gets the same assigned the same location in memory.

Fix loop in LegoROI::ColorAliasLookup

---

LEGO1/mxgeometry/mxgeometry3d.h

It's actually compiler-generated

Remove explicit operator= definition from Mx3DPointFloat

---

tools/isledecomp/isledecomp/parser/parser.py
tools/isledecomp/tests/test_parser.py

According to Mindscape style docs and the 96 source, global variables should have the prefix `g_` as in `Character g_characters[47]`.
The assert strings in Beta 1.0 have shown that many of these global variables might actually be static variables from a class, and that they used the `m_` prefix, much like instance members.
This problem of naming convention overlaps with the decomp parser because we have been checking any annotated variable for the `g_` prefix. We now have the `ncc` script that can more comprehensively enforce naming convention, so we are taking this warning out of the parser.

parser: don't enforce variable naming convention

---

LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
LEGO1/tgl/d3drm/impl.h
LEGO1/tgl/d3drm/meshbuilder.cpp
LEGO1/tgl/tgl.h

Match is ~88%, one function isn't properly inlined right now. Figuring this out is tricky because the compiler treats generated/synthetic inline functions differently than user-defined ones (even if code equivalent), and it's not possible to distinguish them even in the beta. In particular this affects functions like the assignment operators of the vector classes.

Implement/match LegoCharacterManager::FUN_10085870

---

tools/datacmp.py
tools/decomplint/decomplint.py
tools/reccmp/reccmp.py
tools/requirements.txt
tools/vtable/vtable.py

To enable ANSI colors for our Python scripts, we are using the `colorama` module and we have been calling `colorama.init()` to set this up. Our main reason for doing this is to support the ANSI codes on Windows terminals; for this situation the colorama folks recommend calling [`colorama.just_fix_windows_console()`](https://github.com/tartley/colorama?tab=readme-ov-file#initialisation) instead.
This is available on colorama 0.4.6 and later. Our github CI environments use 0.4.4. This is either cached somewhere or built-in with the container/VM image. I changed requirements.txt to 0.4.6 to force the newer version.
Users might have to update colorama but probably not. Aside from that, there should be no impact to user text display. Where this _will_ change things is on the github CI output, …

Use colorama.just_fix_windows_console

---

LEGO1/omni/include/mxdsaction.h
LEGO1/omni/include/mxdsmediaaction.h
LEGO1/omni/include/mxdsmultiaction.h
LEGO1/omni/include/mxdsobject.h
LEGO1/omni/include/mxdsselectaction.h
LEGO1/omni/include/mxdssound.h
LEGO1/omni/include/mxutilities.h
LEGO1/omni/src/action/mxdsaction.cpp
LEGO1/omni/src/action/mxdsmediaaction.cpp
LEGO1/omni/src/action/mxdsmultiaction.cpp
LEGO1/omni/src/action/mxdsobject.cpp
LEGO1/omni/src/action/mxdsselectaction.cpp
LEGO1/omni/src/action/mxdssound.cpp
LEGO1/omni/src/common/mxutilities.cpp
LEGO1/omni/src/stream/mxdsbuffer.cpp
LEGO1/omni/src/stream/mxramstreamprovider.cpp
LEGO1/omni/src/stream/mxstreamchunk.cpp

`DeserializeDSObjectDispatch()` and each `Deserialize()` function for `MxDSObject` and children take a buffer as an argument. The expectation is that the function will modify the caller's buffer as we seek through the data read in from the file.
We had been using a double pointer `MxU8**` for this, but I think it's cleaner to use a reference `MxU8*&` instead. No diff except register swap on one function.
`MxStreamChunk::ReadChunkHeader` wasn't playing along so I changed the code to use `memcpy` instead to get back to 100%. This matches Beta 1.0 and the Alpha, per the code comment.

Use reference on MxDSObject Deserialize calls

---

tools/isledecomp/isledecomp/compare/asm/fixes.py
tools/isledecomp/isledecomp/compare/core.py

Some common diffs that we get are these:
```diff
-cmp edx, eax
+cmp eax, edx
je 0x70
-cmp eax, dword ptr [esp + 0x24]
-jae 0x6
+cmp dword ptr [esp + 0x24], eax
+jbe 0x6
```
In these examples the `cmp` instruction has its operands flipped. Depending on the type of comparison, the jump directly below might also be inverted, or it is `je` / `jne` where the order doesn't matter.
This PR extends the asm comparison engine to look for these situations and patch them out. If doing so resolves all diffs, declare a 100% effective match.

Swap cmp operands for effective match

---

tools/isledecomp/isledecomp/compare/asm/parse.py
tools/isledecomp/isledecomp/compare/core.py
tools/isledecomp/tests/test_sanitize.py

Most calls with an address are the 5-byte variation:
```asm
100ae2c3 e8 d8      CALL    MxCore::MxCore
fe ff ff
```
But some are 6 bytes, as with imported functions:
```asm
100bcd81 ff 15      CALL    dword ptr [->KERNEL32.DLL::ReadFile]
98 b4 
10 10
```
or calls directly into a class vtable, which is common with the vector/matrix classes:
```asm
1002d90a ff 15      CALL    dword ptr [->FUN_10003c10]
10 45
0d 10
```
In these examples from Ghidra, the actual address being called is indicated by the arrow inside the square brackets. Until now, we were using the *pointer value* for the instruction we get from `capstone`. This worked okay for imports because we have an address for the `__imp__` symbol that contains the entry in the import table. If the call used any other kind of pointer, …

Detect calls using absolute indirect addressing

---

CMakeLists.txt
LEGO1/lego/legoomni/include/legopathactor.h
LEGO1/lego/legoomni/include/legopathboundary.h
LEGO1/lego/legoomni/src/actors/helicopter.cpp
LEGO1/lego/legoomni/src/paths/legopathactor.cpp
LEGO1/lego/legoomni/src/paths/legopathboundary.cpp
LEGO1/lego/sources/geom/legoedge.cpp
LEGO1/lego/sources/geom/legoedge.h
LEGO1/lego/sources/geom/legounkown100db7f4.cpp
LEGO1/lego/sources/geom/legounkown100db7f4.h
LEGO1/lego/sources/geom/legoweedge.h
LEGO1/lego/sources/geom/legowegedge.h
LEGO1/mxgeometry/mxgeometry3d.h
LEGO1/realtime/vector.h

More problems with vectors, sigh.  I'm not sure what's different about this function that it calls the Vector2 constructor. (but only for 4 of the 5?) Aside from that, the main thing affecting the match is there's an extra stack variable somewhere.  I'm pretty sure the compiler reused a stack offset in the original code that it's not doing for some reason now.  Other minor issues:
the return FAILURE is wrong, but does match how it is in beta (function at 0x100ae9da), so not sure what changed.
the call at line 113 should be EqualsCross at 0x80 (same as line 106) and then inlined to 0x74 according to the beta, but I couldn't figure out what cast would call that. The inline declaration at mxgeomtry3d.h line 41 seems to be masking the parent class method, even though the parameter types are …

Implement LegoPathActor::VTable0x88

---

LEGO1/lego/legoomni/include/legoanimpresenter.h
LEGO1/lego/legoomni/src/paths/legoanimactor.cpp
LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp

The match doesn't seem good at ~67%, however it comes down to mostly 3 register swaps throughout the entire function and a few re-ordered instructions. The logic is pretty convoluted but seems correct to me, so it might just be compiler randomness.
Matched `LegoAnimActor::FUN_1001c360` to 100%

Implement LegoAnimPresenter::FUN_1006a3c0

---

tools/isledecomp/isledecomp/compare/asm/fixes.py
tools/isledecomp/isledecomp/compare/core.py

I made these changes to our effective match validation:
- Everything is now under the `find_effective_match` method so we can limit changes to `core.py`.
- I tried a new approach to register swapping. The way we have been doing this is through a "rolling patch" where we check each token of each instruction string in both original and recomp. If we find a diff and both tokens are registers, patch the current and all future occurrences of that register. This continues and patches new diffs that are created along the way. As it turns out, this algorithm is the same as replacing all registers with a placeholder string (of the correct size for the register used). Doing it that way passed a handful of new functions, too. I'm not sure why the previous approach didn't allow those because they …

More effective match strategies

---

LEGO1/omni/include/mxcore.h
LEGO1/omni/include/mxhashtable.h
LEGO1/omni/include/mxvariable.h
LEGO1/omni/include/mxvariabletable.h
LEGO1/omni/src/common/mxcore.cpp
LEGO1/omni/src/common/mxvariabletable.cpp
LEGO1/omni/src/main/mxomni.cpp

Matching `MxVariableTable`, `MxHashTable`, and `MxVariable` to Beta 1.0. I added new `BETA10` annotations for the functions from these modules, including `MxOmni::Create` where the variable table gets constructed. I also added them for `MxCore` which I already beta patched in #663.
There's an unused dword each time something gets new'd in `MxHashTable`. This doesn't seem like it's the SEH `__$EHRec$` variable but no way to know what the intended use was.
Some diff thrashing everywhere but the functions changed here. We can probably expect that any time a header file gets changed.

Beta matching MxVariableTable

---

LEGO1/lego/legoomni/include/legotextureinfo.h
LEGO1/lego/legoomni/src/common/legotextureinfo.cpp
LEGO1/lego/legoomni/src/control/legocontrolmanager.cpp
LEGO1/lego/sources/misc/legocontainer.cpp
LEGO1/lego/sources/roi/legolod.cpp
LEGO1/lego/sources/roi/legolod.h
LEGO1/lego/sources/roi/legoroi.cpp
LEGO1/lego/sources/roi/legoroi.h

100% matches on the `GetTexture` functions (one with compiler randomness), `GetGroupTexture` isn't quite correct which is most likely due to missing inline functions required in TGL. Unfortunately anything related to `LegoTextureInfo` isn't in the beta since it was added at a later time

Implement/match LegoROI/LegoLOD::GetTexture

---

tools/isledecomp/isledecomp/compare/core.py
tools/isledecomp/isledecomp/compare/db.py

This is intended to help beta analysis/matching. Should be no change to retail analysis because thunks aren't used in the same way.
Debug builds (i.e. alpha and beta) use thunks all over the place to support incremental linking. We can identify these thunks easily because they all appear right at the start of the .text section.
We had been matching these thunks but only if: 
1. the function was thunked in both original and recomp
2. we had already matched the actual function.
When comparing asm for a function, if thunks are used but could not be matched/identified, you get the placeholder string. The side effect is that most of the `call` instructions match because they use the same `<OFFSETX>` number.
It's more helpful for analysis to actually see what's going on, so this PR changes the …

Change thunk match strategy

---

LEGO1/lego/legoomni/include/act2actor.h
LEGO1/lego/legoomni/include/act3actor.h
LEGO1/lego/legoomni/include/act3shark.h
LEGO1/lego/legoomni/include/bumpbouy.h
LEGO1/lego/legoomni/src/act3/act3shark.cpp
LEGO1/lego/legoomni/src/actors/act2actor.cpp
LEGO1/lego/legoomni/src/actors/act3actor.cpp
LEGO1/lego/legoomni/src/actors/bumpbouy.cpp

My attempt to untangle the multiple inheritance web that connects LegoPathActor and LegoAnimActor as superclasses of:
- Act2Actor
- Act3Actor
- Act3Shark
- BumpBouy
There are some new error messages complaining about duplicate entries in the database. These are not caused by annotation address reuse because the linter would alert to that. I think it's caused by the code that unwraps the `vtordisp` thunks being called multiple times on the same address. If the address appears in multiple vtables, this is expected. We can just suppress the error in these cases.

Enable some multiple-inheritance vtables

---

LEGO1/lego/legoomni/include/legoeventnotificationparam.h
LEGO1/lego/legoomni/include/legoomni.h
LEGO1/lego/legoomni/src/common/legoanimmmpresenter.cpp
LEGO1/lego/legoomni/src/common/legogamestate.cpp
LEGO1/lego/legoomni/src/common/legoutils.cpp
LEGO1/lego/legoomni/src/entity/legoworldpresenter.cpp
LEGO1/lego/legoomni/src/main/legoomni.cpp
LEGO1/lego/legoomni/src/worlds/isle.cpp
LEGO1/omni/include/mxactionnotificationparam.h
LEGO1/omni/include/mxnotificationmanager.h
LEGO1/omni/include/mxnotificationparam.h
LEGO1/omni/include/mxomni.h
LEGO1/omni/include/mxstreamer.h
LEGO1/omni/include/mxtype18notificationparam.h
LEGO1/omni/src/common/mxcompositepresenter.cpp
LEGO1/omni/src/common/mxmediapresenter.cpp
LEGO1/omni/src/common/mxpresenter.cpp
LEGO1/omni/src/main/mxomni.cpp
LEGO1/omni/src/notify/mxactionnotificationparam.cpp
LEGO1/omni/src/notify/mxnotificationmanager.cpp
LEGO1/omni/src/stream/mxdiskstreamcontroller.cpp
LEGO1/omni/src/stream/mxstreamer.cpp

`NotificationManager::Send` eventually clones the passed notification parameter, so there was no reason not to give it a const-qualifier. This removes a number of `COMPAT_MODE` switches, matches stay the same.

Make NotificationManager::Send take a const reference to notification

---

tools/isledecomp/isledecomp/compare/asm/parse.py
tools/isledecomp/isledecomp/compare/core.py
tools/isledecomp/isledecomp/compare/db.py
tools/isledecomp/tests/test_sanitize.py
tools/reccmp/reccmp.py

There are a few cases where the code will refer to an address that is not the exact start of any particular variable, but an offset into a variable. (Either a struct member or an array.)
In these cases, if we detect that the nearest address in the database is a variable and our address is within the bounds _of_ that variable, we will replace it with a special offset name like this:
```diff
-0x1001a7d8: mov ecx, <OFFSET6>
+0x1001a7d8: mov ecx, g_extraPaths+56 (OFFSET)
-0x10055653: lea ebx, [edi + edi*2 + <OFFSET3>]
+0x10055653: lea ebx, [edi + edi*2 + g_cameraLocations+20 (OFFSET)]
-0x100849cb: push <OFFSET3>
+0x100849cb: push g_characterLODs+356 (OFFSET)
```
@foxtacles found that our not doing this caused a bug to go unseen in #835. We can detect diffs like that now:
```diff
-0x10084f0d: …
```

Pointer substitution can use offset into variable

---

CMakeLists.txt
LEGO1/lego/legoomni/include/legophonemelist.h
LEGO1/lego/legoomni/src/common/legovariables.cpp
LEGO1/omni/include/mxstring.h
LEGO1/omni/src/common/mxstring.cpp

How do we feel about dead code? There are a few functions in `MxString` that aren't used even in the beta, but they are there. Their presence in mxstring.h is what affects the compiler entropy.
It doesn't seem like there are separate getter functions for const `m_data` vs. non, so I consolidated those.
I will confess to not really knowing what I was doing when I implemented the `operator+` function way back at the beginning. It doesn't return `*this` which seems to be the convention, but I couldn't get that or the second (unused) one here to match any other way. Any C++ experts have any thoughts?

Beta matching MxString

---

LEGO1/omni/include/mxatom.h
LEGO1/omni/include/mxmisc.h
LEGO1/omni/include/mxomni.h
LEGO1/omni/src/common/mxatom.cpp
LEGO1/omni/src/common/mxmisc.cpp
LEGO1/omni/src/main/mxomni.cpp

I took this opportunity to rename some stuff. One of the asserts refers to the item inside the `<set>` as just "atom". I take that to mean that the reference counter is the atom and the text identifier for that atom is (like the name says) `MxAtomId`.
With that, `MxAtomIdCounter` and `MxAtomIdCounterSet` are now just `MxAtom` and `MxAtomSet`. The name "AtomSet" is also referenced in an assert.
The `operator!=` function from`MxAtomId` used by MSVC 4.20 seems to be a synthetic function that flips the result from `operator==`. The cvdump output points to this as coming from `include/utility`. Modern compilers don't have this so I left the explicit function there for compatibility.
The `operator=` function with the `MxString` param used to be a setter on the `m_internal` member. The problem …

Beta matching MxAtom classes

---

LEGO1/omni/include/mxio.h
LEGO1/omni/src/stream/mxio.cpp

More dead code on this one.
The assert in `MXIOINFO::Write` points to the devs not using an intermediate `m_info` member. I remember that being a topic of debate in the early PR that added this file. Not something I feel compelled to change now unless it stands between us and byte-perfect match.

Beta match MXIOINFO

---

LEGO1/lego/legoomni/src/actors/radio.cpp
LEGO1/lego/legoomni/src/common/legogamestate.cpp

I found some magic values and replaced them by enums. Ideally, I wanted to have a version of `LegoWorld::Find()` that only accepts enums, but I found no elegant way to do so. The best I could come up with was
```c++
// legoworld.h
inline MxCore* Find(const MxAtomId& p_atom, IsleScript::Script p_entityId) { return Find(p_atom, (MxS32) p_entityId); }
inline MxCore* Find(const MxAtomId& p_atom, CopterScript::Script p_entityId) { return Find(p_atom, (MxS32) p_entityId); }
inline MxCore* Find(const MxAtomId& p_atom, DunecarScript::Script p_entityId) { return Find(p_atom, (MxS32) p_entityId); }
inline MxCore* Find(const MxAtomId& p_atom, JetskiScript::Script p_entityId) { return Find(p_atom, (MxS32) p_entityId); }
inline MxCore* Find(const MxAtomId& p_atom, RacecarScript::Script p_entityId) { …
```

Refactor: Replace magic values by enum values

---

LEGO1/lego/legoomni/include/legocharacters.h
LEGO1/lego/legoomni/src/common/legocharactermanager.cpp

This adds enums to better understand what the indices into the global character LOD/part arrays actually reference. Changes to accuracy are due to compiler entropy (verified)

Add enums for character LODs and parts

---

LEGO1/lego/legoomni/include/legocharactermanager.h
LEGO1/lego/legoomni/include/legocharacters.h
LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
LEGO1/lego/legoomni/src/common/legocharacters.cpp

Based on some beta asserts the struct `LegoCharacterData` was most likely called `LegoCharacterInfo` instead. Renamed the structure and corresponding variables/functions.

Rename LegoCharacterData to LegoCharacterInfo

---

tools/isledecomp/isledecomp/bin.py
tools/isledecomp/isledecomp/compare/asm/parse.py
tools/isledecomp/isledecomp/compare/core.py
tools/isledecomp/isledecomp/compare/db.py
tools/isledecomp/isledecomp/types.py
tools/isledecomp/tests/test_sanitize.py
tools/roadmap/roadmap.py

Many of the floating point instructions that refer to a pointer are actually referencing a constant value. We started sanitizing these instructions differently back in #473. The approach is to read the value "just in time" while inside the sanitize function.
It's possible to read all these values ahead of time by exploiting the following:
- Any instructions that use pointers use the absolute address, which means they will be in the relocation table.
- The floating point instructions that reference a pointer are all 6 bytes.
- The opcodes for those instructions have a simple format that we can parse quickly without using `capstone`.
- We can tell whether the pointer is a constant (and not a variable) because its address is inside `.rdata`.
We can now just add the constants to the database …

Read floating point constants up front

---

LEGO1/omni/include/mxdsaction.h
LEGO1/omni/include/mxdsobject.h
LEGO1/omni/src/action/mxdsaction.cpp
LEGO1/omni/src/action/mxdsanim.cpp
LEGO1/omni/src/action/mxdsevent.cpp
LEGO1/omni/src/action/mxdsmediaaction.cpp
LEGO1/omni/src/action/mxdsmultiaction.cpp
LEGO1/omni/src/action/mxdsobject.cpp
LEGO1/omni/src/action/mxdsobjectaction.cpp
LEGO1/omni/src/action/mxdsparallelaction.cpp
LEGO1/omni/src/action/mxdsselectaction.cpp
LEGO1/omni/src/action/mxdsserialaction.cpp
LEGO1/omni/src/action/mxdssound.cpp
LEGO1/omni/src/action/mxdsstill.cpp
LEGO1/realtime/vector.h

Some more corrections from the beta. The secondary goal here is to get more annotations down so it's easier to parse through the file and compare/match other stuff.
It seems like they used getters more consistently than setters. I had to change `MxDSObject` from private to protected so we can set `m_type` and other members directly. The constructors for all the MxDS* child classes do this, but I only marked the address for this PR. I wanted to limit the overall changes so we wouldn't have a messy diff, and that seems to have worked out. The only degrade is `DeserializeDSObjectDispatch` which is compiler noise.
Dead code: copy constructors for `MxDSObject` and `MxDSAction`. (maybe all of them?)
In the `MxDSAction` constructor, I have the calls to `Vector3::Fill` splayed out to match the …

Beta matching MxDSObject/MxDSAction

---

LEGO1/omni/include/mxdsmediaaction.h
LEGO1/omni/include/mxdsobject.h
LEGO1/omni/src/action/mxdsmediaaction.cpp

The drop in `MxDSMediaAction::Deserialize` is compiler noise, confirmed by adding a dummy class right before the function.

Beta matching MxDSMediaAction

---

LEGO1/realtime/matrix.h

This implementation of `Matrix4::ToQuaternion()` matches up to the stack layout of the function. Not sure if this is compiler entropy or if this can be influenced in the source code.

Refactor Matrix4::ToQuaternion()

---

LEGO1/omni/include/mxatom.h
LEGO1/omni/include/mxnotificationmanager.h
LEGO1/omni/include/mxomni.h
LEGO1/omni/src/common/mxmisc.cpp
LEGO1/omni/src/main/mxomni.cpp
LEGO1/omni/src/notify/mxnotificationmanager.cpp

The only real change here is the addition of a utility function `IsEmpty()` on the `MxNotificationManager` list. Still 100% match on `MxOmni::Destroy`.
The function differs in the beta for these reasons:
- Used `AUTOLOCK(m_criticalSection)`. It is typical for the beta to call this more often
- No isolate scope on the `MxDSAction` object, but retail doesn't match without it
- `m_notificationManager->SetActive(FALSE)` called earlier
- Deletes on members are wrapped in if statements that get optimized away in retail
- `m_tickleManager` calls `UnregisterClient()` on `m_notificationManager` before getting deleted
- `m_notificationManager` set to null after delete
Most of these are incompatible with retail so I left them out. Adding the remaining asserts to `MxMisc` did not create any diffs.

Tweak MxOmni::Destroy and add more beta annotations

---

LEGO1/realtime/lodlist.h
LEGO1/viewmanager/viewlodlist.cpp
LEGO1/viewmanager/viewlodlist.h

Implemented `ViewLODListManager::Destroy`. It would return an `MxBool` if we used the Mx types here, so I have it as `char`.
I moved global `g_unk0x10101064` to a static member `ViewLODListManager::g_ROINameUID`. It is only ever incremented and only in `ViewLODListManager::Create` so it just seems to be a unique id for the ROI name.
There are a few _alpha_ addresses here along with the usual beta ones. The reason is to verify which asserts should be there.
The STL function `erase()` on the map of `ViewLODList` is called two different ways; one with a single iterator and one with two (i.e. start, end). The problem is that both functions have the name `map<char const *,ViewLODList *,ROINameComparator,allocator<ViewLODList *> >::erase` in the PDB output. There is no mangled symbol name to …

Beta addrs for ViewLODList

---

tools/isledecomp/isledecomp/parser/util.py
tools/isledecomp/tests/test_parser.py
tools/isledecomp/tests/test_parser_util.py

Bug fix for the parser. We were not reading namespaces properly for vtables defined in a comment annotation. For example:
```cpp
// VTABLE: BETA10 0x101c3148
// class Tgl::Object
// VTABLE: BETA10 0x101c30d8
// class TglImpl::RendererImpl<D3DRMImpl::D3DRM>
```
These had been coming back as just `Tgl` and `TglImpl`.

Parser bugfix: vtable namespace

---

LEGO1/lego/legoomni/include/legocharactermanager.h
LEGO1/lego/legoomni/include/legopathcontroller.h
LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
LEGO1/lego/legoomni/src/main/legomain.cpp
LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
LEGO1/lego/sources/misc/legocontainer.h
tools/decomplint/decomplint.py

100% matches
@disinvite I think the decomp parser might have an issue with macros that could create situations with mismatching braces (since the macro probably isn't evaluated) which leads to some annotations not being picked up. I've fixed it like this for now by keeping the braces out of the macro:
https://github.com/isledecomp/isle/pull/917/commits/8ad98d12a8e720270722848a3236493012129c91
You can reproduce the issue by reverting that commit and you will notice that for example `0x100d86d4` is not being recognized anymore (but also a bunch of others). Maybe it's possible to get a warning/error in case braces aren't matching in a file? I think there might be other places in the code base where this can occur and we might not notice right now.

Match LegoOmni::Destroy and related

---

LEGO1/lego/sources/misc/legounknown.cpp

100% match but it doesn't resolve the float offset atm (@disinvite)
Autonomous navigation of extra actors now works
https://github.com/isledecomp/isle/assets/1135351/5c0e9b08-4fe0-431a-80a4-d25472122c60

Match LegoUnknown::FUN_1009a1e0

---

tools/isledecomp/isledecomp/compare/core.py

Fix for the bug @foxtacles noticed in #957.
Starting with #868, we build the list of floating point constants in `.rdata` by checking floating point instructions found via the relocation table. This works fine in most cases, but the constants do not always appear in the recomp asm. When this happens, we did not add the constant to the database of recomp addresses because something was already there in its place.
That something is a dummy entry from the `SECTION CONTRIBUTIONS` output from `cvdump`. This listing is not all that useful; multiple items/symbols can be lumped together as a single "contribution", so it is not even a precise reference for where things are and how big they are. We mainly use it as a lower bound on the size of a symbol that we have found elsewhere in the pdb.
The …

Fix missing float constants

---

LEGO1/omni/include/mxbitmap.h
LEGO1/omni/src/video/mxbitmap.cpp

Using the beta as our template for where functions should be inlined. This is a widely used class, so the minimal changes to the header created a big diff. The change to `GetDataSize` alone is responsible for a lot of that, though it is functionally equivalent.
- Removed `this->` to match other files where we've stopped using it.
- Refactored if-block "pyramids" to use `goto`. The beta supports doing this.
- We had been confused by the `Abs` function used here that does not precisely match the other `Abs` used everywhere else. The beta tells all: it is only used in combination with bitmap height, so it does appear to be a dedicated function just for this purpose.
- References to `sizeof(MxBITMAPINFO)` instead call a function that just returns the constant of 0x428 bytes. This could mean …

Refactor MxBitmap (again)

---

LEGO1/lego/legoomni/include/legometerpresenter.h
LEGO1/lego/legoomni/src/control/legometerpresenter.cpp
LEGO1/omni/include/mxbitmap.h
LEGO1/omni/include/mxrect16.h

The `DrawMeter` function displays the horizontal or vertical progress bars in vehicles. e.g. the fuel gauge and speedometer (brick with wings).
To get this finished, I had to change `MxBitmap::GetStart` to match the beta, and this created a new batch of compiler noise. The functions that call `GetStart` show some improvement:
- `HistoryBook::ReadyWorld` (68.75% -> 69.58%)
- `MxBitmap::BitBlt` (64.46% -> 75.90%)
- `MxBitmap::BitBltTransparent` (41.19% -> 81.19%)
- `MxControlPresenter::FUN_10044270` (47.09% -> 50.38%)
- `MxDisplaySurface::VTable0x28` (45.47% -> 46.90%)
- `MxDisplaySurface::VTable0x30` (74.90% -> 75.30%)
- `MxDisplaySurface::VTable0x44` (47.65% -> 48.69%)
LegoMeterPresenter uses a rect struct with word-sized members. The beta shows a two class hierarchy, and neither …

Implement LegoMeterPresenter::DrawMeter

---

LEGO1/omni/include/mxpalette.h
LEGO1/omni/src/video/mxpalette.cpp

Mostly small things.
- `CreateNativePalette` and `SetEntries` reuse the `i` variable in an odd way, but this is what matches the beta.
- Dead code in retail: `SetPalette`. Conversely, `Reset` is not called in the beta and it is slightly different.
- Removed `this->`.
- For the `peFlags` member, use macros from `d3dtypes.h` and `WINGDI.H` in place of magic numbers.

Beta match MxPalette

---

LEGO1/lego/legoomni/src/common/legoactioncontrolpresenter.cpp
LEGO1/lego/legoomni/src/common/legoanimmmpresenter.cpp
LEGO1/lego/legoomni/src/common/mxcontrolpresenter.cpp
LEGO1/lego/legoomni/src/control/legometerpresenter.cpp
LEGO1/lego/legoomni/src/entity/legoactorpresenter.cpp
LEGO1/lego/legoomni/src/entity/legoentitypresenter.cpp
LEGO1/lego/legoomni/src/entity/legoworldpresenter.cpp
LEGO1/lego/legoomni/src/paths/legopathpresenter.cpp
LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
LEGO1/lego/legoomni/src/video/legomodelpresenter.cpp
LEGO1/lego/sources/roi/legolod.cpp
LEGO1/omni/src/audio/mxwavepresenter.cpp
LEGO1/omni/src/common/mxpresenter.cpp
LEGO1/omni/src/video/mxstillpresenter.cpp

`USHRT_MAX` is defined in the C standard library and available everywhere, while `MAXWORD` comes from Windows. For portability, we want to use `USHRT_MAX` instead. This was already available in MSVC4 and there is no reason to believe the developers didn't use it, so it doesn't break with authenticity.

Use USHRT_MAX instead of MAXWORD

---

CMakeLists.txt
LEGO1/lego/legoomni/include/legoactors.h
LEGO1/lego/legoomni/include/legocharactermanager.h
LEGO1/lego/legoomni/include/legoentity.h
LEGO1/lego/legoomni/src/audio/lego3dsound.cpp
LEGO1/lego/legoomni/src/common/legoactors.cpp
LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
LEGO1/lego/legoomni/src/common/legogamestate.cpp
LEGO1/lego/legoomni/src/entity/legoactor.cpp
LEGO1/lego/legoomni/src/entity/legoentity.cpp
LEGO1/lego/legoomni/src/entity/legoworld.cpp
LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
LEGO1/lego/legoomni/src/video/legomodelpresenter.cpp
LEGO1/lego/legoomni/src/video/legophonemepresenter.cpp
LEGO1/lego/legoomni/src/worlds/infocenter.cpp

Based on recent decompilation work, I've renamed a number of functions/variables in `LegoCharacterManager`.
The key insight is that there are essentially two types of "characters" that are being managed by this class: actors, which are the Lego characters found in the game (66 of them), and "auto ROIs", which are dynamically created (animated) entities (for example a parrot).
Actors are treated as a superset of auto ROIs for the purposes of this class.

Name/rename functions in LegoCharacterManager

---

LEGO1/omni/include/mxomnicreateflags.h
LEGO1/omni/include/mxvideoparam.h
LEGO1/omni/include/mxvideoparamflags.h
LEGO1/omni/src/main/mxomnicreateflags.cpp
LEGO1/omni/src/video/mxvideoparam.cpp
LEGO1/omni/src/video/mxvideoparamflags.cpp

Removes the unused bit functions from `MxVideoParamFlags`. We get the expected compiler noise for header changes, but I don't see any change to the functions that actually touch the flags.
I couldn't find a beta address for the sets used only by ISLE (in `IsleApp::SetupVideoFlags`) so those don't get one.
Beta match and addresses for `MxVideoParam` too. I took the opportunity to remove `this->` from both of those classes and `MxOmniCreateFlags` which is similar to `MxVideoParamFlags`.

Streamline MxVideoParamFlags

---

tools/isledecomp/isledecomp/compare/core.py

A small change but one that should help keep the diffs more stable.
The python [difflib](https://docs.python.org/3/library/difflib.html) library provides the `SequenceMatcher` class that we use to compare assembly. For sequences over 200 elements, the code will identify common elements and not use these as the anchor for a match. If, for example, your sequence contains a list of words, a match on common words like "the" should not be considered significant inside a larger diff. The name of the general algorithm is Longest Common Subsequence: providing that is the general goal, but with the added approach of having a straightforward diff without the "zebra" effect. As the python doc page puts it:
> This does not yield minimal edit sequences, but does tend to yield matches that "look right" …

Disable autojunk for python difflib

---

LEGO1/lego/legoomni/include/legoact2.h
LEGO1/lego/legoomni/include/towtrack.h
LEGO1/lego/legoomni/src/actors/towtrack.cpp
LEGO1/lego/legoomni/src/entity/legoworld.cpp
LEGO1/lego/legoomni/src/worlds/legoact2.cpp

Adds missing destructor functions for TowTrack and LegoAct2. These bring the scalar dtor functions to 100%. I noticed these were off when checking #1004.
Also: beta addrs for LegoAct2, but the functions are slightly different there.

TowTrack and LegoAct2 destructors

---

tools/isledecomp/isledecomp/cvdump/symbols.py
tools/isledecomp/tests/test_cvdump_symbols.py

This is a probably only an issue for debug builds or non-optimized builds. (It came up for me when comparing with Beta 1.0.)
In the `SYMBOLS` section of cvdump, the `S_END` node plays (at least) two roles. It can end the overall function definition (`S_GPROC32`) and close (what I assume is) a stack/scope frame (`S_BLOCK32`). We were not handling `S_BLOCK32` and this produced a slew of errors. It looks like cvdump actually uses whitespace to indicate the stack level, but for well-formed output we should be able to handle this just as well by counting the level as I've done here.
I'm not sure whether it's possible to reuse a stack offset for two different variables in this context. This sometimes happens in the optimized builds but perhaps not here. The ultimate goal is not to run the …

Handle S_BLOCK32 in cvdump symbols parser

---

tools/isledecomp/isledecomp/cvdump/types.py
tools/isledecomp/tests/test_cvdump_types.py

Another issue that came up on the debug build. The `__output` function from `LIBCMTD.lib` has two anonymous union types. e.g.:
```
0x369c : Length = 22, Leaf = 0x1506 LF_UNION
```
The problem here is that the members line is missing the UDT field. I made this optional in the regular expression so that we can parse it.

Parse anonymous LF_UNION type

---

LEGO1/lego/legoomni/include/legocarraceactor.h
LEGO1/lego/legoomni/include/legojetski.h
LEGO1/lego/legoomni/include/legojetskiraceactor.h
LEGO1/lego/legoomni/include/legoraceactor.h
LEGO1/lego/legoomni/include/legoracecar.h
LEGO1/lego/legoomni/include/legoracemap.h
LEGO1/lego/legoomni/src/entity/legocarraceactor.cpp
LEGO1/lego/legoomni/src/entity/legojetski.cpp
LEGO1/lego/legoomni/src/entity/legojetskiraceactor.cpp
LEGO1/lego/legoomni/src/race/legoraceactor.cpp
LEGO1/lego/legoomni/src/race/legoracecar.cpp
LEGO1/lego/legoomni/src/race/legoracemap.cpp
tools/isledecomp/isledecomp/compare/db.py

Enabled the `// VTABLE` annotations for these classes that use virtual inheritance:
- LegoRaceActor
- LegoRaceMap
- LegoCarRaceActor
- LegoJetskiRaceActor
- LegoJetski
- LegoRaceCar
I moved some of the override functions around to get the tables up to 100%.
The code in `isledecomp` that autodetects the vtordisp thunks alerted to the original address being reused. With this change we now have far more of those alerts than before. They are not indicative of a problem with the annotations so I have set these to appear only in debug mode for now.

Fix remaining vtordisp issues

---

LEGO1/lego/legoomni/src/control/legometerpresenter.cpp

Vertical meters were not displayed properly. The main one we have available now is the fuel gauge in the ambulance:
We never entered the for-loop to start drawing pixels because the less-than/greater-than was swapped. This slipped by because it blended in with compiler noise: the `si` and `di` registers are swapped, so this means that `cmp si, di` should flip `jle` to `jge`. I had it matched on the jump instruction, hence the bug.

Bugfix for LegoMeterPresenter::DrawMeter

---

tools/ghidra_scripts/lego_util/function_importer.py
tools/ghidra_scripts/lego_util/type_importer.py

Fixes applied:
- Reuse existing `Enum` data types
- Detect function signatures with return types larger than 4 bytes correctly
- Ignore a template-related parameter
- Change some template-related parameter names by hand in Ghidra (which are detected but not modified correctly)
Overall, the script now shows `Functions changed: 0` after the second run.
Closes #1011

Fix Ghidra import script re-importing unchanged functions

---

ISLE/library_smartheap.h
tools/datacmp.py
tools/roadmap/roadmap.py

In `datacmp` we had some problems matching variables that should be initialized to zero. The linker might put these in the uninitialized zone of the data section and this gets reported as a diff. In the actual program, these virtual addrs are set to zero by Windows, so for practical purposes, such a variable would behave the same in both situations. This might still be wrong enough to care about (i.e. if the variables are not in the same order in each binary) so we will flag it as a warning for the user to review.
With this fix, I re-enabled the `_pnhHeap` variable from smartheap in the files for `ISLE`. We disabled it back in #990.
There was also a bug with the `roadmap` script that I noticed while checking out the `CONFIG` app. We are using a dummy value for the address of each ordinal …

Small update to datacmp and roadmap

---

LEGO1/mxgeometry/mxgeometry3d.h
LEGO1/realtime/vector.h

There is some progress here, but I'd also appreciate some ideas for further improvements.
- Add BETA10 references
- Turn some functions into inline functions based on BETA10
- Identify and improve `Vector4::EqualsHamiltonProduct()`, partly based on BETA10
- Match `Vector4::NormalizeQuaternion()` to 100 %, partly based on BETA10
The remaining issue with `Vector4::EqualsHamiltonProduct()` is the same as `Vector3::EqualsCrossImpl()` due to an `inline`. I was unable to improve the match on that one.

Improve several functions in `vector.h`

---

CMakeLists.txt
LEGO1/lego/legoomni/src/input/legoinputmanager.cpp
LEGO1/omni/include/mxdebug.h
LEGO1/omni/include/mxdssubscriber.h
LEGO1/omni/include/mxmemorypool.h
LEGO1/omni/include/mxstreamcontroller.h
LEGO1/omni/include/mxstreamer.h
LEGO1/omni/src/action/mxdsmediaaction.cpp
LEGO1/omni/src/common/mxdebug.cpp
LEGO1/omni/src/stream/mxstreamcontroller.cpp
LEGO1/omni/src/stream/mxstreamer.cpp

This adds the `MxTrace` function, a wrapper around the Windows API call `OutputDebugString`. The beta/debug builds use this (along with asserts) and this provides some extra information about what the real code looked like. There are three versions of almost the exact same function in the beta. I added the most commonly used one at `// FUNCTION BETA10 0x10124cdd`. The ifdefs and macro in mxdebug.h should stop this from appearing in retail builds.
- I had `printf` in place of `MxTrace` in mxmemorypool.h; this is now fixed.
- Reshuffled code in `LegoInputManager::CreateAndAcquireKeyboard` to demonstrate `MxTrace`.
- Added `MxTrace` to `MxDSMediaAction::CopyMediaSrcPath` because its beta addr was already marked.
- The most significant changes are to `MxStreamer` and `MxStreamController`. An …

Add MxTrace function

---

LEGO1/omni/include/mxbitmap.h
LEGO1/omni/include/mxdisplaysurface.h
LEGO1/omni/src/video/mxbitmap.cpp
LEGO1/omni/src/video/mxdisplaysurface.cpp

The stride of a bitmap is the number of bytes to seek ahead to get to the next row of pixels. Each row of the bitmap is dword-aligned, so there are between 0 and 3 padding bytes added to the visible image width on each row.
The `MxBitmap::GetAdjustedStride` function takes into account that the image can be stored with its rows in reverse order:
>There are two varieties of [Device-Independent Bitmaps]:
>
>A bottom-up DIB, in which the origin lies at the lower-left corner.
>A top-down DIB, in which the origin lies at the upper-left corner.
>If the height of a DIB, as indicated by the Height member of the bitmap information header structure, is a positive value, it is a bottom-up DIB; if the height is a negative value, it is a top-down DIB. Top-down DIBs cannot be compressed.
>
> …

Refactor surrounding `MxBitmap::GetAdjustedStride`

---

.clang-format
.clang-tidy

As previously suggested in Matrix, clang-format supports `InsertBraces` since version 15 which is essentially the same as `readability-braces-around-statements` in clang-tidy. Generally a clang-format option is preferable since it doesn't require a compilation pass.

User clang-format InsertBraces instead of clang-tidy

---

LEGO1/lego/legoomni/include/legocarraceactor.h
LEGO1/lego/legoomni/include/legoracers.h
LEGO1/lego/legoomni/src/entity/legocarraceactor.cpp
LEGO1/lego/legoomni/src/race/legoracers.cpp

Matches to 100 %.
There is one minor detail where I'm unsure whether it is an issue or not:
```c++
// GLOBAL: LEGO1 0x100f0b10
// STRING: LEGO1 0x100f09cc
const char* LegoRaceCar::g_strSpeedCopy = "SPEED";
```
points at the same string as the following string in `define.cpp`:
```c++
// GLOBAL: LEGO1 0x101020b8
// STRING: LEGO1 0x100f09cc
const char* g_strSPEED = "SPEED";
```
However, I first tried
```c++
// GLOBAL: LEGO1 0x100f0b10
const char* LegoRaceCar::g_strSpeedCopy = g_strSPEED;
```
which led to an datacmp error `initialized : uninitialized`. Not sure if the latter syntax is not allowed in C++ or if datacmp does not correctly detect the latter string.

More legoracers functions

---

LEGO1/lego/legoomni/include/legoentity.h
LEGO1/lego/legoomni/include/legopathactor.h
LEGO1/lego/legoomni/include/legoracers.h
LEGO1/lego/legoomni/src/race/legoracers.cpp
LEGO1/lego/sources/roi/legoroi.h
LEGO1/mxgeometry/mxmatrix.h
LEGO1/omni/include/mxtimer.h
LEGO1/realtime/orientableroi.h

Most of the remaining discrepancy is due to compiler entropy. I was unable to get the return statements to an exact match (the logic should be correct). Here is the remaining diff:
```
0x100135bd : mov ecx, dword ptr [eax + 4]
0x100135c0 : -mov eax, 0
0x100135c5 : -test dword ptr [ecx + ebp - 0x30], 0x7fffffff
0x100135cd : -jne 0x20
: +test dword ptr [ecx + esi - 0x30], 0x7fffffff
: +je 0xc
: +xor eax, eax
0x100135cf : pop ebp
0x100135d0 : -mov eax, 0xffffffff
0x100135d5 : pop edi
```
As mentioned on Matrix, I encountered a static instance of an `Mx3DPointFloat`:
```
Mx3DPointFloat LegoRaceCar::g_vector020 = Mx3DPointFloat(0.0f, 2.0f, 0.0f);
```
It is being initialised by a dedicated function at `LEGO1 0x10012db0`, though I don't if there is an annotation for this case. From what I can …

Implement/match `LegoRaceCar::VTable0x94`

---

LEGO1/lego/legoomni/include/legocarraceactor.h
LEGO1/lego/legoomni/include/legoentity.h
LEGO1/lego/legoomni/include/legoraceactor.h
LEGO1/lego/legoomni/include/legoracemap.h
LEGO1/lego/legoomni/include/legoracers.h
LEGO1/lego/legoomni/src/paths/legopathactor.cpp
LEGO1/lego/legoomni/src/race/legoracers.cpp

The implementation of `LegoRaceCar` should be completed with this PR.
I also added some additional BETA10 references and corrections, notably a number of variable names. Unfortunately, these re-introduced the entropy issue in `LegoRaceCar::VTable0x94` - it seems to be one of those functions that just goes back and forth with its register allocation.

Implement/match the rest of `LegoRaceCar`, BETA10 improvements

---

tools/ghidra_scripts/lego_util/function_importer.py
tools/ghidra_scripts/lego_util/ghidra_helper.py
tools/ghidra_scripts/lego_util/pdb_extraction.py
tools/ghidra_scripts/lego_util/type_importer.py
tools/isledecomp/isledecomp/cvdump/types.py
tools/isledecomp/tests/test_cvdump_types.py

Here are some of the changes to improve the situation with virtual inhertiance (as best as possible, but with limitations).
For the sake of simplicity, let's say we have three classes A, B, C with `class B: virtual A` and `class C: B`.
* Multiple non-virtual inheritance is now supported (see e.g. `LegoRaceCar`).
* Parsing virtual base class information from the PDB is now supported (with a unit test).
* The reported class sizes in the PDB include "unallocated" space for the virtual base classes:
* An instance of `B` consists of (in this order)
* its vtable,
* vboffset,
* its own fields,
* some "unallocated" space to account for an `A` (the exact offset is not specified in the PDB).
* This causes problems for class `C`, which consists of (in this order)
* The parts of `B` directly it …

Ghidra Import: Support virtual inheritance

---

LEGO1/library_smack.h
LEGO1/omni/include/mxbitmap.h
LEGO1/omni/src/video/mxsmack.cpp

`LoadHeader` is almost 100%. The only diff now is the order of the members on this line:
```cpp
p_mxSmack->m_huffmanTables = new MxU8[smackTag->codesize +
smackTag->detailsize +
smackTag->typesize +
smackTag->absize +
sizetables];
```
They are ordered how they appear in the beta, but compiler entropy scrambles them.
- Beta addrs for the Smacker lib functions and MxSmack class.
- The beta tells us that the `Abs` function from `MxBitmap` is used in `LoadFrame`, so I updated that and removed the temp one.

Some improvements to MxSmack

---

LEGO1/lego/legoomni/include/carrace.h
LEGO1/lego/legoomni/include/legojetskiraceactor.h
LEGO1/lego/legoomni/include/legoracespecial.h
LEGO1/lego/legoomni/src/entity/legojetskiraceactor.cpp
LEGO1/lego/legoomni/src/race/legoracespecial.cpp
LEGO1/realtime/orientableroi.h

`VTable0x70` matches to 100 %.
I am somewhat stuck on `VTable0x1c` - the logic seems to be correct, but the stack layout does not quite match and I have run out of ideas; some variables are off by 4 bytes. Suggestions are greatly appreciated.

Implement `LegoCarRaceActor::VTable0x70` and `VTable0x1c`

---

LEGO1/lego/legoomni/include/legopathcontrollerlist.h
LEGO1/lego/legoomni/src/entity/legoworld.cpp
LEGO1/omni/include/mxcore.h
LEGO1/omni/include/mxdsactionlist.h
LEGO1/omni/include/mxdsmultiaction.h
LEGO1/omni/include/mxdsselectaction.h
LEGO1/omni/include/mxlist.h
LEGO1/omni/include/mxrectlist.h
LEGO1/omni/include/mxregionlist.h
LEGO1/omni/include/mxstringlist.h
LEGO1/omni/src/action/mxdsmultiaction.cpp
LEGO1/omni/src/action/mxdsselectaction.cpp
LEGO1/omni/src/common/mxcompositepresenter.cpp
LEGO1/omni/src/video/mxregion.cpp
LEGO1/omni/src/video/mxregioncursor.cpp

This is a very small code change bundled with a huge number of beta addresses for `MxList` and related template classes.
Prior to this change, these functions call `DeleteAll` on an `MxList`[^1]:
- LegoWorld::Destroy
- MxDSMultiAction::CopyFrom
- MxDSSelectAction::CopyFrom
- MxDSSelectAction::Deserialize
- MxRegion::Reset
- MxCompositePresenter::EndAction
`MxCompositePresenter::EndAction` is a special case; it is the only one of these that skips destroying the values for each entry in the list. The optional parameter has a default of `TRUE`, but we use `FALSE` explicitly here.
The beta shows that these are two different functions and no parameter is passed. It doesn't seem to be a case where the destroy-or-not option is part of the template, because `MxCompositePresenter` calls the same …

Minor tweak to MxList template

---

LEGO1/lego/legoomni/src/common/legoactioncontrolpresenter.cpp
LEGO1/lego/legoomni/src/common/legoanimmmpresenter.cpp
LEGO1/lego/legoomni/src/common/mxcontrolpresenter.cpp
LEGO1/lego/legoomni/src/control/legometerpresenter.cpp
LEGO1/lego/legoomni/src/entity/legoactorpresenter.cpp
LEGO1/lego/legoomni/src/entity/legoentitypresenter.cpp
LEGO1/lego/legoomni/src/entity/legoworldpresenter.cpp
LEGO1/lego/legoomni/src/paths/legopathpresenter.cpp
LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
LEGO1/lego/legoomni/src/video/legomodelpresenter.cpp
LEGO1/omni/src/audio/mxwavepresenter.cpp
LEGO1/omni/src/common/mxpresenter.cpp
LEGO1/omni/src/video/mxstillpresenter.cpp

The `extraLength` variable in the various `ParseExtra` functions is a 16-bit variable. Occasionally the compiler will place it in one of the registers and mask out the top 16 bits. For example:
```asm
; From MxPresenter::ParseExtra
100b5012  MOV     EAX,dword ptr [EBP + extraLength]
100b501b  AND     EAX,0xffff
; set in ECX for upcoming REP MOVSD
100b5022  MOV     this,EAX
```
We have been doing this mask explicitly in the code:
```cpp
if (extraLength & USHRT_MAX) {
char extraCopy[512];
memcpy(extraCopy, extraData, extraLength & USHRT_MAX);
extraCopy[extraLength & USHRT_MAX] = '\0';
```
At one point I think this _was_ necessary for accuracy (I may have even added it) but now that the functions are built out, removing it doesn't change anything.
There are masks like this in a few other …

Remove USHRT_MAX from ParseExtra functions

---

LEGO1/lego/legoomni/include/legopathboundary.h
LEGO1/lego/legoomni/src/paths/legopathactor.cpp
LEGO1/lego/legoomni/src/race/legoracespecial.cpp
LEGO1/realtime/roi.h

The logic and structure of this function appears to be correct, but there are some mismatches coming from the inlined iterator functions. The overall match percentage is 89 %. Since `LegoPathActor::VTable0x6c` is affected by the same problem, I think that these mismatches have a common root cause that is caused by something else.

Implement/match `LegoCarRaceActor::VTable0x6c`

---

README.md
tools/README.md

I added some information regarding BETA10 to the Readme.
On a different note, I also experimented with running the comparison and Ghidra import scripts against BETA10. I'll open a PR as soon as that code is sufficiently polished.

BETA10 Readme additions

---

.gitignore
LEGO1/lego/legoomni/src/race/legoracespecial.cpp
LEGO1/realtime/vector.h
tools/ghidra_scripts/import_functions_and_types_from_pdb.py
tools/ghidra_scripts/lego_util/function_importer.py
tools/ghidra_scripts/lego_util/ghidra_helper.py
tools/ghidra_scripts/lego_util/headers.pyi
tools/ghidra_scripts/lego_util/pdb_extraction.py
tools/isledecomp/isledecomp/compare/core.py
tools/isledecomp/isledecomp/compare/db.py
util/decomp.h

Changes:
- A small issue was fixed that caused `reccmp` to crash when comparing a debug build to BETA10.
- A debug build can now be imported into Ghidra using the import script. I will upload a version to the shared Ghidra repository after the review.
- The import script received some improvements regarding thunks, which also has a positive effect on the LEGO1 repository.
- I fixed a few obviously wrong BETA10 annotations (probably made by me) that I found after running `reccmp`.
This is clearly not perfect since the codebase differs between BETA10 and LEGO1, but it has still shown to be rather helpful. In the future we could add some dedicated annotations / blacklists in case we want to maintain some BETA10/LEGO1 differences in the BETA10 Ghidra repository by hand, that shouldn't be …

BETA10: reccomp support and Ghidra imports

---

tools/ghidra_scripts/lego_util/function_importer.py
tools/ghidra_scripts/lego_util/pdb_extraction.py

Due to a mistake I made a while ago, static functions were incorrectly imported as a `__thiscall`, leading to some incorrect decompiles. I have not found any `C Near` function that *should* be a `__thiscall`, though I did not search exhaustively.

Fix Ghidra import call type

---

tools/isledecomp/isledecomp/compare/asm/fixes.py
tools/isledecomp/isledecomp/compare/core.py

Calls to `assert` push the code filename and line number along with the assert expression. From assert.h:
```cpp
#define assert(exp) (void)( (exp) || (_assert(#exp, __FILE__, __LINE__), 0) )
```
Line numbers almost never match. We are using the same code filenames where these are known, but the full filepath in these strings won't match either. To eliminate diff noise, this adds a post-sanitization step to replace both pushed values with the `__LINE__` and `__FILE__` macros. We only need to do this for debug builds (BETA10) because release builds have no asserts.

Sanitize args for assert in BETA10

---

tools/isledecomp/isledecomp/bin.py
tools/isledecomp/isledecomp/compare/core.py

String constants in release builds are de-duplicated (meaning: the string appears once in the binary even if it's used in multiple places). Because the strings are a unique item in the binary, they also get a symbol. For example: "Helicopter" is in the PDB under the symbol: `??_C@_0L@OPFI@Helicopter?$AA@` ([Reference](https://en.wikiversity.org/wiki/Visual_C%2B%2B_name_mangling))
Debug builds (i.e. BETA10) don't de-dupe the strings, which means that only one occurrence of the string gets assigned a symbol, with the majority left unidentified. We could solve this with annotation coverage (`// STRING`) or just scan each binary to find them. This PR adds that brute force search and some code to weed out junk data. 
This should cover all of the assert strings so they will now stand out in the …

Brute force string search for BETA10

---

LEGO1/omni/include/mxatom.h
LEGO1/omni/include/mxbitset.h
LEGO1/omni/include/mxmemorypool.h
LEGO1/omni/include/mxnotificationparam.h
LEGO1/omni/include/mxparam.h
LEGO1/omni/include/mxstreamer.h
LEGO1/omni/src/notify/mxnotificationmanager.cpp
LEGO1/omni/src/stream/mxstreamer.cpp

- Added more beta addrs for `MxBitSet` and `MxMemoryPool` that I had in my local file.
- Renamed `m_openStreams` to `m_controllers` based on the assert in `AddStreamControllerToOpenList`.
- `Notify` does not match the beta exactly because it calls `GetController` each time it is used. Retail gets to 100% if you save this in a variable. Maybe this could (or should) be optimized away?
- `AddStreamControllerToOpenList` does not match retail 100%, but this should be fine for now (unless it was at 100% earlier). The previous code looked like this:
```cpp
if (find(m_controllers.begin(), m_controllers.end(), p_stream) == m_controllers.end()) {
m_controllers.push_back(p_stream);
return SUCCESS;
}
```
This is closer to what we have in the assembly; if we know we reached the end of the list without …

Beta match* MxStreamer

---

LEGO1/omni/include/mxstreamlist.h
LEGO1/omni/src/main/mxomni.cpp
LEGO1/omni/src/stream/mxdiskstreamcontroller.cpp
LEGO1/omni/src/stream/mxdiskstreamprovider.cpp
LEGO1/omni/src/stream/mxdsbuffer.cpp
LEGO1/omni/src/stream/mxramstreamcontroller.cpp
LEGO1/omni/src/stream/mxstreamcontroller.cpp
LEGO1/omni/src/stream/mxstreamlist.cpp

`MxStreamListMxDSAction::Find` has a `p_delete` parameter that removes the matching item from the STL list. The beta shows that this is not called directly, but aliased by two other functions. `Find` is now `FindInternal` and the helper functions are `Find` and `FindAndErase`. These names match similar functions we already have for `MxStreamListMxNextActionDataStart`, but the ones in _that_ class are unique functions. (i.e. the helpers are not part of the main `MxStreamList` template.)
Relatively small impact from compiler randomness this time. The functions that call `Find` look to be unaffected.

MxStreamListMxDSAction helper functions

---

tools/isledecomp/isledecomp/cvdump/symbols.py

This small change fixes a lot of spurious errors logged e.g. in `reccmp`, particularly when working with `BETA10`. I first considered not adding the `LPROC32` functions to the list of known symbols, but they do not appear to cause any harm and might come in handy at some point.

Fix spurious reccmp warnings

---

LEGO1/library_msvc.h
LEGO1/mxgeometry/mxgeometry3d.h
LEGO1/realtime/vector.h

This one was quite annoying and I didn't get it to match as well as I hoped, but I still think it is an improvement. I would greatly appreciate if someone else took a look as well.
I tried to match `FUN_100040a0` to BETA10 and found a number of corrections there, bringing it up to 91.4 %. LEGO1 might be down to compiler entropy, but I am not sure.
One extremely annoying thing I noticed is that the BETA10 compilation depends on the _names of variables_, even if they are unused.

Improve `UnknownMx4DPointFloat::FUN_100040a0`

---

tools/ghidra_scripts/import_functions_and_types_from_pdb.py
tools/ghidra_scripts/lego_util/ghidra_helper.py
tools/ghidra_scripts/lego_util/globals.py

A lot of functions in our codebase are named `FUN_$address` which is fine for LEGO1 Ghidra imports, but it is confusing for BETA10 - it is hard to tell apart imported functions from Ghidra's autodetected ones. This new behaviour does the following:
* Nothing changes for the LEGO1 import
* In the BETA10 import, `FUN_$address` in function names is replaced by `LEGO1_$address`.
Let me know what you think.

BETA10 import: Fix `FUN_...` collisions

---

LEGO1/lego/legoomni/include/legocarbuild.h
LEGO1/lego/legoomni/include/legocarbuildpresenter.h
LEGO1/lego/legoomni/src/build/legocarbuild.cpp
LEGO1/lego/legoomni/src/build/legocarbuildpresenter.cpp
LEGO1/lego/sources/anim/legoanim.h
LEGO1/mxgeometry/mxgeometry3d.h
LEGO1/realtime/vector.h

Matches to 100 %.
Since the purpose of the code was sufficiently clear, I gave this one a speculative name and changed some other names as well. 
`g_rotationAngleStepYAxis` is not referenced anywhere else in the code base, so we will not get any additional information on it. It might be declared as `const MxFloat` in `legocarbuild.cpp`, but I guess we will only worry about that when all functions are implemented and we try to get the order of everything in the `.dll` file correct.

Implement `LegoCarBuildAnimPresenter::FUN_10079920()`

---

LEGO1/lego/legoomni/include/legomodelpresenter.h
LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
LEGO1/lego/legoomni/src/video/legomodelpresenter.cpp
LEGO1/lego/sources/geom/legounkown100db7f4.h
LEGO1/library_msvc.h
LEGO1/mxgeometry/mxgeometry3d.h
LEGO1/omni/include/mxdsaction.h
LEGO1/realtime/matrix.h
LEGO1/realtime/vector.h

As discussed in https://github.com/isledecomp/isle/pull/1109#discussion_r1788641625, I have investigated the various index operators in BETA10. Please let me know what you think. Overall, the match percentage on BETA10 goes down a bit, but that is misleading - the correctness actually increases. As for LEGO1, we see a **lot** of entropy on changes especially in `vector.h`. I will add some details below. Overall, I have not found that anything seriously breaks in LEGO1, but I'd appreciate if someone else took a look.

Refactor various `operator[]` based on BETA10

---

tools/README.md
tools/ghidra_scripts/lego_util/pdb_extraction.py
tools/isledecomp/isledecomp/compare/core.py
tools/isledecomp/isledecomp/compare/diff.py
tools/stackcmp/stackcmp.py

I have written a script that compares all references to the stack between the original and the recompiled binary. This is especially useful for BETA10, where it can be hard to tell if the order of variables on the stack is wrong or if there is an actual logic error in the recomp (the wrong variable is read or written). The script may also help understand how `msvc` decides the stack order since the analysis is much faster now. The names of the variables are pulled from the debug info.
Looking forward to your feedback - especially whether the built-in explanations are clear and/or how they could be improved.
**Example outputs**
Here is the (slightly abbreviated) output for a modified version of `LegoCarBuildAnimPresenter::FUN_10079160()` that matches up to the order of stack variables …

Add new script to compare the stack layout

---

tools/isledecomp/isledecomp/compare/core.py

Debug builds put their thunk functions right at the start of `.text`. To match these up, we just scan the list in orig and recomp and look for cases where each points to the same real function that has already been matched.
I had assumed each thunk would only appear once, but there are duplicates in BETA10. (I would guess that only one ends up being used in most/all cases.)
This changes `match_thunks()` so that we detect any duplicates and match in order of the thunk's virtual address. This is probably a naive way to do it, but it works fine for the code in its current state. (Open question: does thunk order depend on module order?)

Handle duplicate thunks in BETA10

---

LEGO1/lego/legoomni/include/pizza.h
LEGO1/lego/legoomni/src/actors/pizza.cpp

Implement/match Pizza::Tickle

---

LEGO1/lego/legoomni/include/gasstation.h
LEGO1/lego/legoomni/src/worlds/gasstation.cpp

Implement/match remaining GasStation functions

---

LEGO1/lego/legoomni/include/legocarbuild.h
LEGO1/lego/legoomni/include/legomain.h
LEGO1/lego/legoomni/include/legoutils.h
LEGO1/lego/legoomni/src/audio/mxbackgroundaudiomanager.cpp
LEGO1/lego/legoomni/src/build/legocarbuild.cpp
LEGO1/lego/legoomni/src/common/legoutils.cpp
LEGO1/lego/legoomni/src/common/misc.cpp
LEGO1/lego/sources/roi/legoroi.cpp
LEGO1/lego/sources/roi/legoroi.h
LEGO1/library_msvc.h

`FUN_10025720` matches up to one minor detail, the rest matches to 100 %.

Implement `FUN_10025720()` and others

---

LEGO1/omni/include/mxflcpresenter.h
LEGO1/omni/src/video/flic.cpp
LEGO1/omni/src/video/mxflcpresenter.cpp

New 100% match for ClampLine, DecodeColorPacket, DecodeBrun, and DecodeBlack. DecodeLC should be a 100% effective match (`bp` for `di` swap) but `push ebp` and `pop ebp` are the same in both, so the tools don't detect it perfectly.
I tried to get DecodeSS2, but it's a mess of gotos so I just left it alone. Even with the help of `stackcmp`, I still couldn't get a 100% beta match for a lot of these, but here's the beta diff:
```
New (18):
0x1013a10f - MxFlcPresenter::LoadFrame (new -> 34.21%)
0x1013dd80 - WritePixel (new -> 100.00%)
0x1013ddef - WritePixels (new -> 100.00%)
0x1013de84 - ClampLine (new -> 100.00%)
0x1013df77 - WritePixelRun (new -> 100.00%)
0x1013dfee - WritePixelPairs (new -> 100.00%)
0x1013e097 - DecodeChunks (new -> 100.00%)
0x1013e22c - DecodeColors256 (new -> 100.00%) …
```

Beta match progress for flic.cpp

---

.editorconfig
CMakeLists.txt

This adds a `beta10` target that builds `BETA10.DLL` when configuring cmake with `-DISLE_BUILD_BETA10=ON`.
Because `debug10` is supposed to be built in Debug mode, and `lego1` in Release mode, it's helpful to configure CMake with a multi-configuration generator (e.g. `Ninja Multi-Config`)
```cmd
$ cmake -S . -B build -DISLE_BUILD_BETA10=ON -DISLE_BUILD_CONFIG=ON -G "Ninja Multi-Config"
$ cmake --build build --target beta10 --config Debug
$ cmake --build build --target lego1 isle config --config Release
```
And using the following `reccmp-build.yml`: (minus the environment variables which reccmp does not support)
```yml
project: /home/maarten/programming/isle
targets:
ISLE:
path: $HOME/projects/isle/build/Release/ISLE.EXE
pdb: $HOME/projects/isle/build/Release/ISLE.PDB
LEGO1:
path: …
```

cmake: add beta10 target

---

LEGO1/lego/legoomni/include/legobuildingmanager.h
LEGO1/lego/legoomni/src/common/legobuildingmanager.cpp
LEGO1/lego/sources/geom/legoweedge.h
LEGO1/lego/sources/geom/legowegedge.h

Match is at ~95% but rest seems to be compiler randomness

Implement/match LegoBuildingManager::FUN_10030630

---

LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
LEGO1/lego/legoomni/src/common/legogamestate.cpp
LEGO1/lego/legoomni/src/common/legoutils.cpp
LEGO1/lego/legoomni/src/entity/legoentity.cpp
LEGO1/lego/legoomni/src/entity/legonavcontroller.cpp
LEGO1/lego/legoomni/src/entity/legopovcontroller.cpp
LEGO1/lego/legoomni/src/video/legomodelpresenter.cpp
LEGO1/lego/legoomni/src/video/legovideomanager.cpp
LEGO1/lego/sources/3dmanager/lego3dmanager.h
LEGO1/lego/sources/3dmanager/lego3dview.cpp
LEGO1/lego/sources/3dmanager/lego3dview.h

Lego3DView provides four functions: Add, Remove, SetPointOfView, and Moved. Lego3DManager has the same four functions: they are an alias to Lego3DView via the `m_pLego3DView` member.
The typical use case is:
```cpp
VideoManager()->Get3DManager()->GetLego3DView()->Remove(*roi);
VideoManager()->Get3DManager()->GetLego3DView()->Add(*roi);
```
The beta shows that the Lego3DView functions are rarely called directly, so we get:
```cpp
VideoManager()->Get3DManager()->Remove(*roi);
VideoManager()->Get3DManager()->Add(*roi);
```
I fixed this anywhere the beta supported fixing it, and put in addresses for the calling functions. The exception is `Lego3DView::Moved`, which _is_ called directly in a few places. Those are marked too.
`LegoModelPresenter::FUN_1007ff70` should be an effective match, but …

Use alias functions from Lego3DManager

---

LEGO1/lego/legoomni/include/buildings.h
LEGO1/lego/legoomni/src/common/legovariables.cpp
LEGO1/lego/legoomni/src/race/legoracers.cpp
LEGO1/library_msvc.h
LEGO1/mxdirectx/mxdirectdraw.cpp
LEGO1/tgl/d3drm/renderer.cpp

This PR has no match difference compared to `master`.
It reduces the errors raised on a `reccmp` run down to the following (with some minor changes in reccmp's logging that I'll PR soon):
```
[ERROR] Failed to find function symbol with filename and line: C:\Users\Jonathan\vscode-workspace\isle\LEGO1\lego\sources\anim\legoanim.cpp:788
[ERROR] Failed to find function symbol with name annotated with 0x10092310: _siglookup
[ERROR] Failed to find function symbol with name annotated with 0x10022360: ?_Construct@@YAXPAPAVMxCore@@ABQAV1@@Z
[ERROR] Failed to find function symbol with name annotated with 0x100c7ef0: list<MxNextActionDataStart *>::insert
[ERROR] Failed to find function symbol with name annotated with 0x100c1bc0: list<MxDSAction *,allocator<MxDSAction *> >::insert
[ERROR] Failed to …
```

Clean up unused annotations to reduce errors

---

LEGO1/lego/legoomni/include/act2brick.h
LEGO1/lego/legoomni/include/act3.h
LEGO1/lego/legoomni/include/legoact2.h
LEGO1/lego/legoomni/include/misc.h
LEGO1/lego/legoomni/src/actors/buildings.cpp
LEGO1/lego/legoomni/src/actors/helicopter.cpp
LEGO1/lego/legoomni/src/common/misc.cpp
LEGO1/lego/legoomni/src/entity/act2brick.cpp
LEGO1/lego/legoomni/src/worlds/legoact2.cpp

`LegoAct2::Enable` matches to ~95%. The remaining diff is the same we have in `Isle::Enable`, and is related to the initial check `m_set0xd0.empty() == p_enable`. Functionally it should be correct.
Implementations of the other functions match 100%.

Implement/match LegoAct2::Enable

---

LEGO1/lego/legoomni/src/worlds/isle.cpp
LEGO1/lego/legoomni/src/worlds/legoact2.cpp

The match percentage for `Isle::Enable` goes down very slightly but the code is actually more accurate.

Improve `Isle::Enable` and `LegoAct2::Enable` matches

---

LEGO1/lego/legoomni/src/actors/ambulance.cpp
LEGO1/lego/legoomni/src/actors/buildingentity.cpp
LEGO1/lego/legoomni/src/actors/bumpbouy.cpp
LEGO1/lego/legoomni/src/actors/isleactor.cpp
LEGO1/lego/legoomni/src/actors/islepathactor.cpp
LEGO1/lego/legoomni/src/actors/jukeboxentity.cpp
LEGO1/lego/legoomni/src/actors/radio.cpp
LEGO1/lego/legoomni/src/actors/towtrack.cpp
LEGO1/lego/legoomni/src/audio/mxbackgroundaudiomanager.cpp
LEGO1/lego/legoomni/src/build/legocarbuild.cpp
LEGO1/lego/legoomni/src/common/legoanimmmpresenter.cpp
LEGO1/lego/legoomni/src/entity/act2brick.cpp
LEGO1/lego/legoomni/src/entity/act2policestation.cpp
LEGO1/lego/legoomni/src/entity/legocameracontroller.cpp
LEGO1/lego/legoomni/src/race/legorace.cpp
LEGO1/lego/legoomni/src/race/legoracemap.cpp
LEGO1/lego/legoomni/src/worlds/elevatorbottom.cpp
LEGO1/lego/legoomni/src/worlds/gasstation.cpp
LEGO1/lego/legoomni/src/worlds/historybook.cpp
LEGO1/lego/legoomni/src/worlds/hospital.cpp
LEGO1/lego/legoomni/src/worlds/infocenter.cpp
LEGO1/lego/legoomni/src/worlds/infocenterdoor.cpp
LEGO1/lego/legoomni/src/worlds/isle.cpp
LEGO1/lego/legoomni/src/worlds/jukebox.cpp
LEGO1/lego/legoomni/src/worlds/police.cpp
LEGO1/lego/legoomni/src/worlds/registrationbook.cpp
LEGO1/lego/legoomni/src/worlds/score.cpp
LEGO1/omni/src/common/mxcompositepresenter.cpp

Many (most?) of the `Notify` functions call `GetNotification()` on the given `MxParam`. This function belongs to `MxNotificationParam`, so we need to cast the incoming reference variable. The beta shows that the cast almost always happens in a separate variable (and not in-place) so I changed that where the data supported it.
I intentionally did not make other changes (for now) to limit the diff for retail. For example: reordering switch cases, or introducing a switch where we have ifs.
There doesn't seem to be any consistency as to which of these lines appear first:
```cpp
MxNotificationParam& param = (MxNotificationParam&) p_param;
MxLong result = 0;
```
You can tell by looking that two of the three accuracy drops are from entropy. `InfocenterState::InfocenterState` goes back to 100% if …

Fix MxParam casts in Notify functions

---

LEGO1/lego/legoomni/include/legoeventnotificationparam.h
LEGO1/lego/legoomni/src/entity/legocameracontroller.cpp
LEGO1/lego/legoomni/src/input/legoinputmanager.cpp
LEGO1/omni/include/mxnotificationparam.h

The constructor for `MxNotification` is at `0x101253c6` in the beta, and it shows a debug string set at the `+0x08` offset. This conveniently provides the listing of the enum for notification type. There are other differences, but I noticed the notifications for dragging an object were out of order, so I changed those to match. `LegoCameraController::Notify` reads better now:
- if `c_notificationDragEnd` call `OnLButtonUp/OnRButtonUp`
- if `c_notificationDragStart` call `OnLButtonDown/OnRButtonDown`
- if `c_notificationDrag` call `OnMouseMove`
Accuracy boost due to slight tweaks in `LegoInputManager::FUN_1005cdf0`, but no diff other than that.

Rename c_notificationDrag* enum

---

.github/workflows/build.yml
LEGO1/lego/legoomni/include/act2actor.h
LEGO1/lego/legoomni/include/legopathcontroller.h
LEGO1/lego/legoomni/include/legopathedgecontainer.h
LEGO1/lego/legoomni/src/actors/act2actor.cpp
LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
LEGO1/lego/legoomni/src/paths/legopathboundary.cpp
LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
LEGO1/lego/sources/geom/legounkown100db7f4.h
LEGO1/lego/sources/geom/legoweedge.h
LEGO1/lego/sources/geom/legowegedge.h
LEGO1/mxgeometry/mxgeometry3d.h
LEGO1/mxstl/stlcompat.h
LEGO1/realtime/vector.h

The match is only at ~55% since some of the functions aren't inlined correctly. I've matched it as best as possible to the BETA version (except for adding the BETA annotations) and it's very close to matching, but they probably refactored some stuff in the final version. Functionally it should be accurate.
I've also raised the max functions of `LEGO1.DLL` in the CI build by 50.
@disinvite @jonschz there is one oddity regarding this symbol:
`_Tree<LegoPathCtrlEdge *,LegoPathCtrlEdge *,set<LegoPathCtrlEdge *,LegoPathCtrlEdgeCompare,allocator<LegoPathCtrlEdge *> >::_Kfn,LegoPathCtrlEdgeCompare,allocator<LegoPathCtrlEdge *> >::erase`
apparently this symbol exists twice in the PDB and refers to two different functions. Unfortunately for the purposes of comparison/matching, `reccmp` is picking …

Implement `LegoPathController::FUN_10048310`

---

LEGO1/lego/legoomni/src/actors/act3actors.cpp
LEGO1/lego/legoomni/src/actors/helicopter.cpp
LEGO1/lego/legoomni/src/actors/islepathactor.cpp
LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
LEGO1/lego/legoomni/src/entity/act2brick.cpp
LEGO1/lego/legoomni/src/entity/legojetskiraceactor.cpp
LEGO1/lego/legoomni/src/paths/legoextraactor.cpp
LEGO1/lego/legoomni/src/paths/legopathactor.cpp
LEGO1/lego/legoomni/src/paths/legopathboundary.cpp
LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
LEGO1/lego/legoomni/src/race/legoraceactor.cpp
LEGO1/lego/legoomni/src/race/legoracers.cpp
LEGO1/lego/legoomni/src/race/legoracespecial.cpp
LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
LEGO1/lego/legoomni/src/video/legoloopinganimpresenter.cpp
LEGO1/lego/legoomni/src/worlds/isle.cpp
LEGO1/lego/legoomni/src/worlds/legoact2.cpp
LEGO1/lego/sources/anim/legoanim.cpp
LEGO1/lego/sources/geom/legounkown100db7f4.h
LEGO1/lego/sources/misc/legounknown.cpp
LEGO1/lego/sources/roi/legoroi.cpp
LEGO1/mxgeometry/mxgeometry3d.h
LEGO1/omni/include/mxnotificationmanager.h
LEGO1/omni/src/stream/mxdiskstreamcontroller.cpp
LEGO1/realtime/vector.h
LEGO1/viewmanager/viewmanager.cpp

This PR attempts to resolve the following awkward syntax we've been seeing across the code base:
`((Vector3&) positionRef).Sub(g_unk0x10104ef0);`
In all of those instances, what we are finding in the original assembly is a dynamic dispatch to the `Add`/`Sub`/`Mul`/`Div` virtual functions. However, whenever the type is known to the compiler (usually when we have a `Mx3DPointFloat` on the stack), the compiler optimizes the call and inlines the virtual function (almost all the time). What we've done so far is take a base class reference which strips away the type information, which forced dynamic dispatch. However:
* It is very unlikely the developers wrote code like this
* In *all* cases in the code base, `Add`/`Sub`/`Mul`/`Div` are never actually inlined in the original assembly
* This …

(Proposal) Introduce arithmetic operators to `Vector2`

---

reccmp-project.yml

When we switched to using the reccmp project file, we stopped scanning the LEGO1 directory on the CONFIG and ISLE targets, and so we lost some annotations. They're back now.

Restore annotations for ISLE and CONFIG from LEGO1 dir

---

LEGO1/lego/legoomni/src/actors/act2actor.cpp

Match is now at 100%. Sometimes bugs like this can hide in what looks like a stack allocation issue

Fix `Act2Actor::FUN_10019700`

---

LEGO1/lego/legoomni/src/common/legobuildingmanager.cpp
LEGO1/lego/legoomni/src/common/legoplantmanager.cpp
LEGO1/lego/sources/geom/legowegedge.h
LEGO1/mxgeometry/mxgeometry3d.h

Matches down to compiler entropy (and one small issue in `reccmp` which we haven't addressed yet). I also found small BETA10 improvements for `LegoBuildingManager::FUN_10030630`.
I did notice an oddity with `LegoWEGEdge::GetUnknown0x14()` in BETA10, which appears to be defined twice. Not sure what is going on here, opinions are appreciated.

Implement/match `LegoPlantManager::FUN_10026410`

---

LEGO1/omni/include/mxdisplaysurface.h
LEGO1/omni/src/video/mxdisplaysurface.cpp

I'm not sure this function is ever used. Hopefully not: it's full of bugs!
1. We assume `p_bitmapData` is set to the location where we start drawing pixels, but our range check is based on that pointer plus `p_bitmapSize`. In the caller `VTable0x30`, that parameter is the full size of the bitmap, so we will run off the end unless the full image is drawn.
2. `p_height` is ignored, so I assume a sprite drawn to the bottom of the screen surface will also cause issues.
3. This probably doesn't work well for a bottom-up bitmap.
Do we have any non-standard bitmaps that could be used here? Aren't the transparent images drawn using special palette colors instead of this method?
The match looks pretty good in retail. `stackcmp` shows an effective match[^1] for BETA10. The `goto` is bizarre but …

Implement `MxDisplaySurface::DrawTransparentRLE`

---

LEGO1/lego/legoomni/include/legopathcontroller.h
LEGO1/lego/legoomni/src/actors/act3actors.cpp
LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
LEGO1/lego/sources/geom/legoedge.h
LEGO1/lego/sources/geom/legounkown100db7f4.h
LEGO1/mxgeometry/mxgeometry3d.h
LEGO1/realtime/vector.h

Initially, the match was very poor at ~30% due to wrong inlining. I've then stepped through all the functions in the BETA and found out that the assignment operator of `Vector3` has been explicitly defined, and was not synthetic as previously assumed (which lead to an additional function call). This fixed the inlining.  In this case, the match reaches ~95%.
However, changing the assignment operator like that worsens matches in a number of other functions and makes `LEGO1 0x10010be0` disappear. As such, I've chosen to leave it as-is even if that means having a low match of ~30% in this function. I've left a comment about it in `vector.h`. Maybe we can figure this out eventually.

Implement/match `Act3Brickster::FUN_10042300`

---

.github/workflows/build.yml
LEGO1/tgl/d3drm/group.cpp

Implement `GroupImpl::RemoveAll`: accuracy is 81.30%

Implement GroupImpl::RemoveAll

---

LEGO1/omni/src/stream/mxdsbuffer.cpp

Found this rummaging through some old branches and stash files. I can get a beta match for the similar function `MxDSBuffer::FUN_100c6fa0` but only a slight increase on retail. That could be compiler randomness. I'll keep working on it.

`MxDSBuffer::SkipToData` to 100%

---

LEGO1/omni/include/mxdsbuffer.h
LEGO1/omni/include/mxdsstreamingaction.h
LEGO1/omni/src/stream/mxdsbuffer.cpp

`MxDSBuffer::FUN_100c67b0` to 100%.
Beta match for:
- `MxDSBuffer::CreateObject` 
- `MxDSBuffer::ReadChunk`
- `MxDSBuffer::CalcBytesRemaining` (minus stack positions)

`MxDSBuffer::FUN_100c67b0` 100%

---

LEGO1/omni/include/mxdsaction.h
LEGO1/omni/include/mxdsbuffer.h
LEGO1/omni/include/mxdschunk.h
LEGO1/omni/src/stream/mxdsbuffer.cpp
LEGO1/omni/src/stream/mxdschunk.cpp
LEGO1/omni/src/stream/mxstreamchunk.cpp

Not a full beta match because the beta does not call `MxDSStreamingAction::FUN_100cd2d0`. It does almost the same thing but like this:
```cpp
if (m_unk0x30->GetDuration() != -1) {
m_unk0x30->SetLoopCount(m_unk0x30->GetLoopCount() - 1);
m_unk0x30->SetUnknowna8toDuration()
}
```
Filled in some other beta addrs and fixed member set order in `MxDSBuffer` and `MxDSChunk` constructors.

`MxDSBuffer::ParseChunk` to 100%

---

LEGO1/omni/include/mxdisplaysurface.h
LEGO1/omni/src/video/mxdisplaysurface.cpp
tools/ncc/skip.yml

This is basically the same as VTable0x30 but giving the LPDDSURFACEDESC via parameter instead of creating it in the function.
92.09% match, I fiddled with this and that's the most I got. It's weird - the default case comes *before* the regular cases?

Implement MxDisplaySurface::VTable0x2c

---

LEGO1/omni/include/mxdiskstreamcontroller.h
LEGO1/omni/include/mxutilitylist.h
LEGO1/omni/src/stream/mxdiskstreamcontroller.cpp

BETA10 revealed they had a `PushBack` proxy function on the `MxUtilityList` - this finally allows `MxDiskStreamController::FUN_100c7db0` to match to 100%.
Based on the alpha we know that they initially used their own STL-like structures and later migrated to using the STL. I'm assuming they kept their own classes, slapped the corresponding STL class as a base on them, forwarded some functions and called it a day.

Match `MxDiskStreamController::FUN_100c7db0`

---

.github/workflows/build.yml
LEGO1/omni/include/mxdisplaysurface.h
LEGO1/omni/src/video/mxdisplaysurface.cpp
README.md

Accuracy is an embarrassing 34.91%.
Here's some stack information to get you started:
```
Stack depth is 0x84, DDSURFACEDESC surfaceDesc is at ESP+0x18
The arguments are at:
p_pixels: ESP+0x88
p_bpp: ESP+0x8c
p_width: ESP+0x90
p_height: ESP+0x94
p_x: ESP+0x98
p_y: ESP+0x9c
``` 
(It's a "RawBlitAt" function)

Implement MxDisplaySurface::VTable0x34

---

LEGO1/lego/legoomni/include/act2brick.h
LEGO1/lego/legoomni/include/legoanimationmanager.h
LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
LEGO1/lego/legoomni/src/entity/act2brick.cpp
LEGO1/lego/legoomni/src/race/carrace.cpp
LEGO1/lego/legoomni/src/worlds/legoact2.cpp

warning: ISO C++ forbids converting a string constant to 'LegoChar*'

Fix -Wwrite-strings warnings

---

LEGO1/lego/legoomni/include/skateboard.h
LEGO1/lego/legoomni/src/actors/pizza.cpp
LEGO1/lego/legoomni/src/actors/skateboard.cpp
LEGO1/lego/legoomni/src/worlds/isle.cpp

m_unk0x160 is just a boolean for whether the pizza is shown in the hand on the left when skateboarding.
This can easily be tested by setting the value to TRUE in the constructor.
By the way - how should we name variables? This could be m_isPizzaVisible, m_showPizza, m_showingPizza, etc

SkateBoard: name m_unk0x160 -> m_pizzaVisible

---

LEGO1/lego/legoomni/include/legoentity.h
LEGO1/lego/legoomni/src/actors/act2actor.cpp
LEGO1/lego/legoomni/src/actors/act3actors.cpp
LEGO1/lego/legoomni/src/actors/act3ammo.cpp
LEGO1/lego/legoomni/src/actors/helicopter.cpp
LEGO1/lego/legoomni/src/actors/islepathactor.cpp
LEGO1/lego/legoomni/src/build/legocarbuildpresenter.cpp
LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
LEGO1/lego/legoomni/src/common/legobuildingmanager.cpp
LEGO1/lego/legoomni/src/common/legoplantmanager.cpp
LEGO1/lego/legoomni/src/entity/legojetskiraceactor.cpp
LEGO1/lego/legoomni/src/paths/legoextraactor.cpp
LEGO1/lego/legoomni/src/paths/legopathactor.cpp
LEGO1/lego/legoomni/src/paths/legopathboundary.cpp
LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
LEGO1/lego/legoomni/src/race/legoracespecial.cpp
LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
LEGO1/lego/legoomni/src/video/legoloopinganimpresenter.cpp
LEGO1/lego/legoomni/src/worlds/legoact2.cpp
LEGO1/lego/sources/anim/legoanim.cpp
LEGO1/lego/sources/geom/legowegedge.cpp
LEGO1/lego/sources/misc/legounknown.cpp
LEGO1/lego/sources/roi/legoroi.cpp
LEGO1/mxgeometry/mxgeometry3d.h
LEGO1/realtime/vector.h
LEGO1/viewmanager/viewmanager.cpp

The overload mechanism for the multiplication implementation is in all likelihood a reference vs pointer. `roadmap` results for the beginning of `Helicopter` and subsequent vector functions:
```
0001:00000e60   0001:00000e60          0  fun  259     Helicopter::Helicopter
0001:00000f70   0001:00000f70          0  fun  3       MxCore::Tickle
0001:00000f80   0001:00000f80          0  fun  29      Vector2::AddImpl
0001:00000fa0   0001:00000fa0          0  fun  28      Vector2::AddImpl
0001:00000fc0   0001:00000fc0          0  fun  29      Vector2::SubImpl
0001:00000fe0   0001:00000fe0          0  fun  29      Vector2::MulImpl
0001:00001000   0001:00001000          0  fun  28      Vector2::MulImpl
0001:00001020   0001:00001020          0  fun  28      Vector2::DivImpl
0001:00001040 …
```

Fix `Vector2`/`Vector3` order

---

README.md

Since the LEGO1.DLL has been fully decompiled, I’ve updated the README.md to reflect that debug builds can be compiled with the decompiled LEGO1.DLL, as the previous line was written when the LEGO1.DLL was still a work in progress.

(docs)README.md: Update Debug builds line

---

README.md

Please see my comments in #1283 and #1280. Thanks!

rewrite and clarify usage information in readme 

---

LEGO1/lego/legoomni/include/legonamedpart.h

100% match. Looks like we had a memory leak here.

Match `MxPtrList<LegoNamedPart>::Destroy`

---

LEGO1/realtime/vector.h

In reference to: https://github.com/isledecomp/isle/pull/1193
I've been thinking more about this, and considering that even in the BETA, all the arithmetic operations always and consistently use dynamic dispatch, I figured whatever it is, it must have been present in the BETA as well.
Then I randomly tried making the arithmetic operations virtual operator functions, and it turns out that for some arcane reason, MSVC 4.20 *always* uses dynamic dispatch for virtual functions that are operators, even if they for all intents and purposes should be inlined. Since operators in C++ are essentially just regular functions (with an extra way of calling them using the operator syntax) I did not expect that the compiler would treat them differently, but here we are.
I think this solves the mystery …

Use virtual operators in `vector.h`

---

LEGO1/lego/legoomni/include/infocenter.h
LEGO1/lego/legoomni/src/worlds/infocenter.cpp

Beta addr for `Infocenter::InitializeBitmaps`. Renames `m_mapAreas` to `m_glowInfo`, with `m_presenter` member renamed to `m_destCtl` based on asserts. Also renamed `m_frameHotBitmap` to just `m_frame` from an assert in the same function.
My reason for being here was to work on the `MxRect32` restructuring (see #1282). This function is one of the only places that calls one of the `(Point,Size)` constructors. The jury is still out on whether those are `MxPoint32` and `MxSize32` or the respective superclasses. I didn't add that here because it's not going to match until we get the structure right. It _did_ seem to match retail with the draft from #1282, but that might not be stable.

Rename some things in `Infocenter`

---

LEGO1/lego/legoomni/include/legocharactermanager.h
LEGO1/lego/legoomni/src/common/legocharactermanager.cpp

- `GetActorROI` used `operator==` and a `const_iterator`. I'm thinking about ways we can identify blocks of these template functions all at once in BETA10 because many have identical structures. (In Ghidra, use Search > For Matching Instructions > Exclude Operands).
- `FindChildROI` has the iterator constructed outside of the loop.
- Beta shows that many functions here have an unnecessary final `else`.
- `FUN_100849a0`: Arg name `p_texture` confirmed by assert.
The next thing I want to try is separating the first entry of `g_actorLODs` from the rest of the list. The loop in `LegoCharacterManager::SwitchColor` suggests that this may be correct in the beta.

Some tweaks to `LegoCharacterManager`

---

LEGO1/omni/include/mxio.h
LEGO1/omni/src/stream/mxio.cpp

Another beta-only function that is never called. I have to assume this file was shared with other internal Mindscape tools for writing data.
I got the name for this function (and other things) from the mmio pages on Microsoft's site. https://learn.microsoft.com/en-us/windows/win32/api/mmiscapi/nf-mmiscapi-mmiocreatechunk
I also went through and added the `MMSYSERR_NOERROR` macro (replacing `0`), also referenced in those doc pages.

Add `MXIOINFO::CreateChunk`

---

README.md
docker/Dockerfile
docker/entrypoint.sh

I frequently get asked if it's possible to build the project on Linux and macOS hosts. It always has been possible; many contributors have used and do use a workflow with Wine on non-Windows platforms, but the manual configuration for this setup has never been officially documented and is a bit cumbersome. I've been thinking about ways to address this over the course of the project, but I haven't sat down and fleshed it out until now.
This PR introduces Docker as a method of compilation. I've written a `Dockerfile` and accompanying shell script to create a Docker image that has MSVC 4.20 and CMake pre-configured properly with Wine under Debian. I've already built the image and pushed it to `ghcr.io` under our organization, so all end users have to do to build the project under Linux and …

introduce Docker as a compilation method

---

LEGO1/library_msvc.h
LEGO1/library_smack.h

This PR increases the coverage on LEGO1 for some unused functions. Also, the end of `_SmackDoFrameToBuffer` was misdetected, now the match is better. I got some of the matches by importing `smack.lib` into Ghidra (not shared at the moment). Note that `smack.lib` does not use `INT3` to fill unreachable code segments, but an odd alternation of
```asm
xchg ebx, ebx
xchg ecx, ecx
```
which we also see in some parts of LEGO1. I am still quite suprised that the smack code does not match perfectly, but maybe we don't have the correct version? This would be out of the scope of this PR.

Add smack functions and math globals

---

LEGO1/lego/legoomni/include/gasstation.h
LEGO1/lego/legoomni/include/legostate.h
LEGO1/lego/legoomni/src/worlds/gasstation.cpp

Everything lines up in `GasStation` - we do have a constant diff of `16` bytes, but this discrepancy is because of a function that doesn't match in the preceding compilation unit, `Helicopter`.
`GasStation::ReadyWorld` matches 100% now.
```
0001:000036a0   0001:000036b0         16  fun  198     GasStation::GasStation
0001:00003770   0001:00003780         16  fun  3       GasStation::VTable0x5c
0001:00003780   0001:00003790         16  fun  6       GasStation::ClassName
0001:00003790   0001:000037a0         16  fun  266     GasStation::IsA
0001:000038a0   0001:000038b0         16  fun  30      GasStation::`scalar deleting destructor'
0001:000038c0   0001:000038d0         16  fun  205     GasStation::~GasStation
0001:00003990   0001:000039a0         16  fun  198     GasStation::Create …
```

Order functions up to the end of `GasStation`, match `GasStation::ReadyWorld`

---

LEGO1/omni/include/mxdsbuffer.h
LEGO1/omni/include/mxdschunk.h
LEGO1/omni/include/mxdsstreamingaction.h
LEGO1/omni/src/stream/mxdiskstreamprovider.cpp
LEGO1/omni/src/stream/mxdsbuffer.cpp
LEGO1/omni/src/stream/mxramstreamprovider.cpp
LEGO1/omni/src/stream/mxstreamchunk.cpp

Specifically: the functions `IntoType` and `IntoLength` from the `MxDSChunk` header. They seek a pointer into the right place when reading the chunk, but the beta shows they are not used. The `Size` and `End` functions are used, but they are different from what we had.
These two functions are users of the utility functions:
- `MxDiskStreamProvider::FUN_100d1b20` now 100%
- `ReadData` (from `MxRAMStreamProvider`) still 100% but with entropy
I'm not sure why, but this has also caused us to jump from 141 to 432 functions aligned. It may just be chance, but these two runs of functions now line up:
```
0001:0000b110          0  fun  103     MxEntity::~MxEntity
to
0001:00012c40          0  fun  458     LegoJetski::HitActor
and
0001:00016650          0  fun  390     CarRace::HandleClick
to …
```

Refactor surrounding `MxDSChunk` utility functions

---

LEGO1/omni/include/mxdsstreamingaction.h
LEGO1/omni/src/action/mxdsstreamingaction.cpp

Removed `this->` and added beta addresses. `Init()` can be void and still use `xor eax, eax` to null out all members.
The beta shows that the `MxDSAction` version of `operator=` is used instead of one from `MxDSStreamingAction`, so I have this as `*(MxDSAction*) this = ...`. Is that syntax okay?

Beta match `MxDSStreamingAction`

---

LEGO1/lego/legoomni/include/legoworld.h
LEGO1/lego/legoomni/src/entity/legoworld.cpp

Resolves #1322.
The main thing was swapping `!set.empty()` for `set.size() != 0` and pulling an iterator out into its own variable. The rest is just rearranging things around beta doing an early return.
The diff on `AddPath` is from entropy. I'm not sure what's wrong with `Enable` but it looks okay in the beta. I changed `Remove` around but accuracy is still 100%.

`LegoWorld::Add` to 100%

---

LEGO1/lego/legoomni/include/legopathcontroller.h
LEGO1/lego/legoomni/include/legoworld.h
LEGO1/lego/legoomni/src/entity/legoworld.cpp

This fixes the order of symbols in `LegoWorld` around `LegoWorld::RemoveActor`.
```
0001:0001ea70   0001:0001ea60        -16  fun  249     LegoWorld::PlaceActor
0001:0001eb70   0001:0001eb60        -16  fun  263     LegoWorld::PlaceActor
0001:0001ec80   0001:0001ec70        -16  fun  227     LegoWorld::RemoveActor
0001:0001ed70   0001:0001ed60        -16  fun  45      _Tree<LegoPathActor *,LegoPathActor *,set<LegoPathActor *,LegoPathActorSetCompare,allocator<LegoPathActor *> >::_Kfn,LegoPathActorSetCompare,allocator<LegoPathActor *> >::_Lbound
0001:0001eda0   0001:0001ed90        -16  fun  225     LegoWorld::FUN_1001fda0
0001:0001ee90   0001:0001ee80        -16  fun  225     LegoWorld::FUN_1001fe90
0001:0001ef80   0001:0001ef70        -16  fun  152     LegoWorld::AddPath
```

Implement/match `LegoWorld::ActorExists`

---

.github/workflows/build.yml
LEGO1/lego/legoomni/include/legorace.h

As discussed on https://github.com/isledecomp/reccmp/pull/76, this PR makes the pipeline use JSON diff instead of text output diff to compare the current branch to `master`. I would like to merge this change in two separate PRs - the first one generating a diff output for the second one to compare against.
Here is a successful run on my PR branch: https://github.com/jonschz/isle/actions/runs/12852523439/job/35834652699

Refactor diffs in the pipeline, part 1

---

LEGO1/lego/legoomni/include/legogamestate.h
LEGO1/lego/legoomni/src/common/legogamestate.cpp

An attempt to solve #1337. `SwitchPlayer` is 100% but this feels like an entropy match.
The only change in that method is removing the copy constructor for `LegoGameState::Username`. The code looks like this:
```asm
; Username selectedName(m_players[p_playerId]);
; Starting at BETA10 0x10085036
; Set EAX to m_players[p_playerId]
movsx eax, word ptr [ebp + 8]    ; p_playerId
mov ecx, eax
shl eax, 3
sub eax, ecx
add eax, eax
add eax, dword ptr [ebp - 0x54]  ; "this"
add eax, 0x20
; ECX is selectedName
lea ecx, [ebp - 0x40]
; Copy 14 bytes
mov edx, dword ptr [eax]
mov dword ptr [ecx], edx
mov edx, dword ptr [eax + 4]
mov dword ptr [ecx + 4], edx
mov edx, dword ptr [eax + 8]
mov dword ptr [ecx + 8], edx
mov ax, word ptr [eax + 0xc]
mov word ptr [ecx + 0xc], ax
```
Removing the copy …

Some improvements to `LegoGameState`

---

LEGO1/lego/legoomni/include/legopathboundary.h
LEGO1/lego/legoomni/include/legoworld.h
LEGO1/library_msvc.h

Corrects two annotations for `_Construct` functions and points the `operator new` annotation for `BETA10` at the version that takes one argument.
These would be exposed as diffs when we merge isledecomp/reccmp#76.

Fix annotations for overloaded functions

---

LEGO1/lego/legoomni/src/build/legocarbuildpresenter.cpp
LEGO1/lego/sources/misc/legostorage.h

Implement `LegoCarBuildAnimPresenter::Serialize`

---

LEGO1/lego/legoomni/include/historybook.h
LEGO1/lego/legoomni/include/legogamestate.h
LEGO1/lego/legoomni/src/worlds/historybook.cpp
LEGO1/lego/legoomni/src/worlds/registrationbook.cpp
LEGO1/library_msvc.h
LEGO1/omni/include/mxvideopresenter.h
reccmp-project.yml

Closes #1369.
Matches to about 53 % on BETA10, though most of the mismatch comes from incorrect registers / entropy. The structural match isn't perfect, but quite decent.
I got LEGO1 to 91 %. Some of it appears to be entropy, but I can't make the beginning work:
```diff
0x1008271e : mov ecx, 'A_Bitmap' (STRING)
-0x10082723 : -cmp si, 0x1a
0x10082727 : lea edx, [esp + 0x40]
0x1008272b : mov cl, byte ptr [ecx + 8]
0x1008272e : mov dword ptr [edx], eax
0x10082730 : mov dword ptr [edx + 4], ebx
0x10082733 : mov byte ptr [edx + 8], cl
-0x10082736 : -jge 0x25
0x10082738 : lea eax, [esp + 0x40]
0x1008273c : mov ecx, dword ptr [esp + 0x18]
0x10082740 : push eax
0x10082741 : push 'MxStillPresenter' (STRING)
0x10082746 : call LegoWorld::Find(char const *, char const *) (FUNCTION)
```
It looks as if …

Match `HistoryBook::ReadyWorld()`

---

LEGO1/omni/include/mxatom.h
LEGO1/omni/include/mxpresenterlist.h
LEGO1/viewmanager/viewlodlist.h

I noticed these were wrong while working on a change for `reccmp`. Two got truncated by `clang-format` and two used the wrong generic type.
`map<char const *,ViewLODList *,ROINameComparator,allocator<ViewLODList *> >::erase` does not generate a symbol for both of its appearances:
```
(002E64) S_GPROC32: [0001:00124AC0], Cb: 0000002F, Type:             0x2B2E, map<char const *,ViewLODList *,ROINameComparator,allocator<ViewLODList *> >::erase
Parent: 00000000, End: 00002F30, Next: 00000000
Debug start: 0000000C, Debug end: 00000028
Flags: Frame Ptr Present
(004930) S_GPROC32: [0001:00125BA0], Cb: 0000002B, Type:             0x2B5F, map<char const *,ViewLODList *,ROINameComparator,allocator<ViewLODList *> >::erase
Parent: 00000000, End: 000049EC, Next: 00000000
Debug start: 0000000C, Debug …
```

Fix some beta annotations

---

LEGO1/lego/legoomni/include/infocenter.h
LEGO1/lego/legoomni/include/legomain.h
LEGO1/lego/legoomni/include/registrationbook.h
LEGO1/lego/legoomni/src/common/misc.cpp
LEGO1/lego/legoomni/src/worlds/historybook.cpp
LEGO1/lego/legoomni/src/worlds/registrationbook.cpp

As noted on Element, this function is pretty fragile and highly susceptible to small changes. It now closely resembles BETA10, but has gone down from 100 % to 100 % effective relative to `master` - I hope this is due to entropy.
I was also able to track down a few more BETA10 functions and verify the existence of the inline function `RegistrationBook::PlayAction()` (which is actually `static` - maybe it belongs somewhere else? Its BETA10 version is only called  from `RegistrationBook`, though).
One detail I couldn't work:
```diff
0x100f3a90 : push 0x1f4
-0x100f3a95 : -call RegistrationBook::PlayAction (FUNCTION)
+           : +call Thunk of 'RegistrationBook::PlayAction' (FUNCTION)
0x100f3a9a : add esp, 4
```
Not sure how we can declare a non-thunked function in BETA10 that is inlined in …

BETA10 match `RegistrationBook::ReadyWorld()`

---

LEGO1/lego/legoomni/include/legoanimactor.h
LEGO1/lego/legoomni/include/legoracers.h
LEGO1/lego/legoomni/src/race/carrace.cpp
LEGO1/lego/legoomni/src/race/jetskirace.cpp
LEGO1/lego/legoomni/src/race/legoraceactor.cpp
LEGO1/lego/legoomni/src/race/legoracers.cpp

Corrects beta address for `g_skBMap` array.
Moved `MxMatrix` variable init position in `HitActor` functions to match beta. Removed `timeElapsed` variable per the beta.
Renamed global variables related to sounds and timed events. This was partly based on checking the actual files with SIEdit. I didn't check in the actual game so feel free to correct me if I'm wrong here. I'm basing the name `g_playerHitStudsSounds` on the fact that `srt018sl` through `srt029sl` are grunts and pain sounds. In contrast, `srt006sl` is "Eat my bricks buddy!" so this seems like a sound for when Studs hits you instead of you hitting him. Does this mean that the second bool parameter of all the `HitActor` functions tells whether the player is moving at the time of the collision? (As a way to tell who hit who) …

Tweaks to `LegoRaceCar` and `LegoJetski`

---

LEGO1/lego/legoomni/include/legocachsound.h
LEGO1/lego/legoomni/src/audio/legocachsound.cpp

Beta matching where possible. `LegoCacheSound` does not extend `MxCore` in beta10, so the constructor, destructor, and vtable all look different. `FUN_10006be0` has slightly different branching too.
This improves the code for `LegoCacheSound::GetBaseFilename`. Still 100% match.

Beta matching `LegoCacheSound`

---

LEGO1/lego/legoomni/include/jetski.h
LEGO1/lego/legoomni/include/legoactor.h
LEGO1/lego/legoomni/include/legogamestate.h
LEGO1/lego/legoomni/src/actors/dunebuggy.cpp
LEGO1/lego/legoomni/src/actors/islepathactor.cpp
LEGO1/lego/legoomni/src/actors/jetski.cpp

Closes #1368. The BETA10 match cannot be improved significantly since it has been changed a lot.

Match `Jetski::HandleClick`

---

LEGO1/mxgeometry/mxgeometry3d.h
LEGO1/mxgeometry/mxgeometry4d.h
LEGO1/realtime/vector2d.inl.h
LEGO1/realtime/vector3d.inl.h
LEGO1/realtime/vector4d.inl.h

This completes the vtables of `Vector2,3,4` and `Mx3,4DPointFloat`. There are still a few diffs on BETA10, most of them are likely due to entropy. I have not seen any significant changes on BETA10 or LEGO1 other than the usual entropy.

Match simple BETA10 vector calls

---

LEGO1/lego/legoomni/include/legoanimpresenter.h
LEGO1/lego/legoomni/include/legocarbuildpresenter.h
LEGO1/lego/legoomni/include/legopathactor.h
LEGO1/lego/legoomni/src/paths/legopathactor.cpp
LEGO1/lego/legoomni/src/video/legoanimpresenter.cpp
LEGO1/lego/sources/misc/legounknown.cpp
LEGO1/lego/sources/misc/legounknown.h
LEGO1/lego/sources/roi/legoroi.cpp
LEGO1/mxgeometry/mxmatrix.h
LEGO1/realtime/matrix.h
LEGO1/realtime/matrix4d.inl.h
LEGO1/realtime/orientableroi.cpp

This fixes the BETA annotation of `Matrix4::operator[]`, which was previously annotated as `MxMatrix::operator[] const`. The best place to verify that this is correct is `LegoView1::Create`, since it accesses both a `Matrix4` and `MxMatrix`.
In consequence, several function parameters and members which were previously `MxMatrix` were changed to be of type `Matrix4` instead. Matches of affected functions stay the same. (but plenty of entropy in the code base as usual)

Fix `Matrix4::operator[]` annotation

---

LEGO1/library_msvc.h

See https://github.com/isledecomp/reccmp/pull/89#issuecomment-2692662622. Should have no impact at the moment, but will fix/prevent a small regression when the linked PR on `reccmp` is merged.

Add BETA10 reference to `_aexit_rtn`

---

.github/workflows/build.yml

isledecomp/reccmp#94 adds the feature to `reccmp-aggregate` to create an HTML report from the aggregate run. This enables that option in CI so the files will get included in the build artifact.
For each entity we choose the sample that has the highest accuracy score. The new HTML report includes the diff that resulted in that score.

Write entropy report to HTML

---

LEGO1/lego/legoomni/src/common/mxcontrolpresenter.cpp

The only way to get this to match is to have an inline function like `advance` (with that exact interface). However, standard STL `advance` doesn't work because of the bidirectional nature of the list iterator; it will decrement the iterator if `n` is negative. But this is not part of the original assembly.
Defining a new (template) method like `advance` separately would work, but doesn't make a whole lot of sense in the context of that class with the required interface so I used a direct call to internal `_Advance` with the `forward_iterator` tag instead. Maybe they defined a function like that in the global scope like other template functions in `mxutilities.h`? Or they had a diferent version of the STL?

Match `MxControlPresenter::HasTickleStatePassed`

---

LEGO1/lego/legoomni/include/legopathboundary.h

Matches `_Tree<LegoAnimPresenter *,LegoAnimPresenter *,set<LegoAnimPresenter *,LegoAnimPresenterSetCompare,allocator<LegoAnimPresenter *> >::_Kfn,LegoAnimPresenterSetCompare,allocator<LegoAnimPresenter *> >::insert`

Match `LegoAnimPresenterSetCompare` comparison

---

LEGO1/omni/src/stream/mxstreamcontroller.cpp

Doesn't use the `Remove` proxy function for some reason in retail

Match `MxStreamController::RemoveSubscriber`

---

LEGO1/omni/include/mxgeometry.h

Fixed a wrong address in `mxutilities.h`. It should point to the point/size constructor for `MxRect<int>` instead of `MxRect32`.
Should now get 100% on `GetRectIntersection` when the entropy cooperates.

Fix address for `MxRect` constructor

---

LEGO1/lego/legoomni/include/mxcontrolpresenter.h
LEGO1/lego/legoomni/src/common/mxcontrolpresenter.cpp
LEGO1/lego/legoomni/src/control/legocontrolmanager.cpp
LEGO1/omni/src/common/mxutilities.cpp

Resolves #1344. The best I can get with a lot of entropy samples is 95.51%. But here's the main diff:
```diff
mov eax, dword ptr [ebx + 0x18]
cmp dword ptr [edi + 0x18], eax
-jge 0x119
+jge 0x11b
+mov eax, dword ptr [ebx]
+mov ecx, ebx
+call dword ptr [eax + 0x7c]
+test al, al
+je 0x10c
mov ebp, dword ptr [edi]
-mov ecx, edi
-call dword ptr [ebp + 0x7c]
-test al, al
-je 0x10a
mov ecx, edi
call dword ptr [ebp + 0x84]
```
That looks fine to me. Easier to see it side by side. The jump diffs are caused by using different registers.
```
mov eax, dword ptr [ebx + 0x18]
cmp dword ptr [edi + 0x18], eax
jge 0x119                        ; jge 0x11b
mov ebp, dword ptr [edi]         ; mov eax, dword ptr [ebx]
mov ecx, edi                     ; mov ecx, ebx
call dword ptr [ebp + 0x7c]      ; call …
```

`MxControlPresenter::FUN_10044270` to 100%?

---

LEGO1/omni/include/mxbitmap.h
LEGO1/omni/src/video/mxvideopresenter.cpp

Resolves #1424. I wrote up the issue expecting it to sit for a while and then figured it out pretty quickly. As it turns out, we _did_ already have the utility function we needed (`GetStart`) from the beta.
`IsHit` and the bitmap constructor can both hit 100% in an entropy build.

Fix `AlphaMask` functions

---

LEGO1/omni/include/mxvideopresenter.h

Resolves #1388.
Results of a 256-build entropy run below. (I removed the `_Tree` template functions.) GH won't let me attach the HTML report here but you can find it on the branch on my fork. I checked the decreased functions and they all look fine.
```
Increased (22):
0x1000c7e0 - MxVideoPresenter::GetWidth (60.00% -> 100.00%)
0x1000c800 - MxVideoPresenter::GetHeight (61.54% -> 100.00%)
0x10025450 - LegoCarBuild::FUN_10025450 (96.51% -> 97.09%)
0x1002aba0 - LegoExtraActor::HitActor (89.30% -> 89.52%)
0x1002b980 - LegoExtraActor::VTable0x6c (98.57% -> 100.00%*)
0x10031820 - Isle::Enable (99.80% -> 100.00%)
0x10040360 - Act3Cop::FUN_10040360 (90.64% -> 91.18%)
0x10041050 - Act3Brickster::Animate (98.38% -> 98.57%)
0x10048310 - LegoPathController::FUN_10048310 (89.75% -> 89.89%)
0x10054050 …
```

Add getters to `MxVideoPresenter::AlphaMask`

---

LEGO1/omni/include/mxdsaction.h
LEGO1/omni/include/mxdsactionlist.h
LEGO1/omni/include/mxdsanim.h
LEGO1/omni/include/mxdsevent.h
LEGO1/omni/include/mxdsmediaaction.h
LEGO1/omni/include/mxdsmultiaction.h
LEGO1/omni/include/mxdsobject.h
LEGO1/omni/include/mxdsobjectaction.h
LEGO1/omni/include/mxdsparallelaction.h
LEGO1/omni/include/mxdsselectaction.h
LEGO1/omni/include/mxdsserialaction.h
LEGO1/omni/include/mxdssound.h
LEGO1/omni/include/mxdsstill.h
LEGO1/omni/include/mxdsstreamingaction.h
LEGO1/omni/src/action/mxdsanim.cpp
LEGO1/omni/src/action/mxdsevent.cpp
LEGO1/omni/src/action/mxdsmediaaction.cpp
LEGO1/omni/src/action/mxdsmultiaction.cpp
LEGO1/omni/src/action/mxdsobjectaction.cpp
LEGO1/omni/src/action/mxdsparallelaction.cpp
LEGO1/omni/src/action/mxdsselectaction.cpp
LEGO1/omni/src/action/mxdsserialaction.cpp
LEGO1/omni/src/action/mxdssound.cpp
LEGO1/omni/src/action/mxdsstill.cpp

- Added beta addrs for (hopefully) all functions.
- Removed `this->`.
- All vtable offsets use our preferred format `// vtable+0x__` instead of `// vtable+__`.
- Copy constructor added for all classes (unused in and removed from retail)
- `SetType` removed from each constructor, per the beta
- Renamed `m_actions` to `m_actionList` to match beta assert
I excluded some beta matches that (for now) decreased retail.

Beta match and cleanup of `MxDS*` classes

---

LEGO1/tgl/d3drm/impl.h
LEGO1/tgl/d3drm/view.cpp

I started by adding `Destroy()` methods to the destructor of each of the 9 `TglImpl` types. The entropy impact was surprisingly minimal, even for a single build, so I added more abstraction functions to `ViewImpl` (chosen at random) until they were all there.
This is not the full conversion to the templated `Tgl`, but there are now functions in each place where there should be one.
These functions are now 100%.
```
0x100a2df0 - TglImpl::ViewImpl::SetCamera (66.67% -> 100.00%)
0x100a2e70 - TglImpl::ViewImpl::SetProjection (70.00% -> 100.00%)
0x100a2eb0 - TglImpl::ViewImpl::SetFrustrum (66.67% -> 100.00%)
0x100a30f0 - TglImpl::ViewImpl::TransformWorldToScreen (72.73% -> 100.00%)
```
`TglImpl::ViewImpl::ForceUpdate` goes back to 100% with enough entropy samples.

Add abstraction functions to `TglImpl::ViewImpl`

---

LEGO1/tgl/d3drm/device.cpp
LEGO1/tgl/d3drm/impl.h
LEGO1/tgl/d3drm/light.cpp
LEGO1/tgl/d3drm/mesh.cpp
LEGO1/tgl/d3drm/meshbuilder.cpp
LEGO1/tgl/d3drm/renderer.cpp
LEGO1/tgl/tgl.h

These three:
```
0x100a1cf0 - TglImpl::RendererImpl::CreateLight (68.51% -> 100.00%)
0x100a2c30 - TglImpl::DeviceImpl::SetShadingModel (70.97% -> 100.00%)
0x100a3fc0 - TglImpl::MeshImpl::SetShadingModel (46.58% -> 100.00%)
```
I had the beta addresses for `Light` and `Mesh` backwards, which was proven by adding the abstraction functions required to match.

Match a few more `Tgl` functions

---

LEGO1/tgl/d3drm/impl.h
LEGO1/tgl/d3drm/mesh.cpp
LEGO1/tgl/d3drm/renderer.cpp
LEGO1/tgl/d3drm/view.cpp

The 9 classes now use a `DataType` typedef as in the 96 code.
To get all the methods to appear, I added more abstraction functions in `RendererImpl` and `MeshImpl`. That resulted in:
```
0x100a1900 - TglImpl::RendererImpl::CreateDevice(struct Tgl::DeviceDirectDrawCreateData const &) (68.60% -> 98.88%)
0x100a1a00 - TglImpl::RendererImpl::CreateView (77.73% -> 100.00%)
0x100a1f50 - TglImpl::RendererImpl::CreateTexture(int, int, int, void const *, int, int, struct Tgl::PaletteEntry const *) (79.70% -> 100.00%)
0x100a20d0 - TglImpl::RendererImpl::CreateTexture(void) (92.06% -> 100.00%)
0x100a4030 - TglImpl::MeshImpl::DeepClone (46.92% -> 100.00%)
```
`CreateDevice` is 99% because reccmp doesn't pick up the static variable. The function where it lives gets inlined so we can't match it with our …

Add all `TglImpl::ImplementationData` methods

---

LEGO1/lego/legoomni/src/worlds/isle.cpp

This takes a `Vector3*` not a `BOOL`.

Fix input to FUN_10064740

---

CONFIG/config.h

I couldn't find a way to get this working on Linux so hoping this is the correct fix.

Fix definition of WriteRegisterSettings()

---

LEGO1/omni/src/audio/mxmusicmanager.cpp

I missed this in #1470, even though it isn't a function call.

make MIDIOUTCAPS format-agnostic

---

docker/Dockerfile

This PR pins the registry, and pins the base image of the container file to use debian (stable, slim). Tested working with the provided build instructions in the readme.

pin container base image registry and debian version

---

CONFIG/config.cpp
LEGO1/lego/legoomni/src/video/legovideomanager.cpp
LEGO1/mxdirectx/legodxinfo.cpp
LEGO1/mxdirectx/legodxinfo.h

Gets any hardware device that can output an image, or a software rendere, the software rendere will be color if the CPU has MMX else a black and white software render is picked.
There may well be some logic errors here since it only gets a software render if it's ONLY capable of color OR monochrome but the API seems to allow for multiple flags.

Rename FUN_1009d0d0 into GetBestDevice

---

LEGO1/library_msvc.h

Corrects these two annotations:
```
// LIBRARY: LEGO1 0x1008b340
// __fpmath
// GLOBAL: LEGO1 0x100fc8dc
// __FPinit
```
`__FPinit` is a pointer to the function `__fpmath`. The previous version tried to match the function to the variable, so we didn't get any instructions out from `capstone`.
Fixing this revealed a new branch of floating point related functions that are now marked. Some of these are not public so there is nothing from the PDB that we can use to match. I disabled these annotations for now, but the names are there (based on Ghidra's identification) in case we want to use them later.

Fix some MSVC annotations for LEGO1

---

ISLE/isleapp.cpp
LEGO1/lego/legoomni/src/common/legogamestate.cpp
LEGO1/lego/legoomni/src/video/legovideomanager.cpp
LEGO1/omni/include/mxvideoparamflags.h

A better name for the flag. It's one of the most common places for the miniwin directx implementation to die so I have been starting at this very bit of code for to many times to live with this name any longer.

Rename F2bit0 to LacksLightSupport

---

LEGO1/mxdirectx/mxdirectxinfo.cpp
LEGO1/mxdirectx/mxdirectxinfo.h

`const` qualifiers are stripped during compilation and don't affect the generated code — they're primarily a tool to help developers avoid unintended mutations.
This change adds `const` in several places where it makes sense for clarity and code safety. While we can't be certain whether these were originally present (since decompiled code doesn't retain them), adding them improves code quality and intent.

Use consts in callbacks

---

LEGO1/omni/src/video/mxdisplaysurface.cpp

To match LEGO1/mxdirectx/mxdirectdraw.cpp so it's not so confusing to compare uage

Order enums the same way in both places

---

LEGO1/omni/src/video/mxpalette.cpp

Noticed that MxPalette::SetSkyColor was using 0 and -1 instead of SUCCESS and FAILURE.

Use SUCCESS and FAILURE in MxPalette::SetSkyColor

---

.github/workflows/compare.yml

#1505 reminded me that I never added this. With this we can run 1024 sample entropy runs.

Use argument file for `reccmp-aggregate` samples

---

LEGO1/tgl/d3drm/group.cpp
LEGO1/tgl/d3drm/impl.h
LEGO1/tgl/d3drm/mesh.cpp
LEGO1/tgl/d3drm/meshbuilder.cpp

This time we have functions from the similar `MeshImpl` and `GroupImpl` classes:
```
0x100a31e0 - TglImpl::GroupImpl::SetTransformation (45.16% -> 100.00%)
0x100a3240 - TglImpl::GroupImpl::SetColor (74.36% -> 100.00%)
0x100a33c0 - TglImpl::GroupImpl::SetMaterialMode (50.00% -> 100.00%)
0x100a34b0 - TglImpl::GroupImpl::RemoveAll (93.55% -> 100.00%)
0x100a3540 - TglImpl::GroupImpl::Bounds (75.89% -> 100.00%)
0x100a3ee0 - TglImpl::MeshImpl::SetColor (60.00% -> 100.00%)
0x100a3f80 - TglImpl::MeshImpl::SetTextureMappingMode (69.23% -> 100.00%)
0x100a4240 - TglImpl::MeshImpl::ShallowClone (52.78% -> 100.00%)
```
`Bounds` and `ShallowClone` need some encouragement from the entropy build. The latter is not in the beta, but I got to 100% by imitating `DeepClone`.
These two are nearly perfect, but …

Match Tgl `MeshImpl` and `GroupImpl` functions

---

LEGO1/lego/legoomni/src/actors/helicopter.cpp

To be honest, I have no idea why this worked, but it's up to 100 % effective. No obvious other pattern had such a good outcome.
Fixes #1317.

Match `Helicopter::FUN_100042a0`

---

LEGO1/lego/legoomni/src/build/legocarbuildpresenter.cpp

Fixes one of the issues here: https://github.com/isledecomp/isle-portable/issues/197
Does not change accuracy/assembly

Fix `LegoTreeNode*` construction

---

LEGO1/lego/legoomni/src/common/legogamestate.cpp

I could clear the unknown color string descriptions by looking for the ROI with the same name.
I'm not sure if there are "more official" names than these and guessed them from the shortened name.

Fill in unknown color string descriptions

---

LEGO1/lego/legoomni/src/common/mxtransitionmanager.cpp

This fixes an assertion error, triggered by the following actions:
1. Start the game
2. Skip intro (probably optional)
3. Turn left to the elevator room
4. Enter the elevator
5. Press the (I) button

Assertion in MxTransitionManager::StartTransition is beta10-only

---

LEGO1/lego/legoomni/include/legocharactermanager.h
LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
LEGO1/lego/legoomni/src/common/legoplantmanager.cpp
LEGO1/lego/legoomni/src/video/legophonemepresenter.cpp

With this almost all unknowns in `legocharactermanager.cpp` are now named.
I noticed the pattern where it matches different rois to another one (e.g. the each claw to their respective arm) and used the constants. If this is not wanted (here) I can remove it or extract it into a separate patch.

Clear unknowns in legocharactermanager

---

LEGO1/lego/legoomni/include/hospital.h
LEGO1/lego/legoomni/src/worlds/hospital.cpp

I've tried to clear unknowns in `Hospital`, and maybe the names are not the best.
For example I'm not really sure about those:
* `m_interactionMode` is weird, as the values seem to be `0`, `1` and `3`. Not sure if those specific values have been used elsewhere.
* `m_setWithCurrentAction` is only set and never read. But it is always (and only) set when an animation is started.
* `g_deleteCounter` just "enables" you to skip the animation with space. Not sure why it is 3 or decremented with each tickle.
If you want I can split this into separate pull requests, depending on the "likeliness" of being correct.
While working on the states I noticed that there the state 10 can never be reached, and because of this 11 is also out of reach. Not sure if this a decompilation artefact or unfinished …

Clear unknowns/numbers in `Hospital` and `HospitalState`

---

LEGO1/lego/legoomni/include/hospital.h
LEGO1/lego/legoomni/src/worlds/hospital.cpp

It should now send the player to the right place (infocenter or back to the map at the hospital door) if you click either exit after the guy shows you the hat.
See also: isledecomp/reccmp#135

Fix Hospital exit bug #1548

---

LEGO1/lego/legoomni/include/police.h
LEGO1/lego/legoomni/src/worlds/police.cpp

While in others (e.g. Hospital) a field like `m_unk0x0c` is used as a state and can have multiple values it appears to be that the police has only two states: Whether an animation is playing or not.
If you want I can use a name like `m_state` and some enum with `e_noAnimation` and `e_playingAnimation`.

Clear unknowns in `PoliceState`

---

LEGO1/lego/legoomni/src/paths/legopathcontroller.cpp
LEGO1/lego/sources/geom/legoweedge.h

Inspired by #1546. These assertions also document that we know the original names. `ReadEdges()` now matches 100 % on BETA10, `ReadBoundaries()` matches structurally.

Add BETA10 assertions in LegoPathController

---

CMakeLists.txt

As discussed at https://github.com/isledecomp/isle/pull/1569#discussion_r2156457825, I noticed that there are some issues in linking BETA10, leading to a numerous instances of calls into Redistributable DLLs where the original had the functions inlined. Here is a shortened diff on BETA10:
```
New (26):
0x100f8ad0 - strcmp (new -> 100.00%)
0x100f9060 - _assert (new -> 88.66%)
0x100f9420 - memcpy (new -> 100.00%)
0x100f9570 - memset (new -> 100.00%)
0x100f9610 - rand (new -> 96.77%)
0x100f9690 - sprintf (new -> 100.00%)
0x100f9780 - strlen (new -> 100.00%)
0x100f9b90 - _purecall (new -> 100.00%)
0x100f9f60 - strtok (new -> 99.17%)
0x100fa0e0 - atof (new -> 91.84%)
0x100fa200 - strcpy (new -> 100.00%)
0x100faa00 - memcmp (new -> 100.00%)
0x100fad10 - fclose (new -> 100.00%)
0x100fae70 - …
```

Fix BETA10 linker settings

---

LEGO1/omni/src/video/flic.cpp

FLIC decoding requires working with `signed char` in some places. On some platforms, `char` is `unsigned char` and this will lead to crashes: https://github.com/isledecomp/isle-portable/issues/378

Fix implicit `signed char`-ness

---

LEGO1/lego/legoomni/src/common/legocharactermanager.cpp
LEGO1/lego/sources/roi/legolod.cpp
LEGO1/lego/sources/roi/legolod.h

The function does mostly the same as `SetTextureInfo` but does not explicitly set the color as well.

Clear unknown in `LegoLOD`

---

LEGO1/lego/legoomni/include/carrace.h
LEGO1/lego/legoomni/include/jetskirace.h
LEGO1/lego/legoomni/include/legorace.h
LEGO1/lego/legoomni/src/race/carrace.cpp
LEGO1/lego/legoomni/src/race/jetskirace.cpp
LEGO1/lego/legoomni/src/race/legorace.cpp

Fixing this bug: https://github.com/isledecomp/isle-portable/issues/481
`reccmp` didn't catch this, the function was 100%* before but used a wrong value in the switch-case. Something to look at? @disinvite @jonschz

Fix wrong notification type in `LegoRace::Notify`

---

LEGO1/lego/legoomni/src/race/legoracers.cpp

Removing `const` from `g_skeletonKickPhases` moves it from the `.rdata` section into `.data`. It now sits between `g_skBMap` and `g_strSpeed` as in the original.

Move `g_skeletonKickPhases` to `.data`

---

CONFIG/config.cpp
CONFIG/config.h
reccmp-project.yml
tools/README.md

This matches functions from `CConfigApp` in `CONFIG` using the beta 1.0 copy. I renamed that to `CONFIGD` and the annotations use that label.
I can add the checksum to `reccmp-project.yml` if we want it there.
One of the functions appears to degrade, but here is the result of a 256 sample entropy run:
```
New (1):
0x403890 - CConfigApp::WriteRegisterSettings (new -> 100.00%)
Increased (5):
0x402dc0 - CConfigApp::InitInstance (77.92% -> 99.01%)
0x4031b0 - CConfigApp::WriteReg (62.63% -> 100.00%)
0x403430 - CConfigApp::ReadRegisterSettings (88.58% -> 100.00%)
0x403630 - CConfigApp::ValidateSettings (93.90% -> 100.00%)
0x404340 - CMainDialog::OnButtonCancel (78.26% -> 86.96%)
```

Beta matching `CConfigApp`

---

CONFIG/MainDlg.cpp
CONFIG/config.cpp
LEGO1/mxdirectx/legodxinfo.cpp
LEGO1/mxdirectx/mxdirect3d.cpp
LEGO1/mxdirectx/mxdirectxinfo.cpp
LEGO1/mxdirectx/mxdirectxinfo.h

`CONFIGD` shows that the list member from `MxDeviceEnumerate` is accessed directly. This removes the now-unused `GetDriverList()` getter and adds the two config classes as friends.
This also renames `m_list` to `m_ddInfo` to match the assert in `EnumDisplayModesCallback`.

Remove `GetDriverList` getter

---

LEGO1/lego/legoomni/include/legoanimationmanager.h
LEGO1/lego/legoomni/include/legotraninfolist.h
LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
LEGO1/lego/legoomni/src/common/legoanimmmpresenter.cpp
LEGO1/lego/legoomni/src/entity/legoworld.cpp
LEGO1/omni/include/mxlist.h
LEGO1/realtime/orientableroi.cpp

I tried to match `LegoAnimationManager::FUN_10061010` and got some improvements. I couldn't get one function to inline (specifically `MxListEntry<LegoTranInfo *>::MxListEntry<LegoTranInfo *>` around `LEGO1 0x1006120f`, called from `MxList::Append` -> `MxList::InsertEntry` -> `MxListEntry::MxListEntry`). Not sure if @foxtacles wants to take a look or if we just merge this. #1355 cannot be closed until that issue is fixed, unfortunately. The rest looks like it could match with a different stack layout.

Improve `FUN_10061010`, other fixes

---

LEGO1/omni/include/mxsemaphore.h
LEGO1/omni/include/mxthread.h
LEGO1/omni/src/stream/mxdiskstreamprovider.cpp
LEGO1/omni/src/system/mxsemaphore.cpp
LEGO1/omni/src/system/mxthread.cpp

Matching `MxThread` and `MxSemaphore` where possible, without adding any new members. Includes the uncalled functions for both.

Beta match `MxThread` and `MxSemaphore`

---

LEGO1/lego/legoomni/include/legobuildingmanager.h
LEGO1/lego/legoomni/include/legomain.h
LEGO1/lego/legoomni/include/legoplantmanager.h
LEGO1/lego/legoomni/include/legovideomanager.h
LEGO1/lego/legoomni/include/legoworldlist.h
LEGO1/lego/legoomni/src/audio/mxbackgroundaudiomanager.cpp
LEGO1/lego/legoomni/src/common/legobuildingmanager.cpp
LEGO1/lego/legoomni/src/common/legoplantmanager.cpp
LEGO1/lego/legoomni/src/common/misc.cpp
LEGO1/lego/legoomni/src/common/mxtransitionmanager.cpp
LEGO1/lego/legoomni/src/control/legocontrolmanager.cpp
LEGO1/lego/legoomni/src/input/legoinputmanager.cpp
LEGO1/lego/legoomni/src/main/legomain.cpp
LEGO1/lego/legoomni/src/main/scripts.cpp
LEGO1/lego/legoomni/src/video/legoflctexturepresenter.cpp
LEGO1/lego/legoomni/src/video/legovideomanager.cpp
LEGO1/lego/sources/misc/legocontainer.h
LEGO1/library_msvc.h
LEGO1/omni/include/mxomni.h
LEGO1/omni/include/mxomnicreateparam.h
LEGO1/omni/src/main/mxomni.cpp
LEGO1/omni/src/notify/mxnotificationmanager.cpp
LEGO1/omni/src/video/mxvideomanager.cpp

Closes #1349 
`LegoOmni::Create()` is at 100 % effective for LEGO1 and has a full structural match against BETA10 (up to one short section that has no corresponding part in LEGO1, so I didn't decompile it).
I'll add a comment where I'll leave TODOs for future PRs since this one is quite large already.

Match `LegoOmni::Create()`, other BETA10 matches

---

LEGO1/lego/legoomni/include/legoanimationmanager.h
LEGO1/lego/legoomni/src/common/legoanimationmanager.cpp
LEGO1/mxgeometry/mxgeometry3d.h
LEGO1/viewmanager/viewmanager.cpp

As discussed in #1663. We cannot close that ticket yet since there are other functions still to be matched.
There should be no regressions on BETA10 on this one, but a double check wouldn't hurt.
The constructors on `Vector3::Vector3` appear to be the right way round - switchting them causes major regressions with very few improvements.

Match Mx3DPointFloat overloads on BETA10

---

LEGO1/mxgeometry/mxmatrix.h
LEGO1/realtime/matrix.h
LEGO1/realtime/matrix4d.inl.h

I usually associate a function like `Equals` with an equality check and not with a clone or copy. So renamed the function respectively.

Improve naming for `Equals` in `MxMatrix`

---

reccmp-project.yml

See https://github.com/isledecomp/reccmp/pull/198. It should be merged soon after that `reccmp` PR has been merged in order to not have a regression in the `BETA10` Ghidra import.

Add name substitution config
